<a href="https://colab.research.google.com/github/LadonV/Data-Viz/blob/main/From_Votes_to_Victory_Modeling_Success_in_Survivor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Ladon Vance

## CPSMA 4313

## Dr. Jacob

In [ ]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

## Seasons 1-10

In [ ]:
url = "https://en.wikipedia.org/wiki/List_of_Survivor_(American_TV_series)_contestants"

# Add a User-Agent header to mimic a browser
headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'}
response = requests.get(url, headers=headers)

# Use pandas.read_html to parse the content from the response
tables = pd.read_html(response.text)

winners_df = tables[0]  # usually first table
winners_df.head()

/tmp/ipykernel_3126/2426466482.py:8: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(response.text)

,Name,Age,Hometown,Profession,Season,Finish
0,Sonja Christopher,63,"Walnut Creek, CA",Gym Teacher / Retired,Survivor: Borneo,16th
1,"Bill ""B.B."" Andersen",64,"Mission Hills, KS",Real Estate Developer,Survivor: Borneo,15th
2,Stacey Stillman,27,"San Francisco, CA",Attorney,Survivor: Borneo,14th
3,Ramona Gray,29,"Edison, NJ",Biochemist,Survivor: Borneo,13th
4,Dirk Been,23,"Spring Green, WI",Dairy Farmer,Survivor: Borneo,12th

In [ ]:
winner_count = winners_df[winners_df['Finish'] == 'Winner'].shape[0]
print(f"Total count of 'Winner' in the 'Finish' column: {winner_count}")

Total count of 'Winner' in the 'Finish' column: 10

In [ ]:
winner_rows_df = winners_df[winners_df['Finish'] == 'Winner']
print("DataFrame restricted to winner rows:")
print(winner_rows_df.head(10))

DataFrame restricted to winner rows:
                  Name  Age          Hometown                   Profession  \
15       Richard Hatch   39       Newport, RI            Corporate Trainer
31         Tina Wesson   39     Knoxville, TN               Personal Nurse
47          Ethan Zohn   27      New York, NY   Professional Soccer Player
63      Vecepia Towery   36       Hayward, CA               Office Manager
79        Brian Heidik   34   Quartz Hill, CA            Used Car Salesman
95       Jenna Morasca   21    Pittsburgh, PA               Swimsuit Model
111  Sandra Diaz-Twine   29    Fort Lewis, WA             Office Assistant
129      Amber Brkich^   25        Beaver, PA     Administrative Assistant
147    Chris Daugherty   33  South Vienna, OH  Highway Construction Worker
167        Tom Westman   41      Sayville, NY                  Firefighter

                               Season  Finish
15                   Survivor: Borneo  Winner
31   Survivor: The Australian Outback  Winner
47                   Survivor: Africa  Winner
63                Survivor: Marquesas  Winner
79                 Survivor: Thailand  Winner
95               Survivor: The Amazon  Winner
111           Survivor: Pearl Islands  Winner
129               Survivor: All-Stars  Winner
147                 Survivor: Vanuatu  Winner
167                   Survivor: Palau  Winner

## Seasons 11-20

In [ ]:
url = "https://en.wikipedia.org/wiki/List_of_Survivor_(American_TV_series)_contestants"

headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'}
response = requests.get(url, headers=headers)

tables = pd.read_html(response.text)

winners_df2 = tables[1]
winners_df2.head()

/tmp/ipykernel_3126/2254125280.py:6: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(response.text)

,Name,Age,Hometown,Profession,Season,Finish
0,"James ""Jim"" Lynch",63,"Northglenn, CO",Retired Fire Captain,Survivor: Guatemala,18th
1,Morgan McDevitt,21,"Decatur, IL",Magician's Assistant,Survivor: Guatemala,17th
2,Brianna Varela,21,"Edmonds, WA",Retail Salesperson,Survivor: Guatemala,16th
3,Brooke Struck,26,"Hood River, OR",Law Student,Survivor: Guatemala,15th
4,Blake Towsley,24,"Dallas, TX",Real Estate Broker,Survivor: Guatemala,14th

In [ ]:
winner_count = winners_df2[winners_df2['Finish'] == 'Winner'].shape[0]
print(f"Total count of 'Winner' in the 'Finish' column: {winner_count}")

Total count of 'Winner' in the 'Finish' column: 10

In [ ]:
winner_rows_df = winners_df2[winners_df2['Finish'] == 'Winner']
print("DataFrame restricted to winner rows:")
print(winner_rows_df[['Name', 'Finish']].head(10))

DataFrame restricted to winner rows:
                            Name  Finish
17   Danielle "Danni" Boatwright  Winner
33               Aras Baskauskas  Winner
53                      Yul Kwon  Winner
72                     Earl Cole  Winner
88                   Todd Herzog  Winner
108             Parvati Shallow^  Winner
126         Robert "Bob" Crowley  Winner
142     James "J.T." Thomas, Jr.  Winner
162                Natalie White  Winner
182           Sandra Diaz-Twine^  Winner

## Seasons 21-30

In [ ]:
url = "https://en.wikipedia.org/wiki/List_of_Survivor_(American_TV_series)_contestants"

headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'}
response = requests.get(url, headers=headers)

tables = pd.read_html(response.text)

winners_df3 = tables[2]
winners_df3.head()

/tmp/ipykernel_3126/2906372919.py:6: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(response.text)

,Name,Age,Hometown,Profession,Season,Finish
0,Wendy Jo DeSmidt-Kohlhoff,48,"Fromberg, MT",Goat Rancher,Survivor: Nicaragua,20th
1,Shannon Elkins,30,"Lafayette, LA",Pest Control Company Owner,Survivor: Nicaragua,19th
2,Jimmy Johnson,67,"Islamorada, FL",Former NFL Coach,Survivor: Nicaragua,18th
3,Jimmy Tarantino,48,"Gloucester, MA",Commercial Fisherman,Survivor: Nicaragua,17th
4,Tyrone Davis,42,"Inglewood, CA",Firefighter,Survivor: Nicaragua,16th

In [ ]:
winner_rows_df = winners_df3[winners_df3['Finish'] == 'Winner']
print("DataFrame restricted to winner rows:")
print(winner_rows_df[['Name', 'Finish']].head(10))

DataFrame restricted to winner rows:
                  Name  Finish
19   Jud "Fabio" Birza  Winner
37        Rob Marianoo  Winner
55       Sophie Clarke  Winner
73        Kim Spradlin  Winner
91      Denise Stapley  Winner
111      John Cochran^  Winner
131     Tyson Apostol◊  Winner
149       Tony Vlachos  Winner
167   Natalie Anderson  Winner
185      Mike Holloway  Winner

## Seasons 31-40

In [ ]:
url = "https://en.wikipedia.org/wiki/List_of_Survivor_(American_TV_series)_contestants"

headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'}
response = requests.get(url, headers=headers)

tables = pd.read_html(response.text)

winners_df4 = tables[3]
winners_df4.head()

/tmp/ipykernel_3126/4171613112.py:6: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(response.text)

,Name,Age,Hometown,Profession,Season,Finish
0,Vytas Baskauskas^,35,"Santa Monica, CA",Yoga Instructor/Math Professor,Survivor: Cambodia,20th
1,Shirin Oskooi^,32,"San Francisco, CA",Yahoo! Executive,Survivor: Cambodia,19th
2,Peih-Gee Law^,37,"San Francisco, CA",Jeweler,Survivor: Cambodia,18th
3,Jeff Varner^,49,"Greensboro, NC",Internet Projects Manager,Survivor: Cambodia,17th
4,Monica Padilla^,30,"Queens, NY",Law Student,Survivor: Cambodia,16th

In [ ]:
winner_rows_df = winners_df4[winners_df4['Finish'] == 'Winner']
print("DataFrame restricted to winner rows:")
print(winner_rows_df[['Name', 'Finish']].head(10))

DataFrame restricted to winner rows:
                   Name  Finish
19      Jeremy Collins^  Winner
37   Michele Fitzgerald  Winner
57           Adam Klein  Winner
77        Sarah Lacina^  Winner
95       Ben Driebergen  Winner
115     Wendell Holland  Winner
135         Nick Wilson  Winner
153     Chris Underwood  Winner
173       Tommy Sheehan  Winner
193       Tony Vlachos◊  Winner

## Seasons 41-49

In [ ]:
url = "https://en.wikipedia.org/wiki/List_of_Survivor_(American_TV_series)_contestants"

headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'}
response = requests.get(url, headers=headers)

tables = pd.read_html(response.text)

winners_df5 = tables[4]
winners_df5.head()

/tmp/ipykernel_3126/1212791794.py:6: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(response.text)

,Name,Age,Hometown,Profession,Season,Finish
0,Eric Abraham,51,"San Antonio, TX",Cyber Security Analyst,Survivor 41,18th
1,Sara Wilson,24,"Boston, MA",Healthcare Consultant,Survivor 41,17th
2,David Voce,35,"Chicago, IL",Neurosurgeon,Survivor 41,16th
3,Brad Reese,50,"Shawnee, WY",Rancher,Survivor 41,15th
4,"Jairus ""JD"" Robinson",20,"Oklahoma City, OK",College Student,Survivor 41,14th

In [ ]:
winner_rows_df = winners_df5[winners_df5['Finish'] == 'Winner']
print("DataFrame restricted to winner rows:")
print(winner_rows_df[['Name', 'Finish']].head(9))

DataFrame restricted to winner rows:
                          Name  Finish
17             Erika Casupanan  Winner
35             Maryanne Oketch  Winner
53                 Mike Gabler  Winner
71      Yamil "Yam Yam" Arocho  Winner
89   Dianelys "Dee" Valladares  Winner
107               Kenzie Petty  Winner
125              Rachel LaMont  Winner
143                Kyle Fraser  Winner
161             Savannah Louie  Winner

## Season 1

In [ ]:
import requests
from bs4 import BeautifulSoup

headers = {
    "User-Agent": "Mozilla/5.0",
    "Accept-Language": "en-US,en;q=0.9"
}

url = "https://en.wikipedia.org/wiki/Survivor:_Borneo"

r = requests.get(url, headers=headers)

html_soup = BeautifulSoup(r.text, "html.parser")

tables = html_soup.find_all("table")

print(len(tables))

8

In [ ]:
print(r.status_code)
print(r.url)

200
https://en.wikipedia.org/wiki/Survivor:_Borneo

In [ ]:
print(len(html_soup.find_all('table')))

8

In [ ]:
tables = html_soup.find_all('table',class_="wikitable")
if tables:
    print(tables[0].find_all('a'))
else:
    print("No wikitable found on the page. This might be because the requested page (Survivor: Borneo) returned a 'Wikimedia Error' page instead of the actual content. Check the `html_contents` variable for details.")

[<a href="/wiki/Walnut_Creek,_California" title="Walnut Creek, California">Walnut Creek,<br/>California</a>, <a href="/wiki/Mission_Hills,_Kansas" title="Mission Hills, Kansas">Mission Hills,<br/>Kansas</a>, <a href="/wiki/San_Francisco" title="San Francisco">San Francisco,<br/>California</a>, <a href="/wiki/Edison,_New_Jersey" title="Edison, New Jersey">Edison,<br/>New Jersey</a>, <a href="/wiki/Spring_Green,_Wisconsin" title="Spring Green, Wisconsin">Spring Green,<br/>Wisconsin</a>, <a href="/wiki/Sherwood,_Arkansas" title="Sherwood, Arkansas">Sherwood,<br/>Arkansas</a>, <a href="/wiki/Clarksville,_Tennessee" title="Clarksville, Tennessee">Clarksville,<br/>Tennessee</a>, <a href="/wiki/Gold_Hill,_Colorado" title="Gold Hill, Colorado">Gold Hill,<br/>Colorado</a>, <a href="/wiki/Franklin,_New_Hampshire" title="Franklin, New Hampshire">Franklin,<br/><span class="nowrap">New Hampshire</span></a>, <a href="/wiki/Gervase_Peterson" title="Gervase Peterson">Gervase Peterson</a>, <a href="/wiki/Willingboro_Township,_New_Jersey" title="Willingboro Township, New Jersey">Willingboro,<br/>New Jersey</a>, <a href="/wiki/Colleen_Haskell" title="Colleen Haskell">Colleen Haskell</a>, <a href="/wiki/Miami_Beach,_Florida" title="Miami Beach, Florida">Miami Beach,<br/>Florida</a>, <a href="/wiki/Carle_Place,_New_York" title="Carle Place, New York">Carle Place,<br/>New York</a>, <a href="/wiki/Sue_Hawk" title="Sue Hawk">Susan Hawk</a>, <a href="/wiki/Palmyra,_Wisconsin" title="Palmyra, Wisconsin">Palmyra,<br/>Wisconsin</a>, <a href="/wiki/Rudy_Boesch" title="Rudy Boesch">Rudy Boesch</a>, <a href="/wiki/Virginia_Beach,_Virginia" title="Virginia Beach, Virginia">Virginia Beach,<br/>Virginia</a>, <a href="/wiki/Kernville,_California" title="Kernville, California">Kernville,<br/>California</a>, <a href="/wiki/Richard_Hatch_(Survivor_contestant)" title="Richard Hatch (Survivor contestant)">Richard Hatch</a>, <a href="/wiki/Newport,_Rhode_Island" title="Newport, Rhode Island">Newport,<br/>Rhode Island</a>]

In [ ]:
df = pd.read_html(str(tables))[3]
df

/tmp/ipykernel_3126/1238544221.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(tables))[3]

   Unnamed: 0_level_0 Original tribes                                          \
              Episode               1       2       3        4      5       6
0                 Day               3       6       9       12     15      18
1               Tribe            Tagi  Pagong    Tagi   Pagong   Tagi  Pagong
2          Eliminated           Sonja    B.B.  Stacey   Ramona   Dirk    Joel
3               Votes           4–3–1     6–2     5–2    4–2–1  4–1–1     4–2
4                 NaN             NaN     NaN     NaN      NaN    NaN     NaN
5               Voter           Votes   Votes   Votes    Votes  Votes   Votes
6             Richard          Stacey     NaN  Stacey      NaN   Dirk     NaN
7               Kelly            Rudy     NaN    Rudy      NaN   Dirk     NaN
8                Rudy           Sonja     NaN  Stacey      NaN   Dirk     NaN
9               Susan           Sonja     NaN  Stacey      NaN   Dirk     NaN
10               Sean           Sonja     NaN  Stacey      NaN   Rudy     NaN
11            Colleen             NaN    B.B.     NaN   Ramona    NaN    Joel
12            Gervase             NaN    B.B.     NaN  Colleen    NaN   Jenna
13              Jenna             NaN    B.B.     NaN   Ramona    NaN    Joel
14               Greg             NaN  Ramona     NaN    Jenna    NaN    Joel
15           Gretchen             NaN    B.B.     NaN   Ramona    NaN    Joel
16               Joel             NaN    B.B.     NaN   Ramona    NaN   Jenna
17               Dirk           Sonja     NaN  Stacey      NaN  Susan     NaN
18             Ramona             NaN    B.B.     NaN  Colleen    NaN     NaN
19             Stacey            Rudy     NaN    Rudy      NaN    NaN     NaN
20               B.B.             NaN  Ramona     NaN      NaN    NaN     NaN
21              Sonja            Rudy     NaN     NaN      NaN    NaN     NaN

     Merged tribe                                                        \
                7        8        9       10       11       12       13
0              21       24       27       30       33       36       37
1         Rattana  Rattana  Rattana  Rattana  Rattana  Rattana  Rattana
2        Gretchen     Greg    Jenna  Gervase  Colleen     Sean   Tie[a]
3   4–1–1–1–1–1–1      6–3    4–3–1      5–2      4–2      4–1      2–2
4             NaN      NaN      NaN      NaN      NaN      NaN      NaN
5           Votes    Votes    Votes    Votes    Votes    Votes    Votes
6        Gretchen     Greg    Jenna  Gervase  Colleen     Sean    Susan
7        Gretchen     Greg     Sean  Gervase     Sean     Sean  Richard
8        Gretchen     Greg    Jenna  Gervase  Colleen     Sean    Susan
9        Gretchen     Greg    Jenna  Gervase  Colleen     Sean  Richard
10        Colleen     Greg    Jenna  Gervase  Colleen    Susan      NaN
11        Richard    Jenna  Richard     Sean     Sean      NaN      NaN
12          Susan    Jenna  Richard     Sean      NaN      NaN      NaN
13        Gervase     Greg  Richard      NaN      NaN      NaN      NaN
14          Jenna    Jenna      NaN      NaN      NaN      NaN      NaN
15           Rudy      NaN      NaN      NaN      NaN      NaN      NaN
16            NaN      NaN      NaN      NaN      NaN      NaN      NaN
17            NaN      NaN      NaN      NaN      NaN      NaN      NaN
18            NaN      NaN      NaN      NaN      NaN      NaN      NaN
19            NaN      NaN      NaN      NaN      NaN      NaN      NaN
20            NaN      NaN      NaN      NaN      NaN      NaN      NaN
21            NaN      NaN      NaN      NaN      NaN      NaN      NaN


       13.1     13.2
0        37       38
1   Rattana  Rattana
2     Susan     Rudy
3       2–0      1–0
4       NaN      NaN
5     Votes    Votes
6   None[b]  None[c]
7     Susan     Rudy
8     Susan  None[c]
9   None[b]      NaN
10      NaN      NaN
11      NaN      NaN
12      NaN      NaN
13      NaN      NaN
14      NaN      NaN
15      NaN      NaN
16      NaN      NaN
17      NaN      NaN
18      NaN      NaN
19      NaN      NaN
20      NaN      NaN
21      NaN      NaN

In [ ]:
richard_row = df[df[('Unnamed: 0_level_0', 'Episode')] == 'Richard']
print(richard_row)

  Unnamed: 0_level_0 Original tribes                               \
             Episode               1    2       3    4     5    6
6            Richard          Stacey  NaN  Stacey  NaN  Dirk  NaN

  Merged tribe
             7     8      9       10       11    12     13     13.1     13.2
6     Gretchen  Greg  Jenna  Gervase  Colleen  Sean  Susan  None[b]  None[c]

## Season 2

In [ ]:
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
}

r = requests.get('https://en.wikipedia.org/wiki/Survivor:_The_Australian_Outback', headers=headers)
html_contents = r.text
html_soup = BeautifulSoup(html_contents,"lxml")

In [ ]:
len(html_soup.find_all('table'))

8

In [ ]:
tables = html_soup.find_all('table',class_="wikitable")
tables[0].find_all('a')

[<a href="/wiki/Milan,_New_Hampshire" title="Milan, New Hampshire">Milan,<br/>New Hampshire</a>,
 <a class="mw-redirect" href="/wiki/Fort_Cavazos" title="Fort Cavazos">Fort Hood,<br/>Texas</a>,
 <a href="/wiki/Wakefield,_Virginia" title="Wakefield, Virginia">Wakefield,<br/>Virginia</a>,
 <a href="/wiki/Union_City,_New_Jersey" title="Union City, New Jersey">Union City,<br/>New Jersey</a>,
 <a href="/wiki/Ronkonkoma,_New_York" title="Ronkonkoma, New York">Ronkonkoma,<br/>New York</a>,
 <a href="/wiki/Michael_Skupin" title="Michael Skupin">Michael Skupin</a>,
 <a href="/wiki/White_Lake_Township,_Michigan" title="White Lake Township, Michigan">White Lake,<br/>Michigan</a>,
 <a href="/wiki/Jeff_Varner" title="Jeff Varner">Jeff Varner</a>,
 <a href="/wiki/Manhattan" title="Manhattan">Manhattan,<br/>New York</a>,
 <a href="/wiki/Manhattan" title="Manhattan">Manhattan,<br/>New York</a>,
 <a href="/wiki/Jerri_Manthey" title="Jerri Manthey">Jerri Manthey</a>,
 <a href="/wiki/Los_Angeles" title="Los Angeles">Los Angeles,<br/>California</a>,
 <a href="/wiki/Nicholas_W._Brown_(lawyer)" title="Nicholas W. Brown (lawyer)">Nick Brown</a>,
 <a href="/wiki/Steilacoom,_Washington" title="Steilacoom, Washington">Steilacoom,<br/>Washington</a>,
 <a href="/wiki/Amber_Mariano" title="Amber Mariano">Amber Brkich</a>,
 <a href="/wiki/Beaver,_Pennsylvania" title="Beaver, Pennsylvania">Beaver,<br/>Pennsylvania</a>,
 <a href="/wiki/Crittenden,_Kentucky" title="Crittenden, Kentucky">Crittenden,<br/>Kentucky</a>,
 <a href="/wiki/Elisabeth_Hasselbeck" title="Elisabeth Hasselbeck">Elisabeth Filarski</a>,
 <a href="/wiki/Newton,_Massachusetts" title="Newton, Massachusetts">Newton,<br/>Massachusetts</a>,
 <a href="/wiki/Keith_Famie" title="Keith Famie">Keith Famie</a>,
 <a href="/wiki/West_Bloomfield_Township,_Michigan" title="West Bloomfield Township, Michigan"><span class="nowrap">West Bloomfield,</span><br/>Michigan</a>,
 <a href="/wiki/Colby_Donaldson" title="Colby Donaldson">Colby Donaldson</a>,
 <a href="/wiki/Dallas" title="Dallas">Dallas,<br/>Texas</a>,
 <a href="/wiki/Knoxville,_Tennessee" title="Knoxville, Tennessee">Knoxville,<br/>Tennessee</a>]

In [ ]:
df = pd.read_html(str(tables))[3]
df

/tmp/ipykernel_3126/1238544221.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(tables))[3]

   Unnamed: 0_level_0 Original tribes                                        \
              Episode               1       2         3         4       4.1
0                 Day               3       6         9        12        12
1               Tribe           Kucha  Ogakor    Ogakor    Ogakor    Ogakor
2          Eliminated            Debb     Kel   Maralyn    Tie[a]    Tie[b]
3               Votes             7–1     7–1     5–1–1       3–3       2–2
4                 NaN             NaN     NaN       NaN       NaN       NaN
5               Voter           Votes   Votes     Votes     Votes     Votes
6                Tina             NaN     Kel   Maralyn  Mitchell  Mitchell
7               Colby             NaN     Kel   Maralyn  Mitchell  Mitchell
8               Keith             NaN     Kel  Mitchell  Mitchell   None[g]
9           Elisabeth            Debb     NaN       NaN       NaN       NaN
10             Rodger            Debb     NaN       NaN       NaN       NaN
11              Amber             NaN     Kel   Maralyn     Keith     Keith
12               Nick            Debb     NaN       NaN       NaN       NaN
13              Jerri             NaN     Kel   Maralyn     Keith     Keith
14             Alicia            Debb     NaN       NaN       NaN       NaN
15               Jeff            Debb     NaN       NaN       NaN       NaN
16            Michael            Debb     NaN       NaN       NaN       NaN
17              Kimmi            Debb     NaN       NaN       NaN       NaN
18           Mitchell             NaN     Kel   Maralyn     Keith   None[g]
19            Maralyn             NaN     Kel     Jerri       NaN       NaN
20                Kel             NaN   Jerri       NaN       NaN       NaN
21               Debb            Jeff     NaN       NaN       NaN       NaN

                                      Merged tribe                            \
             4.2      5             6            7         7.1           7.2
0             12     15            17           21          21            21
1         Ogakor  Kucha         Kucha   Barramundi  Barramundi    Barramundi
2       Mitchell  Kimmi       Michael       Tie[a]      Tie[c]          Jeff
3   Countback[b]    6–1  Evacuated[d]          5–5         4–4  Countback[c]
4            NaN    NaN           NaN          NaN         NaN           NaN
5          Votes  Votes         Votes        Votes       Votes         Votes
6            NaN    NaN           NaN         Jeff        Jeff           NaN
7            NaN    NaN           NaN         Jeff     None[f]    0 Votes[c]
8     0 Votes[b]    NaN           NaN         Jeff        Jeff           NaN
9            NaN  Kimmi           NaN        Colby       Colby           NaN
10           NaN  Kimmi           NaN        Colby       Colby           NaN
11           NaN    NaN           NaN         Jeff        Jeff           NaN
12           NaN  Kimmi           NaN        Colby       Colby           NaN
13           NaN    NaN           NaN         Jeff        Jeff           NaN
14           NaN  Kimmi           NaN        Colby       Colby           NaN
15           NaN  Kimmi           NaN        Colby     None[f]    2 Votes[c]
16           NaN  Kimmi     Evacuated          NaN         NaN           NaN
17           NaN   Jeff           NaN          NaN         NaN           NaN
18     1 Vote[b]    NaN           NaN          NaN         NaN           NaN
19           NaN    NaN           NaN          NaN         NaN           NaN
20           NaN    NaN           NaN          NaN         NaN           NaN
21           NaN    NaN           NaN          NaN         NaN           NaN

                                                                            \
             8          10          11          12          13          14
0           24          27          30          33          36          39
1   Barramundi  Barramundi  Barramundi  Barramundi  Barramundi  Barramundi
2       Alicia       Jerri        Nick       Amber      Rodger   Elisabeth
3          5–4         6–2       4–2–1         4–2         3–2         3–1
4          NaN         NaN         NaN         NaN         NaN         NaN
5        Votes       Votes       Votes       Votes       Votes       Votes
6       Alicia       Jerri        Nick       Amber      Rodger   Elisabeth
7       Alicia       Jerri        Nick      Rodger      Rodger   Elisabeth
8       Alicia       Jerri        Nick       Amber      Rodger   Elisabeth
9        Jerri       Jerri       Amber       Amber       Keith       Keith
10       Jerri       Jerri       Amber       Amber       Keith         NaN
11      Alicia   Elisabeth        Nick      Rodger         NaN         NaN
12       Jerri       Jerri       Keith         NaN         NaN         NaN
13      Alicia   Elisabeth         NaN         NaN         NaN         NaN
14       Jerri         NaN         NaN         NaN         NaN         NaN
15         NaN         NaN         NaN         NaN         NaN         NaN
16         NaN         NaN         NaN         NaN         NaN         NaN
17         NaN         NaN         NaN         NaN         NaN         NaN
18         NaN         NaN         NaN         NaN         NaN         NaN
19         NaN         NaN         NaN         NaN         NaN         NaN
20         NaN         NaN         NaN         NaN         NaN         NaN
21         NaN         NaN         NaN         NaN         NaN         NaN


            15
0           41
1   Barramundi
2        Keith
3          1–0
4          NaN
5        Votes
6      None[e]
7        Keith
8      None[e]
9          NaN
10         NaN
11         NaN
12         NaN
13         NaN
14         NaN
15         NaN
16         NaN
17         NaN
18         NaN
19         NaN
20         NaN
21         NaN

In [ ]:
tina_row = df[df[('Unnamed: 0_level_0', 'Episode')] == 'Tina']
print(tina_row)

  Unnamed: 0_level_0 Original tribes                                         \
             Episode               1    2        3         4       4.1  4.2
6               Tina             NaN  Kel  Maralyn  Mitchell  Mitchell  NaN

            Merged tribe                                                 \
     5    6            7   7.1  7.2       8     10    11     12      13
6  NaN  NaN         Jeff  Jeff  NaN  Alicia  Jerri  Nick  Amber  Rodger


          14       15
6  Elisabeth  None[e]

## Survivor 3

In [ ]:
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
}

r = requests.get('https://en.wikipedia.org/wiki/Survivor:_Africa', headers=headers)
html_contents = r.text
html_soup = BeautifulSoup(html_contents,"lxml")

In [ ]:
tables = html_soup.find_all('table',class_="wikitable")
tables[0].find_all('a')

[<a href="/wiki/Lincoln,_Nebraska" title="Lincoln, Nebraska">Lincoln,<br/>Nebraska</a>,
 <a href="/wiki/Orlando,_Florida" title="Orlando, Florida">Orlando,<br/>Florida</a>,
 <a href="/wiki/Winter_Springs,_Florida" title="Winter Springs, Florida">Winter Springs,<br/>Florida</a>,
 <a href="/wiki/Boston" title="Boston">Boston,<br/>Massachusetts</a>,
 <a href="/wiki/Los_Angeles" title="Los Angeles">Los Angeles,<br/>California</a>,
 <a href="/wiki/Portland,_Oregon" title="Portland, Oregon">Portland,<br/>Oregon</a>,
 <a href="/wiki/Detroit" title="Detroit">Detroit,<br/>Michigan</a>,
 <a href="/wiki/Kelly_Goldsmith" title="Kelly Goldsmith">Kelly Goldsmith</a>,
 <a href="/wiki/San_Diego" title="San Diego">San Diego,<br/>California</a>,
 <a href="/wiki/Dallas" title="Dallas">Dallas,<br/>Texas</a>,
 <a href="/wiki/Odessa,_New_York" title="Odessa, New York">Odessa,<br/>New York</a>,
 <a href="/wiki/Conshohocken,_Pennsylvania" title="Conshohocken, Pennsylvania">Conshohocken,<br/>Pennsylvania</a>,
 <a href="/wiki/Jackson,_Georgia" title="Jackson, Georgia">Jackson,<br/>Georgia</a>,
 <a href="/wiki/Rich_Valley,_Virginia" title="Rich Valley, Virginia">Rich Valley,<br/>Virginia</a>,
 <a href="/wiki/Santa_Cruz,_California" title="Santa Cruz, California">Santa Cruz,<br/>California</a>,
 <a href="/wiki/Oyster_Bay,_New_York" title="Oyster Bay, New York">Oyster Bay,<br/>New York</a>,
 <a href="/wiki/Ethan_Zohn" title="Ethan Zohn">Ethan Zohn</a>,
 <a href="/wiki/New_York_City" title="New York City">New York City,<br/>New York</a>]

In [ ]:
df = pd.read_html(str(tables))[3]
df

/tmp/ipykernel_3126/1238544221.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(tables))[3]

   Unnamed: 0_level_0 Original tribes                              \
              Episode               1         2        3      3.1
0                 Day               3         6        9        9
1               Tribe           Boran     Boran  Samburu  Samburu
2          Eliminated           Diane    Jessie   Tie[a]   Tie[b]
3                Vote             6–2       5–2      4–4      3–3
4                 NaN             NaN       NaN      NaN      NaN
5               Voter           Votes     Votes    Votes    Votes
6               Ethan           Diane    Jessie      NaN      NaN
7              Kim J.           Diane    Jessie      NaN      NaN
8                 Lex           Diane    Jessie      NaN      NaN
9                 Tom        Clarence  Clarence      NaN      NaN
10             Teresa             NaN       NaN  Lindsey  Lindsey
11             Kim P.             NaN       NaN     Carl     Carl
12              Frank             NaN       NaN  Lindsey  Lindsey
13            Brandon             NaN       NaN     Carl     Carl
14              Kelly           Diane    Jessie      NaN      NaN
15           Clarence           Diane    Jessie      NaN      NaN
16            Lindsey             NaN       NaN     Carl  None[f]
17              Silas             NaN       NaN     Carl     Carl
18              Linda             NaN       NaN  Lindsey  Lindsey
19               Carl             NaN       NaN  Lindsey  None[f]
20             Jessie           Diane  Clarence      NaN      NaN
21              Diane        Clarence       NaN      NaN      NaN

                          Switched tribes                                  \
             3.2        4               5        6      6.1           6.2
0              9       12              15       18       18            18
1        Samburu  Samburu           Boran  Samburu  Samburu       Samburu
2           Carl    Linda           Silas   Tie[a]   Tie[c]       Lindsey
3   Challenge[b]      4–3             5–1      3–3      2–2  Countback[c]
4            NaN      NaN             NaN      NaN      NaN           NaN
5          Votes    Votes           Votes    Votes    Votes         Votes
6            NaN      NaN           Silas      NaN      NaN           NaN
7            NaN      NaN           Silas      NaN      NaN           NaN
8            NaN      NaN             NaN  Lindsey  Lindsey           NaN
9            NaN      NaN             NaN  Lindsey  None[e]    0 Votes[c]
10           NaN    Silas           Silas      NaN      NaN           NaN
11           NaN    Linda             NaN      Tom      Tom           NaN
12           NaN    Silas           Silas      NaN      NaN           NaN
13           NaN    Linda             NaN      Tom      Tom           NaN
14           NaN      NaN             NaN  Lindsey  Lindsey           NaN
15           NaN      NaN           Silas      NaN      NaN           NaN
16        Won[b]    Linda             NaN      Tom  None[e]    4 Votes[c]
17           NaN    Linda           Frank      NaN      NaN           NaN
18           NaN    Silas             NaN      NaN      NaN           NaN
19       Lost[b]      NaN             NaN      NaN      NaN           NaN
20           NaN      NaN             NaN      NaN      NaN           NaN
21           NaN      NaN             NaN      NaN      NaN           NaN

   Merged tribe                                                         \
              7          9         10         11         12         13
0            21         24         27         30         33         36
1     Moto Maji  Moto Maji  Moto Maji  Moto Maji  Moto Maji  Moto Maji
2      Clarence      Kelly    Brandon      Frank     Kim P.     Teresa
3           8–2        5–4        6–2        6–1        4–2        4–1
4           NaN        NaN        NaN        NaN        NaN        NaN
5         Votes      Votes      Votes      Votes      Votes      Votes
6      Clarence      Kelly    Brandon      Frank     Kim P.     Teresa
7      Clarence      Kelly    Brandon      Frank     Kim P.     Teresa
8      Clarence      Kelly      Frank      Frank     Kim P.     Teresa
9      Clarence      Kelly    Brandon      Frank     Kim P.     Teresa
10          Lex        Lex    Brandon      Frank        Lex        Tom
11     Clarence        Lex    Brandon      Frank        Lex        NaN
12     Clarence        Lex    Brandon     Kim J.        NaN        NaN
13     Clarence      Kelly      Frank        NaN        NaN        NaN
14     Clarence        Lex        NaN        NaN        NaN        NaN
15          Lex        NaN        NaN        NaN        NaN        NaN
16          NaN        NaN        NaN        NaN        NaN        NaN
17          NaN        NaN        NaN        NaN        NaN        NaN
18          NaN        NaN        NaN        NaN        NaN        NaN
19          NaN        NaN        NaN        NaN        NaN        NaN
20          NaN        NaN        NaN        NaN        NaN        NaN
21          NaN        NaN        NaN        NaN        NaN        NaN


           14       14.1
0          37         38
1   Moto Maji  Moto Maji
2         Tom        Lex
3         3–1        1–0
4         NaN        NaN
5       Votes      Votes
6         Tom    None[d]
7         Tom        Lex
8         Tom    None[d]
9         Lex        NaN
10        NaN        NaN
11        NaN        NaN
12        NaN        NaN
13        NaN        NaN
14        NaN        NaN
15        NaN        NaN
16        NaN        NaN
17        NaN        NaN
18        NaN        NaN
19        NaN        NaN
20        NaN        NaN
21        NaN        NaN

In [ ]:
ethan_row = df[df[('Unnamed: 0_level_0', 'Episode')] == 'Ethan']
print(ethan_row)

  Unnamed: 0_level_0 Original tribes                              \
             Episode               1       2    3  3.1  3.2    4
6              Ethan           Diane  Jessie  NaN  NaN  NaN  NaN

  Switched tribes                Merged tribe                                 \
                5    6  6.1  6.2            7      9       10     11      12
6           Silas  NaN  NaN  NaN     Clarence  Kelly  Brandon  Frank  Kim P.


       13   14     14.1
6  Teresa  Tom  None[d]

## Survivor 4

In [ ]:
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
}

r = requests.get('https://en.wikipedia.org/wiki/Survivor:_Marquesas', headers=headers)
html_contents = r.text
html_soup = BeautifulSoup(html_contents,"lxml")

In [ ]:
tables = html_soup.find_all('table',class_="wikitable")
tables[0].find_all('a')

[<a href="/wiki/Millis,_Massachusetts" title="Millis, Massachusetts">Millis,<br/>Massachusetts</a>,
 <a href="/wiki/Lugoff,_South_Carolina" title="Lugoff, South Carolina">Lugoff,<br/>South Carolina</a>,
 <a href="/wiki/Hunter_Ellis" title="Hunter Ellis">Hunter Ellis</a>,
 <a href="/wiki/La_Jolla" title="La Jolla">La Jolla,<br/>California</a>,
 <a href="/wiki/Newport_Beach,_California" title="Newport Beach, California"><span class="nowrap">Newport Beach,</span><br/>California</a>,
 <a href="/wiki/Hollywood,_Los_Angeles" title="Hollywood, Los Angeles">Hollywood,<br/>California</a>,
 <a href="/wiki/Gainesville,_Florida" title="Gainesville, Florida">Gainesville,<br/>Florida</a>,
 <a href="/wiki/Rob_Mariano" title="Rob Mariano">Rob Mariano</a>,
 <a href="/wiki/Canton,_Massachusetts" title="Canton, Massachusetts">Canton,<br/>Massachusetts</a>,
 <a href="/wiki/Omaha,_Nebraska" title="Omaha, Nebraska">Omaha,<br/>Nebraska</a>,
 <a href="/wiki/Monhegan,_Maine" title="Monhegan, Maine">Monhegan,<br/>Maine</a>,
 <a href="/wiki/Tammy_Leitner" title="Tammy Leitner">Tammy Leitner</a>,
 <a href="/wiki/Mesa,_Arizona" title="Mesa, Arizona">Mesa,<br/>Arizona</a>,
 <a class="mw-redirect" href="/wiki/College_Point,_Queens" title="College Point, Queens">College Point,<br/>New York</a>,
 <a href="/wiki/Harlem" title="Harlem">Harlem,<br/>New York</a>,
 <a href="/wiki/Paschal_English" title="Paschal English">Paschal English</a>,
 <a href="/wiki/Thomaston,_Georgia" title="Thomaston, Georgia">Thomaston,<br/>Georgia</a>,
 <a href="#cite_note-3"><span class="cite-bracket">[</span>a<span class="cite-bracket">]</span></a>,
 <a href="/wiki/Burlington,_Vermont" title="Burlington, Vermont">Burlington,<br/>Vermont</a>,
 <a href="/wiki/Layton,_Utah" title="Layton, Utah">Layton,<br/>Utah</a>,
 <a href="/wiki/Hayward,_California" title="Hayward, California">Hayward,<br/>California</a>]

In [ ]:
df = pd.read_html(str(tables))[3]
df

/tmp/ipykernel_3126/1238544221.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(tables))[3]

   Unnamed: 0_level_0 Original tribes                    Switched tribes  \
              Episode               1         2        3               4
0                 Day               3         6        9              12
1               Tribe         Maraamu   Maraamu  Maraamu         Maraamu
2          Eliminated           Peter  Patricia   Hunter           Sarah
3               Votes           5–2–1       4–3      4–2             4–1
4                 NaN             NaN       NaN      NaN             NaN
5               Voter           Votes     Votes    Votes           Votes
6             Vecepia           Sarah  Patricia   Hunter             NaN
7               Neleh             NaN       NaN      NaN           Sarah
8               Kathy             NaN       NaN      NaN           Sarah
9             Paschal             NaN       NaN      NaN           Sarah
10               Sean           Sarah  Patricia   Hunter             NaN
11             Robert             NaN       NaN      NaN             NaN
12              Tammy             NaN       NaN      NaN             NaN
13                Zoe             NaN       NaN      NaN             NaN
14               John             NaN       NaN      NaN             NaN
15                Rob           Peter  Patricia   Hunter             NaN
16               Gina           Peter     Sarah    Sarah           Sarah
17            Gabriel             NaN       NaN      NaN             NaN
18              Sarah           Peter  Patricia   Hunter           Kathy
19             Hunter           Peter     Sarah    Sarah             NaN
20           Patricia           Peter     Sarah      NaN             NaN
21              Peter        Patricia       NaN      NaN             NaN

                     Merged tribe                                          \
          5        6            7         8        10        11        12
0        15       18           21        24        27        30        33
1      Rotu  Maraamu     Soliantu  Soliantu  Soliantu  Soliantu  Soliantu
2   Gabriel     Gina          Rob      John       Zoe     Tammy    Robert
3       7–1      3–1        7–2–1       6–3       7–1       5–2       5–1
4       NaN      NaN          NaN       NaN       NaN       NaN       NaN
5     Votes    Votes        Votes     Votes     Votes     Votes     Votes
6   Gabriel      NaN          Rob      John       Zoe     Tammy    Robert
7       NaN     Gina          Rob      John       Zoe     Tammy    Robert
8       NaN     Gina          Zoe      John       Zoe     Tammy    Robert
9       NaN     Gina          Rob      John       Zoe     Tammy    Robert
10  Gabriel      NaN         John      John       Zoe     Tammy    Robert
11  Gabriel      NaN          Rob      Sean       Zoe   Vecepia      Sean
12  Gabriel      NaN          Rob      Sean       Zoe   Vecepia       NaN
13  Gabriel      NaN          Rob      John    Robert       NaN       NaN
14  Gabriel      NaN          Rob      Sean       NaN       NaN       NaN
15  Gabriel      NaN         John       NaN       NaN       NaN       NaN
16      NaN    Kathy          NaN       NaN       NaN       NaN       NaN
17      Rob      NaN          NaN       NaN       NaN       NaN       NaN
18      NaN      NaN          NaN       NaN       NaN       NaN       NaN
19      NaN      NaN          NaN       NaN       NaN       NaN       NaN
20      NaN      NaN          NaN       NaN       NaN       NaN       NaN
21      NaN      NaN          NaN       NaN       NaN       NaN       NaN


          13        14          14.1      14.2
0         36        37            37        38
1   Soliantu  Soliantu      Soliantu  Soliantu
2       Sean    Tie[a]       Paschal     Kathy
3        3–2       2–2  Rock Draw[b]       1–0
4        NaN       NaN           NaN       NaN
5      Votes     Votes         Votes     Votes
6      Neleh     Neleh        Immune   None[c]
7       Sean     Kathy   Yellow rock     Kathy
8       Sean     Neleh   Yellow rock   None[c]
9       Sean     Kathy   Purple rock       NaN
10     Neleh       NaN           NaN       NaN
11       NaN       NaN           NaN       NaN
12       NaN       NaN           NaN       NaN
13       NaN       NaN           NaN       NaN
14       NaN       NaN           NaN       NaN
15       NaN       NaN           NaN       NaN
16       NaN       NaN           NaN       NaN
17       NaN       NaN           NaN       NaN
18       NaN       NaN           NaN       NaN
19       NaN       NaN           NaN       NaN
20       NaN       NaN           NaN       NaN
21       NaN       NaN           NaN       NaN

In [ ]:
vecepia_row = df[df[('Unnamed: 0_level_0', 'Episode')] == 'Vecepia']
print(vecepia_row)

  Unnamed: 0_level_0 Original tribes                   Switched tribes  \
             Episode               1         2       3               4
6            Vecepia           Sarah  Patricia  Hunter             NaN

                Merged tribe                                                  \
         5    6            7     8   10     11      12     13     14    14.1
6  Gabriel  NaN          Rob  John  Zoe  Tammy  Robert  Neleh  Neleh  Immune


      14.2
6  None[c]

## Survivor 5

In [ ]:
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
}

r = requests.get('https://en.wikipedia.org/wiki/Survivor:_Thailand', headers=headers)
html_contents = r.text
html_soup = BeautifulSoup(html_contents,"lxml")

In [ ]:
tables = html_soup.find_all('table',class_="wikitable")
tables[0].find_all('a')

[<a href="/wiki/Slidell,_Louisiana" title="Slidell, Louisiana">Slidell,<br/>Louisiana</a>,
 <a href="/wiki/Gray,_Tennessee" title="Gray, Tennessee">Gray,<br/>Tennessee</a>,
 <a href="/wiki/Dallas" title="Dallas">Dallas,<br/>Texas</a>,
 <a href="/wiki/Denver" title="Denver">Denver,<br/>Colorado</a>,
 <a href="/wiki/Ozark,_Arkansas" title="Ozark, Arkansas">Ozark,<br/>Arkansas</a>,
 <a href="/wiki/Scottsdale,_Arizona" title="Scottsdale, Arizona">Scottsdale,<br/>Arizona</a>,
 <a href="/wiki/New_York_City" title="New York City">New York City,<br/>New York</a>,
 <a href="/wiki/Austin,_Texas" title="Austin, Texas">Austin,<br/>Texas</a>,
 <a href="/wiki/Brooklyn" title="Brooklyn">Brooklyn,<br/>New York</a>,
 <a href="/wiki/Plano,_Texas" title="Plano, Texas">Plano,<br/>Texas</a>,
 <a href="/wiki/McKinney,_Texas" title="McKinney, Texas">McKinney,<br/>Texas</a>,
 <a href="/wiki/Durham,_North_Carolina" title="Durham, North Carolina">Durham,<br/><span class="nowrap">North Carolina</span></a>,
 <a href="/wiki/Helen_Glover_(Survivor_contestant)" title="Helen Glover (Survivor contestant)">Helen Glover</a>,
 <a href="/wiki/Middletown,_Rhode_Island" title="Middletown, Rhode Island">Middletown,<br/>Rhode Island</a>,
 <a href="/wiki/Tampa,_Florida" title="Tampa, Florida">Tampa,<br/>Florida</a>,
 <a href="/wiki/Monroe,_Louisiana" title="Monroe, Louisiana">Monroe,<br/>Louisiana</a>,
 <a href="/wiki/Quartz_Hill,_California" title="Quartz Hill, California">Quartz Hill,<br/>California</a>]

In [ ]:
df = pd.read_html(str(tables))[3]
df

/tmp/ipykernel_3126/1238544221.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(tables))[3]

   Unnamed: 0_level_0 Original tribes                                    \
              Episode               1           2         3           4
0                 Day               3           6         9          12
1               Tribe      Chuay Gahn  Chuay Gahn  Sook Jai  Chuay Gahn
2          Eliminated            John       Tanya       Jed     Ghandia
3               Votes           6–1–1         5–2       5–3         4–2
4                 NaN             NaN         NaN       NaN         NaN
5               Voter           Votes       Votes     Votes       Votes
6               Brian            John       Tanya       NaN     Ghandia
7                Clay            John       Tanya       NaN     Ghandia
8                 Jan            John       Tanya       NaN        Clay
9               Helen            Clay       Tanya       NaN     Ghandia
10                Ted            John       Tanya       NaN     Ghandia
11               Jake             NaN         NaN       Jed         NaN
12              Penny             NaN         NaN       Jed         NaN
13                Ken             NaN         NaN       Jed         NaN
14               Erin             NaN         NaN       Jed         NaN
15           Shii Ann             NaN         NaN       Jed         NaN
16               Robb             NaN         NaN  Shii Ann         NaN
17          Stephanie             NaN         NaN  Shii Ann         NaN
18            Ghandia            John       Helen       NaN        Clay
19                Jed             NaN         NaN  Shii Ann         NaN
20              Tanya            John       Helen       NaN         NaN
21               John         Ghandia         NaN       NaN         NaN

                                            Merged tribe             \
            5         6         7         8            9         10
0          15        18        21        24           27         30
1    Sook Jai  Sook Jai  Sook Jai  Sook Jai    Chuay Jai  Chuay Jai
2   Stephanie      Robb  Shii Ann      Erin          Ken      Penny
3         5–2       5–1       4–1       3–1          5–3      4–2–1
4         NaN       NaN       NaN       NaN          NaN        NaN
5       Votes     Votes     Votes     Votes        Votes      Votes
6         NaN       NaN       NaN       NaN          Ken      Penny
7         NaN       NaN       NaN       NaN          Ken       Jake
8         NaN       NaN       NaN       NaN          Ken      Penny
9         NaN       NaN       NaN       NaN          Ken      Penny
10        NaN       NaN       NaN       NaN          Ken      Penny
11  Stephanie      Robb  Shii Ann      Erin          Ted        Jan
12  Stephanie      Robb  Shii Ann      Erin          Ted       Jake
13  Stephanie      Robb  Shii Ann      Erin          Ted        NaN
14  Stephanie      Robb  Shii Ann       Ken          NaN        NaN
15  Stephanie      Robb     Penny       NaN          NaN        NaN
16   Shii Ann  Shii Ann       NaN       NaN          NaN        NaN
17   Shii Ann       NaN       NaN       NaN          NaN        NaN
18        NaN       NaN       NaN       NaN          NaN        NaN
19        NaN       NaN       NaN       NaN          NaN        NaN
20        NaN       NaN       NaN       NaN          NaN        NaN
21        NaN       NaN       NaN       NaN          NaN        NaN


           12         13         14       14.1
0          33         36         37         38
1   Chuay Jai  Chuay Jai  Chuay Jai  Chuay Jai
2        Jake        Ted      Helen        Jan
3         5–1        4–1        3–1        1–0
4         NaN        NaN        NaN        NaN
5       Votes      Votes      Votes      Votes
6        Jake        Ted      Helen        Jan
7        Jake        Ted      Helen    None[a]
8        Jake        Ted      Helen    None[a]
9        Jake        Ted        Jan        NaN
10       Jake        Jan        NaN        NaN
11        Jan        NaN        NaN        NaN
12        NaN        NaN        NaN        NaN
13        NaN        NaN        NaN        NaN
14        NaN        NaN        NaN        NaN
15        NaN        NaN        NaN        NaN
16        NaN        NaN        NaN        NaN
17        NaN        NaN        NaN        NaN
18        NaN        NaN        NaN        NaN
19        NaN        NaN        NaN        NaN
20        NaN        NaN        NaN        NaN
21        NaN        NaN        NaN        NaN

In [ ]:
brian_row = df[df[('Unnamed: 0_level_0', 'Episode')] == 'Brian']
print(brian_row)

  Unnamed: 0_level_0 Original tribes                                           \
             Episode               1      2    3        4    5    6    7    8
6              Brian            John  Tanya  NaN  Ghandia  NaN  NaN  NaN  NaN

  Merged tribe
             9     10    12   13     14 14.1
6          Ken  Penny  Jake  Ted  Helen  Jan

## Survivor 6

In [ ]:
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
}

r = requests.get('https://en.wikipedia.org/wiki/Survivor:_The_Amazon', headers=headers)
html_contents = r.text
html_soup = BeautifulSoup(html_contents,"lxml")

In [ ]:
tables = html_soup.find_all('table',class_="wikitable")
tables[0].find_all('a')

[<a href="/wiki/Ellicott_City,_Maryland" title="Ellicott City, Maryland">Ellicott City,<br/>Maryland</a>,
 <a href="/wiki/Manchester,_Missouri" title="Manchester, Missouri">Manchester,<br/>Missouri</a>,
 <a href="/wiki/Houston" title="Houston">Houston,<br/>Texas</a>,
 <a href="/wiki/Orangeburg,_South_Carolina" title="Orangeburg, South Carolina">Orangeburg,<br/>South Carolina</a>,
 <a href="/wiki/North_Attleborough,_Massachusetts" title="North Attleborough, Massachusetts"><span class="nowrap">North Attleborough,</span><br/>Massachusetts</a>,
 <a href="/wiki/Los_Angeles" title="Los Angeles">Los Angeles,<br/>California</a>,
 <a href="/wiki/Valencia,_Santa_Clarita,_California" title="Valencia, Santa Clarita, California">Valencia,<br/>California</a>,
 <a href="/wiki/Pasadena,_California" title="Pasadena, California">Pasadena,<br/>California</a>,
 <a href="/wiki/Riverside,_California" title="Riverside, California">Riverside,<br/>California</a>,
 <a href="/wiki/Los_Angeles" title="Los Angeles">Los Angeles,<br/>California</a>,
 <a href="/wiki/Christy_Smith_(Survivor_contestant)" title="Christy Smith (Survivor contestant)">Christy Smith</a>,
 <a href="/wiki/Basalt,_Colorado" title="Basalt, Colorado">Basalt,<br/>Colorado</a>,
 <a href="/wiki/Jefferson_City,_Missouri" title="Jefferson City, Missouri">Jefferson City,<br/>Missouri</a>,
 <a href="/wiki/Olney,_Illinois" title="Olney, Illinois">Olney,<br/>Illinois</a>,
 <a href="/wiki/Rob_Cesternino" title="Rob Cesternino">Rob Cesternino</a>,
 <a href="/wiki/Wantagh,_New_York" title="Wantagh, New York">Wantagh,<br/>New York</a>,
 <a href="/wiki/Washington,_D.C." title="Washington, D.C.">Washington,<br/>D.C.</a>,
 <a href="/wiki/Jenna_Morasca" title="Jenna Morasca">Jenna Morasca</a>,
 <a href="/wiki/Bridgeville,_Pennsylvania" title="Bridgeville, Pennsylvania">Bridgeville,<br/>Pennsylvania</a>]

In [ ]:
df = pd.read_html(str(tables))[3]
df

/tmp/ipykernel_3126/1238544221.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(tables))[3]

   Unnamed: 0_level_0 Original tribes                              \
              Episode               1        2         3        4
0                 Day               3        6         9       12
1               Tribe        Tambaqui   Jaburu  Tambaqui   Jaburu
2          Eliminated            Ryan    Janet    Daniel   JoAnna
3               Votes           4–3–1  5–1–1–1       6–1    4–2–1
4                 NaN             NaN      NaN       NaN      NaN
5               Voter           Votes    Votes     Votes    Votes
6               Jenna             NaN    Janet       NaN   JoAnna
7             Matthew           Roger      NaN    Daniel      NaN
8                 Rob            Ryan      NaN    Daniel      NaN
9               Butch            Ryan      NaN    Daniel      NaN
10              Heidi             NaN    Janet       NaN   JoAnna
11            Christy             NaN    Jenna       NaN   JoAnna
12               Alex            Ryan      NaN    Daniel      NaN
13              Deena             NaN    Janet       NaN   JoAnna
14               Dave          Daniel      NaN    Daniel      NaN
15              Roger            Ryan      NaN    Daniel      NaN
16             Shawna             NaN    Janet       NaN  Christy
17             Jeanne             NaN    Janet       NaN   Shawna
18             JoAnna             NaN  Christy       NaN   Shawna
19             Daniel           Roger      NaN     Roger      NaN
20              Janet             NaN   Jeanne       NaN      NaN
21               Ryan           Roger      NaN       NaN      NaN

   Switched tribes          Merged tribe                                     \
                 5        6            7        8       9       11       12
0               15       18           21       24      27       30       33
1         Tambaqui   Jaburu       Jacaré   Jacaré  Jacaré   Jacaré   Jacaré
2           Jeanne   Shawna        Roger     Dave   Deena     Alex  Christy
3              4–2      4–2          7–3      8–1     6–2      4–3      4–2
4              NaN      NaN          NaN      NaN     NaN      NaN      NaN
5            Votes    Votes        Votes    Votes   Votes    Votes    Votes
6              NaN   Shawna        Roger     Dave   Deena  Matthew  Christy
7              NaN   Shawna        Roger     Dave   Deena     Alex  Christy
8              NaN   Shawna        Roger     Dave   Deena     Alex  Christy
9           Jeanne      NaN      Christy     Dave   Deena     Alex    Jenna
10          Jeanne      NaN        Roger     Dave   Deena  Matthew  Christy
11           Butch      NaN        Roger     Dave    Alex     Alex    Jenna
12             NaN  Matthew        Roger     Dave   Deena  Matthew      NaN
13             NaN   Shawna        Roger     Dave    Alex      NaN      NaN
14          Jeanne      NaN      Christy  Matthew     NaN      NaN      NaN
15          Jeanne      NaN      Christy      NaN     NaN      NaN      NaN
16             NaN  Matthew          NaN      NaN     NaN      NaN      NaN
17           Butch      NaN          NaN      NaN     NaN      NaN      NaN
18             NaN      NaN          NaN      NaN     NaN      NaN      NaN
19             NaN      NaN          NaN      NaN     NaN      NaN      NaN
20             NaN      NaN          NaN      NaN     NaN      NaN      NaN
21             NaN      NaN          NaN      NaN     NaN      NaN      NaN


        13      14     14.1
0       36      37       38
1   Jacaré  Jacaré   Jacaré
2    Heidi   Butch      Rob
3      3–2     3–1      1–0
4      NaN     NaN      NaN
5    Votes   Votes    Votes
6      Rob   Butch      Rob
7    Heidi   Butch  None[a]
8    Heidi   Butch  None[a]
9    Heidi     Rob      NaN
10     Rob     NaN      NaN
11     NaN     NaN      NaN
12     NaN     NaN      NaN
13     NaN     NaN      NaN
14     NaN     NaN      NaN
15     NaN     NaN      NaN
16     NaN     NaN      NaN
17     NaN     NaN      NaN
18     NaN     NaN      NaN
19     NaN     NaN      NaN
20     NaN     NaN      NaN
21     NaN     NaN      NaN

In [ ]:
jenna_row = df[df[('Unnamed: 0_level_0', 'Episode')] == 'Jenna']
print(jenna_row)

  Unnamed: 0_level_0 Original tribes                     Switched tribes  \
             Episode               1      2    3       4               5
6              Jenna             NaN  Janet  NaN  JoAnna             NaN

          Merged tribe
        6            7     8      9       11       12   13     14 14.1
6  Shawna        Roger  Dave  Deena  Matthew  Christy  Rob  Butch  Rob

## Survivor 7

In [ ]:
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
}

r = requests.get('https://en.wikipedia.org/wiki/Survivor:_Pearl_Islands', headers=headers)
html_contents = r.text
html_soup = BeautifulSoup(html_contents,"lxml")

In [ ]:
tables = html_soup.find_all('table',class_="wikitable")
tables[0].find_all('a')

[<a href="/wiki/Hermosa_Beach,_California" title="Hermosa Beach, California"><span class="nowrap">Hermosa Beach,</span><br/>California</a>,
 <a href="/wiki/Clarksville,_Tennessee" title="Clarksville, Tennessee">Clarksville,<br/>Tennessee</a>,
 <a href="/wiki/Washington,_D.C." title="Washington, D.C.">Washington,<br/>D.C.</a>,
 <a href="/wiki/Annapolis,_Maryland" title="Annapolis, Maryland">Annapolis,<br/>Maryland</a>,
 <a href="/wiki/Hollywood,_Los_Angeles" title="Hollywood, Los Angeles">Hollywood,<br/>California</a>,
 <a href="/wiki/Boston" title="Boston">Boston,<br/>Massachusetts</a>,
 <a href="/wiki/Chicago" title="Chicago">Chicago,<br/>Illinois</a>,
 <a href="/wiki/Los_Gatos,_California" title="Los Gatos, California">Los Gatos,<br/>California</a>,
 <a href="/wiki/Rupert_Boneham" title="Rupert Boneham">Rupert Boneham</a>,
 <a href="/wiki/Indianapolis" title="Indianapolis">Indianapolis,<br/>Indiana</a>,
 <a href="/wiki/St._Louis" title="St. Louis">St. Louis,<br/>Missouri</a>,
 <a href="/wiki/Los_Angeles" title="Los Angeles">Los Angeles,<br/>California</a>,
 <a href="/wiki/San_Francisco" title="San Francisco">San Francisco,<br/>California</a>,
 <a href="#cite_note-Lillian_and_Burton-1"><span class="cite-bracket">[</span>a<span class="cite-bracket">]</span></a>,
 <a href="/wiki/Liberty,_Mississippi" title="Liberty, Mississippi">Liberty,<br/>Mississippi</a>,
 <a href="/wiki/Jonny_Fairplay" title="Jonny Fairplay">Jon Dalton</a>,
 <a href="/wiki/Los_Angeles" title="Los Angeles">Los Angeles,<br/>California</a>,
 <a href="/wiki/Loveland,_Ohio" title="Loveland, Ohio">Loveland,<br/>Ohio</a>,
 <a href="#cite_note-Lillian_and_Burton-1"><span class="cite-bracket">[</span>a<span class="cite-bracket">]</span></a>,
 <a href="/wiki/Sandra_Diaz-Twine" title="Sandra Diaz-Twine">Sandra Diaz-Twine</a>,
 <a href="/wiki/Fort_Lewis_(Washington)" title="Fort Lewis (Washington)">Fort Lewis,<br/>Washington</a>]

In [ ]:
df = pd.read_html(str(tables))[3]
df

/tmp/ipykernel_3126/1238544221.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(tables))[3]

   Unnamed: 0_level_0 Original tribes                                  \
              Episode               1        2        3             4
0                 Day               3        6        9            12
1               Tribe          Morgan   Morgan   Morgan         Drake
2          Eliminated          Nicole  Ryan S.  Lillian        Burton
3               Votes             7–1      5–2      5–1           5–2
4                 NaN             NaN      NaN      NaN           NaN
5               Voter           Votes    Votes    Votes         Votes
6              Sandra             NaN      NaN      NaN        Burton
7             Lillian          Nicole    Osten   Darrah           NaN
8                 Jon             NaN      NaN      NaN        Burton
9              Darrah          Nicole  Ryan S.  Lillian           NaN
10             Burton             NaN      NaN      NaN       Christa
11            Christa             NaN      NaN      NaN        Burton
12            Tijuana          Nicole  Ryan S.  Lillian           NaN
13             Rupert             NaN      NaN      NaN  Kidnapped[d]
14            Ryan O.          Nicole  Ryan S.  Lillian           NaN
15             Andrew          Nicole  Ryan S.  Lillian           NaN
16              Osten          Nicole  Ryan S.  Lillian           NaN
17              Shawn             NaN      NaN      NaN        Burton
18              Trish             NaN      NaN      NaN        Burton
19           Michelle             NaN      NaN      NaN       Christa
20            Ryan S.          Nicole    Osten      NaN           NaN
21             Nicole         Ryan S.      NaN      NaN           NaN

                     Outcasts twist[a]          Merged tribe                   \
           5       6                 7      7.1            8        9      10
0         15      18                19       19           21       24      27
1      Drake   Drake             Drake   Morgan       Balboa   Balboa  Balboa
2   Michelle   Trish             Shawn    Osten       Andrew  Ryan O.  Rupert
3        6–1     4–2               4–1  Quit[b]          6–4      8–1   5–2–1
4        NaN     NaN               NaN      NaN          NaN      NaN     NaN
5      Votes   Votes             Votes    Votes        Votes    Votes   Votes
6   Michelle   Trish             Shawn      NaN       Andrew  Ryan O.     Jon
7        NaN     NaN               NaN      NaN       Andrew  Ryan O.  Rupert
8   Michelle  Rupert             Shawn      NaN       Andrew  Ryan O.  Rupert
9        NaN     NaN               NaN      NaN          Jon  Ryan O.  Rupert
10       NaN     NaN               NaN      NaN       Andrew  Ryan O.  Rupert
11  Michelle   Trish             Shawn      NaN       Andrew  Ryan O.  Darrah
12       NaN     NaN               NaN      NaN          Jon  Ryan O.  Rupert
13  Michelle   Trish             Shawn      NaN       Andrew  Ryan O.  Darrah
14       NaN     NaN               NaN      NaN          Jon  Christa     NaN
15       NaN     NaN               NaN      NaN          Jon      NaN     NaN
16       NaN     NaN               NaN     Quit          NaN      NaN     NaN
17  Michelle   Trish               Jon      NaN          NaN      NaN     NaN
18  Michelle  Rupert               NaN      NaN          NaN      NaN     NaN
19     Shawn     NaN               NaN      NaN          NaN      NaN     NaN
20       NaN     NaN               NaN      NaN          NaN      NaN     NaN
21       NaN     NaN               NaN      NaN          NaN      NaN     NaN


         11       12       13       14     14.1
0        30       33       36       37       38
1    Balboa   Balboa   Balboa   Balboa   Balboa
2   Tijuana  Christa   Burton   Darrah      Jon
3       5–2      4–2      3–2      3–1      1–0
4       NaN      NaN      NaN      NaN      NaN
5     Votes    Votes    Votes    Votes    Votes
6   Tijuana  Lillian   Burton   Darrah  None[c]
7   Tijuana  Christa   Burton   Darrah      Jon
8   Tijuana  Christa  Lillian   Darrah  None[c]
9    Burton  Christa   Burton  Lillian      NaN
10  Tijuana  Christa  Lillian      NaN      NaN
11  Tijuana  Lillian      NaN      NaN      NaN
12   Burton      NaN      NaN      NaN      NaN
13      NaN      NaN      NaN      NaN      NaN
14      NaN      NaN      NaN      NaN      NaN
15      NaN      NaN      NaN      NaN      NaN
16      NaN      NaN      NaN      NaN      NaN
17      NaN      NaN      NaN      NaN      NaN
18      NaN      NaN      NaN      NaN      NaN
19      NaN      NaN      NaN      NaN      NaN
20      NaN      NaN      NaN      NaN      NaN
21      NaN      NaN      NaN      NaN      NaN

In [ ]:
sandra_row = df[df[('Unnamed: 0_level_0', 'Episode')] == 'Sandra']
print(sandra_row)

  Unnamed: 0_level_0 Original tribes                                     \
             Episode               1    2    3       4         5      6
6             Sandra             NaN  NaN  NaN  Burton  Michelle  Trish

  Outcasts twist[a]      Merged tribe                                          \
                  7  7.1            8        9   10       11       12      13
6             Shawn  NaN       Andrew  Ryan O.  Jon  Tijuana  Lillian  Burton


       14     14.1
6  Darrah  None[c]

## Survivor 8

In [ ]:
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
}

r = requests.get('https://en.wikipedia.org/wiki/Survivor:_All-Stars', headers=headers)
html_contents = r.text
html_soup = BeautifulSoup(html_contents,"lxml")

In [ ]:
tables = html_soup.find_all('table',class_="wikitable")
tables[0].find_all('a')

[<a href="/wiki/Survivor:_The_Australian_Outback" title="Survivor: The Australian Outback">The Australian Outback</a>,
 <a href="/wiki/Knoxville,_Tennessee" title="Knoxville, Tennessee">Knoxville,<br/>Tennessee</a>,
 <a href="/wiki/Rudy_Boesch" title="Rudy Boesch">Rudy Boesch</a>,
 <a href="/wiki/Survivor:_Borneo" title="Survivor: Borneo">Borneo</a>,
 <a href="/wiki/Virginia_Beach,_Virginia" title="Virginia Beach, Virginia"><span class="nowrap">Virginia Beach,</span><br/>Virginia</a>,
 <a href="/wiki/Jenna_Morasca" title="Jenna Morasca">Jenna Morasca</a>,
 <a href="/wiki/Survivor:_The_Amazon" title="Survivor: The Amazon">The Amazon</a>,
 <a href="/wiki/Bridgeville,_Pennsylvania" title="Bridgeville, Pennsylvania">Bridgeville,<br/>Pennsylvania</a>,
 <a href="/wiki/Rob_Cesternino" title="Rob Cesternino">Rob Cesternino</a>,
 <a href="/wiki/Survivor:_The_Amazon" title="Survivor: The Amazon">The Amazon</a>,
 <a href="/wiki/Plainview,_New_York" title="Plainview, New York">Plainview,<br/> New York</a>,
 <a href="/wiki/Richard_Hatch_(Survivor_contestant)" title="Richard Hatch (Survivor contestant)">Richard Hatch</a>,
 <a href="/wiki/Survivor:_Borneo" title="Survivor: Borneo">Borneo</a>,
 <a href="/wiki/Middletown,_Rhode_Island" title="Middletown, Rhode Island">Middletown,<br/>Rhode Island</a>,
 <a href="/wiki/Sue_Hawk" title="Sue Hawk">Sue Hawk</a>,
 <a href="/wiki/Survivor:_Borneo" title="Survivor: Borneo">Borneo</a>,
 <a href="/wiki/Las_Vegas" title="Las Vegas">Las Vegas,<br/>Nevada</a>,
 <a href="/wiki/Colby_Donaldson" title="Colby Donaldson">Colby Donaldson</a>,
 <a href="/wiki/Survivor:_The_Australian_Outback" title="Survivor: The Australian Outback">The Australian Outback</a>,
 <a href="/wiki/Los_Angeles" title="Los Angeles">Los Angeles,<br/> California</a>,
 <a href="/wiki/Ethan_Zohn" title="Ethan Zohn">Ethan Zohn</a>,
 <a href="/wiki/Survivor:_Africa" title="Survivor: Africa">Africa</a>,
 <a href="/wiki/New_York_City" title="New York City">New York City,<br/>New York</a>,
 <a href="/wiki/Jerri_Manthey" title="Jerri Manthey">Jerri Manthey</a>,
 <a href="/wiki/Survivor:_The_Australian_Outback" title="Survivor: The Australian Outback">The Australian Outback</a>,
 <a href="/wiki/Los_Angeles" title="Los Angeles">Los Angeles,<br/>California</a>,
 <a href="/wiki/Survivor:_Africa" title="Survivor: Africa">Africa</a>,
 <a href="/wiki/Santa_Cruz,_California" title="Santa Cruz, California">Santa Cruz,<br/>California</a>,
 <a href="/wiki/Survivor:_Marquesas" title="Survivor: Marquesas">Marquesas</a>,
 <a href="/wiki/Burlington,_Vermont" title="Burlington, Vermont">Burlington,<br/>Vermont</a>,
 <a href="/wiki/Survivor:_The_Australian_Outback" title="Survivor: The Australian Outback">The Australian Outback</a>,
 <a href="/wiki/New_York_City" title="New York City">New York City,<br/>New York</a>,
 <a href="/wiki/Survivor:_Thailand" title="Survivor: Thailand">Thailand</a>,
 <a href="/wiki/New_York_City" title="New York City">New York City,<br/>New York</a>,
 <a href="/wiki/Survivor:_Africa" title="Survivor: Africa">Africa</a>,
 <a href="/wiki/Rich_Valley,_Virginia" title="Rich Valley, Virginia">Rich Valley,<br/>Virginia</a>,
 <a href="/wiki/Rupert_Boneham" title="Rupert Boneham">Rupert Boneham</a>,
 <a href="/wiki/Survivor:_Pearl_Islands" title="Survivor: Pearl Islands">Pearl Islands</a>,
 <a href="/wiki/Indianapolis" title="Indianapolis">Indianapolis,<br/>Indiana</a>,
 <a href="/wiki/Survivor:_Borneo" title="Survivor: Borneo">Borneo</a>,
 <a href="/wiki/Burbank,_California" title="Burbank, California">Burbank,<br/>California</a>,
 <a href="/wiki/Rob_Mariano" title="Rob Mariano">Rob Mariano</a>,
 <a href="/wiki/Survivor:_Marquesas" title="Survivor: Marquesas">Marquesas</a>,
 <a href="/wiki/Canton,_Massachusetts" title="Canton, Massachusetts">Canton,<br/>Massachusetts</a>,
 <a href="/wiki/Amber_Mariano" title="Amber Mariano">Amber Brkich</a>,
 <a href="/wiki/Survivor:_The_Australian_Outback" title="Survivor: The Australian Outback">The Australian Outback</a>,
 <a href="/wiki/Beaver,_Pennsylvania" title="Beaver, Pennsylvania">Beaver,<br/>Pennsylvania</a>]

In [ ]:
df = pd.read_html(str(tables))[3]
df

/tmp/ipykernel_3126/1238544221.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(tables))[3]

   Unnamed: 0_level_0 Original tribes                              \
              Episode               1       2          3        4
0                 Day               3       6          9       12
1               Tribe          Saboga  Saboga  Mogo Mogo  Chapera
2          Eliminated            Tina    Rudy   Jenna M.   Rob C.
3               Votes             4–2     3–2    Quit[a]      5–1
4                 NaN             NaN     NaN        NaN      NaN
5               Voter           Votes   Votes      Votes    Votes
6               Amber             NaN     NaN        NaN   Rob C.
7              Rob M.             NaN     NaN        NaN   Rob C.
8            Jenna L.            Tina    Rudy        NaN      NaN
9              Rupert            Tina   Ethan        NaN      NaN
10                Tom             NaN     NaN        NaN   Rob C.
11           Shii Ann             NaN     NaN        NaN      NaN
12             Alicia             NaN     NaN        NaN   Rob C.
13              Kathy             NaN     NaN        NaN      NaN
14                Lex             NaN     NaN        NaN      NaN
15              Jerri            Tina    Rudy        NaN      NaN
16              Ethan        Jenna L.    Rudy        NaN      NaN
17              Colby             NaN     NaN        NaN      NaN
18                Sue             NaN     NaN        NaN   Rob C.
19            Richard             NaN     NaN        NaN      NaN
20             Rob C.             NaN     NaN        NaN   Alicia
21           Jenna M.             NaN     NaN       Quit      NaN
22               Rudy            Tina   Ethan        NaN      NaN
23               Tina        Jenna L.     NaN        NaN      NaN

   Absorbed tribes                                   Switched tribes  \
                 5        6             7          8              10
0               15       17            19         21              24
1        Mogo Mogo  Chapera     Mogo Mogo  Mogo Mogo         Chapera
2          Richard      Sue         Colby      Ethan           Jerri
3              6–1  Quit[b]           3–2        4–1             4–1
4              NaN      NaN           NaN        NaN             NaN
5            Votes    Votes         Votes      Votes           Votes
6              NaN      NaN           NaN        NaN           Jerri
7              NaN      NaN           NaN        NaN             NaN
8              NaN      NaN           NaN        NaN             NaN
9              NaN      NaN           NaN        NaN             NaN
10             NaN      NaN           NaN        NaN             NaN
11         Richard      NaN         Colby      Ethan           Jerri
12             NaN      NaN           NaN        NaN             NaN
13         Richard      NaN  Kidnapped[d]      Ethan           Jerri
14         Richard      NaN         Colby      Ethan           Jerri
15         Richard      NaN         Colby      Ethan           Amber
16         Richard      NaN         Jerri      Jerri             NaN
17         Richard      NaN         Jerri        NaN             NaN
18             NaN     Quit           NaN        NaN             NaN
19           Colby      NaN           NaN        NaN             NaN
20             NaN      NaN           NaN        NaN             NaN
21             NaN      NaN           NaN        NaN             NaN
22             NaN      NaN           NaN        NaN             NaN
23             NaN      NaN           NaN        NaN             NaN

    Merged tribe                                                          \
              11            12            13            14            15
0             27            28            30            33            36
1   Chaboga Mogo  Chaboga Mogo  Chaboga Mogo  Chaboga Mogo  Chaboga Mogo
2            Lex         Kathy        Alicia      Shii Ann           Tom
3            7–2           6–2           6–1           5–1           4–1
4            NaN           NaN           NaN           NaN           NaN
5          Votes         Votes         Votes         Votes         Votes
6            Lex         Kathy        Alicia      Shii Ann           Tom
7            Lex         Kathy        Alicia      Shii Ann           Tom
8            Lex         Kathy        Alicia      Shii Ann           Tom
9            Lex         Kathy        Alicia      Shii Ann           Tom
10           Lex         Kathy        Alicia      Shii Ann      Jenna L.
11           Lex         Amber        Alicia         Amber           NaN
12           Lex         Kathy        Rupert           NaN           NaN
13         Amber         Amber           NaN           NaN           NaN
14         Amber           NaN           NaN           NaN           NaN
15           NaN           NaN           NaN           NaN           NaN
16           NaN           NaN           NaN           NaN           NaN
17           NaN           NaN           NaN           NaN           NaN
18           NaN           NaN           NaN           NaN           NaN
19           NaN           NaN           NaN           NaN           NaN
20           NaN           NaN           NaN           NaN           NaN
21           NaN           NaN           NaN           NaN           NaN
22           NaN           NaN           NaN           NaN           NaN
23           NaN           NaN           NaN           NaN           NaN


              16          16.1
0             37            38
1   Chaboga Mogo  Chaboga Mogo
2         Rupert      Jenna L.
3            3–1           1–0
4            NaN           NaN
5          Votes         Votes
6         Rupert       None[c]
7         Rupert      Jenna L.
8         Rupert       None[c]
9         Rob M.           NaN
10           NaN           NaN
11           NaN           NaN
12           NaN           NaN
13           NaN           NaN
14           NaN           NaN
15           NaN           NaN
16           NaN           NaN
17           NaN           NaN
18           NaN           NaN
19           NaN           NaN
20           NaN           NaN
21           NaN           NaN
22           NaN           NaN
23           NaN           NaN

In [ ]:
amber_row = df[df[('Unnamed: 0_level_0', 'Episode')] == 'Amber']
print(amber_row)

  Unnamed: 0_level_0 Original tribes                   Absorbed tribes       \
             Episode               1    2    3       4               5    6
6              Amber             NaN  NaN  NaN  Rob C.             NaN  NaN

            Switched tribes Merged tribe                                \
     7    8              10           11     12      13        14   15
6  NaN  NaN           Jerri          Lex  Kathy  Alicia  Shii Ann  Tom


       16     16.1
6  Rupert  None[c]

## Survivor 9

In [ ]:
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
}

r = requests.get('https://en.wikipedia.org/wiki/Survivor:_Vanuatu', headers=headers)
html_contents = r.text
html_soup = BeautifulSoup(html_contents,"lxml")

In [ ]:
tables = html_soup.find_all('table',class_="wikitable")
tables[0].find_all('a')

[<a href="/wiki/Winthrop,_Massachusetts" title="Winthrop, Massachusetts">Winthrop,<br/>Massachusetts</a>,
 <a href="/wiki/Lake_Latonka,_Pennsylvania" title="Lake Latonka, Pennsylvania">Lake Latonka,<br/>Pennsylvania</a>,
 <a href="/wiki/Los_Angeles" title="Los Angeles">Los Angeles,<br/>California</a>,
 <a href="/wiki/Boston" title="Boston">Boston,<br/>Massachusetts</a>,
 <a href="/wiki/Huntington_Beach,_California" title="Huntington Beach, California">Huntington Beach,<br/>California</a>,
 <a href="/wiki/Johnson_City,_Tennessee" title="Johnson City, Tennessee">Johnson City,<br/>Tennessee</a>,
 <a href="/wiki/Mandeville,_Louisiana" title="Mandeville, Louisiana">Mandeville,<br/>Louisiana</a>,
 <a href="/wiki/Los_Angeles" title="Los Angeles">Los Angeles,<br/>California</a>,
 <a href="/wiki/Des_Moines,_Iowa" title="Des Moines, Iowa">Des Moines,<br/>Iowa</a>,
 <a href="/wiki/Columbia,_South_Carolina" title="Columbia, South Carolina">Columbia,<br/>South Carolina</a>,
 <a href="/wiki/Oakland,_California" title="Oakland, California">Oakland,<br/>California</a>,
 <a href="/wiki/Kansasville,_Wisconsin" title="Kansasville, Wisconsin">Kansasville,<br/>Wisconsin</a>,
 <a href="/wiki/Lakewood,_Colorado" title="Lakewood, Colorado">Lakewood,<br/>Colorado</a>,
 <a href="/wiki/Gorham,_Maine" title="Gorham, Maine">Gorham,<br/>Maine</a>,
 <a href="/wiki/Eliza_Orlins" title="Eliza Orlins">Eliza Orlins</a>,
 <a href="/wiki/Syracuse,_New_York" title="Syracuse, New York">Syracuse,<br/>New York</a>,
 <a href="/wiki/Stillwater,_Oklahoma" title="Stillwater, Oklahoma">Stillwater,<br/>Oklahoma</a>,
 <a href="/wiki/Marshall,_Missouri" title="Marshall, Missouri">Marshall,<br/>Missouri</a>,
 <a href="/wiki/South_Vienna,_Ohio" title="South Vienna, Ohio">South Vienna,<br/>Ohio</a>]

In [ ]:
df = pd.read_html(str(tables))[3]
df

/tmp/ipykernel_3126/1238544221.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(tables))[3]

   Unnamed: 0_level_0 Original tribes                                 \
              Episode               1      2        3    3.1       4
0                 Day               3      6        7      7      10
1               Tribe          Lopevi  Yasur   Lopevi  Yasur  Lopevi
2          Eliminated           Brook  Dolly  John P.    Mia   Brady
3               Votes           5–3–1    5–4      5–3    5–3     6–1
4                 NaN             NaN    NaN      NaN    NaN     NaN
5               Voter            Vote   Vote     Vote   Vote    Vote
6               Chris           Brook    NaN  John P.    NaN   Brady
7               Twila             NaN  Dolly      NaN    Mia     NaN
8               Scout             NaN  Dolly      NaN    Mia     NaN
9               Eliza             NaN  Dolly      NaN  Twila     NaN
10              Julie             NaN  Leann      NaN  Twila     NaN
11                Ami             NaN  Dolly      NaN    Mia     NaN
12              Leann             NaN  Dolly      NaN    Mia     NaN
13               Chad           Brook    NaN  John P.    NaN   Brady
14                Lea           Brook    NaN  John P.    NaN   Brady
15               Rory           Brook    NaN  John P.    NaN   Brady
16            John K.           Chris    NaN     Rory    NaN   Brady
17               Lisa             NaN  Leann      NaN    Mia     NaN
18             Travis           Brook    NaN  John P.    NaN   Brady
19              Brady            Rory    NaN     Rory    NaN    Rory
20                Mia             NaN  Leann      NaN  Twila     NaN
21            John P.           Chris    NaN     Rory    NaN     NaN
22              Dolly             NaN  Leann      NaN    NaN     NaN
23              Brook           Chris    NaN      NaN    NaN     NaN

   Switched tribes                 Merged tribe                          \
                 5      6        7            8       9      10      11
0               12     15       18           21      24      27      30
1            Yasur  Yasur   Lopevi       Alinta  Alinta  Alinta  Alinta
2           Travis   Lisa  John K.         Rory     Lea    Chad   Leann
3              6–1    4–2      5–1          6–4   7–1–1     6–2     4–3
4              NaN    NaN      NaN          NaN     NaN     NaN     NaN
5             Vote   Vote     Vote         Vote    Vote    Vote    Vote
6              NaN    NaN  John K.          Ami     Lea   Eliza   Leann
7              NaN    NaN  John K.         Rory     Lea    Chad   Leann
8           Travis   Rory      NaN         Rory     Lea    Chad   Leann
9           Travis   Lisa      NaN         Rory     Lea    Chad   Leann
10             NaN    NaN  John K.         Rory     Lea    Chad   Eliza
11          Travis   Lisa      NaN         Rory     Lea    Chad   Eliza
12          Travis   Lisa      NaN         Rory     Lea    Chad   Eliza
13             NaN    NaN  John K.          Ami   Julie   Eliza     NaN
14             NaN    NaN  John K.          Ami   Eliza     NaN     NaN
15          Travis   Lisa      NaN          Ami     NaN     NaN     NaN
16             NaN    NaN     Chad          NaN     NaN     NaN     NaN
17          Travis   Rory      NaN          NaN     NaN     NaN     NaN
18            Rory    NaN      NaN          NaN     NaN     NaN     NaN
19             NaN    NaN      NaN          NaN     NaN     NaN     NaN
20             NaN    NaN      NaN          NaN     NaN     NaN     NaN
21             NaN    NaN      NaN          NaN     NaN     NaN     NaN
22             NaN    NaN      NaN          NaN     NaN     NaN     NaN
23             NaN    NaN      NaN          NaN     NaN     NaN     NaN

                                    Unnamed: 17_level_0 Unnamed: 18_level_0
        12      13      14     14.1 Unnamed: 17_level_1 Unnamed: 18_level_1
0       33      36      37       38                 NaN                 NaN
1   Alinta  Alinta  Alinta   Alinta                 NaN                 NaN
2      Ami   Julie   Eliza    Scout                 NaN                 NaN
3      4–2     3–2     3–1      1–0                 NaN                 NaN
4      NaN     NaN     NaN      NaN                 NaN                 NaN
5     Vote    Vote    Vote     Vote                 NaN                 NaN
6      Ami   Julie   Eliza    Scout                 NaN                 NaN
7      Ami   Julie   Eliza  None[a]                 NaN                 NaN
8      Ami   Julie   Eliza  None[a]                 NaN                 NaN
9      Ami   Twila   Twila      NaN                 NaN                 NaN
10   Scout   Twila     NaN      NaN                 NaN                 NaN
11   Scout     NaN     NaN      NaN                 NaN                 NaN
12     NaN     NaN     NaN      NaN                 NaN                 NaN
13     NaN     NaN     NaN      NaN                 NaN                 NaN
14     NaN     NaN     NaN      NaN                 NaN                 NaN
15     NaN     NaN     NaN      NaN                 NaN                 NaN
16     NaN     NaN     NaN      NaN                 NaN                 NaN
17     NaN     NaN     NaN      NaN                 NaN                 NaN
18     NaN     NaN     NaN      NaN                 NaN                 NaN
19     NaN     NaN     NaN      NaN                 NaN                 NaN
20     NaN     NaN     NaN      NaN                 NaN                 NaN
21     NaN     NaN     NaN      NaN                 NaN                 NaN
22     NaN     NaN     NaN      NaN                 NaN                 NaN
23     NaN     NaN     NaN      NaN                 NaN                 NaN

In [ ]:
chrisD_row = df[df[('Unnamed: 0_level_0', 'Episode')] == 'Chris']
print(chrisD_row)

  Unnamed: 0_level_0 Original tribes                            \
             Episode               1    2        3  3.1      4
6              Chris           Brook  NaN  John P.  NaN  Brady

  Switched tribes               Merged tribe                                 \
                5    6        7            8    9     10     11   12     13
6             NaN  NaN  John K.          Ami  Lea  Eliza  Leann  Ami  Julie

                Unnamed: 17_level_0 Unnamed: 18_level_0
      14   14.1 Unnamed: 17_level_1 Unnamed: 18_level_1
6  Eliza  Scout                 NaN                 NaN

## Survivor 10

In [ ]:
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
}

r = requests.get('https://en.wikipedia.org/wiki/Survivor:_Palau', headers=headers)
html_contents = r.text
html_soup = BeautifulSoup(html_contents,"lxml")

In [ ]:
tables = html_soup.find_all('table',class_="wikitable")
tables[0].find_all('a')

[<a class="mw-redirect" href="/wiki/Dallas,_Texas" title="Dallas, Texas">Dallas,<br/>Texas</a>,
 <a href="#cite_note-Day_1_Elimination-4"><span class="cite-bracket">[</span>a<span class="cite-bracket">]</span></a>,
 <a href="#cite_note-Day_1_Elimination-4"><span class="cite-bracket">[</span>a<span class="cite-bracket">]</span></a>,
 <a href="/wiki/Ulysses,_Pennsylvania" title="Ulysses, Pennsylvania">Ulysses,<br/>Pennsylvania</a>,
 <a href="/wiki/Jolanda_Jones" title="Jolanda Jones">Jolanda Jones</a>,
 <a href="/wiki/Houston" title="Houston">Houston,<br/>Texas</a>,
 <a href="/wiki/Easley,_South_Carolina" title="Easley, South Carolina">Easley,<br/>South Carolina</a>,
 <a href="/wiki/Ventura,_California" title="Ventura, California">Ventura,<br/>California</a>,
 <a href="/wiki/Huber_Heights,_Ohio" title="Huber Heights, Ohio">Huber Heights,<br/>Ohio</a>,
 <a href="/wiki/Bellevue,_Washington" title="Bellevue, Washington">Bellevue,<br/>Washington</a>,
 <a class="mw-redirect" href="/wiki/New_Orleans,_Louisiana" title="New Orleans, Louisiana">New Orleans,<br/>Louisiana</a>,
 <a href="/wiki/Mobile,_Alabama" title="Mobile, Alabama">Mobile,<br/>Alabama</a>,
 <a href="/wiki/Birmingham,_Alabama" title="Birmingham, Alabama">Birmingham,<br/>Alabama</a>,
 <a href="/wiki/Troy,_Alabama" title="Troy, Alabama">Troy,<br/>Alabama</a>,
 <a href="#cite_note-5"><span class="cite-bracket">[</span>b<span class="cite-bracket">]</span></a>,
 <a href="/wiki/Athens,_Texas" title="Athens, Texas">Athens,<br/>Texas</a>,
 <a class="mw-redirect" href="/wiki/Las_Vegas,_Nevada" title="Las Vegas, Nevada">Las Vegas,<br/>Nevada</a>,
 <a href="/wiki/Stephenie_LaGrossa_Kendrick" title="Stephenie LaGrossa Kendrick">Stephenie LaGrossa</a>,
 <a href="/wiki/Toms_River,_New_Jersey" title="Toms River, New Jersey">Toms River,<br/>New Jersey</a>,
 <a href="/wiki/Chicago" title="Chicago">Chicago,<br/>Illinois</a>,
 <a href="/wiki/Solon,_Ohio" title="Solon, Ohio">Solon,<br/>Ohio</a>,
 <a href="/wiki/Jennifer_Lyon" title="Jennifer Lyon">Jenn Lyon</a>,
 <a class="mw-redirect" href="/wiki/Encino,_California" title="Encino, California">Encino,<br/>California</a>,
 <a href="/wiki/Ambridge,_Pennsylvania" title="Ambridge, Pennsylvania">Ambridge,<br/>Pennsylvania</a>,
 <a href="/wiki/Merced,_California" title="Merced, California">Merced,<br/>California</a>,
 <a href="/wiki/Tom_Westman" title="Tom Westman">Tom Westman</a>,
 <a href="/wiki/Sayville,_New_York" title="Sayville, New York">Sayville,<br/>New York</a>]

In [ ]:
df = pd.read_html(str(tables))[3]
df

/tmp/ipykernel_3126/1238544221.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(tables))[3]

   Unnamed: 0_level_0      No tribes                Original tribes          \
              Episode              1            1.1               1       2
0                 Day              2              2               3       6
1               Tribe            NaN            NaN           Ulong   Ulong
2          Eliminated       Jonathan          Wanda         Jolanda  Ashlee
3               Votes  Eliminated[c]  Eliminated[c]             6–3   6–1–1
4                 NaN            NaN            NaN             NaN     NaN
5               Voter           Vote           Vote            Vote    Vote
6                 Tom            NaN            NaN             NaN     NaN
7               Katie            NaN            NaN             NaN     NaN
8                 Ian            NaN            NaN             NaN     NaN
9                Jenn            NaN            NaN             NaN     NaN
10              Caryn            NaN            NaN             NaN     NaN
11              Gregg            NaN            NaN             NaN     NaN
12          Stephenie            NaN            NaN         Jolanda  Ashlee
13               Janu            NaN            NaN             NaN     NaN
14               Coby            NaN            NaN             NaN     NaN
15          Bobby Jon            NaN            NaN           Angie  Ashlee
16            Ibrehem            NaN            NaN           Angie     Kim
17              James            NaN            NaN         Jolanda  Ashlee
18              Angie            NaN            NaN         Jolanda  Ashlee
19            Willard            NaN            NaN             NaN     NaN
20                Kim            NaN            NaN         Jolanda  Ashlee
21               Jeff            NaN            NaN         Jolanda  Ashlee
22             Ashlee            NaN            NaN         Jolanda    Jeff
23            Jolanda            NaN            NaN           Angie     NaN
24              Wanda     Eliminated     Eliminated             NaN     NaN
25           Jonathan     Eliminated     Eliminated             NaN     NaN

                                               ... Absorbed tribe             \
        3      4        5        5.1      5.2  ...             10         11
0       8     11       12         12       12  ...             27         30
1   Ulong  Ulong    Koror      Ulong    Ulong  ...          Koror      Koror
2    Jeff    Kim  Willard     Tie[a]    Angie  ...           Janu  Stephenie
3   4–2–1    5–1      8–1      2–2–1      3–0  ...        Quit[e]        6–1
4     NaN    NaN      NaN        NaN      NaN  ...            NaN        NaN
5    Vote   Vote     Vote       Vote     Vote  ...           Vote       Vote
6     NaN    NaN  Willard        NaN      NaN  ...            NaN  Stephenie
7     NaN    NaN  Willard        NaN      NaN  ...            NaN  Stephenie
8     NaN    NaN  Willard        NaN      NaN  ...            NaN  Stephenie
9     NaN    NaN  Willard        NaN      NaN  ...            NaN  Stephenie
10    NaN    NaN  Willard        NaN      NaN  ...            NaN  Stephenie
11    NaN    NaN  Willard        NaN      NaN  ...            NaN  Stephenie
12   Jeff    Kim      NaN  Bobby Jon    Angie  ...            NaN      Caryn
13    NaN    NaN  Willard        NaN      NaN  ...            NaN        NaN
14    NaN    NaN  Willard        NaN      NaN  ...            NaN        NaN
15    Kim    Kim      NaN      Angie  None[i]  ...            NaN        NaN
16   Jeff    Kim      NaN      James    Angie  ...            NaN        NaN
17    Kim    Kim      NaN      Angie    Angie  ...            NaN        NaN
18   Jeff    Kim      NaN  Bobby Jon  None[i]  ...            NaN        NaN
19    NaN    NaN    Katie        NaN      NaN  ...            NaN        NaN
20   Jeff  James      NaN        NaN      NaN  ...            NaN        NaN
21  James    NaN      NaN        NaN      NaN  ...            NaN        NaN
22    NaN    NaN      NaN        NaN      NaN  ...            NaN        NaN
23    NaN    NaN      NaN        NaN      NaN  ...            NaN        NaN
24    NaN    NaN      NaN        NaN      NaN  ...            NaN        NaN
25    NaN    NaN      NaN        NaN      NaN  ...            NaN        NaN

                                                         Unnamed: 23_level_0  \
       12     13      14     14.1          14.2     14.3 Unnamed: 23_level_1
0      33     36      37       37            37       38                 NaN
1   Koror  Koror   Koror    Koror         Koror    Koror                 NaN
2   Gregg  Caryn  Tie[a]   Tie[b]          Jenn      Ian                 NaN
3     4–2    4–1     2–2      1–1  Challenge[f]      1–0                 NaN
4     NaN    NaN     NaN      NaN           NaN      NaN                 NaN
5    Vote   Vote    Vote     Vote          Vote     Vote                Vote
6   Gregg  Caryn     Ian      Ian           NaN      Ian                 NaN
7   Gregg  Caryn    Jenn     Jenn           NaN  None[g]                 NaN
8   Gregg  Caryn    Jenn  None[h]        Won[f]  None[g]                 NaN
9   Caryn  Caryn     Ian  None[h]       Lost[f]      NaN                 NaN
10  Gregg    Ian     NaN      NaN           NaN      NaN                 NaN
11  Caryn    NaN     NaN      NaN           NaN      NaN                 NaN
12    NaN    NaN     NaN      NaN           NaN      NaN                 NaN
13    NaN    NaN     NaN      NaN           NaN      NaN                 NaN
14    NaN    NaN     NaN      NaN           NaN      NaN                 NaN
15    NaN    NaN     NaN      NaN           NaN      NaN                 NaN
16    NaN    NaN     NaN      NaN           NaN      NaN                 NaN
17    NaN    NaN     NaN      NaN           NaN      NaN                 NaN
18    NaN    NaN     NaN      NaN           NaN      NaN                 NaN
19    NaN    NaN     NaN      NaN           NaN      NaN                 NaN
20    NaN    NaN     NaN      NaN           NaN      NaN                 NaN
21    NaN    NaN     NaN      NaN           NaN      NaN                 NaN
22    NaN    NaN     NaN      NaN           NaN      NaN                 NaN
23    NaN    NaN     NaN      NaN           NaN      NaN                 NaN
24    NaN    NaN     NaN      NaN           NaN      NaN                 NaN
25    NaN    NaN     NaN      NaN           NaN      NaN                 NaN

   Unnamed: 24_level_0
   Unnamed: 24_level_1
0                  NaN
1                  NaN
2                  NaN
3                  NaN
4                  NaN
5                  NaN
6                  NaN
7                  NaN
8                  NaN
9                  NaN
10                 NaN
11                 NaN
12                 NaN
13                 NaN
14                 NaN
15                 NaN
16                 NaN
17                 NaN
18                 NaN
19                 NaN
20                 NaN
21                 NaN
22                 NaN
23                 NaN
24                 NaN
25                 NaN

[26 rows x 25 columns]

In [ ]:
tom_row = df[df[('Unnamed: 0_level_0', 'Episode')] == 'Tom']
print(tom_row)

  Unnamed: 0_level_0 No tribes      Original tribes                          \
             Episode         1  1.1               1    2    3    4        5
6                Tom       NaN  NaN             NaN  NaN  NaN  NaN  Willard

             ... Absorbed tribe                                               \
   5.1  5.2  ...             10         11     12     13   14 14.1 14.2 14.3
6  NaN  NaN  ...            NaN  Stephenie  Gregg  Caryn  Ian  Ian  NaN  Ian

  Unnamed: 23_level_0 Unnamed: 24_level_0
  Unnamed: 23_level_1 Unnamed: 24_level_1
6                 NaN                 NaN

[1 rows x 25 columns]

## Survivor 11

In [ ]:
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
}

r = requests.get('https://en.wikipedia.org/wiki/Survivor:_Guatemala', headers=headers)
html_contents = r.text
html_soup = BeautifulSoup(html_contents,"lxml")

In [ ]:
tables = html_soup.find_all('table',class_="wikitable")
tables[0].find_all('a')

[<a href="/wiki/Northglenn,_Colorado" title="Northglenn, Colorado">Northglenn,<br/>Colorado</a>,
 <a href="/wiki/Decatur,_Illinois" title="Decatur, Illinois">Decatur,<br/>Illinois</a>,
 <a href="/wiki/Edmonds,_Washington" title="Edmonds, Washington">Edmonds,<br/>Washington</a>,
 <a href="/wiki/Hood_River,_Oregon" title="Hood River, Oregon">Hood River,<br/>Oregon</a>,
 <a class="mw-redirect" href="/wiki/Dallas,_Texas" title="Dallas, Texas">Dallas,<br/>Texas</a>,
 <a href="/wiki/Chardon,_Ohio" title="Chardon, Ohio">Chardon,<br/>Ohio</a>,
 <a class="mw-redirect" href="/wiki/New_York_City,_New_York" title="New York City, New York">New York City,<br/>New York</a>,
 <a href="/wiki/Revere,_Massachusetts" title="Revere, Massachusetts">Revere,<br/>Massachusetts</a>,
 <a href="/wiki/Manhattan,_Kansas" title="Manhattan, Kansas">Manhattan,<br/>Kansas</a>,
 <a href="/wiki/Survivor:_Palau" title="Survivor: Palau">Palau</a>,
 <a href="/wiki/Troy,_Alabama" title="Troy, Alabama">Troy,<br/>Alabama</a>,
 <a href="/wiki/Douglas,_Georgia" title="Douglas, Georgia">Douglas,<br/>Georgia</a>,
 <a href="/wiki/Gary_Hogeboom" title="Gary Hogeboom">Gary Hogeboom</a>,
 <a href="/wiki/Grand_Haven,_Michigan" title="Grand Haven, Michigan">Grand Haven,<br/>Michigan</a>,
 <a href="/wiki/Ridgefield,_New_Jersey" title="Ridgefield, New Jersey">Ridgefield,<br/>New Jersey</a>,
 <a href="/wiki/Naples,_Florida" title="Naples, Florida">Naples,<br/>Florida</a>,
 <a href="/wiki/Lakewood,_Washington" title="Lakewood, Washington">Lakewood,<br/>Washington</a>,
 <a href="/wiki/Rafe_Judkins" title="Rafe Judkins">Rafe Judkins</a>,
 <a class="mw-redirect" href="/wiki/Pittsburgh,_Pennsylvania" title="Pittsburgh, Pennsylvania">Pittsburgh,<br/>Pennsylvania</a>,
 <a href="/wiki/Stephenie_LaGrossa_Kendrick" title="Stephenie LaGrossa Kendrick">Stephenie LaGrossa</a>,
 <a href="/wiki/Survivor:_Palau" title="Survivor: Palau">Palau</a>,
 <a href="/wiki/Toms_River,_New_Jersey" title="Toms River, New Jersey">Toms River,<br/>New Jersey</a>,
 <a href="/wiki/Danni_Boatwright" title="Danni Boatwright">Danni Boatwright</a>,
 <a href="/wiki/Tonganoxie,_Kansas" title="Tonganoxie, Kansas">Tonganoxie,<br/>Kansas</a>]

In [ ]:
df = pd.read_html(str(tables))[3]
df

/tmp/ipykernel_3126/1238544221.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(tables))[3]

   Unnamed: 0_level_0 Original tribes                  Switched tribes         \
              Episode               1       2        3               4      5
0                 Day               3       6        8              11     14
1               Tribe           Nakúm   Yaxhá    Yaxhá           Nakúm  Yaxhá
2          Eliminated             Jim  Morgan  Brianna          Brooke  Blake
3               Votes             8–1     8–1      7–1             5–3    5–2
4                 NaN             NaN     NaN      NaN             NaN    NaN
5               Voter            Vote    Vote     Vote            Vote   Vote
6               Danni             Jim     NaN      NaN             NaN  Blake
7           Stephenie             NaN  Morgan  Brianna          Brooke    NaN
8                Rafe             NaN  Morgan  Brianna          Brooke    NaN
9               Lydia             NaN  Morgan  Brianna          Brooke    NaN
10              Cindy             Jim     NaN      NaN           Lydia    NaN
11               Judd             Jim     NaN      NaN          Brooke    NaN
12               Gary             NaN  Morgan  Brianna             NaN  Blake
13              Jamie             NaN  Morgan  Brianna          Brooke    NaN
14          Bobby Jon             Jim     NaN      NaN             NaN  Blake
15            Brandon             Jim     NaN      NaN             NaN  Brian
16                Amy             NaN  Morgan  Brianna             NaN  Blake
17              Brian             NaN  Morgan  Brianna             NaN  Blake
18           Margaret             Jim     NaN      NaN           Lydia    NaN
19              Blake             Jim     NaN      NaN             NaN  Brian
20             Brooke             Jim     NaN      NaN           Lydia    NaN
21            Brianna             NaN  Morgan    Lydia             NaN    NaN
22             Morgan             NaN   Lydia      NaN             NaN    NaN
23                Jim        Margaret     NaN      NaN             NaN    NaN

                                   Merged tribe                             \
           6        6.1          7            8          9      10      11
0         15         15         18           21         24      27      30
1      Nakúm      Yaxhá      Yaxhá       Xhakúm     Xhakúm  Xhakúm  Xhakúm
2   Margaret      Brian        Amy      Brandon  Bobby Jon   Jamie    Gary
3        6–1        5–1        4–1          6–4      6–2–1     6–2     6–1
4        NaN        NaN        NaN          NaN        NaN     NaN     NaN
5       Vote       Vote       Vote         Vote       Vote    Vote    Vote
6        NaN      Brian        Amy        Jamie  Stephenie   Jamie    Gary
7   Margaret        NaN        NaN      Brandon  Bobby Jon   Jamie    Gary
8   Margaret        NaN        NaN      Brandon  Bobby Jon   Jamie    Gary
9   Margaret        NaN        NaN      Brandon  Bobby Jon   Jamie    Gary
10  Margaret        NaN        NaN      Brandon  Bobby Jon   Jamie    Gary
11  Margaret        NaN        NaN      Brandon  Bobby Jon    Gary    Gary
12       NaN      Brian        Amy        Jamie      Cindy   Jamie   Cindy
13  Margaret        NaN        NaN      Brandon  Bobby Jon    Gary     NaN
14       NaN      Brian        Amy        Jamie  Stephenie     NaN     NaN
15       NaN      Brian        Amy        Jamie        NaN     NaN     NaN
16       NaN      Brian  Bobby Jon          NaN        NaN     NaN     NaN
17       NaN  Bobby Jon        NaN          NaN        NaN     NaN     NaN
18      Judd        NaN        NaN          NaN        NaN     NaN     NaN
19       NaN        NaN        NaN          NaN        NaN     NaN     NaN
20       NaN        NaN        NaN          NaN        NaN     NaN     NaN
21       NaN        NaN        NaN          NaN        NaN     NaN     NaN
22       NaN        NaN        NaN          NaN        NaN     NaN     NaN
23       NaN        NaN        NaN          NaN        NaN     NaN     NaN

                                    Unnamed: 17_level_0 Unnamed: 18_level_0
        12      13      14     14.1 Unnamed: 17_level_1 Unnamed: 18_level_1
0       33      36      37       38                 NaN                 NaN
1   Xhakúm  Xhakúm  Xhakúm   Xhakúm                 NaN                 NaN
2     Judd   Cindy   Lydia     Rafe                 NaN                 NaN
3      4–2     4–1     3–1      1–0                 NaN                 NaN
4      NaN     NaN     NaN      NaN                 NaN                 NaN
5     Vote    Vote    Vote     Vote                 NaN                 NaN
6     Judd   Cindy   Lydia     Rafe                 NaN                 NaN
7     Judd   Cindy   Lydia  None[a]                 NaN                 NaN
8     Judd   Cindy   Lydia  None[a]                 NaN                 NaN
9     Judd   Cindy   Danni      NaN                 NaN                 NaN
10   Lydia    Rafe     NaN      NaN                 NaN                 NaN
11   Lydia     NaN     NaN      NaN                 NaN                 NaN
12     NaN     NaN     NaN      NaN                 NaN                 NaN
13     NaN     NaN     NaN      NaN                 NaN                 NaN
14     NaN     NaN     NaN      NaN                 NaN                 NaN
15     NaN     NaN     NaN      NaN                 NaN                 NaN
16     NaN     NaN     NaN      NaN                 NaN                 NaN
17     NaN     NaN     NaN      NaN                 NaN                 NaN
18     NaN     NaN     NaN      NaN                 NaN                 NaN
19     NaN     NaN     NaN      NaN                 NaN                 NaN
20     NaN     NaN     NaN      NaN                 NaN                 NaN
21     NaN     NaN     NaN      NaN                 NaN                 NaN
22     NaN     NaN     NaN      NaN                 NaN                 NaN
23     NaN     NaN     NaN      NaN                 NaN                 NaN

In [ ]:
danni_row = df[df[('Unnamed: 0_level_0', 'Episode')] == 'Danni']
print(danni_row)

  Unnamed: 0_level_0 Original tribes           Switched tribes              \
             Episode               1    2    3               4      5    6
6              Danni             Jim  NaN  NaN             NaN  Blake  NaN

              Merged tribe                                                    \
     6.1    7            8          9     10    11    12     13     14  14.1
6  Brian  Amy        Jamie  Stephenie  Jamie  Gary  Judd  Cindy  Lydia  Rafe

  Unnamed: 17_level_0 Unnamed: 18_level_0
  Unnamed: 17_level_1 Unnamed: 18_level_1
6                 NaN                 NaN

## Survivor 12

In [ ]:
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
}

r = requests.get('https://en.wikipedia.org/wiki/Survivor:_Panama', headers=headers)
html_contents = r.text
html_soup = BeautifulSoup(html_contents,"lxml")

In [ ]:
tables = html_soup.find_all('table',class_="wikitable")
tables[0].find_all('a')

[<a href="/wiki/Hayward,_Wisconsin" title="Hayward, Wisconsin">Hayward,<br/>Wisconsin</a>,
 <a href="/wiki/Sevierville,_Tennessee" title="Sevierville, Tennessee">Sevierville,<br/>Tennessee</a>,
 <a class="mw-redirect" href="/wiki/Dallas,_Texas" title="Dallas, Texas">Dallas,<br/>Texas</a>,
 <a href="/wiki/Greenville,_South_Carolina" title="Greenville, South Carolina">Greenville,<br/>South Carolina</a>,
 <a href="/wiki/Los_Angeles" title="Los Angeles">Los Angeles,<br/>California</a>,
 <a href="/wiki/Daniel_T._Barry" title="Daniel T. Barry">Dan Barry</a>,
 <a href="/wiki/South_Hadley,_Massachusetts" title="South Hadley, Massachusetts">South Hadley,<br/>Massachusetts</a>,
 <a href="/wiki/Tempe,_Arizona" title="Tempe, Arizona">Tempe,<br/>Arizona</a>,
 <a href="/wiki/High_Point,_North_Carolina" title="High Point, North Carolina">High Point,<br/>North Carolina</a>,
 <a href="/wiki/Chicago" title="Chicago">Chicago,<br/>Illinois</a>,
 <a href="/wiki/Simi_Valley,_California" title="Simi Valley, California">Simi Valley,<br/>California</a>,
 <a href="/wiki/Los_Angeles" title="Los Angeles">Los Angeles,<br/>California</a>,
 <a href="/wiki/Los_Angeles" title="Los Angeles">Los Angeles,<br/>California</a>,
 <a href="/wiki/Cirie_Fields" title="Cirie Fields">Cirie Fields</a>,
 <a href="/wiki/Walterboro,_South_Carolina" title="Walterboro, South Carolina">Walterboro,<br/>South Carolina</a>,
 <a href="/wiki/Terry_Deitz" title="Terry Deitz">Terry Deitz</a>,
 <a href="/wiki/Simsbury,_Connecticut" title="Simsbury, Connecticut">Simsbury,<br/>Connecticut</a>,
 <a href="/wiki/Pompano_Beach,_Florida" title="Pompano Beach, Florida">Pompano Beach,<br/>Florida</a>,
 <a href="/wiki/Santa_Monica,_California" title="Santa Monica, California">Santa Monica,<br/>California</a>]

In [ ]:
df = pd.read_html(str(tables))[3]
df

/tmp/ipykernel_3126/1238544221.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(tables))[3]

   Unnamed: 0_level_0 Original tribes Switched tribes                          \
              Episode               1               2           3           4
0                 Day               3               6           8          11
1               Tribe          Casaya          Casaya     La Mina     La Mina
2          Eliminated            Tina         Melinda       Misty  Ruth Marie
3               Votes             3–1             5–2         5–2         4–2
4                 NaN             NaN             NaN         NaN         NaN
5               Voter            Vote            Vote        Vote        Vote
6                Aras             NaN         Melinda         NaN         NaN
7            Danielle             NaN         Melinda         NaN         NaN
8               Terry             NaN             NaN       Misty  Ruth Marie
9               Cirie            Tina           Shane         NaN         NaN
10              Shane             NaN         Melinda         NaN         NaN
11           Courtney             NaN         Melinda         NaN         NaN
12              Bruce             NaN       Exiled[e]         NaN         NaN
13              Sally             NaN             NaN  Ruth Marie  Ruth Marie
14             Austin             NaN             NaN       Misty  Ruth Marie
15               Nick             NaN             NaN       Misty  Ruth Marie
16                Dan             NaN             NaN       Misty       Sally
17              Bobby             NaN         Melinda         NaN         NaN
18         Ruth Marie            Tina             NaN       Misty       Sally
19              Misty             NaN             NaN  Ruth Marie         NaN
20            Melinda            Tina           Shane         NaN         NaN
21               Tina           Cirie             NaN         NaN         NaN

                        Merged tribe                                  \
           5          6            8        9       10            11
0         14         15           18       21       24            25
1     Casaya    La Mina      Gitanos  Gitanos  Gitanos       Gitanos
2      Bobby        Dan         Nick   Austin    Sally         Bruce
3    3–2–1–1        3–1          6–4      6–3      6–2  Evacuated[b]
4        NaN        NaN          NaN      NaN      NaN           NaN
5       Vote       Vote         Vote     Vote     Vote          Vote
6      Bruce        NaN         Nick   Austin    Sally           NaN
7      Bobby        NaN         Nick   Austin    Sally           NaN
8        NaN        Dan        Shane     Aras     Aras           NaN
9      Bobby        NaN         Nick   Austin    Sally           NaN
10      Aras        NaN         Nick   Austin    Sally           NaN
11     Bobby        NaN         Nick   Austin    Sally           NaN
12  Courtney        NaN         Nick   Austin    Sally     Evacuated
13       NaN  Exiled[f]        Shane     Aras     Aras           NaN
14       NaN        Dan        Shane     Aras      NaN           NaN
15       NaN        Dan        Shane      NaN      NaN           NaN
16       NaN     Austin          NaN      NaN      NaN           NaN
17     Bruce        NaN          NaN      NaN      NaN           NaN
18       NaN        NaN          NaN      NaN      NaN           NaN
19       NaN        NaN          NaN      NaN      NaN           NaN
20       NaN        NaN          NaN      NaN      NaN           NaN
21       NaN        NaN          NaN      NaN      NaN           NaN

                                                        Unnamed: 16_level_0  \
          12        13        14            15     15.1 Unnamed: 16_level_1
0         30        33        36            36       38                 NaN
1    Gitanos   Gitanos   Gitanos       Gitanos  Gitanos                 NaN
2   Courtney     Shane    Tie[a]         Cirie    Terry                 NaN
3      3–2–1     3–1–1       2–2  Challenge[c]      1–0                 NaN
4        NaN       NaN       NaN           NaN      NaN                 NaN
5       Vote      Vote      Vote          Vote     Vote                 NaN
6   Courtney     Shane  Danielle           NaN  None[d]                 NaN
7   Courtney     Shane     Cirie        Won[c]    Terry                 NaN
8       Aras      Aras     Cirie           NaN  None[d]                 NaN
9   Courtney     Shane  Danielle       Lost[c]      NaN                 NaN
10  Danielle  Danielle       NaN           NaN      NaN                 NaN
11      Aras       NaN       NaN           NaN      NaN                 NaN
12       NaN       NaN       NaN           NaN      NaN                 NaN
13       NaN       NaN       NaN           NaN      NaN                 NaN
14       NaN       NaN       NaN           NaN      NaN                 NaN
15       NaN       NaN       NaN           NaN      NaN                 NaN
16       NaN       NaN       NaN           NaN      NaN                 NaN
17       NaN       NaN       NaN           NaN      NaN                 NaN
18       NaN       NaN       NaN           NaN      NaN                 NaN
19       NaN       NaN       NaN           NaN      NaN                 NaN
20       NaN       NaN       NaN           NaN      NaN                 NaN
21       NaN       NaN       NaN           NaN      NaN                 NaN

   Unnamed: 17_level_0
   Unnamed: 17_level_1
0                  NaN
1                  NaN
2                  NaN
3                  NaN
4                  NaN
5                  NaN
6                  NaN
7                  NaN
8                  NaN
9                  NaN
10                 NaN
11                 NaN
12                 NaN
13                 NaN
14                 NaN
15                 NaN
16                 NaN
17                 NaN
18                 NaN
19                 NaN
20                 NaN
21                 NaN

In [ ]:
aras_row = df[df[('Unnamed: 0_level_0', 'Episode')] == 'Aras']
print(aras_row)

  Unnamed: 0_level_0 Original tribes Switched tribes                        \
             Episode               1               2    3    4      5    6
6               Aras             NaN         Melinda  NaN  NaN  Bruce  NaN

  Merged tribe                                                               \
             8       9     10   11        12     13        14   15     15.1
6         Nick  Austin  Sally  NaN  Courtney  Shane  Danielle  NaN  None[d]

  Unnamed: 16_level_0 Unnamed: 17_level_0
  Unnamed: 16_level_1 Unnamed: 17_level_1
6                 NaN                 NaN

## Survivor 13

In [ ]:
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
}

r = requests.get('https://en.wikipedia.org/wiki/Survivor:_Cook_Islands', headers=headers)
html_contents = r.text
html_soup = BeautifulSoup(html_contents,"lxml")

In [ ]:
tables = html_soup.find_all('table',class_="wikitable")
tables[0].find_all('a')

[<a href="/wiki/Los_Angeles" title="Los Angeles">Los Angeles,<br/>California</a>,
 <a href="/wiki/New_York_City" title="New York City">New York City,<br/>New York</a>,
 <a class="mw-redirect" href="/wiki/Oakland_California" title="Oakland California">Oakland,<br/>California</a>,
 <a href="/wiki/J._P._Calderon" title="J. P. Calderon">J.P. Calderon</a>,
 <a href="/wiki/Long_Beach,_California" title="Long Beach, California">Long Beach,<br/>California</a>,
 <a href="/wiki/Columbia,_South_Carolina" title="Columbia, South Carolina">Columbia,<br/>South Carolina</a>,
 <a href="/wiki/Christiansburg,_Virginia" title="Christiansburg, Virginia">Christiansburg,<br/>Virginia</a>,
 <a href="/wiki/Santa_Monica,_California" title="Santa Monica, California">Santa Monica,<br/>California</a>,
 <a href="/wiki/Chico,_California" title="Chico, California">Chico,<br/>California</a>,
 <a href="/wiki/Santa_Monica,_California" title="Santa Monica, California">Santa Monica,<br/>California</a>,
 <a href="/wiki/Laurelton,_Queens" title="Laurelton, Queens">Laurelton,<br/>New York</a>,
 <a href="/wiki/Lake_Forest,_Illinois" title="Lake Forest, Illinois">Lake Forest,<br/>Illinois</a>,
 <a href="/wiki/Playa_del_Rey,_Los_Angeles" title="Playa del Rey, Los Angeles">Playa del Rey,<br/>California</a>,
 <a href="/wiki/Washington,_D.C." title="Washington, D.C.">Washington,<br/>D.C.</a>,
 <a href="/wiki/Jonathan_Penner" title="Jonathan Penner">Jonathan Penner</a>,
 <a href="/wiki/Los_Angeles" title="Los Angeles">Los Angeles,<br/>California</a>,
 <a href="/wiki/Parvati_Shallow" title="Parvati Shallow">Parvati Shallow</a>,
 <a href="/wiki/West_Hollywood,_California" title="West Hollywood, California">West Hollywood,<br/>California</a>,
 <a href="/wiki/San_Diego" title="San Diego">San Diego,<br/>California</a>,
 <a href="/wiki/Los_Angeles" title="Los Angeles">Los Angeles,<br/>California</a>,
 <a href="/wiki/Washington,_D.C." title="Washington, D.C.">Washington,<br/>D.C.</a>,
 <a href="/wiki/Ozzy_Lusth" title="Ozzy Lusth">Ozzy Lusth</a>,
 <a href="/wiki/Venice,_Los_Angeles" title="Venice, Los Angeles">Venice,<br/>California</a>,
 <a class="mw-redirect" href="/wiki/Yul_Kwon_(television_personality)" title="Yul Kwon (television personality)">Yul Kwon</a>,
 <a href="/wiki/San_Mateo,_California" title="San Mateo, California">San Mateo,<br/>California</a>]

In [ ]:
df = pd.read_html(str(tables))[3]
df

/tmp/ipykernel_3126/1238544221.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(tables))[3]

   Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0  \
              Episode            Episode            Episode
0                 Day                Day                Day
1        Voting tribe       Voting tribe       Voting tribe
2          Eliminated         Eliminated         Eliminated
3               Votes              Votes              Votes
4                 NaN                NaN                NaN
5               Voter              Voter              Voter
6                 Yul                Yul                Yul
7                Ozzy               Ozzy               Ozzy
8               Becky              Becky              Becky
9              Sundra             Sundra             Sundra
10               Adam               Adam               Adam
11            Parvati            Parvati            Parvati
12           Jonathan           Jonathan           Jonathan
13            Candice            Candice            Candice
14               Nate               Nate               Nate
15              Jenny              Jenny              Jenny
16            Rebecca            Rebecca            Rebecca
17               Brad               Brad               Brad
18            Jessica            Jessica            Jessica
19           Cristina           Cristina           Cristina
20            Cao Boi            Cao Boi            Cao Boi
21         Stephannie         Stephannie         Stephannie
22               J.P.               J.P.               J.P.
23            Cecilia            Cecilia            Cecilia
24              Billy              Billy              Billy
25              Sekou              Sekou              Sekou

   Unnamed: 3_level_0 Original tribes           Switched tribes              \
              Episode               1         2               3           4
0                 Day               3         6               8          11
1        Voting tribe        Manihiki  Aitutaki        Aitutaki   Rarotonga
2          Eliminated           Sekou     Billy         Cecilia        J.P.
3               Votes             3–2       4–1             5–3         7–2
4                 NaN             NaN       NaN             NaN         NaN
5               Voter            Vote      Vote            Vote        Vote
6                 Yul             NaN       NaN         Cecilia         NaN
7                Ozzy             NaN     Billy           Becky         NaN
8               Becky             NaN       NaN         Cecilia         NaN
9              Sundra           Sekou       NaN           Becky         NaN
10               Adam             NaN       NaN             NaN        J.P.
11            Parvati             NaN       NaN             NaN        J.P.
12           Jonathan             NaN       NaN         Cecilia         NaN
13            Candice             NaN       NaN       Exiled[d]         NaN
14               Nate          Sundra       NaN             NaN  Stephannie
15              Jenny             NaN       NaN             NaN        J.P.
16            Rebecca           Sekou       NaN             NaN        J.P.
17               Brad             NaN       NaN             NaN        J.P.
18            Jessica             NaN       NaN         Cecilia         NaN
19           Cristina             NaN     Billy             NaN        J.P.
20            Cao Boi             NaN       NaN         Cecilia         NaN
21         Stephannie           Sekou       NaN             NaN        J.P.
22               J.P.             NaN     Billy             NaN  Stephannie
23            Cecilia             NaN     Billy           Becky         NaN
24              Billy             NaN      Ozzy             NaN         NaN
25              Sekou          Sundra       NaN             NaN         NaN

                          ... Merged tribe                                   \
             5         6  ...           11         12         13         14
0           14        15  ...           27         30         33         36
1    Rarotonga  Aitutaki  ...    Aitutonga  Aitutonga  Aitutonga  Aitutonga
2   Stephannie   Cao Boi  ...         Nate    Candice   Jonathan    Parvati
3          7–1     6–1–1  ...          5–4        5–3        6–1        4–2
4          NaN       NaN  ...          NaN        NaN        NaN        NaN
5         Vote      Vote  ...         Vote       Vote       Vote       Vote
6          NaN   Cao Boi  ...         Nate    Candice   Jonathan    Parvati
7          NaN   Cao Boi  ...         Nate    Candice   Jonathan    Parvati
8          NaN   Cao Boi  ...         Nate    Candice   Jonathan    Parvati
9          NaN   Cao Boi  ...         Nate    Candice   Jonathan    Parvati
10  Stephannie       NaN  ...          Yul   Jonathan   Jonathan     Sundra
11  Stephannie       NaN  ...          Yul   Jonathan   Jonathan     Sundra
12         NaN   Cao Boi  ...         Nate    Candice       Adam        NaN
13         NaN   Cao Boi  ...          Yul   Jonathan        NaN        NaN
14  Stephannie       NaN  ...          Yul        NaN        NaN        NaN
15  Stephannie       NaN  ...          NaN        NaN        NaN        NaN
16  Stephannie       NaN  ...          NaN        NaN        NaN        NaN
17  Stephannie       NaN  ...          NaN        NaN        NaN        NaN
18         NaN  Jonathan  ...          NaN        NaN        NaN        NaN
19  Stephannie       NaN  ...          NaN        NaN        NaN        NaN
20         NaN   Candice  ...          NaN        NaN        NaN        NaN
21    Cristina       NaN  ...          NaN        NaN        NaN        NaN
22         NaN       NaN  ...          NaN        NaN        NaN        NaN
23         NaN       NaN  ...          NaN        NaN        NaN        NaN
24         NaN       NaN  ...          NaN        NaN        NaN        NaN
25         NaN       NaN  ...          NaN        NaN        NaN        NaN

                                       Unnamed: 22_level_0  \
           15       15.1          15.2 Unnamed: 22_level_1
0          37         38            38                 NaN
1   Aitutonga  Aitutonga     Aitutonga                 NaN
2        Adam     Tie[b]        Sundra                 NaN
3         4–1        2–2  Challenge[c]                 NaN
4         NaN        NaN           NaN                 NaN
5        Vote       Vote          Vote                 NaN
6        Adam     Sundra           NaN                 NaN
7        Adam      Becky           NaN                 NaN
8        Adam     Sundra        Won[c]                 NaN
9        Adam      Becky       Lost[c]                 NaN
10        Yul        NaN           NaN                 NaN
11        NaN        NaN           NaN                 NaN
12        NaN        NaN           NaN                 NaN
13        NaN        NaN           NaN                 NaN
14        NaN        NaN           NaN                 NaN
15        NaN        NaN           NaN                 NaN
16        NaN        NaN           NaN                 NaN
17        NaN        NaN           NaN                 NaN
18        NaN        NaN           NaN                 NaN
19        NaN        NaN           NaN                 NaN
20        NaN        NaN           NaN                 NaN
21        NaN        NaN           NaN                 NaN
22        NaN        NaN           NaN                 NaN
23        NaN        NaN           NaN                 NaN
24        NaN        NaN           NaN                 NaN
25        NaN        NaN           NaN                 NaN

   Unnamed: 23_level_0 Unnamed: 24_level_0
   Unnamed: 23_level_1 Unnamed: 24_level_1
0                  NaN                 NaN
1                  NaN                 NaN
2                  NaN                 NaN
3                  NaN                 NaN
4                  NaN                 NaN
5                  NaN                 NaN
6                  NaN                 NaN
7                  NaN                 NaN
8                  NaN                 NaN
9                  NaN                 NaN
10                 NaN                 NaN
11                 NaN                 NaN
12                 NaN                 NaN
13                 NaN                 NaN
14                 NaN                 NaN
15                 NaN                 NaN
16                 NaN                 NaN
17                 NaN                 NaN
18                 NaN                 NaN
19                 NaN                 NaN
20                 NaN                 NaN
21                 NaN                 NaN
22                 NaN                 NaN
23                 NaN                 NaN
24                 NaN                 NaN
25                 NaN                 NaN

[26 rows x 25 columns]

In [ ]:
yul_row = df[df[('Unnamed: 0_level_0', 'Episode')] == 'Yul']
print(yul_row)

  Unnamed: 0_level_0 Unnamed: 1_level_0 Unnamed: 2_level_0 Unnamed: 3_level_0  \
             Episode            Episode            Episode            Episode
6                Yul                Yul                Yul                Yul

  Original tribes      Switched tribes                     ... Merged tribe  \
                1    2               3    4    5        6  ...           11
6             NaN  NaN         Cecilia  NaN  NaN  Cao Boi  ...         Nate

                                                 Unnamed: 22_level_0  \
        12        13       14    15    15.1 15.2 Unnamed: 22_level_1
6  Candice  Jonathan  Parvati  Adam  Sundra  NaN                 NaN

  Unnamed: 23_level_0 Unnamed: 24_level_0
  Unnamed: 23_level_1 Unnamed: 24_level_1
6                 NaN                 NaN

[1 rows x 25 columns]

## Survivor 14

In [ ]:
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
}

r = requests.get('https://en.wikipedia.org/wiki/Survivor:_Fiji', headers=headers)
html_contents = r.text
html_soup = BeautifulSoup(html_contents,"lxml")

In [ ]:
tables = html_soup.find_all('table',class_="wikitable")
tables[0].find_all('a')

[<a href="/wiki/Los_Angeles" title="Los Angeles">Los Angeles,<br/>California</a>,
 <a href="/wiki/Baton_Rouge,_Louisiana" title="Baton Rouge, Louisiana">Baton Rouge,<br/>Louisiana</a>,
 <a href="/wiki/Ross,_California" title="Ross, California">Ross,<br/>California</a>,
 <a href="/wiki/Ramsey,_Minnesota" title="Ramsey, Minnesota">Ramsey,<br/>Minnesota</a>,
 <a href="/wiki/Los_Angeles" title="Los Angeles">Los Angeles,<br/>California</a>,
 <a href="/wiki/Rita_Verreos" title="Rita Verreos">Rita Verreos</a>,
 <a href="/wiki/San_Antonio" title="San Antonio">San Antonio,<br/>Texas</a>,
 <a href="/wiki/Compton,_California" title="Compton, California">Compton,<br/>California</a>,
 <a href="/wiki/Los_Angeles" title="Los Angeles">Los Angeles,<br/>California</a>,
 <a href="/wiki/Los_Angeles" title="Los Angeles">Los Angeles,<br/>California</a>,
 <a href="/wiki/Cincinnati" title="Cincinnati">Cincinnati,<br/>Ohio</a>,
 <a href="/wiki/Miami_Beach,_Florida" title="Miami Beach, Florida">Miami Beach,<br/>Florida</a>,
 <a href="/wiki/Chicago" title="Chicago">Chicago,<br/>Illinois</a>,
 <a href="/wiki/Los_Angeles" title="Los Angeles">Los Angeles,<br/>California</a>,
 <a href="/wiki/Boulder,_Colorado" title="Boulder, Colorado">Boulder,<br/>Colorado</a>,
 <a href="/wiki/Lafayette,_Louisiana" title="Lafayette, Louisiana">Lafayette,<br/>Louisiana</a>,
 <a href="/wiki/Yau-Man_Chan" title="Yau-Man Chan">Yau-Man Chan</a>,
 <a href="/wiki/Martinez,_California" title="Martinez, California">Martinez,<br/>California</a>,
 <a href="/wiki/Wilmington,_North_Carolina" title="Wilmington, North Carolina">Wilmington,<br/>North Carolina</a>,
 <a href="/wiki/Los_Angeles" title="Los Angeles">Los Angeles,<br/>California</a>,
 <a href="/wiki/Santa_Monica,_California" title="Santa Monica, California">Santa Monica,<br/>California</a>]

In [ ]:
df = pd.read_html(str(tables))[3]
df

/tmp/ipykernel_3126/1238544221.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(tables))[3]

   Unnamed: 0_level_0 Original tribes                                          \
              Episode               1          2        3        4        4.1
0                 Day               3          6        8       10         11
1               Tribe            Ravu       Ravu     Ravu     Moto       Moto
2          Eliminated         Jessica      Erica   Sylvia     Gary    Liliana
3               Votes         6–1–1–1        6–2    4–3–1  Quit[a]      6–1–1
4                 NaN             NaN        NaN      NaN      NaN        NaN
5               Voter            Vote       Vote     Vote     Vote       Vote
6                Earl         Jessica  Exiled[c]   Sylvia      NaN        NaN
7           Cassandra             NaN        NaN      NaN      NaN       Lisi
8              Dreamz             NaN        NaN      NaN      NaN    Liliana
9             Yau-Man         Jessica      Erica   Sylvia      NaN        NaN
10                Boo             NaN        NaN      NaN      NaN    Liliana
11              Stacy             NaN        NaN      NaN      NaN    Liliana
12               Alex             NaN        NaN      NaN      NaN    Liliana
13             Mookie         Jessica      Erica  Anthony      NaN        NaN
14            Edgardo             NaN        NaN      NaN      NaN    Liliana
15           Michelle         Jessica      Erica   Sylvia      NaN        NaN
16               Lisi             NaN        NaN      NaN      NaN    Liliana
17              Rocky          Mookie      Erica  Anthony      NaN        NaN
18            Anthony         Jessica     Sylvia   Sylvia      NaN        NaN
19               Rita         Jessica      Erica     Earl      NaN        NaN
20            Liliana             NaN        NaN      NaN      NaN  Cassandra
21               Gary             NaN        NaN      NaN     Quit        NaN
22             Sylvia       Exiled[f]      Erica  Anthony      NaN        NaN
23              Erica         Yau-Man     Sylvia      NaN      NaN        NaN
24            Jessica            Rita        NaN      NaN      NaN        NaN

            Switched tribes                Merged tribe                        \
          5               6      7       8            9         10         11
0        14              16     19      21           24         27         30
1      Ravu            Ravu   Ravu    Ravu    Bula Bula  Bula Bula  Bula Bula
2      Rita         Anthony  Rocky    Lisi     Michelle    Edgardo     Mookie
3       5–2             5–1    4–2     4–1          3–2      5–3–1      4–3–1
4       NaN             NaN    NaN     NaN          NaN        NaN        NaN
5      Vote            Vote   Vote    Vote         Vote       Vote       Vote
6      Rita             NaN    NaN     NaN    Immune[d]    Edgardo       Alex
7       NaN             NaN    NaN     NaN    Immune[d]    Edgardo     Mookie
8       NaN         Anthony  Rocky    Lisi     Michelle     Mookie     Mookie
9      Rita             NaN    NaN     NaN    Immune[d]    Edgardo       Alex
10      NaN             NaN    NaN     NaN    Immune[d]    Edgardo     Mookie
11      NaN             NaN    NaN     NaN     Michelle    Edgardo       Alex
12      NaN         Anthony  Rocky    Lisi     Michelle  Cassandra     Mookie
13     Rita         Anthony   Lisi    Lisi        Stacy  Cassandra        Boo
14      NaN         Anthony  Rocky    Lisi    Immune[d]  Cassandra        NaN
15  Anthony             NaN    NaN     NaN        Stacy        NaN        NaN
16      NaN       Exiled[e]  Rocky  Dreamz          NaN        NaN        NaN
17     Rita         Anthony   Lisi     NaN          NaN        NaN        NaN
18     Rita           Rocky    NaN     NaN          NaN        NaN        NaN
19  Anthony             NaN    NaN     NaN          NaN        NaN        NaN
20      NaN             NaN    NaN     NaN          NaN        NaN        NaN
21      NaN             NaN    NaN     NaN          NaN        NaN        NaN
22      NaN             NaN    NaN     NaN          NaN        NaN        NaN
23      NaN             NaN    NaN     NaN          NaN        NaN        NaN
24      NaN             NaN    NaN     NaN          NaN        NaN        NaN

                                               Unnamed: 17_level_0  \
           12         13         14       14.1 Unnamed: 17_level_1
0          33         36         37         38                 NaN
1   Bula Bula  Bula Bula  Bula Bula  Bula Bula                 NaN
2        Alex      Stacy        Boo    Yau-Man                 NaN
3         6–1     2–0[b]        4–1        3–1                 NaN
4         NaN        NaN        NaN        NaN                 NaN
5        Vote       Vote       Vote       Vote                 NaN
6        Alex      Stacy        Boo    Yau-Man                 NaN
7        Alex    Yau-Man        Boo    Yau-Man                 NaN
8        Alex    Yau-Man        Boo    Yau-Man                 NaN
9        Alex      Stacy        Boo  Cassandra                 NaN
10       Alex    Yau-Man     Dreamz        NaN                 NaN
11       Alex    Yau-Man        NaN        NaN                 NaN
12    Yau-Man        NaN        NaN        NaN                 NaN
13        NaN        NaN        NaN        NaN                 NaN
14        NaN        NaN        NaN        NaN                 NaN
15        NaN        NaN        NaN        NaN                 NaN
16        NaN        NaN        NaN        NaN                 NaN
17        NaN        NaN        NaN        NaN                 NaN
18        NaN        NaN        NaN        NaN                 NaN
19        NaN        NaN        NaN        NaN                 NaN
20        NaN        NaN        NaN        NaN                 NaN
21        NaN        NaN        NaN        NaN                 NaN
22        NaN        NaN        NaN        NaN                 NaN
23        NaN        NaN        NaN        NaN                 NaN
24        NaN        NaN        NaN        NaN                 NaN

   Unnamed: 18_level_0
   Unnamed: 18_level_1
0                  NaN
1                  NaN
2                  NaN
3                  NaN
4                  NaN
5                  NaN
6                  NaN
7                  NaN
8                  NaN
9                  NaN
10                 NaN
11                 NaN
12                 NaN
13                 NaN
14                 NaN
15                 NaN
16                 NaN
17                 NaN
18                 NaN
19                 NaN
20                 NaN
21                 NaN
22                 NaN
23                 NaN
24                 NaN

In [ ]:
earl_row = df[df[('Unnamed: 0_level_0', 'Episode')] == 'Earl']
print(earl_row)

  Unnamed: 0_level_0 Original tribes                                     \
             Episode               1          2       3    4  4.1     5
6               Earl         Jessica  Exiled[c]  Sylvia  NaN  NaN  Rita

  Switched tribes           Merged tribe                                   \
                6    7    8            9       10    11    12     13   14
6             NaN  NaN  NaN    Immune[d]  Edgardo  Alex  Alex  Stacy  Boo

           Unnamed: 17_level_0 Unnamed: 18_level_0
      14.1 Unnamed: 17_level_1 Unnamed: 18_level_1
6  Yau-Man                 NaN                 NaN

## Survivor 15

In [ ]:
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
}

r = requests.get('https://en.wikipedia.org/wiki/Survivor:_China', headers=headers)
html_contents = r.text
html_soup = BeautifulSoup(html_contents,"lxml")

In [ ]:
tables = html_soup.find_all('table',class_="wikitable")
tables[0].find_all('a')

[<a href="/wiki/Marion,_Virginia" title="Marion, Virginia">Marion,<br/>Virginia</a>,
 <a href="/wiki/Ashley_Massaro" title="Ashley Massaro">Ashley Massaro</a>,
 <a href="/wiki/East_Northport,_New_York" title="East Northport, New York">East Northport,<br/>New York</a>,
 <a href="/wiki/Tega_Cay,_South_Carolina" title="Tega Cay, South Carolina">Tega Cay,<br/>South Carolina</a>,
 <a href="/wiki/Simi_Valley,_California" title="Simi Valley, California">Simi Valley,<br/>California</a>,
 <a href="/wiki/Venice,_Los_Angeles" title="Venice, Los Angeles">Venice,<br/>California</a>,
 <a href="/wiki/Atlanta" title="Atlanta">Atlanta,<br/>Georgia</a>,
 <a href="/wiki/Columbia,_South_Carolina" title="Columbia, South Carolina">Columbia,<br/>South Carolina</a>,
 <a href="/wiki/Jean-Robert_Bellande" title="Jean-Robert Bellande">Jean-Robert Bellande</a>,
 <a href="/wiki/Las_Vegas" title="Las Vegas">Las Vegas,<br/> Nevada</a>,
 <a href="/wiki/Chicago" title="Chicago">Chicago,<br/>Illinois</a>,
 <a href="/wiki/Lafayette,_Louisiana" title="Lafayette, Louisiana">Lafayette,<br/>Louisiana</a>,
 <a href="/wiki/Nashville,_Tennessee" title="Nashville, Tennessee">Nashville,<br/>Tennessee</a>,
 <a href="/wiki/Marina_del_Rey,_California" title="Marina del Rey, California">Marina del Rey,<br/>California</a>,
 <a href="/wiki/Douglas,_Massachusetts" title="Douglas, Massachusetts">Douglas,<br/>Massachusetts</a>,
 <a href="/wiki/Los_Angeles" title="Los Angeles">Los Angeles,<br/>California</a>,
 <a href="/wiki/New_York_City" title="New York City">New York City,<br/>New York</a>,
 <a href="/wiki/Todd_Herzog" title="Todd Herzog">Todd Herzog</a>,
 <a href="/wiki/Pleasant_Grove,_Utah" title="Pleasant Grove, Utah">Pleasant Grove,<br/>Utah</a>]

In [ ]:
df = pd.read_html(str(tables))[3]
df

/tmp/ipykernel_3126/1238544221.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(tables))[3]

   Unnamed: 0_level_0 Original tribes                                 \
              Episode               1        2            3        4
0                 Day               3        6            9       12
1               Tribe         Zhan Hu  Zhan Hu     Fei Long  Zhan Hu
2          Eliminated         Chicken   Ashley       Leslie     Dave
3               Votes           5–2–1      6–1          6–2      5–1
4                 NaN             NaN      NaN          NaN      NaN
5               Voter            Vote     Vote         Vote     Vote
6                Todd             NaN      NaN       Leslie      NaN
7            Courtney             NaN      NaN  Jean-Robert      NaN
8              Amanda             NaN      NaN       Leslie      NaN
9              Denise             NaN      NaN       Leslie      NaN
10           Peih-Gee         Chicken   Ashley          NaN     Dave
11               Erik         Chicken   Ashley          NaN     Dave
12              James             NaN      NaN       Leslie      NaN
13             Frosti         Chicken   Ashley          NaN     Dave
14        Jean-Robert             NaN      NaN       Leslie      NaN
15              Jaime         Chicken   Ashley          NaN     Dave
16             Sherea         Chicken   Ashley          NaN     Dave
17              Aaron             NaN      NaN       Leslie      NaN
18               Dave          Ashley   Ashley          NaN   Sherea
19             Leslie             NaN      NaN  Jean-Robert      NaN
20             Ashley        Peih-Gee     Dave          NaN      NaN
21            Chicken          Ashley      NaN          NaN      NaN

   Switched tribes              Merged tribe                            \
                 5            6            7            8            9
0               15           18           21           24           27
1          Zhan Hu     Fei Long  Hae Da Fung  Hae Da Fung  Hae Da Fung
2            Aaron       Sherea        Jaime  Jean-Robert       Frosti
3            3–1–1          5–2          7–3        5–3–1          7–1
4              NaN          NaN          NaN          NaN          NaN
5             Vote         Vote         Vote         Vote         Vote
6              NaN       Sherea        Jaime  Jean-Robert       Frosti
7              NaN  Jean-Robert        Jaime  Jean-Robert       Frosti
8              NaN       Sherea        Jaime  Jean-Robert       Frosti
9              NaN       Sherea        Jaime     Peih-Gee       Frosti
10           Aaron          NaN  Jean-Robert        James       Frosti
11           Aaron          NaN  Jean-Robert        James       Frosti
12        Peih-Gee          NaN        Jaime  Jean-Robert       Frosti
13             NaN       Sherea        Jaime  Jean-Robert         Erik
14             NaN       Sherea        Jaime        James          NaN
15           Aaron          NaN  Jean-Robert          NaN          NaN
16             NaN  Jean-Robert          NaN          NaN          NaN
17           James          NaN          NaN          NaN          NaN
18             NaN          NaN          NaN          NaN          NaN
19             NaN          NaN          NaN          NaN          NaN
20             NaN          NaN          NaN          NaN          NaN
21             NaN          NaN          NaN          NaN          NaN

                                                       Unnamed: 14_level_0  \
             11           12           13           14 Unnamed: 14_level_1
0            30           33           36           38                 NaN
1   Hae Da Fung  Hae Da Fung  Hae Da Fung  Hae Da Fung                 NaN
2         James         Erik     Peih-Gee       Denise                 NaN
3         5–1–1          4–2          4–1          3–1                 NaN
4           NaN          NaN          NaN          NaN                 NaN
5          Vote         Vote         Vote         Vote                 NaN
6         James         Erik     Peih-Gee       Denise                 NaN
7         James         Erik     Peih-Gee       Denise                 NaN
8         James         Erik     Peih-Gee       Denise                 NaN
9         James         Erik     Peih-Gee         Todd                 NaN
10         Todd         Todd         Todd          NaN                 NaN
11        James         Todd          NaN          NaN                 NaN
12     Peih-Gee          NaN          NaN          NaN                 NaN
13          NaN          NaN          NaN          NaN                 NaN
14          NaN          NaN          NaN          NaN                 NaN
15          NaN          NaN          NaN          NaN                 NaN
16          NaN          NaN          NaN          NaN                 NaN
17          NaN          NaN          NaN          NaN                 NaN
18          NaN          NaN          NaN          NaN                 NaN
19          NaN          NaN          NaN          NaN                 NaN
20          NaN          NaN          NaN          NaN                 NaN
21          NaN          NaN          NaN          NaN                 NaN

   Unnamed: 15_level_0
   Unnamed: 15_level_1
0                  NaN
1                  NaN
2                  NaN
3                  NaN
4                  NaN
5                  NaN
6                  NaN
7                  NaN
8                  NaN
9                  NaN
10                 NaN
11                 NaN
12                 NaN
13                 NaN
14                 NaN
15                 NaN
16                 NaN
17                 NaN
18                 NaN
19                 NaN
20                 NaN
21                 NaN

In [ ]:
todd_row = df[df[('Unnamed: 0_level_0', 'Episode')] == 'Todd']
print(todd_row)

  Unnamed: 0_level_0 Original tribes                   Switched tribes  \
             Episode               1    2       3    4               5
6               Todd             NaN  NaN  Leslie  NaN             NaN

          Merged tribe                                                      \
        6            7            8       9     11    12        13      14
6  Sherea        Jaime  Jean-Robert  Frosti  James  Erik  Peih-Gee  Denise

  Unnamed: 14_level_0 Unnamed: 15_level_0
  Unnamed: 14_level_1 Unnamed: 15_level_1
6                 NaN                 NaN

## Survivor 16

In [ ]:
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
}

r = requests.get('https://en.wikipedia.org/wiki/Survivor:_Micronesia', headers=headers)
html_contents = r.text
html_soup = BeautifulSoup(html_contents,"lxml")

In [ ]:
tables = html_soup.find_all('table',class_="wikitable")
tables[0].find_all('a')

[<a href="/wiki/Jonny_Fairplay" title="Jonny Fairplay">Jonny Fairplay</a>,
 <a href="/wiki/Survivor:_Pearl_Islands" title="Survivor: Pearl Islands">Pearl Islands</a>,
 <a href="/wiki/Los_Angeles" title="Los Angeles">Los Angeles,<br/>California</a>,
 <a href="/wiki/Emeryville,_California" title="Emeryville, California">Emeryville,<br/>California</a>,
 <a href="/wiki/Yau-Man_Chan" title="Yau-Man Chan">Yau-Man Chan</a>,
 <a href="/wiki/Survivor:_Fiji" title="Survivor: Fiji">Fiji</a>,
 <a href="/wiki/Martinez,_California" title="Martinez, California">Martinez,<br/>California</a>,
 <a href="/wiki/Los_Angeles" title="Los Angeles">Los Angeles,<br/>California</a>,
 <a href="/wiki/Avondale,_Arizona" title="Avondale, Arizona">Avondale,<br/>Arizona</a>,
 <a href="/wiki/Jonathan_Penner" title="Jonathan Penner">Jonathan Penner</a>,
 <a href="/wiki/Survivor:_Cook_Islands" title="Survivor: Cook Islands">Cook Islands</a>,
 <a href="/wiki/Los_Angeles" title="Los Angeles">Los Angeles,<br/>California</a>,
 <a href="/wiki/Ford_City,_Pennsylvania" title="Ford City, Pennsylvania">Ford City,<br/>Pennsylvania</a>,
 <a href="/wiki/Glen_Ellyn,_Illinois" title="Glen Ellyn, Illinois">Glen Ellyn,<br/>Illinois</a>,
 <a href="/wiki/Fredericksburg,_Virginia" title="Fredericksburg, Virginia">Fredericksburg,<br/>Virginia</a>,
 <a href="/wiki/Survivor:_Vanuatu" title="Survivor: Vanuatu">Vanuatu</a>,
 <a href="/wiki/Golden,_Colorado" title="Golden, Colorado">Golden,<br/>Colorado</a>,
 <a href="/wiki/Eliza_Orlins" title="Eliza Orlins">Eliza Orlins</a>,
 <a href="/wiki/Survivor:_Vanuatu" title="Survivor: Vanuatu">Vanuatu</a>,
 <a href="/wiki/Manhattan" title="Manhattan">Manhattan,<br/>New York</a>,
 <a href="/wiki/Ozzy_Lusth" title="Ozzy Lusth">Oscar "Ozzy" Lusth</a>,
 <a href="/wiki/Survivor:_Cook_Islands" title="Survivor: Cook Islands">Cook Islands</a>,
 <a href="/wiki/Venice,_Los_Angeles" title="Venice, Los Angeles">Venice,<br/>California</a>,
 <a href="/wiki/Fox_River_Grove,_Illinois" title="Fox River Grove, Illinois">Fox River Grove,<br/>Illinois</a>,
 <a href="/wiki/Survivor:_China" title="Survivor: China">China</a>,
 <a href="/wiki/Lafayette,_Louisiana" title="Lafayette, Louisiana">Lafayette,<br/>Louisiana</a>,
 <a href="/wiki/Alexis_Jones" title="Alexis Jones">Alexis Jones</a>,
 <a href="/wiki/Beverly_Hills,_California" title="Beverly Hills, California">Beverly Hills,<br/>California</a>,
 <a href="/wiki/Ypsilanti,_Michigan" title="Ypsilanti, Michigan">Ypsilanti,<br/>Michigan</a>,
 <a href="/wiki/West_Hollywood,_California" title="West Hollywood, California">West Hollywood,<br/>California</a>,
 <a href="/wiki/Cirie_Fields" title="Cirie Fields">Cirie Fields</a>,
 <a href="/wiki/Survivor:_Panama" title="Survivor: Panama">Panama</a>,
 <a href="/wiki/Norwalk,_Connecticut" title="Norwalk, Connecticut">Norwalk,<br/>Connecticut</a>,
 <a href="/wiki/Survivor:_China" title="Survivor: China">China</a>,
 <a href="/wiki/Los_Angeles" title="Los Angeles">Los Angeles,<br/>California</a>,
 <a href="/wiki/Parvati_Shallow" title="Parvati Shallow">Parvati Shallow</a>,
 <a href="/wiki/Survivor:_Cook_Islands" title="Survivor: Cook Islands">Cook Islands</a>,
 <a href="/wiki/Los_Angeles" title="Los Angeles">Los Angeles,<br/>California</a>]

In [ ]:
df = pd.read_html(str(tables))[3]
df

/tmp/ipykernel_3126/1238544221.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(tables))[3]

   Unnamed: 0_level_0 Original tribes                           \
              Episode               1      2        3        4
0                 Day               3      6        8       11
1               Tribe         Malakal  Airai  Malakal    Airai
2          Eliminated  Jonny Fairplay   Mary  Yau-Man  Mikey B
3               Votes             9–1  6–2–2    6–2–1      6–3
4               Voter            Vote   Vote     Vote     Vote
5             Parvati  Jonny Fairplay    NaN  Yau-Man      NaN
6              Amanda  Jonny Fairplay    NaN  Yau-Man      NaN
7               Cirie  Jonny Fairplay    NaN  Yau-Man      NaN
8             Natalie             NaN   Mary      NaN  Mikey B
9                Erik             NaN   Mary      NaN  Mikey B
10             Alexis             NaN   Mary      NaN     Chet
11              James  Jonny Fairplay    NaN  Yau-Man      NaN
12              Jason             NaN   Chet      NaN     Chet
13               Ozzy  Jonny Fairplay    NaN  Yau-Man      NaN
14              Eliza  Jonny Fairplay    NaN  Yau-Man      NaN
15                Ami  Jonny Fairplay    NaN    Cirie      NaN
16              Tracy             NaN   Mary      NaN  Mikey B
17              Kathy             NaN   Mary      NaN  Mikey B
18               Chet             NaN   Mary      NaN  Mikey B
19           Jonathan  Jonny Fairplay    NaN  Parvati      NaN
20               Joel             NaN  Tracy      NaN  Mikey B
21            Mikey B             NaN   Chet      NaN     Chet
22            Yau-Man  Jonny Fairplay    NaN  Parvati      NaN
23               Mary             NaN  Tracy      NaN      NaN
24     Jonny Fairplay            Ozzy    NaN      NaN      NaN

   Switched tribes                                           ... Merged tribe  \
                 5             6      6.1        7      7.1  ...            9
0               14            15       17       19       20  ...           24
1          Malakal         Airai  Malakal    Airai  Malakal  ...         Dabu
2             Joel      Jonathan     Chet    Kathy    Tracy  ...        Eliza
3              6–2  Evacuated[a]      5–2  Quit[b]      5–1  ...          8–2
4             Vote          Vote     Vote     Vote     Vote  ...         Vote
5              NaN           NaN      NaN      NaN      NaN  ...        Eliza
6             Joel           NaN     Chet      NaN    Tracy  ...        Eliza
7             Joel           NaN     Chet      NaN    Tracy  ...        Eliza
8              NaN           NaN      NaN      NaN      NaN  ...        Eliza
9             Chet           NaN     Chet      NaN    Tracy  ...        Eliza
10             NaN           NaN      NaN      NaN      NaN  ...        Eliza
11             NaN           NaN      NaN      NaN      NaN  ...        Eliza
12             NaN           NaN      NaN      NaN      NaN  ...         Ozzy
13            Joel           NaN     Chet      NaN    Tracy  ...        Eliza
14             NaN           NaN      NaN      NaN      NaN  ...         Ozzy
15            Joel           NaN     Chet      NaN    Tracy  ...          NaN
16            Joel           NaN     Erik      NaN     Ozzy  ...          NaN
17             NaN           NaN      NaN     Quit      NaN  ...          NaN
18            Joel           NaN     Erik      NaN      NaN  ...          NaN
19             NaN     Evacuated      NaN      NaN      NaN  ...          NaN
20            Chet           NaN      NaN      NaN      NaN  ...          NaN
21             NaN           NaN      NaN      NaN      NaN  ...          NaN
22             NaN           NaN      NaN      NaN      NaN  ...          NaN
23             NaN           NaN      NaN      NaN      NaN  ...          NaN
24             NaN           NaN      NaN      NaN      NaN  ...          NaN

                                                                     \
       10       11            12    12.1       13       14     14.1
0      27       30            31      33       36       37       38
1    Dabu     Dabu          Dabu    Dabu     Dabu     Dabu     Dabu
2    Ozzy    Jason         James  Alexis     Erik  Natalie    Cirie
3     5–4    4–3–1  Evacuated[c]  2–0[d]      4–1      3–1      1–0
4    Vote     Vote          Vote    Vote     Vote     Vote     Vote
5    Ozzy    Jason           NaN  Alexis     Erik  Natalie  None[e]
6   Jason    Jason           NaN  Alexis     Erik  Natalie    Cirie
7    Ozzy    Jason           NaN  Amanda     Erik  Natalie  None[e]
8    Ozzy    James           NaN  Amanda     Erik    Cirie      NaN
9   Jason    Jason           NaN  Amanda  Parvati      NaN      NaN
10   Ozzy    James           NaN  Amanda      NaN      NaN      NaN
11  Jason  Parvati           NaN     NaN      NaN      NaN      NaN
12   Ozzy    James           NaN     NaN      NaN      NaN      NaN
13  Jason      NaN           NaN     NaN      NaN      NaN      NaN
14    NaN      NaN           NaN     NaN      NaN      NaN      NaN
15    NaN      NaN           NaN     NaN      NaN      NaN      NaN
16    NaN      NaN           NaN     NaN      NaN      NaN      NaN
17    NaN      NaN           NaN     NaN      NaN      NaN      NaN
18    NaN      NaN           NaN     NaN      NaN      NaN      NaN
19    NaN      NaN           NaN     NaN      NaN      NaN      NaN
20    NaN      NaN           NaN     NaN      NaN      NaN      NaN
21    NaN      NaN           NaN     NaN      NaN      NaN      NaN
22    NaN      NaN           NaN     NaN      NaN      NaN      NaN
23    NaN      NaN           NaN     NaN      NaN      NaN      NaN
24    NaN      NaN           NaN     NaN      NaN      NaN      NaN


   Unnamed: 19_level_1 Unnamed: 20_level_1
0                  NaN                 NaN
1                  NaN                 NaN
2                  NaN                 NaN
3                  NaN                 NaN
4                  NaN                 NaN
5                  NaN                 NaN
6                  NaN                 NaN
7                  NaN                 NaN
8                  NaN                 NaN
9                  NaN                 NaN
10                 NaN                 NaN
11                 NaN                 NaN
12                 NaN                 NaN
13                 NaN                 NaN
14                 NaN                 NaN
15                 NaN                 NaN
16                 NaN                 NaN
17                 NaN                 NaN
18                 NaN                 NaN
19                 NaN                 NaN
20                 NaN                 NaN
21                 NaN                 NaN
22                 NaN                 NaN
23                 NaN                 NaN
24                 NaN                 NaN

[25 rows x 21 columns]

In [ ]:
parvati_row = df[df[('Unnamed: 0_level_0', 'Episode')] == 'Parvati']
print(parvati_row)

  Unnamed: 0_level_0 Original tribes                    Switched tribes       \
             Episode               1    2        3    4               5    6
5            Parvati  Jonny Fairplay  NaN  Yau-Man  NaN             NaN  NaN

                  ... Merged tribe                                           \
   6.1    7  7.1  ...            9    10     11   12    12.1    13       14
5  NaN  NaN  NaN  ...        Eliza  Ozzy  Jason  NaN  Alexis  Erik  Natalie


      14.1 Unnamed: 19_level_1 Unnamed: 20_level_1
5  None[e]                 NaN                 NaN

[1 rows x 21 columns]

## Survivor 17

In [ ]:
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
}

r = requests.get('https://en.wikipedia.org/wiki/Survivor:_Gabon', headers=headers)
html_contents = r.text
html_soup = BeautifulSoup(html_contents,"lxml")

In [ ]:
tables = html_soup.find_all('table',class_="wikitable")
tables[0].find_all('a')

[<a href="/wiki/Los_Angeles" title="Los Angeles">Los Angeles,<br/>California</a>,
 <a href="/wiki/Temecula,_California" title="Temecula, California">Temecula,<br/>California</a>,
 <a href="/wiki/Downey,_California" title="Downey, California">Downey,<br/>California</a>,
 <a href="/wiki/Santa_Barbara,_California" title="Santa Barbara, California">Santa Barbara,<br/>California</a>,
 <a href="/wiki/Portland,_Oregon" title="Portland, Oregon">Portland,<br/>Oregon</a>,
 <a href="/wiki/Buffalo_Grove,_Illinois" title="Buffalo Grove, Illinois">Buffalo Grove,<br/>Illinois</a>,
 <a href="/wiki/Naples,_Florida" title="Naples, Florida">Naples,<br/>Florida</a>,
 <a href="/wiki/Boston" title="Boston">Boston,<br/>Massachusetts</a>,
 <a href="/wiki/Atlanta" title="Atlanta">Atlanta,<br/>Georgia</a>,
 <a href="/wiki/New_York_City" title="New York City">New York City,<br/>New York</a>,
 <a href="/wiki/Eagle_Rock,_Missouri" title="Eagle Rock, Missouri">Eagle Rock,<br/>Missouri</a>,
 <a href="/wiki/Los_Angeles" title="Los Angeles">Los Angeles,<br/>California</a>,
 <a href="/wiki/Crystal_Cox" title="Crystal Cox">Crystal Cox</a>,
 <a href="/wiki/Durham,_North_Carolina" title="Durham, North Carolina">Durham,<br/>North Carolina</a>,
 <a href="/wiki/Ken_Hoang" title="Ken Hoang">Ken Hoang</a>,
 <a href="/wiki/Westminster,_California" title="Westminster, California">Westminster,<br/>California</a>,
 <a href="/wiki/Pacific_Palisades,_Los_Angeles" title="Pacific Palisades, Los Angeles">Pacific Palisades,<br/>California</a>,
 <a class="mw-redirect" href="/wiki/Jessica_Kiper" title="Jessica Kiper">Jessica "Sugar" Kiper</a>,
 <a href="/wiki/Brooklyn" title="Brooklyn">Brooklyn,<br/>New York</a>,
 <a href="/wiki/Charles_City,_Iowa" title="Charles City, Iowa">Charles City,<br/>Iowa</a>,
 <a href="/wiki/Portland,_Maine" title="Portland, Maine">Portland,<br/>Maine</a>]

In [ ]:
df = pd.read_html(str(tables))[3]
df

/tmp/ipykernel_3126/1238544221.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(tables))[3]

   Unnamed: 0_level_0 Original tribes                  First switch         \
              Episode               1      1.1       2            3      4
0                 Day               3        6       9           12     15
1               Tribe            Fang     Fang    Kota         Fang   Fang
2          Eliminated        Michelle  Gillian  Paloma      Jacquie     GC
3               Votes             8–1      7–1     7–2          5–2    6–1
4                 NaN             NaN      NaN     NaN          NaN    NaN
5               Voter            Vote     Vote    Vote         Vote   Vote
6                 Bob             NaN      NaN  Paloma          NaN    NaN
7               Susie        Michelle  Gillian     NaN          NaN    NaN
8               Sugar             NaN      NaN  Paloma    Exiled[d]     GC
9               Matty        Michelle  Gillian     NaN      Jacquie     GC
10                Ken        Michelle  Gillian     NaN      Jacquie     GC
11            Crystal        Michelle  Gillian     NaN      Jacquie     GC
12            Corinne             NaN      NaN  Paloma          NaN    NaN
13              Randy        Michelle  Gillian     NaN          NaN    NaN
14            Charlie             NaN      NaN  Paloma          NaN    NaN
15             Marcus             NaN      NaN  Paloma          NaN    NaN
16                Dan        Michelle  Gillian     NaN          NaN    NaN
17                Ace             NaN      NaN  Paloma        Kelly     GC
18              Kelly             NaN      NaN     Ace      Jacquie     GC
19                 GC        Michelle  Gillian     NaN      Jacquie  Kelly
20            Jacquie             NaN      NaN  Paloma        Kelly    NaN
21             Paloma             NaN      NaN     Ace          NaN    NaN
22            Gillian        Michelle      Ken     NaN          NaN    NaN
23           Michelle         Gillian      NaN     NaN          NaN    NaN

                            Second switch Merged tribe                  \
          5        6    6.1             7            8      9       11
0        18       21     21            24           27     30       33
1      Fang     Fang   Kota          Kota        Nobag  Nobag    Nobag
2     Kelly      Ace    Dan        Marcus      Charlie  Randy  Corinne
3       5–1      3–2    4–3           3–2          5–4    5–3      4–3
4       NaN      NaN    NaN           NaN          NaN    NaN      NaN
5      Vote     Vote   Vote          Vote         Vote   Vote     Vote
6       NaN      NaN    Dan           Ken      Crystal  Susie    Matty
7       NaN      NaN    Dan        Marcus      Charlie  Randy  Corinne
8     Kelly      Ace    NaN           NaN      Charlie  Randy  Corinne
9     Kelly  Crystal    NaN           NaN      Charlie  Randy  Corinne
10    Kelly      Ace    NaN        Marcus      Charlie  Randy    Matty
11    Kelly      Ace    NaN        Marcus      Charlie  Randy  Corinne
12      NaN      NaN    Dan           NaN      Crystal  Susie    Matty
13      NaN      NaN  Susie           NaN      Crystal  Susie      NaN
14      NaN      NaN    Dan           NaN      Crystal    NaN      NaN
15      NaN      NaN  Susie           Ken          NaN    NaN      NaN
16      NaN      NaN  Susie           NaN          NaN    NaN      NaN
17    Kelly  Crystal    NaN           NaN          NaN    NaN      NaN
18  Crystal      NaN    NaN           NaN          NaN    NaN      NaN
19      NaN      NaN    NaN           NaN          NaN    NaN      NaN
20      NaN      NaN    NaN           NaN          NaN    NaN      NaN
21      NaN      NaN    NaN           NaN          NaN    NaN      NaN
22      NaN      NaN    NaN           NaN          NaN    NaN      NaN
23      NaN      NaN    NaN           NaN          NaN    NaN      NaN

                                         Unnamed: 17_level_0  \
         12     13    13.1          13.2 Unnamed: 17_level_1
0        36     37      38            38                 NaN
1     Nobag  Nobag   Nobag         Nobag                 NaN
2   Crystal    Ken  Tie[a]         Matty                 NaN
3    4–0[b]    4–1     2–2  Challenge[c]                 NaN
4       NaN    NaN     NaN           NaN                 NaN
5      Vote   Vote    Vote          Vote                 NaN
6   Crystal    Ken   Matty        Won[c]                 NaN
7   Crystal    Ken     Bob           NaN                 NaN
8   Crystal    Ken   Matty           NaN                 NaN
9   Crystal    Ken     Bob       Lost[c]                 NaN
10    Matty  Susie     NaN           NaN                 NaN
11    Matty    NaN     NaN           NaN                 NaN
12      NaN    NaN     NaN           NaN                 NaN
13      NaN    NaN     NaN           NaN                 NaN
14      NaN    NaN     NaN           NaN                 NaN
15      NaN    NaN     NaN           NaN                 NaN
16      NaN    NaN     NaN           NaN                 NaN
17      NaN    NaN     NaN           NaN                 NaN
18      NaN    NaN     NaN           NaN                 NaN
19      NaN    NaN     NaN           NaN                 NaN
20      NaN    NaN     NaN           NaN                 NaN
21      NaN    NaN     NaN           NaN                 NaN
22      NaN    NaN     NaN           NaN                 NaN
23      NaN    NaN     NaN           NaN                 NaN

   Unnamed: 18_level_0 Unnamed: 19_level_0
   Unnamed: 18_level_1 Unnamed: 19_level_1
0                  NaN                 NaN
1                  NaN                 NaN
2                  NaN                 NaN
3                  NaN                 NaN
4                  NaN                 NaN
5                  NaN                 NaN
6                  NaN                 NaN
7                  NaN                 NaN
8                  NaN                 NaN
9                  NaN                 NaN
10                 NaN                 NaN
11                 NaN                 NaN
12                 NaN                 NaN
13                 NaN                 NaN
14                 NaN                 NaN
15                 NaN                 NaN
16                 NaN                 NaN
17                 NaN                 NaN
18                 NaN                 NaN
19                 NaN                 NaN
20                 NaN                 NaN
21                 NaN                 NaN
22                 NaN                 NaN
23                 NaN                 NaN

In [ ]:
bob_row = df[df[('Unnamed: 0_level_0', 'Episode')] == 'Bob']
print(bob_row)

  Unnamed: 0_level_0 Original tribes              First switch                 \
             Episode               1  1.1       2            3    4    5    6
6                Bob             NaN  NaN  Paloma          NaN  NaN  NaN  NaN

       Second switch Merged tribe                                             \
   6.1             7            8      9     11       12   13   13.1    13.2
6  Dan           Ken      Crystal  Susie  Matty  Crystal  Ken  Matty  Won[c]

  Unnamed: 17_level_0 Unnamed: 18_level_0 Unnamed: 19_level_0
  Unnamed: 17_level_1 Unnamed: 18_level_1 Unnamed: 19_level_1
6                 NaN                 NaN                 NaN

## Survivor 18

In [ ]:
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
}

r = requests.get('https://en.wikipedia.org/wiki/Survivor:_Tocantins', headers=headers)
html_contents = r.text
html_soup = BeautifulSoup(html_contents,"lxml")

In [ ]:
tables = html_soup.find_all('table',class_="wikitable")
tables[0].find_all('a')

[<a href="/wiki/West_Hollywood,_California" title="West Hollywood, California">West Hollywood,<br/>California</a>,
 <a href="/wiki/Los_Angeles" title="Los Angeles">Los Angeles,<br/>California</a>,
 <a href="/wiki/Rock_Hill,_South_Carolina" title="Rock Hill, South Carolina">Rock Hill,<br/>South Carolina</a>,
 <a href="/wiki/Louisville,_Kentucky" title="Louisville, Kentucky">Louisville,<br/>Kentucky</a>,
 <a href="/wiki/Gainesville,_Florida" title="Gainesville, Florida">Gainesville,<br/>Florida</a>,
 <a href="/wiki/San_Diego" title="San Diego">San Diego,<br/>California</a>,
 <a href="/wiki/Austin,_Texas" title="Austin, Texas">Austin,<br/>Texas</a>,
 <a href="/wiki/Vail,_Colorado" title="Vail, Colorado">Vail,<br/>Colorado</a>,
 <a href="/wiki/Tyson_Apostol" title="Tyson Apostol">Tyson Apostol</a>,
 <a href="/wiki/Heber_City,_Utah" title="Heber City, Utah">Heber City,<br/>Utah</a>,
 <a href="/wiki/Los_Angeles" title="Los Angeles">Los Angeles,<br/>California</a>,
 <a href="/wiki/Auburn,_Alabama" title="Auburn, Alabama">Auburn,<br/>Alabama</a>,
 <a href="/wiki/Coach_(Survivor_contestant)" title="Coach (Survivor contestant)">Benjamin "Coach" Wade</a>,
 <a href="/wiki/Bolivar,_Missouri" title="Bolivar, Missouri">Bolivar,<br/>Missouri</a>,
 <a href="/wiki/Tamara_Johnson-George" title="Tamara Johnson-George">Tamara "Taj" Johnson-George</a>,
 <a href="/wiki/Nashville,_Tennessee" title="Nashville, Tennessee">Nashville,<br/>Tennessee</a>,
 <a href="/wiki/Milwaukee" title="Milwaukee">Milwaukee,<br/>Wisconsin</a>,
 <a href="/wiki/Stephen_Fishbach" title="Stephen Fishbach">Stephen Fishbach</a>,
 <a href="/wiki/New_York_City" title="New York City">New York City,<br/>New York</a>,
 <a href="/wiki/Mobile,_Alabama" title="Mobile, Alabama">Mobile,<br/>Alabama</a>]

In [ ]:
df = pd.read_html(str(tables))[3]
df

/tmp/ipykernel_3126/1238544221.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(tables))[3]

   Unnamed: 0_level_0 Original tribes                                      \
              Episode               1        2        3        4        5
0                 Day               3        6        9       12       15
1               Tribe         Jalapao  Timbira  Timbira  Jalapao  Jalapao
2          Eliminated        Carolina  Candace    Jerry    Sandy  Spencer
3               Votes             7–1      7–1      6–1    5–1–1      5–1
4                 NaN             NaN      NaN      NaN      NaN      NaN
5               Voter            Vote     Vote     Vote     Vote     Vote
6                J.T.        Carolina      NaN      NaN    Sandy  Spencer
7             Stephen        Carolina      NaN      NaN    Sandy  Spencer
8               Erinn             NaN  Candace    Jerry      NaN      NaN
9                 Taj        Carolina      NaN      NaN      Joe  Spencer
10              Coach             NaN  Candace    Jerry      NaN      NaN
11             Debbie             NaN  Candace    Jerry      NaN      NaN
12             Sierra             NaN  Candace    Jerry      NaN      NaN
13              Tyson             NaN  Candace    Jerry      NaN      NaN
14            Brendan             NaN  Candace    Jerry      NaN      NaN
15                Joe        Carolina      NaN      NaN    Sandy  Spencer
16             Sydney        Carolina      NaN      NaN    Sandy  Spencer
17            Spencer        Carolina      NaN      NaN    Sandy      Taj
18              Sandy        Carolina      NaN      NaN   Sydney      NaN
19              Jerry             NaN  Candace    Erinn      NaN      NaN
20            Candace             NaN   Sierra      NaN      NaN      NaN
21           Carolina           Sandy      NaN      NaN      NaN      NaN

             Merged tribe                                                  \
          7             8        9      10       11      12     13     14
0        18            20       24      27       30      33     36     37
1   Jalapao         Forza    Forza   Forza    Forza   Forza  Forza  Forza
2    Sydney           Joe  Brendan   Tyson   Sierra  Debbie  Coach    Taj
3       3–2  Evacuated[a]    4–3–2     5–3    4–2–1   4–1–1    3–2    3–1
4       NaN           NaN      NaN     NaN      NaN     NaN    NaN    NaN
5      Vote          Vote     Vote    Vote     Vote    Vote   Vote   Vote
6    Sydney           NaN   Sierra   Tyson   Sierra  Debbie  Erinn    Taj
7    Sydney           NaN  Brendan   Tyson   Sierra  Debbie  Coach    Taj
8       NaN           NaN   Sierra   Tyson  Stephen  Debbie  Coach    Taj
9    Sydney           NaN  Brendan   Tyson   Debbie  Debbie  Coach  Erinn
10      NaN           NaN  Brendan  Sierra   Sierra     Taj  Erinn    NaN
11      NaN           NaN  Brendan  Sierra   Sierra   Coach    NaN    NaN
12      NaN           NaN    Coach   Tyson   Debbie     NaN    NaN    NaN
13      NaN           NaN   Sierra  Sierra      NaN     NaN    NaN    NaN
14      NaN           NaN    Coach     NaN      NaN     NaN    NaN    NaN
15      Taj     Evacuated      NaN     NaN      NaN     NaN    NaN    NaN
16      Taj           NaN      NaN     NaN      NaN     NaN    NaN    NaN
17      NaN           NaN      NaN     NaN      NaN     NaN    NaN    NaN
18      NaN           NaN      NaN     NaN      NaN     NaN    NaN    NaN
19      NaN           NaN      NaN     NaN      NaN     NaN    NaN    NaN
20      NaN           NaN      NaN     NaN      NaN     NaN    NaN    NaN
21      NaN           NaN      NaN     NaN      NaN     NaN    NaN    NaN

            Unnamed: 15_level_0 Unnamed: 16_level_0
       14.1 Unnamed: 15_level_1 Unnamed: 16_level_1
0        38                 NaN                 NaN
1     Forza                 NaN                 NaN
2     Erinn                 NaN                 NaN
3       1–0                 NaN                 NaN
4       NaN                 NaN                 NaN
5      Vote                 NaN                 NaN
6     Erinn                 NaN                 NaN
7   None[b]                 NaN                 NaN
8   None[b]                 NaN                 NaN
9       NaN                 NaN                 NaN
10      NaN                 NaN                 NaN
11      NaN                 NaN                 NaN
12      NaN                 NaN                 NaN
13      NaN                 NaN                 NaN
14      NaN                 NaN                 NaN
15      NaN                 NaN                 NaN
16      NaN                 NaN                 NaN
17      NaN                 NaN                 NaN
18      NaN                 NaN                 NaN
19      NaN                 NaN                 NaN
20      NaN                 NaN                 NaN
21      NaN                 NaN                 NaN

In [ ]:
jt_row = df[df[('Unnamed: 0_level_0', 'Episode')] == 'J.T.']
print(jt_row)

  Unnamed: 0_level_0 Original tribes                                    \
             Episode               1    2    3      4        5       7
6               J.T.        Carolina  NaN  NaN  Sandy  Spencer  Sydney

  Merged tribe                                                    \
             8       9     10      11      12     13   14   14.1
6          NaN  Sierra  Tyson  Sierra  Debbie  Erinn  Taj  Erinn

  Unnamed: 15_level_0 Unnamed: 16_level_0
  Unnamed: 15_level_1 Unnamed: 16_level_1
6                 NaN                 NaN

## Survivor 19

In [ ]:
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
}

r = requests.get('https://en.wikipedia.org/wiki/Survivor:_Samoa', headers=headers)
html_contents = r.text
html_soup = BeautifulSoup(html_contents,"lxml")

In [ ]:
tables = html_soup.find_all('table',class_="wikitable")
tables[0].find_all('a')

[<a href="/wiki/Cincinnati" title="Cincinnati">Cincinnati,<br/>Ohio</a>,
 <a href="/wiki/Marina_del_Rey,_California" title="Marina del Rey, California">Marina del Rey,<br/>California</a>,
 <a href="/wiki/Campton,_New_Hampshire" title="Campton, New Hampshire">Campton,<br/>New Hampshire</a>,
 <a href="/wiki/Los_Angeles" title="Los Angeles">Los Angeles,<br/>California</a>,
 <a href="/wiki/Los_Angeles" title="Los Angeles">Los Angeles,<br/>California</a>,
 <a href="/wiki/Maple_Grove,_Minnesota" title="Maple Grove, Minnesota">Maple Grove,<br/>Minnesota</a>,
 <a href="/wiki/Glenside,_Pennsylvania" title="Glenside, Pennsylvania">Glenside,<br/>Pennsylvania</a>,
 <a href="/wiki/New_York_City" title="New York City">New York City,<br/>New York</a>,
 <a href="/wiki/Los_Angeles" title="Los Angeles">Los Angeles,<br/>California</a>,
 <a href="/wiki/San_Diego" title="San Diego">San Diego,<br/>California</a>,
 <a href="/wiki/Salem,_Oregon" title="Salem, Oregon">Salem,<br/>Oregon</a>,
 <a href="/wiki/Santa_Monica,_California" title="Santa Monica, California">Santa Monica,<br/>California</a>,
 <a href="/wiki/Los_Angeles" title="Los Angeles">Los Angeles,<br/>California</a>,
 <a href="/wiki/San_Diego" title="San Diego">San Diego,<br/>California</a>,
 <a href="/wiki/Renton,_Washington" title="Renton, Washington">Renton,<br/>Washington</a>,
 <a href="/wiki/Chicago" title="Chicago">Chicago,<br/>Illinois</a>,
 <a href="/wiki/Los_Angeles" title="Los Angeles">Los Angeles,<br/>California</a>,
 <a href="/wiki/Los_Angeles" title="Los Angeles">Los Angeles,<br/>California</a>,
 <a href="/wiki/Russell_Hantz" title="Russell Hantz">Russell Hantz</a>,
 <a href="/wiki/Dayton,_Texas" title="Dayton, Texas">Dayton,<br/>Texas</a>,
 <a href="/wiki/Van_Buren,_Arkansas" title="Van Buren, Arkansas">Van Buren,<br/>Arkansas</a>]

In [ ]:
df = pd.read_html(str(tables))[3]
df

/tmp/ipykernel_3126/1238544221.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(tables))[3]

   Unnamed: 0_level_0 Original tribes                                          \
              Episode               1             2      2.1        3       4
0                 Day               3             5        6        8      11
1               Tribe         Foa Foa       Foa Foa  Foa Foa  Foa Foa    Galu
2          Eliminated          Marisa          Mike    Betsy      Ben  Yasmin
3                Vote             7–3  Evacuated[b]      7–1      6–1     8–2
4                 NaN             NaN           NaN      NaN      NaN     NaN
5               Voter           Votes         Votes    Votes    Votes   Votes
6             Natalie          Marisa           NaN    Betsy      Ben     NaN
7          Russell H.          Marisa           NaN    Betsy      Ben     NaN
8                Mick          Ashley           NaN    Betsy      Ben     NaN
9               Brett             NaN           NaN      NaN      NaN  Yasmin
10             Jaison          Marisa           NaN    Betsy      Ben     NaN
11             Shambo             NaN           NaN      NaN      NaN  Monica
12             Monica             NaN           NaN      NaN      NaN  Yasmin
13               Dave             NaN           NaN      NaN      NaN  Yasmin
14               John             NaN           NaN      NaN      NaN  Yasmin
15              Laura             NaN           NaN      NaN      NaN  Yasmin
16              Kelly             NaN           NaN      NaN      NaN  Yasmin
17               Erik             NaN           NaN      NaN      NaN  Yasmin
18                Liz          Marisa           NaN    Betsy      Ben     NaN
19         Russell S.             NaN           NaN      NaN      NaN  Yasmin
20             Ashley          Marisa           NaN    Betsy      Ben     NaN
21             Yasmin             NaN           NaN      NaN      NaN  Monica
22                Ben          Marisa           NaN    Betsy   Ashley     NaN
23              Betsy          Ashley           NaN      Ben      NaN     NaN
24               Mike          Marisa     Evacuated      NaN      NaN     NaN
25             Marisa          Ashley           NaN      NaN      NaN     NaN

                                   Merged tribe                                \
          5             6        7            8           9       10     10.1
0        14            15       18           21          24       27       27
1   Foa Foa          Galu  Foa Foa         Aiga        Aiga     Aiga     Aiga
2    Ashley    Russell S.      Liz         Erik       Kelly   Tie[a]    Laura
3       5–1  Evacuated[c]      4–1         10–2      4–0[d]      5–5      5–3
4       NaN           NaN      NaN          NaN         NaN      NaN      NaN
5     Votes         Votes    Votes        Votes       Votes    Votes    Votes
6    Ashley           NaN      Liz         Erik       Kelly    Laura  None[e]
7    Ashley           NaN      Liz         Erik       Kelly    Laura    Laura
8    Ashley           NaN      Liz         Erik       Kelly    Laura    Laura
9       NaN           NaN      NaN         Erik  Russell H.  Natalie  Natalie
10   Ashley           NaN      Liz         Erik       Kelly    Laura    Laura
11      NaN           NaN      NaN       Jaison  Russell H.    Laura    Laura
12      NaN           NaN      NaN         Erik  Russell H.  Natalie  Natalie
13      NaN           NaN      NaN         Erik  Russell H.  Natalie  Natalie
14      NaN           NaN      NaN         Erik  Russell H.  Natalie    Laura
15      NaN           NaN      NaN         Erik  Russell H.  Natalie  None[e]
16      NaN           NaN      NaN         Erik  Russell H.      NaN      NaN
17      NaN           NaN      NaN       Jaison         NaN      NaN      NaN
18   Ashley           NaN   Jaison          NaN         NaN      NaN      NaN
19      NaN     Evacuated      NaN          NaN         NaN      NaN      NaN
20      Liz           NaN      NaN          NaN         NaN      NaN      NaN
21      NaN           NaN      NaN          NaN         NaN      NaN      NaN
22      NaN           NaN      NaN          NaN         NaN      NaN      NaN
23      NaN           NaN      NaN          NaN         NaN      NaN      NaN
24      NaN           NaN      NaN          NaN         NaN      NaN      NaN
25      NaN           NaN      NaN          NaN         NaN      NaN      NaN

                                                     Unnamed: 19_level_0
       12      13        13.1      14      15   15.1 Unnamed: 19_level_1
0      30      31          33      36      37     38                 NaN
1    Aiga    Aiga        Aiga    Aiga    Aiga   Aiga                 NaN
2    John    Dave      Monica  Shambo  Jaison  Brett                 NaN
3   7–1–1     7–1         5–2     5–1     4–1    3–1                 NaN
4     NaN     NaN         NaN     NaN     NaN    NaN                 NaN
5   Votes   Votes       Votes   Votes   Votes  Votes                 NaN
6    John    Dave      Monica  Shambo  Jaison  Brett                 NaN
7    John    Dave      Monica  Shambo  Jaison  Brett                 NaN
8    John    Dave      Monica  Shambo  Jaison  Brett                 NaN
9    John    Dave  Russell H.  Shambo  Jaison   Mick                 NaN
10   John    Dave      Monica  Shambo    Mick    NaN                 NaN
11   Dave    Dave      Monica    Mick     NaN    NaN                 NaN
12   John    Dave  Russell H.     NaN     NaN    NaN                 NaN
13   John  Shambo         NaN     NaN     NaN    NaN                 NaN
14   Mick     NaN         NaN     NaN     NaN    NaN                 NaN
15    NaN     NaN         NaN     NaN     NaN    NaN                 NaN
16    NaN     NaN         NaN     NaN     NaN    NaN                 NaN
17    NaN     NaN         NaN     NaN     NaN    NaN                 NaN
18    NaN     NaN         NaN     NaN     NaN    NaN                 NaN
19    NaN     NaN         NaN     NaN     NaN    NaN                 NaN
20    NaN     NaN         NaN     NaN     NaN    NaN                 NaN
21    NaN     NaN         NaN     NaN     NaN    NaN                 NaN
22    NaN     NaN         NaN     NaN     NaN    NaN                 NaN
23    NaN     NaN         NaN     NaN     NaN    NaN                 NaN
24    NaN     NaN         NaN     NaN     NaN    NaN                 NaN
25    NaN     NaN         NaN     NaN     NaN    NaN                 NaN

In [ ]:
nataliew_row = df[df[('Unnamed: 0_level_0', 'Episode')] == 'Natalie']
print(nataliew_row)

  Unnamed: 0_level_0 Original tribes                                          \
             Episode               1    2    2.1    3    4       5    6    7
6            Natalie          Marisa  NaN  Betsy  Ben  NaN  Ashley  NaN  Liz

  Merged tribe                                                             \
             8      9     10     10.1    12    13    13.1      14      15
6         Erik  Kelly  Laura  None[e]  John  Dave  Monica  Shambo  Jaison

         Unnamed: 19_level_0
    15.1 Unnamed: 19_level_1
6  Brett                 NaN

## Survivor 20

In [ ]:
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
}

r = requests.get('https://en.wikipedia.org/wiki/Survivor:_Heroes_vs._Villains', headers=headers)
html_contents = r.text
html_soup = BeautifulSoup(html_contents,"lxml")

In [ ]:
tables = html_soup.find_all('table',class_="wikitable")
tables[0].find_all('a')

[<a class="mw-redirect" href="/wiki/Jessica_Kiper" title="Jessica Kiper">Jessica "Sugar" Kiper</a>,
 <a href="/wiki/Survivor:_Gabon" title="Survivor: Gabon">Gabon</a>,
 <a href="/wiki/Los_Angeles" title="Los Angeles">Los Angeles,<br/>California</a>,
 <a href="/wiki/Stephenie_LaGrossa_Kendrick" title="Stephenie LaGrossa Kendrick">Stephenie LaGrossa</a>,
 <a href="/wiki/Survivor:_Palau" title="Survivor: Palau">Palau</a>,
 <a href="/wiki/Survivor:_Guatemala" title="Survivor: Guatemala">Guatemala</a>,
 <a href="/wiki/Philadelphia" title="Philadelphia">Philadelphia,<br/>Pennsylvania</a>,
 <a href="/wiki/Survivor:_Gabon" title="Survivor: Gabon">Gabon</a>,
 <a href="/wiki/Austin,_Texas" title="Austin, Texas">Austin,<br/>Texas</a>,
 <a href="/wiki/Cirie_Fields" title="Cirie Fields">Cirie Fields</a>,
 <a href="/wiki/Survivor:_Panama" title="Survivor: Panama">Panama</a>,
 <a href="/wiki/Survivor:_Micronesia" title="Survivor: Micronesia">Micronesia</a>,
 <a href="/wiki/Norwalk,_Connecticut" title="Norwalk, Connecticut">Norwalk,<br/>Connecticut</a>,
 <a href="/wiki/Tom_Westman" title="Tom Westman">Tom Westman</a>,
 <a href="/wiki/Survivor:_Palau" title="Survivor: Palau">Palau</a>,
 <a href="/wiki/New_York_City" title="New York City">New York City,<br/>New York</a>,
 <a href="/wiki/Tyson_Apostol" title="Tyson Apostol">Tyson Apostol</a>,
 <a href="/wiki/Survivor:_Tocantins" title="Survivor: Tocantins">Tocantins</a>,
 <a href="/wiki/Heber_City,_Utah" title="Heber City, Utah">Heber City,<br/>Utah</a>,
 <a href="/wiki/Survivor:_China" title="Survivor: China">China</a>,
 <a href="/wiki/Survivor:_Micronesia" title="Survivor: Micronesia">Micronesia</a>,
 <a href="/wiki/Lafayette,_Louisiana" title="Lafayette, Louisiana">Lafayette,<br/>Louisiana</a>,
 <a href="/wiki/Rob_Mariano" title="Rob Mariano">Rob Mariano</a>,
 <a href="/wiki/Survivor:_Marquesas" title="Survivor: Marquesas">Marquesas</a>,
 <a href="/wiki/Survivor:_All-Stars" title="Survivor: All-Stars">All-Stars</a>,
 <a href="/wiki/Pensacola,_Florida" title="Pensacola, Florida">Pensacola,<br/>Florida</a>,
 <a href="/wiki/Coach_(Survivor_contestant)" title="Coach (Survivor contestant)">Benjamin "Coach" Wade</a>,
 <a href="/wiki/Survivor:_Tocantins" title="Survivor: Tocantins">Tocantins</a>,
 <a href="/wiki/Susanville,_California" title="Susanville, California">Susanville,<br/>California</a>,
 <a href="/wiki/Survivor:_China" title="Survivor: China">China</a>,
 <a href="/wiki/New_York_City" title="New York City">New York City,<br/>New York</a>,
 <a href="/wiki/Survivor:_Tocantins" title="Survivor: Tocantins">Tocantins</a>,
 <a href="/wiki/Mobile,_Alabama" title="Mobile, Alabama">Mobile,<br/>Alabama</a>,
 <a href="/wiki/Survivor:_China" title="Survivor: China">China</a>,
 <a href="/wiki/Survivor:_Micronesia" title="Survivor: Micronesia">Micronesia</a>,
 <a href="/wiki/Los_Angeles" title="Los Angeles">Los Angeles,<br/>California</a>,
 <a href="/wiki/Survivor:_Cook_Islands" title="Survivor: Cook Islands">Cook Islands</a>,
 <a href="/wiki/Washington,_D.C." title="Washington, D.C.">Washington,<br/>D.C.</a>,
 <a href="/wiki/Survivor:_Panama" title="Survivor: Panama">Panama</a>,
 <a href="/wiki/Los_Angeles" title="Los Angeles">Los Angeles,<br/>California</a>,
 <a href="/wiki/Rupert_Boneham" title="Rupert Boneham">Rupert Boneham</a>,
 <a href="/wiki/Survivor:_Pearl_Islands" title="Survivor: Pearl Islands">Pearl Islands</a>,
 <a href="/wiki/Survivor:_All-Stars" title="Survivor: All-Stars">All-Stars</a>,
 <a href="/wiki/Indianapolis" title="Indianapolis">Indianapolis,<br/>Indiana</a>,
 <a href="/wiki/Colby_Donaldson" title="Colby Donaldson">Colby Donaldson</a>,
 <a href="/wiki/Survivor:_The_Australian_Outback" title="Survivor: The Australian Outback">The Australian Outback</a>,
 <a href="/wiki/Survivor:_All-Stars" title="Survivor: All-Stars">All-Stars</a>,
 <a href="/wiki/Los_Angeles" title="Los Angeles">Los Angeles,<br/>California</a>,
 <a href="/wiki/Jerri_Manthey" title="Jerri Manthey">Jerri Manthey</a>,
 <a href="/wiki/Survivor:_The_Australian_Outback" title="Survivor: The Australian Outback">The Australian Outback</a>,
 <a href="/wiki/Survivor:_All-Stars" title="Survivor: All-Stars">All-Stars</a>,
 <a href="/wiki/Los_Angeles" title="Los Angeles">Los Angeles,<br/>California</a>,
 <a href="/wiki/Russell_Hantz" title="Russell Hantz">Russell Hantz</a>,
 <a href="/wiki/Survivor:_Samoa" title="Survivor: Samoa">Samoa</a>,
 <a href="/wiki/Dayton,_Texas" title="Dayton, Texas">Dayton,<br/>Texas</a>,
 <a href="/wiki/Parvati_Shallow" title="Parvati Shallow">Parvati Shallow</a>,
 <a href="/wiki/Survivor:_Cook_Islands" title="Survivor: Cook Islands">Cook Islands</a>,
 <a href="/wiki/Survivor:_Micronesia" title="Survivor: Micronesia">Micronesia</a>,
 <a href="/wiki/Los_Angeles" title="Los Angeles">Los Angeles,<br/>California</a>,
 <a href="/wiki/Sandra_Diaz-Twine" title="Sandra Diaz-Twine">Sandra Diaz-Twine</a>,
 <a href="/wiki/Survivor:_Pearl_Islands" title="Survivor: Pearl Islands">Pearl Islands</a>,
 <a href="/wiki/Fayetteville,_North_Carolina" title="Fayetteville, North Carolina">Fayetteville,<br/>North Carolina</a>]

In [ ]:
df = pd.read_html(str(tables))[3]
df

/tmp/ipykernel_3126/1238544221.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(tables))[3]

   Unnamed: 0_level_0 Original Tribes                                         \
              Episode               1          2         3         4       5
0                 Day               3          6         8        11      14
1               Tribe          Heroes     Heroes  Villains    Heroes  Heroes
2          Eliminated           Sugar  Stephenie     Randy     Cirie     Tom
3               Votes             9–1        6–3       9–1  3–2–0[a]     5–2
4                 NaN             NaN        NaN       NaN       NaN     NaN
5               Voter            Vote       Vote      Vote      Vote    Vote
6              Sandra             NaN        NaN     Randy       NaN     NaN
7             Parvati             NaN        NaN     Randy       NaN     NaN
8             Russell             NaN        NaN     Randy       NaN     NaN
9               Jerri             NaN        NaN     Randy       NaN     NaN
10              Colby           Sugar     Amanda       NaN     Cirie   James
11             Rupert           Sugar  Stephenie       NaN     Colby     Tom
12           Danielle             NaN        NaN     Randy       NaN     NaN
13            Candice           Sugar  Stephenie       NaN       Tom     Tom
14             Amanda           Sugar  Stephenie       NaN       Tom     Tom
15               J.T.           Sugar  Stephenie       NaN     Cirie     Tom
16           Courtney             NaN        NaN     Randy       NaN     NaN
17              Coach             NaN        NaN     Randy       NaN     NaN
18                Rob             NaN        NaN     Randy       NaN     NaN
19              James           Sugar  Stephenie       NaN     Colby     Tom
20              Tyson             NaN        NaN     Randy       NaN     NaN
21                Tom           Sugar     Amanda       NaN     Cirie   James
22              Cirie           Sugar  Stephenie       NaN       Tom     NaN
23              Randy             NaN        NaN       Rob       NaN     NaN
24          Stephenie           Sugar     Amanda       NaN       NaN     NaN
25              Sugar          Amanda        NaN       NaN       NaN     NaN

                                                   Merged Tribe            \
           6     6.1         7         8         9           10        11
0         15      15        18        21        24           27        30
1   Villains  Heroes  Villains  Villains  Villains     Yin Yang  Yin Yang
2      Tyson   James       Rob     Coach  Courtney         J.T.    Amanda
3   3–2–0[b]     5–1     4–3–1       4–3       5–1       5–0[c]       6–3
4        NaN     NaN       NaN       NaN       NaN          NaN       NaN
5       Vote    Vote      Vote      Vote      Vote         Vote      Vote
6    Russell     NaN   Russell     Coach  Courtney         J.T.    Amanda
7      Tyson     NaN       Rob     Coach  Courtney         J.T.    Amanda
8      Tyson     NaN       Rob  Courtney  Courtney         J.T.    Amanda
9    Parvati     NaN       Rob  Courtney  Courtney         J.T.    Amanda
10       NaN   James       NaN       NaN       NaN        Jerri   Parvati
11       NaN   James       NaN       NaN       NaN        Jerri   Parvati
12     Tyson     NaN       Rob     Coach  Courtney         J.T.    Amanda
13       NaN   James       NaN       NaN       NaN        Jerri    Amanda
14       NaN   James       NaN       NaN       NaN        Jerri   Parvati
15       NaN   James       NaN       NaN       NaN        Jerri       NaN
16   Parvati     NaN   Russell     Coach     Jerri          NaN       NaN
17   Parvati     NaN  Courtney  Courtney       NaN          NaN       NaN
18   Russell     NaN   Russell       NaN       NaN          NaN       NaN
19       NaN   Colby       NaN       NaN       NaN          NaN       NaN
20   Parvati     NaN       NaN       NaN       NaN          NaN       NaN
21       NaN     NaN       NaN       NaN       NaN          NaN       NaN
22       NaN     NaN       NaN       NaN       NaN          NaN       NaN
23       NaN     NaN       NaN       NaN       NaN          NaN       NaN
24       NaN     NaN       NaN       NaN       NaN          NaN       NaN
25       NaN     NaN       NaN       NaN       NaN          NaN       NaN

                                                     Unnamed: 18_level_0
          12      12.1        13        14      14.1 Unnamed: 18_level_1
0         31        33        36        37        38                 NaN
1   Yin Yang  Yin Yang  Yin Yang  Yin Yang  Yin Yang                 NaN
2    Candice  Danielle    Rupert     Colby     Jerri                 NaN
3        5–3       4–3    4–0[d]       4–1       3–1                 NaN
4        NaN       NaN       NaN       NaN       NaN                 NaN
5       Vote      Vote      Vote      Vote      Vote                Vote
6    Candice    Rupert    Rupert     Colby     Jerri                 NaN
7     Rupert    Rupert    Rupert     Colby     Jerri                 NaN
8    Candice  Danielle    Rupert     Colby     Jerri                 NaN
9    Candice  Danielle    Rupert     Colby   Parvati                 NaN
10   Candice  Danielle    Sandra    Sandra       NaN                 NaN
11   Candice  Danielle    Sandra       NaN       NaN                 NaN
12    Rupert    Rupert       NaN       NaN       NaN                 NaN
13    Rupert       NaN       NaN       NaN       NaN                 NaN
14       NaN       NaN       NaN       NaN       NaN                 NaN
15       NaN       NaN       NaN       NaN       NaN                 NaN
16       NaN       NaN       NaN       NaN       NaN                 NaN
17       NaN       NaN       NaN       NaN       NaN                 NaN
18       NaN       NaN       NaN       NaN       NaN                 NaN
19       NaN       NaN       NaN       NaN       NaN                 NaN
20       NaN       NaN       NaN       NaN       NaN                 NaN
21       NaN       NaN       NaN       NaN       NaN                 NaN
22       NaN       NaN       NaN       NaN       NaN                 NaN
23       NaN       NaN       NaN       NaN       NaN                 NaN
24       NaN       NaN       NaN       NaN       NaN                 NaN
25       NaN       NaN       NaN       NaN       NaN                 NaN

In [ ]:
sandra2_row = df[df[('Unnamed: 0_level_0', 'Episode')] == 'Sandra']
print(sandra_row)

  Unnamed: 0_level_0 Original tribes                                     \
             Episode               1    2    3       4         5      6
6             Sandra             NaN  NaN  NaN  Burton  Michelle  Trish

  Outcasts twist[a]      Merged tribe                                          \
                  7  7.1            8        9   10       11       12      13
6             Shawn  NaN       Andrew  Ryan O.  Jon  Tijuana  Lillian  Burton


       14     14.1
6  Darrah  None[c]

## Survivor 21

In [ ]:
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
}

r = requests.get('https://en.wikipedia.org/wiki/Survivor:_Nicaragua', headers=headers)
html_contents = r.text
html_soup = BeautifulSoup(html_contents,"lxml")

In [ ]:
tables = html_soup.find_all('table',class_="wikitable")
tables[0].find_all('a')

[<a href="/wiki/Fromberg,_Montana" title="Fromberg, Montana">Fromberg,<br/>Montana</a>,
 <a href="/wiki/Lafayette,_Louisiana" title="Lafayette, Louisiana">Lafayette,<br/>Louisiana</a>,
 <a href="/wiki/Jimmy_Johnson_(American_football_coach)" title="Jimmy Johnson (American football coach)">Jimmy Johnson</a>,
 <a href="/wiki/Islamorada,_Florida" title="Islamorada, Florida">Islamorada,<br/>Florida</a>,
 <a href="/wiki/Gloucester,_Massachusetts" title="Gloucester, Massachusetts">Gloucester,<br/>Massachusetts</a>,
 <a href="/wiki/Inglewood,_California" title="Inglewood, California">Inglewood,<br/>California</a>,
 <a href="/wiki/Kelly_Bruno" title="Kelly Bruno">Kelly Bruno</a>,
 <a href="/wiki/Durham,_North_Carolina" title="Durham, North Carolina">Durham,<br/>North Carolina</a>,
 <a href="/wiki/Kansas_City,_Missouri" title="Kansas City, Missouri">Kansas City,<br/>Missouri</a>,
 <a href="/wiki/Erie,_Pennsylvania" title="Erie, Pennsylvania">Erie,<br/>Pennsylvania</a>,
 <a href="/wiki/Downey,_California" title="Downey, California">Downey,<br/>California</a>,
 <a href="/wiki/Mill_Valley,_California" title="Mill Valley, California">Mill Valley,<br/>California</a>,
 <a href="/wiki/Miami" title="Miami">Miami,<br/>Florida</a>,
 <a href="/wiki/Los_Angeles" title="Los Angeles">Los Angeles,<br/>California</a>,
 <a href="/wiki/Mesa,_Arizona" title="Mesa, Arizona">Mesa,<br/>Arizona</a>,
 <a href="/wiki/Los_Angeles" title="Los Angeles">Los Angeles,<br/>California</a>,
 <a href="/wiki/Jackson_Springs,_North_Carolina" title="Jackson Springs, North Carolina">Jackson Springs,<br/>North Carolina</a>,
 <a href="/wiki/Water_Mill,_New_York" title="Water Mill, New York">Water Mill,<br/>New York</a>,
 <a href="/wiki/Eureka,_South_Dakota" title="Eureka, South Dakota">Eureka,<br/>South Dakota</a>,
 <a href="/wiki/New_York_City" title="New York City">New York City,<br/>New York</a>,
 <a href="/wiki/Chase_Rice" title="Chase Rice">Chase Rice</a>,
 <a href="/wiki/Fairview,_Buncombe_County,_North_Carolina" title="Fairview, Buncombe County, North Carolina">Fairview,<br/>North Carolina</a>,
 <a href="/wiki/Venice,_Los_Angeles" title="Venice, Los Angeles">Venice,<br/>California</a>]

In [ ]:
df = pd.read_html(str(tables))[3]
df

/tmp/ipykernel_3126/1238544221.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(tables))[3]

   Unnamed: 0_level_0 Original tribes                               \
              Episode               1        2         3         4
0                 Day               3        6         8        11
1               Tribe          Espada  La Flor    Espada    Espada
2          Eliminated           Wendy  Shannon  Jimmy J.  Jimmy T.
3                Vote             9–1      7–3       8–1       5–3
4                 NaN             NaN      NaN       NaN       NaN
5               Voter            Vote     Vote      Vote      Vote
6               Fabio             NaN   Brenda       NaN       NaN
7               Chase             NaN  Shannon       NaN       NaN
8                Sash             NaN  Shannon       NaN       NaN
9               Holly           Wendy      NaN  Jimmy J.       Dan
10                Dan           Wendy      NaN  Jimmy J.  Jimmy T.
11               Jane           Wendy      NaN  Jimmy J.       Dan
12              Benry             NaN  Shannon       NaN       NaN
13           Kelly S.             NaN  Shannon       NaN       NaN
14             NaOnka             NaN  Shannon       NaN       NaN
15             Brenda             NaN  Shannon       NaN       NaN
16              Marty           Wendy      NaN  Jimmy J.  Jimmy T.
17              Alina             NaN   Brenda       NaN       NaN
18               Jill           Wendy      NaN  Jimmy J.  Jimmy T.
19                Yve           Wendy      NaN  Jimmy J.  Jimmy T.
20           Kelly B.             NaN  Shannon       NaN       NaN
21             Tyrone           Wendy      NaN  Jimmy J.  Jimmy T.
22           Jimmy T.           Wendy      NaN  Jimmy J.       Dan
23           Jimmy J.           Wendy      NaN       Dan       NaN
24            Shannon             NaN   Brenda       NaN       NaN
25              Wendy             Yve      NaN       NaN       NaN

   Switched tribes                                       ... Merged tribe  \
                 5         6       6.1     6.2        7  ...            9
0               14        15        15      15       18  ...           24
1           Espada   La Flor   La Flor  Espada  La Flor  ...     Libertad
2           Tyrone    Tie[a]  Kelly B.     Yve     Jill  ...        Marty
3              6–2     3–3–2       5–1     6–1    3–2–2  ...          7–4
4              NaN       NaN       NaN     NaN      NaN  ...          NaN
5             Vote      Vote      Vote    Vote     Vote  ...         Vote
6              NaN  Kelly B.  Kelly B.     NaN    Marty  ...         Jane
7           Tyrone       NaN       NaN     Yve      NaN  ...        Marty
8              NaN     Marty  Kelly B.     NaN     Jill  ...        Marty
9           Tyrone       NaN       NaN     Yve      NaN  ...        Marty
10          Tyrone       NaN       NaN     Yve      NaN  ...         Jane
11             NaN     Marty     Marty     NaN    Marty  ...        Marty
12          Tyrone       NaN       NaN     Yve      NaN  ...         Jane
13             NaN  Kelly B.  Kelly B.     NaN     Jill  ...        Marty
14          Tyrone       NaN       NaN     Yve      NaN  ...        Marty
15             NaN  Kelly B.  Kelly B.     NaN     Jill  ...        Marty
16             NaN    Brenda   None[d]     NaN     Jane  ...         Jane
17          Tyrone       NaN       NaN     Yve      NaN  ...          NaN
18             NaN    Brenda  Kelly B.     NaN     Jane  ...          NaN
19          NaOnka       NaN       NaN     Dan      NaN  ...          NaN
20             NaN     Marty   None[d]     NaN      NaN  ...          NaN
21          NaOnka       NaN       NaN     NaN      NaN  ...          NaN
22             NaN       NaN       NaN     NaN      NaN  ...          NaN
23             NaN       NaN       NaN     NaN      NaN  ...          NaN
24             NaN       NaN       NaN     NaN      NaN  ...          NaN
25             NaN       NaN       NaN     NaN      NaN  ...          NaN

                                                                          \
          10        12      12.1        13        14        15      15.1
0         27        28        28        32        36        37        38
1   Libertad  Libertad  Libertad  Libertad  Libertad  Libertad  Libertad
2     Brenda    NaOnka  Kelly S.     Benry      Jane       Dan     Holly
3      8–1–1   Quit[b]   Quit[b]     4–2–1    5–0[c]       4–1       3–1
4        NaN       NaN       NaN       NaN       NaN       NaN       NaN
5       Vote      Vote      Vote      Vote      Vote      Vote      Vote
6     Brenda       NaN       NaN     Holly      Jane       Dan     Holly
7     Brenda       NaN       NaN     Benry      Jane       Dan     Holly
8     Brenda       NaN       NaN     Benry      Jane       Dan     Holly
9     Brenda       NaN       NaN     Benry      Jane       Dan      Sash
10    Brenda       NaN       NaN     Fabio      Jane     Chase       NaN
11    Brenda       NaN       NaN     Benry      Sash       NaN       NaN
12    Brenda       NaN       NaN     Fabio       NaN       NaN       NaN
13     Benry       NaN      Quit       NaN       NaN       NaN       NaN
14    Brenda      Quit       NaN       NaN       NaN       NaN       NaN
15    NaOnka       NaN       NaN       NaN       NaN       NaN       NaN
16       NaN       NaN       NaN       NaN       NaN       NaN       NaN
17       NaN       NaN       NaN       NaN       NaN       NaN       NaN
18       NaN       NaN       NaN       NaN       NaN       NaN       NaN
19       NaN       NaN       NaN       NaN       NaN       NaN       NaN
20       NaN       NaN       NaN       NaN       NaN       NaN       NaN
21       NaN       NaN       NaN       NaN       NaN       NaN       NaN
22       NaN       NaN       NaN       NaN       NaN       NaN       NaN
23       NaN       NaN       NaN       NaN       NaN       NaN       NaN
24       NaN       NaN       NaN       NaN       NaN       NaN       NaN
25       NaN       NaN       NaN       NaN       NaN       NaN       NaN

   Unnamed: 19_level_0 Unnamed: 20_level_0
   Unnamed: 19_level_1 Unnamed: 20_level_1
0                  NaN                 NaN
1                  NaN                 NaN
2                  NaN                 NaN
3                  NaN                 NaN
4                  NaN                 NaN
5                  NaN                 NaN
6                  NaN                 NaN
7                  NaN                 NaN
8                  NaN                 NaN
9                  NaN                 NaN
10                 NaN                 NaN
11                 NaN                 NaN
12                 NaN                 NaN
13                 NaN                 NaN
14                 NaN                 NaN
15                 NaN                 NaN
16                 NaN                 NaN
17                 NaN                 NaN
18                 NaN                 NaN
19                 NaN                 NaN
20                 NaN                 NaN
21                 NaN                 NaN
22                 NaN                 NaN
23                 NaN                 NaN
24                 NaN                 NaN
25                 NaN                 NaN

[26 rows x 21 columns]

In [ ]:
fabio_row = df[df[('Unnamed: 0_level_0', 'Episode')] == 'Fabio']
print(fabio_row)

  Unnamed: 0_level_0 Original tribes                   Switched tribes  \
             Episode               1       2    3    4               5
6              Fabio             NaN  Brenda  NaN  NaN             NaN

                                   ... Merged tribe                           \
          6       6.1  6.2      7  ...            9      10   12 12.1     13
6  Kelly B.  Kelly B.  NaN  Marty  ...         Jane  Brenda  NaN  NaN  Holly

                    Unnamed: 19_level_0 Unnamed: 20_level_0
     14   15   15.1 Unnamed: 19_level_1 Unnamed: 20_level_1
6  Jane  Dan  Holly                 NaN                 NaN

[1 rows x 21 columns]

## Survivor 22

In [ ]:
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
}

r = requests.get('https://en.wikipedia.org/wiki/Survivor:_Redemption_Island', headers=headers)
html_contents = r.text
html_soup = BeautifulSoup(html_contents,"lxml")

In [ ]:
tables = html_soup.find_all('table',class_="wikitable")
tables[0].find_all('a')

[<a href="#cite_note-8"><span class="cite-bracket">[</span>a<span class="cite-bracket">]</span></a>,
 <a href="/wiki/Washington,_D.C." title="Washington, D.C.">Washington,<br/>D.C.</a>,
 <a href="/wiki/Wyatt_Nash" title="Wyatt Nash">Matt Elrod</a>,
 <a href="/wiki/Russell_Hantz" title="Russell Hantz">Russell Hantz</a>,
 <a href="/wiki/Survivor:_Samoa" title="Survivor: Samoa">Samoa</a>,
 <a href="/wiki/Survivor:_Heroes_vs._Villains" title="Survivor: Heroes vs. Villains">Heroes vs. Villains</a>,
 <a href="/wiki/Dayton,_Texas" title="Dayton, Texas">Dayton,<br/>Texas</a>,
 <a href="/wiki/Malibu,_California" title="Malibu, California">Malibu,<br/>California</a>,
 <a href="/wiki/Columbia,_South_Carolina" title="Columbia, South Carolina">Columbia,<br/>South Carolina</a>,
 <a href="/wiki/Long_Beach,_California" title="Long Beach, California">Long Beach,<br/>California</a>,
 <a href="/wiki/Santa_Monica,_California" title="Santa Monica, California">Santa Monica,<br/>California</a>,
 <a href="/wiki/Wyatt_Nash" title="Wyatt Nash">Matt Elrod</a>,
 <a href="/wiki/Nashville,_Tennessee" title="Nashville, Tennessee">Nashville,<br/>Tennessee</a>,
 <a href="/wiki/Del_Mar,_California" title="Del Mar, California">Del Mar,<br/>California</a>,
 <a href="/wiki/West_Hollywood,_California" title="West Hollywood, California">West Hollywood,<br/>California</a>,
 <a href="/wiki/Oceanside,_California" title="Oceanside, California">Oceanside,<br/>California</a>,
 <a href="/wiki/Lebanon,_Virginia" title="Lebanon, Virginia">Lebanon,<br/>Virginia</a>,
 <a href="/wiki/Steve_Wright_(American_football,_born_1959)" title="Steve Wright (American football, born 1959)">Steve Wright</a>,
 <a href="/wiki/Huntington_Beach,_California" title="Huntington Beach, California">Huntington Beach,<br/>California</a>,
 <a href="/wiki/Grant_Mattos" title="Grant Mattos">Grant Mattos</a>,
 <a href="/wiki/West_Hollywood,_California" title="West Hollywood, California">West Hollywood,<br/>California</a>,
 <a href="/wiki/Random_Lake,_Wisconsin" title="Random Lake, Wisconsin">Random Lake,<br/>Wisconsin</a>,
 <a href="/wiki/Benton,_Maine" title="Benton, Maine">Benton,<br/>Maine</a>,
 <a href="/wiki/Acton,_California" title="Acton, California">Acton,<br/>California</a>,
 <a href="/wiki/Santa_Monica,_California" title="Santa Monica, California">Santa Monica,<br/>California</a>,
 <a href="/wiki/Rob_Mariano" title="Rob Mariano">Rob Mariano</a>,
 <a href="/wiki/Survivor:_Marquesas" title="Survivor: Marquesas">Marquesas</a>,
 <a href="/wiki/Survivor:_All-Stars" title="Survivor: All-Stars">All-Stars</a>,
 <a href="/wiki/Survivor:_Heroes_vs._Villains" title="Survivor: Heroes vs. Villains">Heroes vs. Villains</a>,
 <a href="/wiki/Pensacola,_Florida" title="Pensacola, Florida">Pensacola,<br/>Florida</a>]

In [ ]:
df = pd.read_html(str(tables))[3]
df

/tmp/ipykernel_3126/1238544221.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(tables))[3]

   Unnamed: 0_level_0 Original tribes                                 \
              Episode               1         2          3       3.1
0                 Day               3         5          8         8
1               Tribe         Ometepe   Ometepe   Zapatera  Zapatera
2          Eliminated       Francesca      Matt     Tie[a]   Russell
3               Votes           4–3–2  4–2–0[b]      3–3–3     5–1–0
4                 NaN             NaN       NaN        NaN       NaN
5               Voter            Vote      Vote       Vote      Vote
6                 Rob       Francesca      Matt        NaN       NaN
7             Phillip       Francesca  Kristina        NaN       NaN
8             Natalie        Kristina      Matt        NaN       NaN
9              Ashley        Kristina      Matt        NaN       NaN
10             Andrea        Kristina  Kristina        NaN       NaN
11              Grant       Francesca      Matt        NaN       NaN
12              Steve             NaN       NaN    Russell   Russell
13              Ralph             NaN       NaN    Russell   None[d]
14              Julie             NaN       NaN  Stephanie   Russell
15              David             NaN       NaN  Stephanie   Russell
16               Mike             NaN       NaN    Russell   Russell
17               Matt       Francesca   Phillip        NaN       NaN
18             Sarita             NaN       NaN  Stephanie   Russell
19          Stephanie             NaN       NaN      Ralph   None[d]
20             Krista             NaN       NaN      Ralph     Ralph
21           Kristina         Phillip   Phillip        NaN       NaN
22            Russell             NaN       NaN      Ralph   None[d]
23          Francesca         Phillip       NaN        NaN       NaN

                                            Merged tribe                      \
           4         5          6         7            8         9       9.1
0         11        13         16        18           21        22        24
1    Ometepe  Zapatera   Zapatera  Zapatera     Murlonio  Murlonio  Murlonio
2   Kristina    Krista  Stephanie    Sarita         Matt      Mike     David
3        4–3       6–2        5–2       4–2        6–5–1       6–5       6–4
4        NaN       NaN        NaN       NaN          NaN       NaN       NaN
5       Vote      Vote       Vote      Vote         Vote      Vote      Vote
6    Phillip       NaN        NaN       NaN         Matt      Mike     David
7   Kristina       NaN        NaN       NaN         Matt      Mike     David
8   Kristina       NaN        NaN       NaN         Matt      Mike     David
9   Kristina       NaN        NaN       NaN         Matt      Mike     David
10  Kristina       NaN        NaN       NaN         Matt      Mike     David
11   Phillip       NaN        NaN       NaN         Matt      Mike     David
12       NaN    Krista  Stephanie    Sarita        Grant   Phillip       Rob
13       NaN    Krista  Stephanie     David        Grant   Phillip       Rob
14       NaN    Krista  Stephanie    Sarita        Grant   Phillip       Rob
15       NaN    Krista     Sarita    Sarita        Grant   Phillip       Rob
16       NaN    Krista  Stephanie    Sarita        Grant   Phillip       NaN
17       NaN       NaN        NaN       NaN        Steve       NaN       NaN
18       NaN    Krista  Stephanie     David          NaN       NaN       NaN
19       NaN     Steve     Sarita       NaN          NaN       NaN       NaN
20       NaN     Steve        NaN       NaN          NaN       NaN       NaN
21   Phillip       NaN        NaN       NaN          NaN       NaN       NaN
22       NaN       NaN        NaN       NaN          NaN       NaN       NaN
23       NaN       NaN        NaN       NaN          NaN       NaN       NaN

                                                                          \
          10        11      11.1        12        13        14      14.1
0         27        30        30        32        35        37        38
1   Murlonio  Murlonio  Murlonio  Murlonio  Murlonio  Murlonio  Murlonio
2      Julie     Ralph     Steve    Andrea     Grant    Andrea    Ashley
3        6–3       6–2       6–1       5–1       4–1    4–0[c]       3–1
4        NaN       NaN       NaN       NaN       NaN       NaN       NaN
5       Vote      Vote      Vote      Vote      Vote      Vote      Vote
6      Julie     Ralph     Steve    Andrea     Grant    Andrea    Ashley
7      Julie     Ralph     Steve    Andrea     Grant    Andrea    Ashley
8      Julie     Ralph     Steve    Andrea     Grant    Andrea    Ashley
9      Julie     Ralph     Steve    Andrea     Grant    Andrea   Phillip
10     Julie     Ralph     Steve   Phillip       NaN       Rob       NaN
11     Julie     Ralph     Steve    Andrea   Natalie       NaN       NaN
12   Phillip       Rob     Grant       NaN       NaN       NaN       NaN
13   Phillip       Rob       NaN       NaN       NaN       NaN       NaN
14   Phillip       NaN       NaN       NaN       NaN       NaN       NaN
15       NaN       NaN       NaN       NaN       NaN       NaN       NaN
16       NaN       NaN       NaN       NaN       NaN       NaN       NaN
17       NaN       NaN       NaN       NaN       NaN       NaN       NaN
18       NaN       NaN       NaN       NaN       NaN       NaN       NaN
19       NaN       NaN       NaN       NaN       NaN       NaN       NaN
20       NaN       NaN       NaN       NaN       NaN       NaN       NaN
21       NaN       NaN       NaN       NaN       NaN       NaN       NaN
22       NaN       NaN       NaN       NaN       NaN       NaN       NaN
23       NaN       NaN       NaN       NaN       NaN       NaN       NaN

   Unnamed: 19_level_0
   Unnamed: 19_level_1
0                  NaN
1                  NaN
2                  NaN
3                  NaN
4                  NaN
5                  NaN
6                  NaN
7                  NaN
8                  NaN
9                  NaN
10                 NaN
11                 NaN
12                 NaN
13                 NaN
14                 NaN
15                 NaN
16                 NaN
17                 NaN
18                 NaN
19                 NaN
20                 NaN
21                 NaN
22                 NaN
23                 NaN

In [ ]:
rob_row = df[df[('Unnamed: 0_level_0', 'Episode')] == 'Rob']
print(rob_row)

  Unnamed: 0_level_0 Original tribes                                          \
             Episode               1     2    3  3.1        4    5    6    7
6                Rob       Francesca  Matt  NaN  NaN  Phillip  NaN  NaN  NaN

  Merged tribe                                                           \
             8     9    9.1     10     11   11.1      12     13      14
6         Matt  Mike  David  Julie  Ralph  Steve  Andrea  Grant  Andrea

          Unnamed: 19_level_0
     14.1 Unnamed: 19_level_1
6  Ashley                 NaN

## Survivor 23

In [ ]:
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
}

r = requests.get('https://en.wikipedia.org/wiki/Survivor:_South_Pacific', headers=headers)
html_contents = r.text
html_soup = BeautifulSoup(html_contents,"lxml")

In [ ]:
tables = html_soup.find_all('table',class_="wikitable")
tables[0].find_all('a')

[<a href="#cite_note-8"><span class="cite-bracket">[</span>a<span class="cite-bracket">]</span></a>,
 <a href="/wiki/Los_Angeles" title="Los Angeles">Los Angeles,<br/>California</a>,
 <a href="/wiki/Merrick,_New_York" title="Merrick, New York">Merrick,<br/>New York</a>,
 <a href="/wiki/Forest_Hills,_Queens" title="Forest Hills, Queens">Forest Hills,<br/>New York</a>,
 <a href="/wiki/Grand_Prairie,_Texas" title="Grand Prairie, Texas">Grand Prairie,<br/>Texas</a>,
 <a href="/wiki/Elyse_Umemoto" title="Elyse Umemoto">Elyse Umemoto</a>,
 <a href="/wiki/Las_Vegas" title="Las Vegas">Las Vegas,<br/>Nevada</a>,
 <a href="/wiki/Tampa,_Florida" title="Tampa, Florida">Tampa,<br/>Florida</a>,
 <a href="/wiki/Edina,_Minnesota" title="Edina, Minnesota">Edina,<br/>Minnesota</a>,
 <a href="/wiki/Denver" title="Denver">Denver,<br/>Colorado</a>,
 <a href="/wiki/South_Jordan,_Utah" title="South Jordan, Utah">South Jordan,<br/>Utah</a>,
 <a href="/wiki/Whitney_Duncan" title="Whitney Duncan">Whitney Duncan</a>,
 <a href="/wiki/Nashville,_Tennessee" title="Nashville, Tennessee">Nashville,<br/>Tennessee</a>,
 <a href="/wiki/John_Cochran_(Survivor_contestant)" title="John Cochran (Survivor contestant)">John Cochran</a>,
 <a href="/wiki/Washington,_D.C." title="Washington, D.C.">Washington,<br/>D.C.</a>,
 <a href="/wiki/Los_Angeles" title="Los Angeles">Los Angeles,<br/>California</a>,
 <a href="/wiki/Katy,_Texas" title="Katy, Texas">Katy,<br/>Texas</a>,
 <a href="/wiki/Aurora,_Utah" title="Aurora, Utah">Aurora,<br/>Utah</a>,
 <a href="/wiki/Ozzy_Lusth" title="Ozzy Lusth">Oscar "Ozzy" Lusth</a>,
 <a href="/wiki/Survivor:_Cook_Islands" title="Survivor: Cook Islands">Cook Islands</a>,
 <a href="/wiki/Survivor:_Micronesia" title="Survivor: Micronesia">Micronesia</a>,
 <a href="/wiki/Venice,_Los_Angeles" title="Venice, Los Angeles">Venice,<br/>California</a>,
 <a href="/wiki/Plantation,_Florida" title="Plantation, Florida">Plantation,<br/>Florida</a>,
 <a href="/wiki/Coach_(Survivor_contestant)" title="Coach (Survivor contestant)">Benjamin "Coach" Wade</a>,
 <a href="/wiki/Survivor:_Tocantins" title="Survivor: Tocantins">Tocantins</a>,
 <a href="/wiki/Survivor:_Heroes_vs._Villains" title="Survivor: Heroes vs. Villains">Heroes vs. Villains</a>,
 <a href="/wiki/Susanville,_California" title="Susanville, California">Susanville,<br/>California</a>,
 <a href="/wiki/Willsboro,_New_York" title="Willsboro, New York">Willsboro,<br/>New York</a>]

In [ ]:
df = pd.read_html(str(tables))[3]
df

/tmp/ipykernel_3126/1238544221.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(tables))[3]

   Unnamed: 0_level_0 Original tribes                                         \
              Episode               1          2          3       4        5
0                 Day               3          5          8      11       14
1               Tribe          Savaii      Upolu     Savaii   Upolu   Savaii
2          Eliminated          Semhar  Christine  Papa Bear  Stacey    Elyse
3               Votes             8–1    4–3–1–1      6–1–1     7–1    3–2–2
4                 NaN             NaN        NaN        NaN     NaN      NaN
5               Voter            Vote       Vote       Vote    Vote     Vote
6              Sophie             NaN     Stacey        NaN  Stacey      NaN
7               Coach             NaN  Christine        NaN  Stacey      NaN
8              Albert             NaN  Christine        NaN  Stacey      NaN
9                Ozzy          Semhar        NaN  Papa Bear     NaN  Cochran
10               Rick             NaN     Stacey        NaN  Stacey      NaN
11            Brandon             NaN  Christine        NaN  Stacey      NaN
12               Edna             NaN     Stacey        NaN  Stacey      NaN
13            Cochran          Semhar        NaN  Papa Bear     NaN    Elyse
14            Whitney          Semhar        NaN  Papa Bear     NaN     Dawn
15               Dawn          Semhar        NaN  Papa Bear     NaN    Elyse
16                Jim          Semhar        NaN    Cochran     NaN    Elyse
17              Keith          Semhar        NaN  Papa Bear     NaN     Dawn
18            Mikayla             NaN  Christine        NaN  Stacey      NaN
19              Elyse          Semhar        NaN  Papa Bear     NaN  Cochran
20             Stacey             NaN     Sophie        NaN    Edna      NaN
21          Papa Bear          Semhar        NaN        Jim     NaN      NaN
22          Christine             NaN       Edna        NaN     NaN      NaN
23             Semhar         Cochran        NaN        NaN     NaN      NaN

                     Merged tribe           ... Unnamed: 26_level_0  \
          6        7            8      8.1  ... Unnamed: 26_level_1
0        16       18           21       21  ...                 NaN
1     Upolu   Savaii      Te Tuna  Te Tuna  ...                 NaN
2   Mikayla     Ozzy       Tie[a]    Keith  ...                 NaN
3       4–3      5–1          6–6      6–4  ...                 NaN
4       NaN      NaN          NaN      NaN  ...                 NaN
5      Vote     Vote         Vote     Vote  ...                 NaN
6      Edna      NaN        Keith    Keith  ...                 NaN
7   Mikayla      NaN        Keith    Keith  ...                 NaN
8      Edna      NaN        Keith    Keith  ...                 NaN
9       NaN  Cochran         Rick     Rick  ...                 NaN
10  Mikayla      NaN        Keith  None[b]  ...                 NaN
11  Mikayla      NaN        Keith    Keith  ...                 NaN
12  Mikayla      NaN        Keith    Keith  ...                 NaN
13      NaN     Ozzy         Rick    Keith  ...                 NaN
14      NaN     Ozzy         Rick     Rick  ...                 NaN
15      NaN     Ozzy         Rick     Rick  ...                 NaN
16      NaN     Ozzy         Rick     Rick  ...                 NaN
17      NaN     Ozzy         Rick  None[b]  ...                 NaN
18     Edna      NaN          NaN      NaN  ...                 NaN
19      NaN      NaN          NaN      NaN  ...                 NaN
20      NaN      NaN          NaN      NaN  ...                 NaN
21      NaN      NaN          NaN      NaN  ...                 NaN
22      NaN      NaN          NaN      NaN  ...                 NaN
23      NaN      NaN          NaN      NaN  ...                 NaN

   Unnamed: 27_level_0 Unnamed: 28_level_0 Unnamed: 29_level_0  \
   Unnamed: 27_level_1 Unnamed: 28_level_1 Unnamed: 29_level_1
0                  NaN                 NaN                 NaN
1                  NaN                 NaN                 NaN
2                  NaN                 NaN                 NaN
3                  NaN                 NaN                 NaN
4                  NaN                 NaN                 NaN
5                  NaN                 NaN                 NaN
6                  NaN                 NaN                 NaN
7                  NaN                 NaN                 NaN
8                  NaN                 NaN                 NaN
9                  NaN                 NaN                 NaN
10                 NaN                 NaN                 NaN
11                 NaN                 NaN                 NaN
12                 NaN                 NaN                 NaN
13                 NaN                 NaN                 NaN
14                 NaN                 NaN                 NaN
15                 NaN                 NaN                 NaN
16                 NaN                 NaN                 NaN
17                 NaN                 NaN                 NaN
18                 NaN                 NaN                 NaN
19                 NaN                 NaN                 NaN
20                 NaN                 NaN                 NaN
21                 NaN                 NaN                 NaN
22                 NaN                 NaN                 NaN
23                 NaN                 NaN                 NaN

   Unnamed: 30_level_0 Unnamed: 31_level_0 Unnamed: 32_level_0  \
   Unnamed: 30_level_1 Unnamed: 31_level_1 Unnamed: 32_level_1
0                  NaN                 NaN                 NaN
1                  NaN                 NaN                 NaN
2                  NaN                 NaN                 NaN
3                  NaN                 NaN                 NaN
4                  NaN                 NaN                 NaN
5                  NaN                 NaN                 NaN
6                  NaN                 NaN                 NaN
7                  NaN                 NaN                 NaN
8                  NaN                 NaN                 NaN
9                  NaN                 NaN                 NaN
10                 NaN                 NaN                 NaN
11                 NaN                 NaN                 NaN
12                 NaN                 NaN                 NaN
13                 NaN                 NaN                 NaN
14                 NaN                 NaN                 NaN
15                 NaN                 NaN                 NaN
16                 NaN                 NaN                 NaN
17                 NaN                 NaN                 NaN
18                 NaN                 NaN                 NaN
19                 NaN                 NaN                 NaN
20                 NaN                 NaN                 NaN
21                 NaN                 NaN                 NaN
22                 NaN                 NaN                 NaN
23                 NaN                 NaN                 NaN

   Unnamed: 33_level_0 Unnamed: 34_level_0 Unnamed: 35_level_0
   Unnamed: 33_level_1 Unnamed: 34_level_1 Unnamed: 35_level_1
0                  NaN                 NaN                 NaN
1                  NaN                 NaN                 NaN
2                  NaN                 NaN                 NaN
3                  NaN                 NaN                 NaN
4                  NaN                 NaN                 NaN
5                  NaN                 NaN                 NaN
6                  NaN                 NaN                 NaN
7                  NaN                 NaN                 NaN
8                  NaN                 NaN                 NaN
9                  NaN                 NaN                 NaN
10                 NaN                 NaN                 NaN
11                 NaN                 NaN                 NaN
12                 NaN                 NaN                 NaN
13                 NaN                 NaN                 NaN
14                 NaN                 NaN                 NaN
15                 NaN                 NaN                 NaN
16                 NaN                 NaN                 NaN
17                 NaN                 NaN                 NaN
18                 NaN                 NaN                 NaN
19                 NaN                 NaN                 NaN
20                 NaN                 NaN                 NaN
21                 NaN                 NaN                 NaN
22                 NaN                 NaN                 NaN
23                 NaN                 NaN                 NaN

[24 rows x 36 columns]

In [ ]:
sophie_row = df[df[('Unnamed: 0_level_0', 'Episode')] == 'Sophie']
print(sophie_row)

  Unnamed: 0_level_0 Original tribes                                       \
             Episode               1       2    3       4    5     6    7
6             Sophie             NaN  Stacey  NaN  Stacey  NaN  Edna  NaN

  Merged tribe         ... Unnamed: 26_level_0 Unnamed: 27_level_0  \
             8    8.1  ... Unnamed: 26_level_1 Unnamed: 27_level_1
6        Keith  Keith  ...                 NaN                 NaN

  Unnamed: 28_level_0 Unnamed: 29_level_0 Unnamed: 30_level_0  \
  Unnamed: 28_level_1 Unnamed: 29_level_1 Unnamed: 30_level_1
6                 NaN                 NaN                 NaN

  Unnamed: 31_level_0 Unnamed: 32_level_0 Unnamed: 33_level_0  \
  Unnamed: 31_level_1 Unnamed: 32_level_1 Unnamed: 33_level_1
6                 NaN                 NaN                 NaN

  Unnamed: 34_level_0 Unnamed: 35_level_0
  Unnamed: 34_level_1 Unnamed: 35_level_1
6                 NaN                 NaN

[1 rows x 36 columns]

## Survivor 24

In [ ]:
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
}

r = requests.get('https://en.wikipedia.org/wiki/Survivor:_One_World', headers=headers)
html_contents = r.text
html_soup = BeautifulSoup(html_contents,"lxml")

In [ ]:
tables = html_soup.find_all('table',class_="wikitable")
tables[0].find_all('a')

[<a href="/wiki/Austin,_Texas" title="Austin, Texas">Austin,<br/>Texas</a>,
 <a href="/wiki/Clovis,_California" title="Clovis, California">Clovis,<br/>California</a>,
 <a href="/wiki/San_Francisco" title="San Francisco">San Francisco,<br/>California</a>,
 <a href="/wiki/Venice,_Los_Angeles" title="Venice, Los Angeles">Venice,<br/>California</a>,
 <a href="/wiki/Tampa,_Florida" title="Tampa, Florida">Tampa,<br/>Florida</a>,
 <a href="/wiki/Monroeville,_Alabama" title="Monroeville, Alabama">Monroeville,<br/>Alabama</a>,
 <a href="/wiki/Lehi,_Utah" title="Lehi, Utah">Lehi,<br/>Utah</a>,
 <a href="/wiki/Seattle" title="Seattle">Seattle,<br/>Washington</a>,
 <a href="/wiki/Gaffney,_South_Carolina" title="Gaffney, South Carolina">Gaffney,<br/>South Carolina</a>,
 <a href="/wiki/San_Diego" title="San Diego">San Diego,<br/>California</a>,
 <a class="mw-redirect" href="/wiki/Troy_%22Troyzan%22_Robertson" title='Troy "Troyzan" Robertson'>Troy "Troyzan" Robertson</a>,
 <a href="/wiki/Miami" title="Miami">Miami,<br/>Florida</a>,
 <a href="/wiki/Orlando,_Florida" title="Orlando, Florida">Orlando,<br/>Florida</a>,
 <a href="/wiki/Houston" title="Houston">Houston,<br/>Texas</a>,
 <a href="/wiki/Chicago" title="Chicago">Chicago,<br/>Illinois</a>,
 <a href="/wiki/Hollywood,_Los_Angeles" title="Hollywood, Los Angeles">Hollywood,<br/>California</a>,
 <a href="/wiki/Charleston,_South_Carolina" title="Charleston, South Carolina">Charleston,<br/>South Carolina</a>,
 <a href="/wiki/Brooklyn" title="Brooklyn">Brooklyn,<br/>New York</a>,
 <a href="/wiki/San_Antonio" title="San Antonio">San Antonio,<br/>Texas</a>]

In [ ]:
df = pd.read_html(str(tables))[3]
df

/tmp/ipykernel_3126/1238544221.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(tables))[3]

   Unnamed: 0_level_0 Original tribes                             \
              Episode               1          2       3       4
0                 Day               3          5       8      11
1               Tribe          Salani     Salani  Manono  Manono
2          Eliminated        Kourtney       Nina    Matt    Bill
3               Votes    Evacuated[a]      6–1–1   7–1–1     7–1
4                 NaN             NaN        NaN     NaN     NaN
5               Voter            Vote       Vote    Vote    Vote
6                 Kim             NaN       Nina     NaN     NaN
7             Sabrina             NaN       Nina     NaN     NaN
8             Chelsea             NaN       Nina     NaN     NaN
9           Christina             NaN       Nina     NaN     NaN
10             Alicia             NaN       Nina     NaN     NaN
11             Tarzan             NaN        NaN    Matt    Bill
12                Kat             NaN       Nina     NaN     NaN
13            Troyzan             NaN        NaN    Matt    Bill
14               Leif             NaN        NaN    Matt    Bill
15                Jay             NaN        NaN    Matt    Bill
16            Michael             NaN        NaN    Bill    Bill
17              Jonas             NaN        NaN    Matt    Bill
18             Colton             NaN        NaN    Matt    Bill
19             Monica             NaN  Christina     NaN     NaN
20               Bill             NaN        NaN    Matt    Leif
21               Matt             NaN        NaN  Colton     NaN
22               Nina             NaN        Kat     NaN     NaN
23           Kourtney       Evacuated        NaN     NaN     NaN

   Switched tribes               Merged tribe                         ...  \
                 5             6            7          8           9  ...
0               14            16           20         22          25  ...
1           Manono        Manono      Tikiano    Tikiano     Tikiano  ...
2           Monica        Colton        Jonas    Michael         Jay  ...
3              5–2  Evacuated[b]         10–2      7–2–2  5–2–1–0[c]  ...
4              NaN           NaN          NaN        NaN         NaN  ...
5             Vote          Vote         Vote       Vote        Vote  ...
6              NaN           NaN        Jonas    Michael         Jay  ...
7              NaN           NaN        Jonas    Michael         Jay  ...
8              NaN           NaN        Jonas    Michael     Troyzan  ...
9           Tarzan           NaN        Jonas     Tarzan         Jay  ...
10          Monica           NaN        Jonas     Tarzan         Jay  ...
11          Monica           NaN        Jonas  Christina         Jay  ...
12             NaN           NaN        Jonas    Michael     Troyzan  ...
13             NaN           NaN        Jonas    Michael         Kim  ...
14          Monica           NaN      Michael    Michael      Alicia  ...
15             NaN           NaN        Jonas    Michael      Alicia  ...
16             NaN           NaN        Jonas  Christina         NaN  ...
17          Monica           NaN      Michael        NaN         NaN  ...
18          Monica     Evacuated          NaN        NaN         NaN  ...
19          Tarzan           NaN          NaN        NaN         NaN  ...
20             NaN           NaN          NaN        NaN         NaN  ...
21             NaN           NaN          NaN        NaN         NaN  ...
22             NaN           NaN          NaN        NaN         NaN  ...
23             NaN           NaN          NaN        NaN         NaN  ...

                                         Unnamed: 16_level_0  \
         12       13       14       14.1 Unnamed: 16_level_1
0        33       36       37         38                 NaN
1   Tikiano  Tikiano  Tikiano    Tikiano                 NaN
2       Kat   Tarzan   Alicia  Christina                 NaN
3       6–1      5–1      3–2        3–1                 NaN
4       NaN      NaN      NaN        NaN                 NaN
5      Vote     Vote     Vote       Vote                Vote
6       Kat   Tarzan   Alicia  Christina                 NaN
7       Kat   Tarzan   Alicia  Christina                 NaN
8       Kat   Tarzan   Alicia  Christina                 NaN
9       Kat   Tarzan  Chelsea    Sabrina                 NaN
10      Kat   Tarzan  Chelsea        NaN                 NaN
11      Kat  Chelsea      NaN        NaN                 NaN
12  Sabrina      NaN      NaN        NaN                 NaN
13      NaN      NaN      NaN        NaN                 NaN
14      NaN      NaN      NaN        NaN                 NaN
15      NaN      NaN      NaN        NaN                 NaN
16      NaN      NaN      NaN        NaN                 NaN
17      NaN      NaN      NaN        NaN                 NaN
18      NaN      NaN      NaN        NaN                 NaN
19      NaN      NaN      NaN        NaN                 NaN
20      NaN      NaN      NaN        NaN                 NaN
21      NaN      NaN      NaN        NaN                 NaN
22      NaN      NaN      NaN        NaN                 NaN
23      NaN      NaN      NaN        NaN                 NaN

   Unnamed: 17_level_0 Unnamed: 18_level_0 Unnamed: 19_level_0  \
   Unnamed: 17_level_1 Unnamed: 18_level_1 Unnamed: 19_level_1
0                  NaN                 NaN                 NaN
1                  NaN                 NaN                 NaN
2                  NaN                 NaN                 NaN
3                  NaN                 NaN                 NaN
4                  NaN                 NaN                 NaN
5                 Vote                Vote                Vote
6                  NaN                 NaN                 NaN
7                  NaN                 NaN                 NaN
8                  NaN                 NaN                 NaN
9                  NaN                 NaN                 NaN
10                 NaN                 NaN                 NaN
11                 NaN                 NaN                 NaN
12                 NaN                 NaN                 NaN
13                 NaN                 NaN                 NaN
14                 NaN                 NaN                 NaN
15                 NaN                 NaN                 NaN
16                 NaN                 NaN                 NaN
17                 NaN                 NaN                 NaN
18                 NaN                 NaN                 NaN
19                 NaN                 NaN                 NaN
20                 NaN                 NaN                 NaN
21                 NaN                 NaN                 NaN
22                 NaN                 NaN                 NaN
23                 NaN                 NaN                 NaN

   Unnamed: 20_level_0 Unnamed: 21_level_0
   Unnamed: 20_level_1 Unnamed: 21_level_1
0                  NaN                 NaN
1                  NaN                 NaN
2                  NaN                 NaN
3                  NaN                 NaN
4                  NaN                 NaN
5                  NaN                 NaN
6                  NaN                 NaN
7                  NaN                 NaN
8                  NaN                 NaN
9                  NaN                 NaN
10                 NaN                 NaN
11                 NaN                 NaN
12                 NaN                 NaN
13                 NaN                 NaN
14                 NaN                 NaN
15                 NaN                 NaN
16                 NaN                 NaN
17                 NaN                 NaN
18                 NaN                 NaN
19                 NaN                 NaN
20                 NaN                 NaN
21                 NaN                 NaN
22                 NaN                 NaN
23                 NaN                 NaN

[24 rows x 22 columns]

In [ ]:
kim_row = df[df[('Unnamed: 0_level_0', 'Episode')] == 'Kim']
print(kim_row)

  Unnamed: 0_level_0 Original tribes                 Switched tribes       \
             Episode               1     2    3    4               5    6
6                Kim             NaN  Nina  NaN  NaN             NaN  NaN

  Merged tribe                ...                                  \
             7        8    9  ...   12      13      14       14.1
6        Jonas  Michael  Jay  ...  Kat  Tarzan  Alicia  Christina

  Unnamed: 16_level_0 Unnamed: 17_level_0 Unnamed: 18_level_0  \
  Unnamed: 16_level_1 Unnamed: 17_level_1 Unnamed: 18_level_1
6                 NaN                 NaN                 NaN

  Unnamed: 19_level_0 Unnamed: 20_level_0 Unnamed: 21_level_0
  Unnamed: 19_level_1 Unnamed: 20_level_1 Unnamed: 21_level_1
6                 NaN                 NaN                 NaN

[1 rows x 22 columns]

## Survivor 25

In [ ]:
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
}

r = requests.get('https://en.wikipedia.org/wiki/Survivor:_Philippines', headers=headers)
html_contents = r.text
html_soup = BeautifulSoup(html_contents,"lxml")

In [ ]:
tables = html_soup.find_all('table',class_="wikitable")
tables[0].find_all('a')

[<a href="/wiki/Danville,_Virginia" title="Danville, Virginia">Danville,<br/>Virginia</a>,
 <a href="/wiki/Brooklyn" title="Brooklyn">Brooklyn,<br/>New York</a>,
 <a href="/wiki/Provo,_Utah" title="Provo, Utah">Provo,<br/>Utah</a>,
 <a href="/wiki/Survivor:_Samoa" title="Survivor: Samoa">Samoa</a>,
 <a href="/wiki/Glenside,_Pennsylvania" title="Glenside, Pennsylvania">Glenside,<br/>Pennsylvania</a>,
 <a href="/wiki/Winston-Salem,_North_Carolina" title="Winston-Salem, North Carolina"><span class="nowrap">Winston-Salem,</span><br/>North Carolina</a>,
 <a href="/wiki/Silver_Spring,_Maryland" title="Silver Spring, Maryland">Silver Spring,<br/>Maryland</a>,
 <a href="/wiki/Newark,_Delaware" title="Newark, Delaware">Newark,<br/>Delaware</a>,
 <a href="/wiki/New_York_City" title="New York City">New York City,<br/>New York</a>,
 <a href="/wiki/Jeff_Kent" title="Jeff Kent">Jeff Kent</a>,
 <a href="/wiki/Austin,_Texas" title="Austin, Texas">Austin,<br/>Texas</a>,
 <a href="/wiki/Terrytown,_Louisiana" title="Terrytown, Louisiana">Terrytown,<br/>Louisiana</a>,
 <a href="/wiki/Holmdel_Township,_New_Jersey" title="Holmdel Township, New Jersey">Holmdel,<br/>New Jersey</a>,
 <a href="/wiki/Jonathan_Penner" title="Jonathan Penner">Jonathan Penner</a>,
 <a href="/wiki/Survivor:_Cook_Islands" title="Survivor: Cook Islands">Cook Islands</a>,
 <a href="/wiki/Survivor:_Micronesia" title="Survivor: Micronesia">Micronesia</a>,
 <a href="/wiki/Los_Angeles" title="Los Angeles">Los Angeles,<br/>California</a>,
 <a href="/wiki/Shawnee,_Kansas" title="Shawnee, Kansas">Shawnee,<br/>Kansas</a>,
 <a href="/wiki/Los_Angeles" title="Los Angeles">Los Angeles,<br/>California</a>,
 <a href="/wiki/Hermosa_Beach,_California" title="Hermosa Beach, California">Hermosa Beach,<br/>California</a>,
 <a href="/wiki/Michael_Skupin" title="Michael Skupin">Michael Skupin</a>,
 <a href="/wiki/Survivor:_The_Australian_Outback" title="Survivor: The Australian Outback">The Australian Outback</a>,
 <a href="/wiki/White_Lake_Township,_Michigan" title="White Lake Township, Michigan">White Lake,<br/>Michigan</a>,
 <a href="/wiki/Lisa_Whelchel" title="Lisa Whelchel">Lisa Whelchel</a>,
 <a href="/wiki/Dallas" title="Dallas">Dallas,<br/>Texas</a>,
 <a href="/wiki/Cedar_Rapids,_Iowa" title="Cedar Rapids, Iowa">Cedar Rapids,<br/>Iowa</a>]

In [ ]:
df = pd.read_html(str(tables))[3]
df

/tmp/ipykernel_3126/1238544221.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(tables))[3]

   Unnamed: 0_level_0 Original tribes                             \
              Episode               1        2        3        4
0                 Day               3        6        8       10
1               Tribe         Matsing  Matsing  Matsing  Matsing
2          Eliminated            Zane     Roxy    Angie  Russell
3               Votes             5–1      4–1      3–1      2–1
4                 NaN             NaN      NaN      NaN      NaN
5               Voter            Vote     Vote     Vote     Vote
6              Denise            Zane     Roxy    Angie  Russell
7                Lisa             NaN      NaN      NaN      NaN
8             Michael             NaN      NaN      NaN      NaN
9             Malcolm            Zane     Roxy    Angie  Russell
10          Abi-Maria             NaN      NaN      NaN      NaN
11             Carter             NaN      NaN      NaN      NaN
12           Jonathan             NaN      NaN      NaN      NaN
13               Pete             NaN      NaN      NaN      NaN
14              Artis             NaN      NaN      NaN      NaN
15               Jeff             NaN      NaN      NaN      NaN
16                 RC             NaN      NaN      NaN      NaN
17              Katie             NaN      NaN      NaN      NaN
18             Dawson             NaN      NaN      NaN      NaN
19               Dana             NaN      NaN      NaN      NaN
20            Russell            Zane     Roxy    Angie  Malcolm
21              Angie            Zane     Roxy  Russell      NaN
22               Roxy            Zane    Angie      NaN      NaN
23               Zane         Russell      NaN      NaN      NaN

   Absorbed tribes                    Merged tribe                        \
                 5      5.1         6            7          8          9
0               12       13        16           19         22         25
1          Kalabaw  Kalabaw   Kalabaw    Dangrayne  Dangrayne  Dangrayne
2             Dana   Dawson     Katie           RC       Jeff      Artis
3          Quit[a]      5–1       4–1     4–2–0[b]      5–4–1        5–4
4              NaN      NaN       NaN          NaN        NaN        NaN
5             Vote     Vote      Vote         Vote       Vote       Vote
6              NaN   Dawson     Katie     Jonathan       Pete      Artis
7              NaN      NaN       NaN     Jonathan       Jeff   Jonathan
8              NaN      NaN       NaN     Jonathan       Jeff      Artis
9              NaN      NaN       NaN     Jonathan       Pete      Artis
10             NaN      NaN       NaN     Jonathan       Jeff   Jonathan
11             NaN   Dawson     Katie           RC       Pete      Artis
12             NaN   Dawson     Katie         Pete  Abi-Maria      Artis
13             NaN      NaN       NaN           RC       Jeff   Jonathan
14             NaN      NaN       NaN           RC       Jeff   Jonathan
15             NaN   Dawson     Katie           RC       Pete        NaN
16             NaN      NaN       NaN         Pete        NaN        NaN
17             NaN   Dawson  Jonathan          NaN        NaN        NaN
18             NaN   Denise       NaN          NaN        NaN        NaN
19            Quit      NaN       NaN          NaN        NaN        NaN
20             NaN      NaN       NaN          NaN        NaN        NaN
21             NaN      NaN       NaN          NaN        NaN        NaN
22             NaN      NaN       NaN          NaN        NaN        NaN
23             NaN      NaN       NaN          NaN        NaN        NaN

                                                                               \
           10         11         12         13         14 Unnamed: 16_level_1
0          27         30         33         36         38                 NaN
1   Dangrayne  Dangrayne  Dangrayne  Dangrayne  Dangrayne                 NaN
2        Pete   Jonathan     Carter  Abi-Maria    Malcolm                 NaN
3    3–2–0[c]        4–3        5–1        4–1        3–1                 NaN
4         NaN        NaN        NaN        NaN        NaN                 NaN
5        Vote       Vote       Vote       Vote       Vote                 NaN
6   Abi-Maria   Jonathan     Carter  Abi-Maria    Malcolm                 NaN
7   Abi-Maria   Jonathan     Carter  Abi-Maria    Malcolm                 NaN
8   Abi-Maria   Jonathan     Carter  Abi-Maria    Malcolm                 NaN
9        Pete   Jonathan     Carter  Abi-Maria     Denise                 NaN
10    Malcolm     Denise     Carter     Denise        NaN                 NaN
11       Pete     Denise  Abi-Maria        NaN        NaN                 NaN
12       Pete     Denise        NaN        NaN        NaN                 NaN
13    Malcolm        NaN        NaN        NaN        NaN                 NaN
14        NaN        NaN        NaN        NaN        NaN                 NaN
15        NaN        NaN        NaN        NaN        NaN                 NaN
16        NaN        NaN        NaN        NaN        NaN                 NaN
17        NaN        NaN        NaN        NaN        NaN                 NaN
18        NaN        NaN        NaN        NaN        NaN                 NaN
19        NaN        NaN        NaN        NaN        NaN                 NaN
20        NaN        NaN        NaN        NaN        NaN                 NaN
21        NaN        NaN        NaN        NaN        NaN                 NaN
22        NaN        NaN        NaN        NaN        NaN                 NaN
23        NaN        NaN        NaN        NaN        NaN                 NaN


   Unnamed: 17_level_1 Unnamed: 18_level_1
0                  NaN                 NaN
1                  NaN                 NaN
2                  NaN                 NaN
3                  NaN                 NaN
4                  NaN                 NaN
5                  NaN                 NaN
6                  NaN                 NaN
7                  NaN                 NaN
8                  NaN                 NaN
9                  NaN                 NaN
10                 NaN                 NaN
11                 NaN                 NaN
12                 NaN                 NaN
13                 NaN                 NaN
14                 NaN                 NaN
15                 NaN                 NaN
16                 NaN                 NaN
17                 NaN                 NaN
18                 NaN                 NaN
19                 NaN                 NaN
20                 NaN                 NaN
21                 NaN                 NaN
22                 NaN                 NaN
23                 NaN                 NaN

In [ ]:
denise_row = df[df[('Unnamed: 0_level_0', 'Episode')] == 'Denise']
print(denise_row)

  Unnamed: 0_level_0 Original tribes                       Absorbed tribes  \
             Episode               1     2      3        4               5
6             Denise            Zane  Roxy  Angie  Russell             NaN

                 Merged tribe                                            \
      5.1      6            7     8      9         10        11      12
6  Dawson  Katie     Jonathan  Pete  Artis  Abi-Maria  Jonathan  Carter

                                                               \
          13       14 Unnamed: 16_level_1 Unnamed: 17_level_1
6  Abi-Maria  Malcolm                 NaN                 NaN


  Unnamed: 18_level_1
6                 NaN

## Survivor 26

In [ ]:
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
}

r = requests.get('https://en.wikipedia.org/wiki/Survivor:_Caramoan', headers=headers)
html_contents = r.text
html_soup = BeautifulSoup(html_contents,"lxml")

In [ ]:
tables = html_soup.find_all('table',class_="wikitable")
tables[0].find_all('a')

[<a href="/wiki/Survivor:_Redemption_Island" title="Survivor: Redemption Island"><span class="nowrap">Redemption Island</span></a>,
 <a href="/wiki/Brooklyn" title="Brooklyn">Brooklyn,<br/>New York</a>,
 <a href="/wiki/Oceanside,_New_York" title="Oceanside, New York">Oceanside,<br/>New York</a>,
 <a href="/wiki/Jefferson_City,_Missouri" title="Jefferson City, Missouri">Jefferson City,<br/>Missouri</a>,
 <a href="/wiki/Brooklyn" title="Brooklyn">Brooklyn,<br/>New York</a>,
 <a href="/wiki/Washington,_D.C." title="Washington, D.C.">Washington,<br/>D.C.</a>,
 <a href="/wiki/Survivor:_South_Pacific" title="Survivor: South Pacific">South Pacific</a>,
 <a href="/wiki/Katy,_Texas" title="Katy, Texas">Katy,<br/>Texas</a>,
 <a href="/wiki/Cincinnati" title="Cincinnati">Cincinnati,<br/>Ohio</a>,
 <a href="/wiki/Julia_Landauer" title="Julia Landauer">Julia Landauer</a>,
 <a href="/wiki/Stanford,_California" title="Stanford, California">Stanford,<br/>California</a>,
 <a href="/wiki/Survivor:_Gabon" title="Survivor: Gabon">Gabon</a>,
 <a href="/wiki/Los_Angeles" title="Los Angeles">Los Angeles,<br/> California</a>,
 <a href="/wiki/New_York_City" title="New York City">New York City,<br/>New York</a>,
 <a href="/wiki/Survivor:_Redemption_Island" title="Survivor: Redemption Island">Redemption Island</a>,
 <a href="/wiki/Santa_Monica,_California" title="Santa Monica, California">Santa Monica,<br/>California</a>,
 <a href="/wiki/Survivor:_Philippines" title="Survivor: Philippines">Philippines</a>,
 <a href="/wiki/Odessa,_New_York" title="Odessa, New York">Odessa,<br/>New York</a>,
 <a href="/wiki/San_Francisco" title="San Francisco">San Francisco,<br/>California</a>,
 <a href="/wiki/Survivor:_Redemption_Island" title="Survivor: Redemption Island">Redemption Island</a>,
 <a href="/wiki/New_York_City" title="New York City">New York City,<br/>New York</a>,
 <a href="/wiki/Survivor:_Nicaragua" title="Survivor: Nicaragua">Nicaragua</a>,
 <a href="/wiki/Miami" title="Miami">Miami,<br/>Florida</a>,
 <a href="/wiki/Survivor:_Micronesia" title="Survivor: Micronesia">Micronesia</a>,
 <a href="/wiki/Santa_Clarita,_California" title="Santa Clarita, California">Santa Clarita,<br/>California</a>,
 <a href="/wiki/East_Brunswick,_New_Jersey" title="East Brunswick, New Jersey"><span class="nowrap">East Brunswick,</span><br/>New Jersey</a>,
 <a href="/wiki/Boise,_Idaho" title="Boise, Idaho">Boise,<br/>Idaho</a>,
 <a href="/wiki/Survivor:_South_Pacific" title="Survivor: South Pacific">South Pacific</a>,
 <a href="/wiki/South_Jordan,_Utah" title="South Jordan, Utah">South Jordan,<br/>Utah</a>,
 <a href="/wiki/John_Cochran_(Survivor_contestant)" title="John Cochran (Survivor contestant)">John Cochran</a>,
 <a href="/wiki/Survivor:_South_Pacific" title="Survivor: South Pacific">South Pacific</a>,
 <a href="/wiki/Washington,_D.C." title="Washington, D.C.">Washington,<br/>D.C.</a>]

In [ ]:
df = pd.read_html(str(tables))[3]
df

/tmp/ipykernel_3126/1238544221.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(tables))[3]

   Unnamed: 0_level_0 Original tribes                                         \
              Episode               1       2       3      3.1             4
0                 Day               3       5       7        7            10
1               Tribe           Bikal    Gota    Gota     Gota          Gota
2          Eliminated       Francesca   Allie  Tie[a]     Hope        Shamar
3               Votes             6–4     6–4   3–3–3    5–1–0  Evacuated[b]
4                 NaN             NaN     NaN     NaN      NaN           NaN
5               Voter            Vote    Vote    Vote     Vote          Vote
6             Cochran       Francesca     NaN     NaN      NaN           NaN
7                Dawn       Francesca     NaN     NaN      NaN           NaN
8              Sherri             NaN   Allie    Hope     Hope           NaN
9               Eddie             NaN  Shamar  Shamar  None[g]           NaN
10               Erik          Andrea     NaN     NaN      NaN           NaN
11             Brenda          Andrea     NaN     NaN      NaN           NaN
12             Andrea       Francesca     NaN     NaN      NaN           NaN
13            Reynold             NaN  Shamar  Shamar   Shamar           NaN
14            Malcolm       Francesca     NaN     NaN      NaN           NaN
15            Phillip       Francesca     NaN     NaN      NaN           NaN
16            Michael             NaN   Allie   Eddie     Hope           NaN
17            Corinne       Francesca     NaN     NaN      NaN           NaN
18              Julia             NaN   Allie    Hope     Hope           NaN
19               Matt             NaN   Allie   Eddie     Hope           NaN
20            Brandon          Andrea     NaN     NaN      NaN           NaN
21              Laura             NaN   Allie    Hope     Hope           NaN
22             Shamar             NaN   Allie   Eddie  None[g]     Evacuated
23               Hope             NaN  Shamar  Shamar  None[g]           NaN
24              Allie             NaN  Shamar     NaN      NaN           NaN
25          Francesca          Andrea     NaN     NaN      NaN           NaN

                     Switched tribes           ... Merged Tribe             \
        4.1        5               6        7  ...           10         11
0        10       13              16       19  ...           28         30
1      Gota    Bikal           Bikal    Bikal  ...    Enil Edam  Enil Edam
2     Laura  Brandon            Matt   Tie[a]  ...      Phillip     Tie[a]
3    6–0[c]   8–1[d]           4–2–1      3–3  ...     4–0–0[e]      3–3–3
4       NaN      NaN             NaN      NaN  ...          NaN        NaN
5      Vote     Vote            Vote     Vote  ...         Vote       Vote
6       NaN  Brandon            Matt  Michael  ...      Malcolm    Malcolm
7       NaN  Brandon            Matt    Julia  ...        Eddie    Reynold
8     Laura      NaN             NaN      NaN  ...        Eddie    Reynold
9     Laura      NaN             NaN      NaN  ...      Phillip     Andrea
10      NaN  Brandon             NaN      NaN  ...      Phillip    Malcolm
11      NaN  Brandon             NaN      NaN  ...        Eddie    Reynold
12      NaN  Brandon             NaN      NaN  ...        Eddie    Malcolm
13    Laura      NaN             NaN      NaN  ...      Phillip     Andrea
14      NaN  Brandon             NaN      NaN  ...      Phillip     Andrea
15      NaN  Brandon            Matt  Michael  ...      Malcolm        NaN
16    Laura      NaN           Julia    Julia  ...          NaN        NaN
17      NaN  Brandon            Matt    Julia  ...          NaN        NaN
18    Laura      NaN            Dawn  Michael  ...          NaN        NaN
19    Laura      NaN           Julia      NaN  ...          NaN        NaN
20      NaN  Phillip             NaN      NaN  ...          NaN        NaN
21  Reynold      NaN             NaN      NaN  ...          NaN        NaN
22      NaN      NaN             NaN      NaN  ...          NaN        NaN
23      NaN      NaN             NaN      NaN  ...          NaN        NaN
24      NaN      NaN             NaN      NaN  ...          NaN        NaN
25      NaN      NaN             NaN      NaN  ...          NaN        NaN

                                                                         \
         11.1         12       12.1         13            14       14.1
0          30         31         33         36            36         38
1   Enil Edam  Enil Edam  Enil Edam  Enil Edam     Enil Edam  Enil Edam
2     Malcolm    Reynold     Andrea     Brenda          Erik      Eddie
3       6–0–0    4–2–1–1      3–2–2      3–2–1  Evacuated[f]        3–1
4         NaN        NaN        NaN        NaN           NaN        NaN
5        Vote       Vote       Vote       Vote          Vote       Vote
6     Malcolm      Eddie      Eddie     Brenda           NaN      Eddie
7     Malcolm    Reynold      Eddie     Brenda           NaN      Eddie
8     Malcolm    Reynold     Andrea     Brenda           NaN      Eddie
9     Malcolm     Sherri     Brenda       Erik           NaN       Dawn
10    Malcolm      Eddie     Andrea      Eddie     Evacuated        NaN
11    Malcolm    Reynold     Andrea      Eddie           NaN        NaN
12    None[h]    Reynold     Brenda        NaN           NaN        NaN
13    None[h]       Erik        NaN        NaN           NaN        NaN
14    None[h]        NaN        NaN        NaN           NaN        NaN
15        NaN        NaN        NaN        NaN           NaN        NaN
16        NaN        NaN        NaN        NaN           NaN        NaN
17        NaN        NaN        NaN        NaN           NaN        NaN
18        NaN        NaN        NaN        NaN           NaN        NaN
19        NaN        NaN        NaN        NaN           NaN        NaN
20        NaN        NaN        NaN        NaN           NaN        NaN
21        NaN        NaN        NaN        NaN           NaN        NaN
22        NaN        NaN        NaN        NaN           NaN        NaN
23        NaN        NaN        NaN        NaN           NaN        NaN
24        NaN        NaN        NaN        NaN           NaN        NaN
25        NaN        NaN        NaN        NaN           NaN        NaN

   Unnamed: 21_level_0 Unnamed: 22_level_0
   Unnamed: 21_level_1 Unnamed: 22_level_1
0                  NaN                 NaN
1                  NaN                 NaN
2                  NaN                 NaN
3                  NaN                 NaN
4                  NaN                 NaN
5                  NaN                 NaN
6                  NaN                 NaN
7                  NaN                 NaN
8                  NaN                 NaN
9                  NaN                 NaN
10                 NaN                 NaN
11                 NaN                 NaN
12                 NaN                 NaN
13                 NaN                 NaN
14                 NaN                 NaN
15                 NaN                 NaN
16                 NaN                 NaN
17                 NaN                 NaN
18                 NaN                 NaN
19                 NaN                 NaN
20                 NaN                 NaN
21                 NaN                 NaN
22                 NaN                 NaN
23                 NaN                 NaN
24                 NaN                 NaN
25                 NaN                 NaN

[26 rows x 23 columns]

In [ ]:
cochran_row = df[df[('Unnamed: 0_level_0', 'Episode')] == 'Cochran']
print(cochran_row)

  Unnamed: 0_level_0 Original tribes                                    \
             Episode               1    2    3  3.1    4  4.1        5
6            Cochran       Francesca  NaN  NaN  NaN  NaN  NaN  Brandon

  Switched tribes           ... Merged Tribe                                  \
                6        7  ...           10       11     11.1     12   12.1
6            Matt  Michael  ...      Malcolm  Malcolm  Malcolm  Eddie  Eddie

                      Unnamed: 21_level_0 Unnamed: 22_level_0
       13   14   14.1 Unnamed: 21_level_1 Unnamed: 22_level_1
6  Brenda  NaN  Eddie                 NaN                 NaN

[1 rows x 23 columns]

## Survivor 27

In [ ]:
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
}

r = requests.get('https://en.wikipedia.org/wiki/Survivor:_Blood_vs._Water', headers=headers)
html_contents = r.text
html_soup = BeautifulSoup(html_contents,"lxml")

In [ ]:
tables = html_soup.find_all('table',class_="wikitable")
tables[0].find_all('a')

[<a href="#cite_note-24"><span class="cite-bracket">[</span>a<span class="cite-bracket">]</span></a>,
 <a href="#cite_note-Rupert-25"><span class="cite-bracket">[</span>b<span class="cite-bracket">]</span></a>,
 <a href="#cite_note-Rupert-25"><span class="cite-bracket">[</span>b<span class="cite-bracket">]</span></a>,
 <a href="#cite_note-Rupert-25"><span class="cite-bracket">[</span>b<span class="cite-bracket">]</span></a>,
 <a href="/wiki/Survivor:_Cook_Islands" title="Survivor: Cook Islands">Cook Islands</a>,
 <a href="/wiki/Survivor:_Heroes_vs._Villains" title="Survivor: Heroes vs. Villains">Heroes vs. Villains</a>,
 <a href="/wiki/Washington,_D.C." title="Washington, D.C.">Washington,<br/>D.C.</a>,
 <a href="/wiki/Rupert_Boneham" title="Rupert Boneham">Rupert Boneham</a>,
 <a href="/wiki/Survivor:_Pearl_Islands" title="Survivor: Pearl Islands">Pearl Islands</a>,
 <a href="/wiki/Survivor:_All-Stars" title="Survivor: All-Stars">All-Stars</a>,
 <a href="/wiki/Survivor:_Heroes_vs._Villains" title="Survivor: Heroes vs. Villains">Heroes vs. Villains</a>,
 <a href="/wiki/Indianapolis" title="Indianapolis">Indianapolis,<br/>Indiana</a>,
 <a href="#cite_note-Rupert-25"><span class="cite-bracket">[</span>b<span class="cite-bracket">]</span></a>,
 <a href="/wiki/Chapel_Hill,_North_Carolina" title="Chapel Hill, North Carolina">Chapel Hill,<br/>North Carolina</a>,
 <a href="/wiki/Provo,_Utah" title="Provo, Utah">Provo,<br/>Utah</a>,
 <a href="/wiki/Survivor:_One_World" title="Survivor: One World">One World</a>,
 <a href="/wiki/Collinsville,_Alabama" title="Collinsville, Alabama">Collinsville,<br/>Alabama</a>,
 <a href="/wiki/Washington,_D.C." title="Washington, D.C.">Washington,<br/>D.C.</a>,
 <a href="/wiki/Brad_Culpepper" title="Brad Culpepper">Brad Culpepper</a>,
 <a href="/wiki/Tampa,_Florida" title="Tampa, Florida">Tampa,<br/>Florida</a>,
 <a href="/wiki/Survivor:_One_World" title="Survivor: One World">One World</a>,
 <a href="/wiki/Orlando,_Florida" title="Orlando, Florida">Orlando,<br/>Florida</a>,
 <a href="/wiki/Indianapolis" title="Indianapolis">Indianapolis,<br/>Indiana</a>,
 <a href="#cite_note-Rupert-25"><span class="cite-bracket">[</span>b<span class="cite-bracket">]</span></a>,
 <a href="/wiki/Survivor:_Panama" title="Survivor: Panama">Panama</a>,
 <a href="/wiki/Santa_Monica,_California" title="Santa Monica, California">Santa Monica,<br/>California</a>,
 <a href="/wiki/Santa_Monica,_California" title="Santa Monica, California">Santa Monica,<br/>California</a>,
 <a href="/wiki/Survivor:_Samoa" title="Survivor: Samoa">Samoa</a>,
 <a href="/wiki/Salem,_Oregon" title="Salem, Oregon">Salem,<br/>Oregon</a>,
 <a href="#cite_note-26"><span class="cite-bracket">[</span>c<span class="cite-bracket">]</span></a>,
 <a href="/wiki/Collinsville,_Alabama" title="Collinsville, Alabama">Collinsville,<br/>Alabama</a>,
 <a href="/wiki/New_York_City" title="New York City">New York City,<br/>New York</a>,
 <a href="#cite_note-27"><span class="cite-bracket">[</span>d<span class="cite-bracket">]</span></a>,
 <a class="mw-redirect" href="/wiki/Hayden_Moss" title="Hayden Moss">Hayden Moss</a>,
 <a href="/wiki/Springtown,_Texas" title="Springtown, Texas">Springtown,<br/>Texas</a>,
 <a href="/wiki/Salem,_Oregon" title="Salem, Oregon">Salem,<br/>Oregon</a>,
 <a href="/wiki/Survivor:_The_Australian_Outback" title="Survivor: The Australian Outback"><span class="nowrap">The Australian Outback</span></a>,
 <a href="/wiki/Survivor:_All-Stars" title="Survivor: All-Stars">All-Stars</a>,
 <a href="/wiki/Robbinsville,_North_Carolina" title="Robbinsville, North Carolina">Robbinsville,<br/>North Carolina</a>,
 <a href="/wiki/Gervase_Peterson" title="Gervase Peterson">Gervase Peterson</a>,
 <a href="/wiki/Survivor:_Borneo" title="Survivor: Borneo">Borneo</a>,
 <a href="/wiki/Philadelphia" title="Philadelphia">Philadelphia,<br/>Pennsylvania</a>,
 <a href="/wiki/Survivor:_One_World" title="Survivor: One World">One World</a>,
 <a href="/wiki/Tampa,_Florida" title="Tampa, Florida">Tampa,<br/>Florida</a>,
 <a href="/wiki/Tyson_Apostol" title="Tyson Apostol">Tyson Apostol</a>,
 <a href="/wiki/Survivor:_Tocantins" title="Survivor: Tocantins">Tocantins</a>,
 <a href="/wiki/Survivor:_Heroes_vs._Villains" title="Survivor: Heroes vs. Villains">Heroes vs. Villains</a>,
 <a href="/wiki/Provo,_Utah" title="Provo, Utah">Provo,<br/>Utah</a>]

In [ ]:
df = pd.read_html(str(tables))[3]
df

/tmp/ipykernel_3126/1238544221.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(tables))[3]

   Unnamed: 0_level_0 Original tribes                                          \
              Episode               1          1.1      1.2      1.3        2
0                 Day               1            1        1        3        6
1               Tribe         Tadhana       Galang   Galang  Tadhana  Tadhana
2          Eliminated     Laura B.[a]      Candice   Rupert  Marissa   Rachel
3               Votes      6–2–1–1[d]     6–3–1[e]  Swap[a]      8–1    5–2–1
4                 NaN             NaN          NaN      NaN      NaN      NaN
5               Voter            Vote         Vote     Vote     Vote     Vote
6               Tyson             NaN     Laura M.      NaN      NaN      NaN
7              Monica             NaN      Candice      NaN      NaN      NaN
8             Gervase             NaN  Candice[71]      NaN      NaN      NaN
9                Tina             NaN      Candice      NaN      NaN      NaN
10              Ciera        Laura B.          NaN      NaN  Marissa     John
11             Hayden        Laura B.          NaN      NaN  Marissa   Rachel
12              Katie     Marissa[72]          NaN      NaN  Marissa     John
13              Caleb        Laura B.          NaN      NaN  Marissa   Rachel
14           Laura M.             NaN      Candice      NaN      NaN      NaN
15              Vytas        Laura B.          NaN      NaN  Marissa   Rachel
16               Aras             NaN      Gervase      NaN      NaN      NaN
17           Laura B.         Marissa          NaN      NaN      NaN      NaN
18                Kat             NaN      Candice      NaN      NaN      NaN
19               Brad        Laura B.          NaN      NaN  Marissa   Rachel
20               John        Laura B.          NaN      NaN  Marissa   Rachel
21             Colton             NaN      Candice      NaN      NaN      NaN
22             Rachel           Katie          NaN      NaN  Marissa    Ciera
23            Marissa            Brad          NaN      NaN    Katie      NaN
24             Rupert             NaN     Laura M.     Swap      NaN      NaN
25            Candice             NaN     Laura M.      NaN      NaN      NaN

                                        ... Unnamed: 894_level_0  \
          3      3.1        4      4.1  ... Unnamed: 894_level_1
0         7        8       10       10  ...                  NaN
1    Galang  Tadhana  Tadhana  Tadhana  ...                  NaN
2    Colton     John   Tie[b]     Brad  ...                  NaN
3   Quit[f]      6–1      3–3      3–1  ...                  NaN
4       NaN      NaN      NaN      NaN  ...                  NaN
5      Vote     Vote     Vote     Vote  ...                  NaN
6       NaN      NaN      NaN      NaN  ...                  NaN
7       NaN      NaN      NaN      NaN  ...                  NaN
8       NaN      NaN      NaN      NaN  ...                  NaN
9       NaN      NaN      NaN      NaN  ...                  NaN
10      NaN     John     Brad  None[j]  ...                  NaN
11      NaN     John    Ciera    Ciera  ...                  NaN
12      NaN     John     Brad     Brad  ...                  NaN
13      NaN     John     Brad     Brad  ...                  NaN
14      NaN      NaN      NaN      NaN  ...                  NaN
15      NaN     John    Ciera     Brad  ...                  NaN
16      NaN      NaN      NaN      NaN  ...                  NaN
17      NaN      NaN      NaN      NaN  ...                  NaN
18      NaN      NaN      NaN      NaN  ...                  NaN
19      NaN     John    Ciera  None[j]  ...                  NaN
20      NaN    Ciera      NaN      NaN  ...                  NaN
21     Quit      NaN      NaN      NaN  ...                  NaN
22      NaN      NaN      NaN      NaN  ...                  NaN
23      NaN      NaN      NaN      NaN  ...                  NaN
24      NaN      NaN      NaN      NaN  ...                  NaN
25      NaN      NaN      NaN      NaN  ...                  NaN

   Unnamed: 895_level_0 Unnamed: 896_level_0 Unnamed: 897_level_0  \
   Unnamed: 895_level_1 Unnamed: 896_level_1 Unnamed: 897_level_1
0                   NaN                  NaN                  NaN
1                   NaN                  NaN                  NaN
2                   NaN                  NaN                  NaN
3                   NaN                  NaN                  NaN
4                   NaN                  NaN                  NaN
5                   NaN                  NaN                  NaN
6                   NaN                  NaN                  NaN
7                   NaN                  NaN                  NaN
8                   NaN                  NaN                  NaN
9                   NaN                  NaN                  NaN
10                  NaN                  NaN                  NaN
11                  NaN                  NaN                  NaN
12                  NaN                  NaN                  NaN
13                  NaN                  NaN                  NaN
14                  NaN                  NaN                  NaN
15                  NaN                  NaN                  NaN
16                  NaN                  NaN                  NaN
17                  NaN                  NaN                  NaN
18                  NaN                  NaN                  NaN
19                  NaN                  NaN                  NaN
20                  NaN                  NaN                  NaN
21                  NaN                  NaN                  NaN
22                  NaN                  NaN                  NaN
23                  NaN                  NaN                  NaN
24                  NaN                  NaN                  NaN
25                  NaN                  NaN                  NaN

   Unnamed: 898_level_0 Unnamed: 899_level_0 Unnamed: 900_level_0  \
   Unnamed: 898_level_1 Unnamed: 899_level_1 Unnamed: 900_level_1
0                   NaN                  NaN                  NaN
1                   NaN                  NaN                  NaN
2                   NaN                  NaN                  NaN
3                   NaN                  NaN                  NaN
4                   NaN                  NaN                  NaN
5                   NaN                  NaN                  NaN
6                   NaN                  NaN                  NaN
7                   NaN                  NaN                  NaN
8                   NaN                  NaN                  NaN
9                   NaN                  NaN                  NaN
10                  NaN                  NaN                  NaN
11                  NaN                  NaN                  NaN
12                  NaN                  NaN                  NaN
13                  NaN                  NaN                  NaN
14                  NaN                  NaN                  NaN
15                  NaN                  NaN                  NaN
16                  NaN                  NaN                  NaN
17                  NaN                  NaN                  NaN
18                  NaN                  NaN                  NaN
19                  NaN                  NaN                  NaN
20                  NaN                  NaN                  NaN
21                  NaN                  NaN                  NaN
22                  NaN                  NaN                  NaN
23                  NaN                  NaN                  NaN
24                  NaN                  NaN                  NaN
25                  NaN                  NaN                  NaN

   Unnamed: 901_level_0 Unnamed: 902_level_0 Unnamed: 903_level_0
   Unnamed: 901_level_1 Unnamed: 902_level_1 Unnamed: 903_level_1
0                   NaN                  NaN                  NaN
1                   NaN                  NaN                  NaN
2                   NaN                  NaN                  NaN
3                   NaN                  NaN                  NaN
4                   NaN                  NaN                  NaN
5                   NaN                  NaN                  NaN
6                   NaN                  NaN                  NaN
7                   NaN                  NaN                  NaN
8                   NaN                  NaN                  NaN
9                   NaN                  NaN                  NaN
10                  NaN                  NaN                  NaN
11                  NaN                  NaN                  NaN
12                  NaN                  NaN                  NaN
13                  NaN                  NaN                  NaN
14                  NaN                  NaN                  NaN
15                  NaN                  NaN                  NaN
16                  NaN                  NaN                  NaN
17                  NaN                  NaN                  NaN
18                  NaN                  NaN                  NaN
19                  NaN                  NaN                  NaN
20                  NaN                  NaN                  NaN
21                  NaN                  NaN                  NaN
22                  NaN                  NaN                  NaN
23                  NaN                  NaN                  NaN
24                  NaN                  NaN                  NaN
25                  NaN                  NaN                  NaN

[26 rows x 904 columns]

In [ ]:
tyson_row = df[df[('Unnamed: 0_level_0', 'Episode')] == 'Tyson']
print(tyson_row)

  Unnamed: 0_level_0 Original tribes                                          \
             Episode               1       1.1  1.2  1.3    2    3  3.1    4
6              Tyson             NaN  Laura M.  NaN  NaN  NaN  NaN  NaN  NaN

        ... Unnamed: 894_level_0 Unnamed: 895_level_0 Unnamed: 896_level_0  \
   4.1  ... Unnamed: 894_level_1 Unnamed: 895_level_1 Unnamed: 896_level_1
6  NaN  ...                  NaN                  NaN                  NaN

  Unnamed: 897_level_0 Unnamed: 898_level_0 Unnamed: 899_level_0  \
  Unnamed: 897_level_1 Unnamed: 898_level_1 Unnamed: 899_level_1
6                  NaN                  NaN                  NaN

  Unnamed: 900_level_0 Unnamed: 901_level_0 Unnamed: 902_level_0  \
  Unnamed: 900_level_1 Unnamed: 901_level_1 Unnamed: 902_level_1
6                  NaN                  NaN                  NaN

  Unnamed: 903_level_0
  Unnamed: 903_level_1
6                  NaN

[1 rows x 904 columns]

## Survivor 28

In [ ]:
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
}

r = requests.get('https://en.wikipedia.org/wiki/Survivor:_Cagayan', headers=headers)
html_contents = r.text
html_soup = BeautifulSoup(html_contents,"lxml")

In [ ]:
tables = html_soup.find_all('table',class_="wikitable")
tables[0].find_all('a')

[<a href="/wiki/David_Samson_(baseball)" title="David Samson (baseball)">David Samson</a>,
 <a href="/wiki/Plantation,_Florida" title="Plantation, Florida">Plantation,<br/>Florida</a>,
 <a href="/wiki/Garrett_Adelstein" title="Garrett Adelstein">Garrett Adelstein</a>,
 <a href="/wiki/Santa_Monica,_California" title="Santa Monica, California">Santa Monica,<br/>California</a>,
 <a href="/wiki/Philadelphia" title="Philadelphia">Philadelphia,<br/>Pennsylvania</a>,
 <a href="/wiki/J%27Tia_Hart" title="J'Tia Hart">J'Tia Taylor</a>,
 <a href="/wiki/Chicago" title="Chicago">Chicago,<br/>Illinois</a>,
 <a href="/wiki/Clifford_Robinson_(basketball,_born_1966)" title="Clifford Robinson (basketball, born 1966)">Cliff Robinson</a>,
 <a href="/wiki/Buffalo,_New_York" title="Buffalo, New York">Buffalo,<br/>New York</a>,
 <a href="/wiki/Kokomo,_Indiana" title="Kokomo, Indiana">Kokomo,<br/>Indiana</a>,
 <a href="/wiki/Addison,_Illinois" title="Addison, Illinois">Addison,<br/>Illinois</a>,
 <a href="/wiki/Sarah_Lacina" title="Sarah Lacina">Sarah Lacina</a>,
 <a href="/wiki/Cedar_Rapids,_Iowa" title="Cedar Rapids, Iowa">Cedar Rapids,<br/>Iowa</a>,
 <a href="/wiki/San_Jose,_California" title="San Jose, California">San Jose,<br/>California</a>,
 <a href="/wiki/Boston" title="Boston">Boston,<br/>Massachusetts</a>,
 <a href="/wiki/Dobson,_North_Carolina" title="Dobson, North Carolina">Dobson,<br/>North Carolina</a>,
 <a href="/wiki/Campbellsville,_Kentucky" title="Campbellsville, Kentucky">Campbellsville,<br/>Kentucky</a>,
 <a href="/wiki/St._Louis" title="St. Louis">St. Louis,<br/>Missouri</a>,
 <a href="/wiki/Needham,_Massachusetts" title="Needham, Massachusetts">Needham,<br/>Massachusetts</a>,
 <a href="/wiki/Chicago" title="Chicago">Chicago,<br/>Illinois</a>,
 <a href="/wiki/Tehachapi,_California" title="Tehachapi, California">Tehachapi,<br/>California</a>,
 <a href="/wiki/Newport_Beach,_California" title="Newport Beach, California">Newport Beach,<br/>California</a>,
 <a href="/wiki/Tony_Vlachos" title="Tony Vlachos">Tony Vlachos</a>,
 <a href="/wiki/Jersey_City,_New_Jersey" title="Jersey City, New Jersey">Jersey City,<br/>New Jersey</a>]

In [ ]:
df = pd.read_html(str(tables))[3]
df

/tmp/ipykernel_3126/1238544221.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(tables))[3]

   Unnamed: 0_level_0 Original tribes                                     \
              Episode               1      1.1       2      2.1        3
0                 Day               3        6       8        8       11
1               Tribe           Luzon    Luzon  Solana   Solana    Luzon
2          Eliminated           David  Garrett  Tie[a]    Brice    J'Tia
3               Votes             4–2      3–2   2–2–2    3–0–0      3–1
4                 NaN             NaN      NaN     NaN      NaN      NaN
5               Voter            Vote     Vote    Vote     Vote     Vote
6                Tony             NaN      NaN     NaN      NaN      NaN
7                 Woo             NaN      NaN     NaN      NaN      NaN
8                Kass           J'Tia  Garrett     NaN      NaN    J'Tia
9             Spencer           David    J'Tia     NaN      NaN    J'Tia
10              Trish             NaN      NaN     NaN      NaN      NaN
11              Tasha           David  Garrett     NaN      NaN    J'Tia
12              Jefra             NaN      NaN   Brice    Brice      NaN
13           Jeremiah             NaN      NaN  Morgan    Brice      NaN
14                 LJ             NaN      NaN  Morgan    Brice      NaN
15             Morgan             NaN      NaN  Alexis  None[d]      NaN
16              Sarah             NaN      NaN     NaN      NaN      NaN
17             Alexis             NaN      NaN   Brice  None[d]      NaN
18            Lindsey             NaN      NaN     NaN      NaN      NaN
19              Cliff             NaN      NaN     NaN      NaN      NaN
20              J'Tia           David  Garrett     NaN      NaN  Spencer
21              Brice             NaN      NaN  Alexis  None[d]      NaN
22            Garrett           David    J'Tia     NaN      NaN      NaN
23              David           J'Tia      NaN     NaN      NaN      NaN

   Switched tribes                    Merged tribe                        \
                 4        5       5.1            6          7          8
0               14       14        16           19         22         25
1           Solana   Solana    Aparri    Solarrion  Solarrion  Solarrion
2            Cliff  Lindsey    Alexis        Sarah     Morgan         LJ
3              4–3  Quit[b]       6–1          6–5        6–4      5–3–1
4              NaN      NaN       NaN          NaN        NaN        NaN
5             Vote     Vote      Vote         Vote       Vote       Vote
6            Cliff      NaN       NaN        Sarah     Morgan         LJ
7               LJ      NaN       NaN        Sarah     Morgan         LJ
8              NaN      NaN    Alexis        Sarah     Morgan   Jeremiah
9              NaN      NaN    Alexis        Jefra       Tony         LJ
10           Cliff      NaN       NaN        Sarah     Morgan   Jeremiah
11             NaN      NaN    Alexis        Jefra       Tony         LJ
12           Cliff      NaN       NaN        Sarah     Morgan   Jeremiah
13             NaN      NaN    Alexis        Jefra       Tony         LJ
14           Cliff      NaN       NaN        Sarah     Morgan    Spencer
15             NaN      NaN    Alexis        Jefra       Tony        NaN
16             NaN      NaN    Alexis        Jefra        NaN        NaN
17             NaN      NaN  Jeremiah          NaN        NaN        NaN
18              LJ     Quit       NaN          NaN        NaN        NaN
19              LJ      NaN       NaN          NaN        NaN        NaN
20             NaN      NaN       NaN          NaN        NaN        NaN
21             NaN      NaN       NaN          NaN        NaN        NaN
22             NaN      NaN       NaN          NaN        NaN        NaN
23             NaN      NaN       NaN          NaN        NaN        NaN

                                                                      \
            9         10         11         12         13       13.1
0          28         30         33         36         37         38
1   Solarrion  Solarrion  Solarrion  Solarrion  Solarrion  Solarrion
2    Jeremiah      Jefra      Tasha      Trish    Spencer       Kass
3         5–3        4–3      4–1–1        4–1        3–1        1–0
4         NaN        NaN        NaN        NaN        NaN        NaN
5        Vote       Vote       Vote       Vote       Vote       Vote
6    Jeremiah      Jefra      Tasha      Trish    Spencer    None[c]
7    Jeremiah      Jefra      Tasha      Trish    Spencer       Kass
8    Jeremiah    Spencer      Tasha      Trish    Spencer    None[c]
9         Woo      Jefra       Tony      Trish        Woo        NaN
10   Jeremiah    Spencer      Tasha       Kass        NaN        NaN
11        Woo      Jefra      Trish        NaN        NaN        NaN
12   Jeremiah    Spencer        NaN        NaN        NaN        NaN
13        Woo        NaN        NaN        NaN        NaN        NaN
14        NaN        NaN        NaN        NaN        NaN        NaN
15        NaN        NaN        NaN        NaN        NaN        NaN
16        NaN        NaN        NaN        NaN        NaN        NaN
17        NaN        NaN        NaN        NaN        NaN        NaN
18        NaN        NaN        NaN        NaN        NaN        NaN
19        NaN        NaN        NaN        NaN        NaN        NaN
20        NaN        NaN        NaN        NaN        NaN        NaN
21        NaN        NaN        NaN        NaN        NaN        NaN
22        NaN        NaN        NaN        NaN        NaN        NaN
23        NaN        NaN        NaN        NaN        NaN        NaN


   Unnamed: 18_level_1 Unnamed: 19_level_1
0                  NaN                 NaN
1                  NaN                 NaN
2                  NaN                 NaN
3                  NaN                 NaN
4                  NaN                 NaN
5                  NaN                 NaN
6                  NaN                 NaN
7                  NaN                 NaN
8                  NaN                 NaN
9                  NaN                 NaN
10                 NaN                 NaN
11                 NaN                 NaN
12                 NaN                 NaN
13                 NaN                 NaN
14                 NaN                 NaN
15                 NaN                 NaN
16                 NaN                 NaN
17                 NaN                 NaN
18                 NaN                 NaN
19                 NaN                 NaN
20                 NaN                 NaN
21                 NaN                 NaN
22                 NaN                 NaN
23                 NaN                 NaN

In [ ]:
tony_row = df[df[('Unnamed: 0_level_0', 'Episode')] == 'Tony']
print(tony_row)

  Unnamed: 0_level_0 Original tribes                     Switched tribes       \
             Episode               1  1.1    2  2.1    3               4    5
6               Tony             NaN  NaN  NaN  NaN  NaN           Cliff  NaN

       Merged tribe                                                      \
   5.1            6       7   8         9     10     11     12       13
6  NaN        Sarah  Morgan  LJ  Jeremiah  Jefra  Tasha  Trish  Spencer


      13.1 Unnamed: 18_level_1 Unnamed: 19_level_1
6  None[c]                 NaN                 NaN

## Survivor 29

In [ ]:
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
}

r = requests.get('https://en.wikipedia.org/wiki/Survivor:_San_Juan_del_Sur', headers=headers)
html_contents = r.text
html_soup = BeautifulSoup(html_contents,"lxml")

In [ ]:
tables = html_soup.find_all('table',class_="wikitable")
tables[0].find_all('a')

[<a class="mw-redirect" href="/wiki/Natalie_and_Nadiya_Anderson" title="Natalie and Nadiya Anderson">Nadiya Anderson</a>,
 <a href="/wiki/Edgewater,_New_Jersey" title="Edgewater, New Jersey">Edgewater,<br/>New Jersey</a>,
 <a href="/wiki/Foxborough,_Massachusetts" title="Foxborough, Massachusetts">Foxboro,<br/>Massachusetts</a>,
 <a href="/wiki/John_Rocker" title="John Rocker">John Rocker</a>,
 <a href="/wiki/Atlanta" title="Atlanta">Atlanta,<br/>Georgia</a>,
 <a href="/wiki/Winter_Park,_Florida" title="Winter Park, Florida">Winter Park,<br/>Florida</a>,
 <a href="/wiki/Seattle" title="Seattle">Seattle,<br/>Washington</a>,
 <a href="/wiki/Ephrata,_Washington" title="Ephrata, Washington">Ephrata,<br/>Washington</a>,
 <a href="/wiki/Atlanta" title="Atlanta">Atlanta,<br/>Georgia</a>,
 <a href="/wiki/New_York_City" title="New York City">New York,<br/>New York</a>,
 <a href="/wiki/Jeremy_Collins" title="Jeremy Collins">Jeremy Collins</a>,
 <a href="/wiki/Foxborough,_Massachusetts" title="Foxborough, Massachusetts">Foxboro,<br/>Massachusetts</a>,
 <a href="/wiki/Shreveport,_Louisiana" title="Shreveport, Louisiana">Shreveport,<br/>Louisiana</a>,
 <a href="/wiki/New_York_City" title="New York City">New York,<br/>New York</a>,
 <a href="/wiki/Winter_Park,_Florida" title="Winter Park, Florida">Winter Park,<br/>Florida</a>,
 <a href="/wiki/Waterford_Township,_Michigan" title="Waterford Township, Michigan">Waterford,<br/>Michigan</a>,
 <a href="/wiki/Nashville,_Tennessee" title="Nashville, Tennessee">Nashville,<br/>Tennessee</a>,
 <a href="/wiki/Shreveport,_Louisiana" title="Shreveport, Louisiana">Shreveport,<br/>Louisiana</a>,
 <a href="/wiki/Dallas" title="Dallas">Dallas,<br/>Texas</a>,
 <a href="/wiki/Las_Vegas" title="Las Vegas">Las Vegas,<br/>Nevada</a>,
 <a class="mw-redirect" href="/wiki/Natalie_and_Nadiya_Anderson" title="Natalie and Nadiya Anderson">Natalie Anderson</a>,
 <a href="/wiki/Edgewater,_New_Jersey" title="Edgewater, New Jersey">Edgewater,<br/>New Jersey</a>]

In [ ]:
df = pd.read_html(str(tables))[3]
df

/tmp/ipykernel_3126/1238544221.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(tables))[3]

   Unnamed: 0_level_0 Original tribes                                    \
              Episode               1       2      2.1       3        4
0                 Day               3       6        6       8       10
1               Tribe          Coyopa  Coyopa   Coyopa  Coyopa  Hunahpu
2          Eliminated          Nadiya  Tie[a]      Val    John     Drew
3               Votes           5–3–1     4–4      5–1     5–2  5–2–1–1
4                 NaN             NaN     NaN      NaN     NaN      NaN
5               Voter            Vote    Vote     Vote    Vote     Vote
6             Natalie             NaN     NaN      NaN     NaN     Drew
7              Jaclyn            Dale  Baylor   Baylor    John      NaN
8               Missy             NaN     NaN      NaN     NaN     Drew
9               Keith             NaN     NaN      NaN     NaN    Julie
10             Baylor          Nadiya     Val  None[f]    John      NaN
11                Jon             NaN     NaN      NaN     NaN    Keith
12               Alec          Nadiya     Val      Val    John      NaN
13               Reed             NaN     NaN      NaN     NaN    Julie
14                Wes          Nadiya     Val      Val    John      NaN
15             Jeremy             NaN     NaN      NaN     NaN     Drew
16               Josh          Baylor     Val      Val    John      NaN
17              Julie             NaN     NaN      NaN     NaN     Drew
18               Dale          Nadiya  Baylor      Val  Baylor      NaN
19             Kelley             NaN     NaN      NaN     NaN     Drew
20               Drew             NaN     NaN      NaN     NaN   Kelley
21               John          Nadiya  Baylor      Val  Baylor      NaN
22                Val            Dale  Baylor  None[f]     NaN      NaN
23             Nadiya            Dale     NaN      NaN     NaN      NaN

   Switched tribes         Merged tribe          ...                    \
                 5       6            7       8  ...        10      11
0               13      15           18      21  ...        26      29
1           Coyopa  Coyopa       Huyopa  Huyopa  ...    Huyopa  Huyopa
2           Kelley    Dale        Julie    Josh  ...       Wes    Reed
3            3–2–2   3–2–1      Quit[b]     6–5  ...  2–0–0[c]     7–1
4              NaN     NaN          NaN     NaN  ...       NaN     NaN
5             Vote    Vote         Vote    Vote  ...      Vote    Vote
6              NaN     NaN          NaN    Josh  ...     Keith    Reed
7           Kelley    Dale          NaN    Josh  ...       Wes    Reed
8           Kelley   Keith          NaN    Josh  ...     Keith    Reed
9             Dale    Dale          NaN  Baylor  ...       Jon    Reed
10          Kelley   Keith          NaN    Josh  ...     Keith    Reed
11            Dale    Dale          NaN    Josh  ...       Wes    Reed
12             NaN     NaN          NaN  Baylor  ...       Jon    Reed
13             NaN     NaN          NaN  Baylor  ...       Jon   Missy
14             NaN     NaN          NaN  Baylor  ...       Jon     NaN
15             NaN     NaN          NaN    Josh  ...       NaN     NaN
16             NaN     NaN          NaN  Baylor  ...       NaN     NaN
17             NaN     NaN         Quit     NaN  ...       NaN     NaN
18          Baylor   Missy          NaN     NaN  ...       NaN     NaN
19          Baylor     NaN          NaN     NaN  ...       NaN     NaN
20             NaN     NaN          NaN     NaN  ...       NaN     NaN
21             NaN     NaN          NaN     NaN  ...       NaN     NaN
22             NaN     NaN          NaN     NaN  ...       NaN     NaN
23             NaN     NaN          NaN     NaN  ...       NaN     NaN

                                            Unnamed: 18_level_0  \
        12      13     13.1      14    14.1 Unnamed: 18_level_1
0       32      35       35      37      38                 NaN
1   Huyopa  Huyopa   Huyopa  Huyopa  Huyopa                 NaN
2     Alec  Tie[a]      Jon  Baylor   Keith                 NaN
3      4–3   2–2–2    2–1–0  2–0[d]     3–1                 NaN
4      NaN     NaN      NaN     NaN     NaN                 NaN
5     Vote    Vote     Vote    Vote    Vote                 NaN
6     Alec     Jon      Jon  Baylor   Keith                 NaN
7    Keith   Keith  None[e]  Baylor   Keith                 NaN
8     Alec  Jaclyn   Jaclyn  Jaclyn   Keith                 NaN
9     Alec     Jon  None[e]  Jaclyn   Missy                 NaN
10    Alec  Jaclyn      Jon  Jaclyn     NaN                 NaN
11   Keith   Keith  None[e]     NaN     NaN                 NaN
12   Keith     NaN      NaN     NaN     NaN                 NaN
13     NaN     NaN      NaN     NaN     NaN                 NaN
14     NaN     NaN      NaN     NaN     NaN                 NaN
15     NaN     NaN      NaN     NaN     NaN                 NaN
16     NaN     NaN      NaN     NaN     NaN                 NaN
17     NaN     NaN      NaN     NaN     NaN                 NaN
18     NaN     NaN      NaN     NaN     NaN                 NaN
19     NaN     NaN      NaN     NaN     NaN                 NaN
20     NaN     NaN      NaN     NaN     NaN                 NaN
21     NaN     NaN      NaN     NaN     NaN                 NaN
22     NaN     NaN      NaN     NaN     NaN                 NaN
23     NaN     NaN      NaN     NaN     NaN                 NaN

   Unnamed: 19_level_0 Unnamed: 20_level_0
   Unnamed: 19_level_1 Unnamed: 20_level_1
0                  NaN                 NaN
1                  NaN                 NaN
2                  NaN                 NaN
3                  NaN                 NaN
4                  NaN                 NaN
5                  NaN                 NaN
6                  NaN                 NaN
7                  NaN                 NaN
8                  NaN                 NaN
9                  NaN                 NaN
10                 NaN                 NaN
11                 NaN                 NaN
12                 NaN                 NaN
13                 NaN                 NaN
14                 NaN                 NaN
15                 NaN                 NaN
16                 NaN                 NaN
17                 NaN                 NaN
18                 NaN                 NaN
19                 NaN                 NaN
20                 NaN                 NaN
21                 NaN                 NaN
22                 NaN                 NaN
23                 NaN                 NaN

[24 rows x 21 columns]

In [ ]:
natalieA_row = df[df[('Unnamed: 0_level_0', 'Episode')] == 'Natalie']
print(natalieA_row)

  Unnamed: 0_level_0 Original tribes                      Switched tribes  \
             Episode               1    2  2.1    3     4               5
6            Natalie             NaN  NaN  NaN  NaN  Drew             NaN

       Merged tribe        ...                                              \
     6            7     8  ...     10    11    12   13 13.1      14   14.1
6  NaN          NaN  Josh  ...  Keith  Reed  Alec  Jon  Jon  Baylor  Keith

  Unnamed: 18_level_0 Unnamed: 19_level_0 Unnamed: 20_level_0
  Unnamed: 18_level_1 Unnamed: 19_level_1 Unnamed: 20_level_1
6                 NaN                 NaN                 NaN

[1 rows x 21 columns]

## Survivor 30

In [ ]:
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
}

r = requests.get('https://en.wikipedia.org/wiki/Survivor:_Worlds_Apart', headers=headers)
html_contents = r.text
html_soup = BeautifulSoup(html_contents,"lxml")

In [ ]:
tables = html_soup.find_all('table',class_="wikitable")
tables[0].find_all('a')

[<a href="/wiki/Long_Beach,_California" title="Long Beach, California">Long Beach,<br/>California</a>,
 <a href="/wiki/Santa_Monica,_California" title="Santa Monica, California">Santa Monica,<br/>California</a>,
 <a href="/wiki/Palmdale,_California" title="Palmdale, California">Palmdale,<br/>California</a>,
 <a href="/wiki/College_Park_(Orlando)" title="College Park (Orlando)">College Park,<br/>Florida</a>,
 <a href="/wiki/Topanga,_California" title="Topanga, California">Topanga,<br/>California</a>,
 <a href="/wiki/Valley_Stream,_New_York" title="Valley Stream, New York">Valley Stream,<br/>New York</a>,
 <a href="/wiki/Grand_Island,_New_York" title="Grand Island, New York">Grand Island,<br/>New York</a>,
 <a href="/wiki/San_Francisco" title="San Francisco">San Francisco,<br/>California</a>,
 <a href="/wiki/Scottsdale,_Arizona" title="Scottsdale, Arizona">Scottsdale,<br/>Arizona</a>,
 <a href="/wiki/Long_Beach,_California" title="Long Beach, California">Long Beach,<br/>California</a>,
 <a href="/wiki/San_Francisco" title="San Francisco">San Francisco,<br/>California</a>,
 <a href="/wiki/Tyler_Fredrickson" title="Tyler Fredrickson">Tyler Fredrickson</a>,
 <a href="/wiki/Los_Angeles" title="Los Angeles">Los Angeles,<br/>California</a>,
 <a href="/wiki/Gorham,_Maine" title="Gorham, Maine">Gorham,<br/>Maine</a>,
 <a href="/wiki/Roy,_Utah" title="Roy, Utah">Roy,<br/>Utah</a>,
 <a href="/wiki/Boston" title="Boston">Boston,<br/>Massachusetts</a>,
 <a href="/wiki/Sherman_Oaks,_Los_Angeles" title="Sherman Oaks, Los Angeles">Sherman Oaks,<br/> California</a>,
 <a href="/wiki/Tampa,_Florida" title="Tampa, Florida">Tampa,<br/>Florida</a>,
 <a href="/wiki/North_Richland_Hills,_Texas" title="North Richland Hills, Texas"><span class="nowrap">North Richland Hills</span>,<br/>Texas</a>]

In [ ]:
df = pd.read_html(str(tables))[3]
df

/tmp/ipykernel_3126/1238544221.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(tables))[3]

   Unnamed: 0_level_0 Original tribes                                          \
              Episode               1         2         3         4       4.1
0                 Day               3         6         8        11        11
1               Tribe          Masaya  Nagarote  Nagarote  Escameca  Escameca
2          Eliminated              So     Vince      Nina    Tie[a]   Lindsey
3               Votes             4–2     3–2–1       3–2     2–2–2     3–0–0
4                 NaN             NaN       NaN       NaN       NaN       NaN
5               Voter            Vote      Vote      Vote      Vote      Vote
6                Mike             NaN       NaN       NaN   Lindsey   Lindsey
7             Carolyn              So       NaN       NaN       NaN       NaN
8                Will             NaN     Vince      Nina       NaN       NaN
9              Rodney             NaN       NaN       NaN    Sierra   None[g]
10             Sierra             NaN       NaN       NaN    Rodney   None[g]
11                Dan             NaN       NaN       NaN   Lindsey   Lindsey
12              Tyler              So       NaN       NaN       NaN       NaN
13             Shirin              So       NaN       NaN       NaN       NaN
14               Jenn             NaN     Vince      Nina       NaN       NaN
15                Joe             NaN      Nina      Nina       NaN       NaN
16               Hali             NaN     Vince      Will       NaN       NaN
17              Kelly             NaN       NaN       NaN    Sierra   Lindsey
18            Joaquin         Carolyn       NaN       NaN       NaN       NaN
19                Max              So       NaN       NaN       NaN       NaN
20            Lindsey             NaN       NaN       NaN    Rodney   None[g]
21               Nina             NaN      Jenn      Will       NaN       NaN
22              Vince             NaN      Jenn       NaN       NaN       NaN
23                 So         Carolyn       NaN       NaN       NaN       NaN

   Switched tribes           Merged tribe          ...                  \
                 5         6            7       8  ...      11      12
0               14        16           19      22  ...      29      32
1         Nagarote  Escameca       Merica  Merica  ...  Merica  Merica
2              Max   Joaquin        Kelly    Hali  ...  Shirin   Tyler
3              5–2       4–3     4–1–0[c]     7–4  ...   4–2–2  3–0[d]
4              NaN       NaN          NaN     NaN  ...     NaN     NaN
5             Vote      Vote         Vote    Vote  ...    Vote    Vote
6              NaN   Joaquin         Jenn    Hali  ...   Tyler   Tyler
7              Max       NaN         Jenn    Hali  ...  Shirin   Tyler
8              Max       NaN         Hali    Hali  ...     Dan    Mike
9              NaN       Joe         Jenn    Hali  ...  Shirin    Mike
10             NaN   Joaquin         Jenn    Hali  ...  Shirin   Tyler
11             NaN   Joaquin         Jenn    Hali  ...  Shirin    Mike
12             NaN       Joe         Jenn    Hali  ...     Dan    Mike
13            Will       NaN        Kelly     Dan  ...   Tyler     NaN
14             Max       NaN        Kelly     Dan  ...     NaN     NaN
15             NaN   Joaquin        Kelly     Dan  ...     NaN     NaN
16             Max       NaN        Kelly     Dan  ...     NaN     NaN
17             Max       NaN         Jenn     NaN  ...     NaN     NaN
18             NaN       Joe          NaN     NaN  ...     NaN     NaN
19            Will       NaN          NaN     NaN  ...     NaN     NaN
20             NaN       NaN          NaN     NaN  ...     NaN     NaN
21             NaN       NaN          NaN     NaN  ...     NaN     NaN
22             NaN       NaN          NaN     NaN  ...     NaN     NaN
23             NaN       NaN          NaN     NaN  ...     NaN     NaN

                                                                            \
         13        13.1      14     14.1          14.2 Unnamed: 19_level_1
0        35          35      37       38            38                 NaN
1    Merica      Merica  Merica   Merica        Merica                 NaN
2       Dan         Dan  Sierra   Tie[b]        Rodney                 NaN
3    2–0[e]      2–0[e]     4–1      2–2  Challenge[f]                 NaN
4       NaN         NaN     NaN      NaN           NaN                 NaN
5      Vote        Vote    Vote     Vote          Vote                Vote
6       Dan         Dan  Sierra   Rodney           NaN                 NaN
7       Dan         Dan  Sierra   Rodney        Won[f]                 NaN
8   Carolyn     Carolyn  Sierra  Carolyn           NaN                 NaN
9   Carolyn     Carolyn  Sierra  Carolyn       Lost[f]                 NaN
10  Carolyn     Carolyn  Rodney      NaN           NaN                 NaN
11  Carolyn  Carolyn[h]     NaN      NaN           NaN                 NaN
12      NaN         NaN     NaN      NaN           NaN                 NaN
13      NaN         NaN     NaN      NaN           NaN                 NaN
14      NaN         NaN     NaN      NaN           NaN                 NaN
15      NaN         NaN     NaN      NaN           NaN                 NaN
16      NaN         NaN     NaN      NaN           NaN                 NaN
17      NaN         NaN     NaN      NaN           NaN                 NaN
18      NaN         NaN     NaN      NaN           NaN                 NaN
19      NaN         NaN     NaN      NaN           NaN                 NaN
20      NaN         NaN     NaN      NaN           NaN                 NaN
21      NaN         NaN     NaN      NaN           NaN                 NaN
22      NaN         NaN     NaN      NaN           NaN                 NaN
23      NaN         NaN     NaN      NaN           NaN                 NaN

   Unnamed: 20_level_0 Unnamed: 21_level_0
   Unnamed: 20_level_1 Unnamed: 21_level_1
0                  NaN                 NaN
1                  NaN                 NaN
2                  NaN                 NaN
3                  NaN                 NaN
4                  NaN                 NaN
5                  NaN                 NaN
6                  NaN                 NaN
7                  NaN                 NaN
8                  NaN                 NaN
9                  NaN                 NaN
10                 NaN                 NaN
11                 NaN                 NaN
12                 NaN                 NaN
13                 NaN                 NaN
14                 NaN                 NaN
15                 NaN                 NaN
16                 NaN                 NaN
17                 NaN                 NaN
18                 NaN                 NaN
19                 NaN                 NaN
20                 NaN                 NaN
21                 NaN                 NaN
22                 NaN                 NaN
23                 NaN                 NaN

[24 rows x 22 columns]

In [ ]:
mike_row = df[df[('Unnamed: 0_level_0', 'Episode')] == 'Mike']
print(mike_row)

  Unnamed: 0_level_0 Original tribes                              \
             Episode               1    2    3        4      4.1
6               Mike             NaN  NaN  NaN  Lindsey  Lindsey

  Switched tribes          Merged tribe        ...                          \
                5        6            7     8  ...     11     12   13 13.1
6             NaN  Joaquin         Jenn  Hali  ...  Tyler  Tyler  Dan  Dan

                                           Unnamed: 20_level_0  \
       14    14.1 14.2 Unnamed: 19_level_1 Unnamed: 20_level_1
6  Sierra  Rodney  NaN                 NaN                 NaN

  Unnamed: 21_level_0
  Unnamed: 21_level_1
6                 NaN

[1 rows x 22 columns]

## Survivor 31

In [ ]:
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
}

r = requests.get('https://en.wikipedia.org/wiki/Survivor:_Cambodia', headers=headers)
html_contents = r.text
html_soup = BeautifulSoup(html_contents,"lxml")

In [ ]:
tables = html_soup.find_all('table',class_="wikitable")
tables[0].find_all('a')

[<a href="/wiki/Jackson,_Georgia" title="Jackson, Georgia">Jackson, Georgia</a>,
 <a href="/wiki/Survivor:_Africa" title="Survivor: Africa"><i>Africa</i></a>,
 <a href="/wiki/Brad_Culpepper" title="Brad Culpepper">Brad Culpepper</a>,
 <a href="#cite_note-gc-14"><span class="cite-bracket">[</span>a<span class="cite-bracket">]</span></a>,
 <a href="/wiki/Tampa,_Florida" title="Tampa, Florida">Tampa, Florida</a>,
 <a href="/wiki/Survivor:_Blood_vs._Water" title="Survivor: Blood vs. Water"><i>Blood vs. Water</i></a>,
 <a href="/wiki/Topanga,_California" title="Topanga, California">Topanga, California</a>,
 <a href="/wiki/Survivor:_Worlds_Apart" title="Survivor: Worlds Apart"><i>Worlds Apart</i></a>,
 <a class="mw-redirect" href="/wiki/Mike_Holloway_(Survivor_contestant)" title="Mike Holloway (Survivor contestant)">Mike Holloway</a>,
 <a href="#cite_note-15"><span class="cite-bracket">[</span>b<span class="cite-bracket">]</span></a>,
 <a href="/wiki/Fort_Worth,_Texas" title="Fort Worth, Texas">Fort Worth, Texas</a>,
 <a href="/wiki/Survivor:_Worlds_Apart" title="Survivor: Worlds Apart"><i>Worlds Apart</i></a>,
 <a href="/wiki/Los_Angeles" title="Los Angeles">Los Angeles, California</a>,
 <a href="/wiki/Survivor:_Panama" title="Survivor: Panama"><i>Panama</i></a>,
 <a href="/wiki/Denver" title="Denver">Denver, Colorado</a>,
 <a href="/wiki/Survivor:_South_Pacific" title="Survivor: South Pacific"><i>South Pacific</i></a>,
 <a href="/wiki/Queens" title="Queens">Queens, New York</a>,
 <a href="/wiki/Survivor:_Worlds_Apart" title="Survivor: Worlds Apart"><i>Worlds Apart</i></a>,
 <a class="mw-redirect" href="/wiki/Troy_%22Troyzan%22_Robertson" title='Troy "Troyzan" Robertson'>Troy "Troyzan" Robertson</a>,
 <a href="#cite_note-gc-14"><span class="cite-bracket">[</span>a<span class="cite-bracket">]</span></a>,
 <a href="/wiki/Miami" title="Miami">Miami, Florida</a>,
 <a href="/wiki/Survivor:_One_World" title="Survivor: One World"><i>One World</i></a>,
 <a href="/wiki/Studio_City,_Los_Angeles" title="Studio City, Los Angeles">Studio City, California</a>,
 <a href="/wiki/Survivor:_Redemption_Island" title="Survivor: Redemption Island"><i>Redemption Island</i></a>,
 <a href="/wiki/Brooklyn" title="Brooklyn">Brooklyn, New York</a>,
 <a href="/wiki/Survivor:_One_World" title="Survivor: One World"><i>One World</i></a>,
 <a href="/wiki/San_Diego" title="San Diego">San Diego, California</a>,
 <a href="/wiki/Survivor:_Redemption_Island" title="Survivor: Redemption Island"><i>Redemption Island</i></a>,
 <a href="/wiki/Miami" title="Miami">Miami, Florida</a>,
 <a href="/wiki/Survivor:_South_Pacific" title="Survivor: South Pacific"><i>South Pacific</i></a>]

In [ ]:
df = pd.read_html(str(tables))[4]
df

/tmp/ipykernel_3126/2242639312.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(tables))[4]

   Unnamed: 0_level_0 Original tribes          First switch                   \
              Episode               1        2            3       4        5
0                 Day               3        6            9      11       13
1               Tribe          Ta Keo   Ta Keo       Angkor  Angkor    Bayon
2          Eliminated           Vytas   Shirin     Peih-Gee    Jeff   Monica
3               Votes             6–4      5–4          4–2     4–1    3–2–1
4                 NaN             NaN      NaN          NaN     NaN      NaN
5               Voter            Vote     Vote         Vote    Vote     Vote
6              Jeremy             NaN      NaN          NaN     NaN   Monica
7             Spencer           Vytas   Shirin          NaN     NaN    Kelly
8               Tasha             NaN      NaN     Peih-Gee    Jeff      NaN
9              Kelley           Vytas  Spencer          NaN     NaN      NaN
10              Keith             NaN      NaN          NaN     NaN      NaN
11              Kimmi             NaN      NaN          NaN     NaN   Monica
12          Abi-Maria           Vytas  Spencer     Peih-Gee    Jeff      NaN
13                Joe             NaN      NaN          NaN     NaN      NaN
14            Stephen             NaN      NaN          NaN     NaN   Monica
15              Ciera             NaN      NaN          NaN     NaN      NaN
16              Kelly       Abi-Maria   Shirin          NaN     NaN  Spencer
17             Andrew             NaN      NaN     Peih-Gee    Jeff      NaN
18               Kass             NaN      NaN          NaN     NaN      NaN
19                Woo       Abi-Maria   Shirin    Abi-Maria    Jeff      NaN
20              Terry       Abi-Maria  Spencer          NaN     NaN      NaN
21             Monica             NaN      NaN          NaN     NaN    Kelly
22               Jeff           Vytas   Shirin     Peih-Gee     Woo      NaN
23           Peih-Gee           Vytas   Shirin    Abi-Maria     NaN      NaN
24             Shirin           Vytas  Spencer          NaN     NaN      NaN
25              Vytas       Abi-Maria      NaN          NaN     NaN      NaN

                Second switch Merged tribe          ...                        \
              6             6            7       8  ...         12         13
0            13            16           19      21  ...         32         35
1        Ta Keo        Ta Keo        Orkun   Orkun  ...      Orkun      Orkun
2         Terry           Woo         Kass  Andrew  ...        Joe  Abi-Maria
3   Withdrew[c]           4–3      6–4–2–1  3–0[d]  ...      6–1–1      4–2–1
4           NaN           NaN          NaN     NaN  ...        NaN        NaN
5          Vote          Vote         Vote    Vote  ...       Vote       Vote
6           NaN           NaN        Ciera  Kelley  ...        Joe  Abi-Maria
7           NaN           Woo        Ciera  Kelley  ...        Joe  Abi-Maria
8           NaN           NaN         Kass  Kelley  ...        Joe  Abi-Maria
9           NaN           NaN         Kass  Andrew  ...        Joe      Tasha
10          NaN           NaN         Kass  Kelley  ...      Tasha      Tasha
11          NaN           NaN         Kass  Kelley  ...        Joe  Abi-Maria
12          NaN           Woo        Tasha  Andrew  ...        Joe      Keith
13          NaN           NaN        Ciera  Kelley  ...  Abi-Maria        NaN
14          NaN           NaN         Kass  Kelley  ...        NaN        NaN
15          NaN           Woo       Andrew  Andrew  ...        NaN        NaN
16          NaN       Spencer        Ciera  Kelley  ...        NaN        NaN
17          NaN       Spencer         Kass  Kelley  ...        NaN        NaN
18          NaN           Woo        Tasha     NaN  ...        NaN        NaN
19          NaN       Spencer          NaN     NaN  ...        NaN        NaN
20     Withdrew           NaN          NaN     NaN  ...        NaN        NaN
21          NaN           NaN          NaN     NaN  ...        NaN        NaN
22          NaN           NaN          NaN     NaN  ...        NaN        NaN
23          NaN           NaN          NaN     NaN  ...        NaN        NaN
24          NaN           NaN          NaN     NaN  ...        NaN        NaN
25          NaN           NaN          NaN     NaN  ...        NaN        NaN

                                                    Unnamed: 21_level_0  \
         14    14.1          14.2     14.3     14.4 Unnamed: 21_level_1
0        36      36            36       37       38                 NaN
1     Orkun   Orkun         Orkun    Orkun    Orkun                 NaN
2   None[a]  Tie[b]         Kimmi    Keith   Kelley                 NaN
3    0–0[a]     3–3  Consensus[f]      3–2      3–1                 NaN
4       NaN     NaN           NaN      NaN      NaN                 NaN
5      Vote    Vote          Vote     Vote     Vote                 NaN
6    Kelley   Kimmi         Kimmi    Keith   Kelley                 NaN
7    Kelley   Kimmi         Kimmi    Keith   Kelley                 NaN
8    Kelley   Kimmi           NaN    Keith   Kelley                 NaN
9    Jeremy   Tasha         Kimmi  Spencer  Spencer                 NaN
10   Jeremy   Tasha         Kimmi  Spencer      NaN                 NaN
11   Jeremy   Tasha           NaN      NaN      NaN                 NaN
12      NaN     NaN           NaN      NaN      NaN                 NaN
13      NaN     NaN           NaN      NaN      NaN                 NaN
14      NaN     NaN           NaN      NaN      NaN                 NaN
15      NaN     NaN           NaN      NaN      NaN                 NaN
16      NaN     NaN           NaN      NaN      NaN                 NaN
17      NaN     NaN           NaN      NaN      NaN                 NaN
18      NaN     NaN           NaN      NaN      NaN                 NaN
19      NaN     NaN           NaN      NaN      NaN                 NaN
20      NaN     NaN           NaN      NaN      NaN                 NaN
21      NaN     NaN           NaN      NaN      NaN                 NaN
22      NaN     NaN           NaN      NaN      NaN                 NaN
23      NaN     NaN           NaN      NaN      NaN                 NaN
24      NaN     NaN           NaN      NaN      NaN                 NaN
25      NaN     NaN           NaN      NaN      NaN                 NaN

   Unnamed: 22_level_0 Unnamed: 23_level_0
   Unnamed: 22_level_1 Unnamed: 23_level_1
0                  NaN                 NaN
1                  NaN                 NaN
2                  NaN                 NaN
3                  NaN                 NaN
4                  NaN                 NaN
5                  NaN                 NaN
6                  NaN                 NaN
7                  NaN                 NaN
8                  NaN                 NaN
9                  NaN                 NaN
10                 NaN                 NaN
11                 NaN                 NaN
12                 NaN                 NaN
13                 NaN                 NaN
14                 NaN                 NaN
15                 NaN                 NaN
16                 NaN                 NaN
17                 NaN                 NaN
18                 NaN                 NaN
19                 NaN                 NaN
20                 NaN                 NaN
21                 NaN                 NaN
22                 NaN                 NaN
23                 NaN                 NaN
24                 NaN                 NaN
25                 NaN                 NaN

[26 rows x 24 columns]

In [ ]:
jeremy_row = df[df[('Unnamed: 0_level_0', 'Episode')] == 'Jeremy']
print(jeremy_row)

  Unnamed: 0_level_0 Original tribes      First switch                    \
             Episode               1    2            3    4       5    6
6             Jeremy             NaN  NaN          NaN  NaN  Monica  NaN

  Second switch Merged tribe          ...                                 \
              6            7       8  ...   12         13      14   14.1
6           NaN        Ciera  Kelley  ...  Joe  Abi-Maria  Kelley  Kimmi

                        Unnamed: 21_level_0 Unnamed: 22_level_0  \
    14.2   14.3    14.4 Unnamed: 21_level_1 Unnamed: 22_level_1
6  Kimmi  Keith  Kelley                 NaN                 NaN

  Unnamed: 23_level_0
  Unnamed: 23_level_1
6                 NaN

[1 rows x 24 columns]

## Survivor 32

In [ ]:
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
}

r = requests.get('https://en.wikipedia.org/wiki/Survivor:_Kaôh_Rōng', headers=headers)
html_contents = r.text
html_soup = BeautifulSoup(html_contents,"lxml")

In [ ]:
tables = html_soup.find_all('table',class_="wikitable")
tables[0].find_all('a')

[<a href="/wiki/Chicago" title="Chicago">Chicago,<br/>Illinois</a>,
 <a href="/wiki/Salt_Lake_City" title="Salt Lake City">Salt Lake City,<br/>Utah</a>,
 <a href="/wiki/New_York_City" title="New York City">New York,<br/>New York</a>,
 <a href="/wiki/Hopkinsville,_Kentucky" title="Hopkinsville, Kentucky">Hopkinsville,<br/>Kentucky</a>,
 <a href="/wiki/Dallas" title="Dallas">Dallas,<br/>Texas</a>,
 <a href="/wiki/Brooklyn" title="Brooklyn">Brooklyn,<br/>New York</a>,
 <a href="/wiki/Minneapolis" title="Minneapolis">Minneapolis,<br/>Minnesota</a>,
 <a href="/wiki/Sausalito,_California" title="Sausalito, California">Sausalito,<br/>California</a>,
 <a href="#cite_note-14"><span class="cite-bracket">[</span>a<span class="cite-bracket">]</span></a>,
 <a href="/wiki/Redondo_Beach,_California" title="Redondo Beach, California"><span class="nowrap">Redondo Beach,</span><br/>California</a>,
 <a href="/wiki/Reading,_Pennsylvania" title="Reading, Pennsylvania">Reading,<br/>Pennsylvania</a>,
 <a href="/wiki/Scot_Pollard" title="Scot Pollard">Scot Pollard</a>,
 <a href="/wiki/Carmel,_Indiana" title="Carmel, Indiana">Carmel,<br/>Indiana</a>,
 <a href="/wiki/Boston" title="Boston">Boston,<br/>Massachusetts</a>,
 <a href="/wiki/Detroit" title="Detroit">Detroit,<br/>Michigan</a>,
 <a href="/wiki/Joe_Del_Campo" title="Joe Del Campo">Joe Del Campo</a>,
 <a href="/wiki/Vero_Beach,_Florida" title="Vero Beach, Florida">Vero Beach,<br/>Florida</a>,
 <a href="/wiki/Cydney_Gillon" title="Cydney Gillon">Cydney Gillon</a>,
 <a href="/wiki/Douglasville,_Georgia" title="Douglasville, Georgia">Douglasville,<br/>Georgia</a>,
 <a href="/wiki/San_Francisco" title="San Francisco">San Francisco,<br/>California</a>,
 <a href="/wiki/Cambridge,_Massachusetts" title="Cambridge, Massachusetts">Cambridge,<br/>Massachusetts</a>,
 <a href="/wiki/Freehold_Township,_New_Jersey" title="Freehold Township, New Jersey">Freehold,<br/>New Jersey</a>]

In [ ]:
df = pd.read_html(str(tables))[3]
df

/tmp/ipykernel_3126/1238544221.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(tables))[3]

   Unnamed: 0_level_0 Original tribes                                         \
              Episode               1      1.1         2         3       3.1
0                 Day               3        3         6         8         8
1               Tribe         To Tang  To Tang   To Tang  Chan Loh  Chan Loh
2          Eliminated          Tie[a]  Darnell  Jennifer    Tie[a]       Liz
3               Votes             3–3      4–0       3–2     2–2–2     3–0–0
4                 NaN             NaN      NaN       NaN       NaN       NaN
5               Voter            Vote     Vote      Vote      Vote      Vote
6             Michele             NaN      NaN       NaN       NaN       NaN
7               Aubry             NaN      NaN       NaN     Peter   None[g]
8                 Tai             NaN      NaN       NaN       NaN       NaN
9              Cydney          Alecia  Darnell  Jennifer       NaN       NaN
10                Joe             NaN      NaN       NaN       Liz       Liz
11              Jason          Alecia  Darnell  Jennifer       NaN       NaN
12              Julia             NaN      NaN       NaN       NaN       NaN
13               Scot         Darnell  Darnell    Alecia       NaN       NaN
14             Debbie             NaN      NaN       NaN       Liz       Liz
15               Nick             NaN      NaN       NaN       NaN       NaN
16               Neal             NaN      NaN       NaN     Peter       Liz
17              Peter             NaN      NaN       NaN     Aubry   None[g]
18               Anna             NaN      NaN       NaN       NaN       NaN
19             Alecia         Darnell  None[j]  Jennifer       NaN       NaN
20              Caleb             NaN      NaN       NaN       NaN       NaN
21                Liz             NaN      NaN       NaN     Aubry   None[g]
22           Jennifer         Darnell  Darnell    Alecia       NaN       NaN
23            Darnell          Alecia  None[j]       NaN       NaN       NaN

                          Switched tribes          ... Merged tribe         \
               4      4.1               5       6  ...           10     11
0              9       11              13      16  ...           27     29
1         Gondol  To Tang          Gondol  Gondol  ...         Dara   Dara
2          Caleb   Alecia            Anna   Peter  ...         Scot  Julia
3   Evacuated[c]      3–1             5–1     4–2  ...        4–2–2    5–2
4            NaN      NaN             NaN     NaN  ...          NaN    NaN
5           Vote     Vote            Vote    Vote  ...         Vote   Vote
6            NaN      NaN             NaN     NaN  ...          Tai  Julia
7            NaN      NaN            Anna   Peter  ...         Scot  Julia
8            NaN      NaN            Anna   Peter  ...         Scot  Julia
9            NaN   Alecia             NaN     NaN  ...         Scot  Julia
10           NaN      NaN            Anna   Julia  ...         Scot  Julia
11           NaN   Alecia             NaN     NaN  ...        Aubry    Tai
12           NaN      NaN       Exiled[i]   Peter  ...          Tai    Tai
13           NaN   Alecia            Anna   Peter  ...        Aubry    NaN
14           NaN      NaN             NaN     NaN  ...          NaN    NaN
15           NaN      NaN             NaN     NaN  ...          NaN    NaN
16           NaN      NaN             NaN     NaN  ...          NaN    NaN
17           NaN      NaN            Anna   Julia  ...          NaN    NaN
18           NaN      NaN           Peter     NaN  ...          NaN    NaN
19           NaN     Scot             NaN     NaN  ...          NaN    NaN
20     Evacuated      NaN             NaN     NaN  ...          NaN    NaN
21           NaN      NaN             NaN     NaN  ...          NaN    NaN
22           NaN      NaN             NaN     NaN  ...          NaN    NaN
23           NaN      NaN             NaN     NaN  ...          NaN    NaN

                                                             \
         12        12.1            13      14          14.1
0        32          32            34      37            37
1      Dara        Dara          Dara    Dara          Dara
2     Jason       Jason           Joe  Tie[b]        Cydney
3     4–2–1       4–2–1  Evacuated[e]     2–2  Challenge[f]
4       NaN         NaN           NaN     NaN           NaN
5      Vote        Vote          Vote    Vote          Vote
6     Jason       Jason           NaN   Aubry           NaN
7     Jason       Jason           NaN  Cydney        Won[f]
8   Michele  Michele[h]           NaN  Cydney           NaN
9     Jason       Jason           NaN   Aubry       Lost[f]
10    Jason       Jason     Evacuated     NaN           NaN
11      Joe         Joe           NaN     NaN           NaN
12      NaN         NaN           NaN     NaN           NaN
13      NaN         NaN           NaN     NaN           NaN
14      NaN         NaN           NaN     NaN           NaN
15      NaN         NaN           NaN     NaN           NaN
16      NaN         NaN           NaN     NaN           NaN
17      NaN         NaN           NaN     NaN           NaN
18      NaN         NaN           NaN     NaN           NaN
19      NaN         NaN           NaN     NaN           NaN
20      NaN         NaN           NaN     NaN           NaN
21      NaN         NaN           NaN     NaN           NaN
22      NaN         NaN           NaN     NaN           NaN
23      NaN         NaN           NaN     NaN           NaN

   Unnamed: 20_level_0 Unnamed: 21_level_0 Unnamed: 22_level_0
   Unnamed: 20_level_1 Unnamed: 21_level_1 Unnamed: 22_level_1
0                  NaN                 NaN                 NaN
1                  NaN                 NaN                 NaN
2                  NaN                 NaN                 NaN
3                  NaN                 NaN                 NaN
4                  NaN                 NaN                 NaN
5                  NaN                 NaN                 NaN
6                  NaN                 NaN                 NaN
7                  NaN                 NaN                 NaN
8                  NaN                 NaN                 NaN
9                  NaN                 NaN                 NaN
10                 NaN                 NaN                 NaN
11                 NaN                 NaN                 NaN
12                 NaN                 NaN                 NaN
13                 NaN                 NaN                 NaN
14                 NaN                 NaN                 NaN
15                 NaN                 NaN                 NaN
16                 NaN                 NaN                 NaN
17                 NaN                 NaN                 NaN
18                 NaN                 NaN                 NaN
19                 NaN                 NaN                 NaN
20                 NaN                 NaN                 NaN
21                 NaN                 NaN                 NaN
22                 NaN                 NaN                 NaN
23                 NaN                 NaN                 NaN

[24 rows x 23 columns]

In [ ]:
michele_row = df[df[('Unnamed: 0_level_0', 'Episode')] == 'Michele']
print(michele_row)

  Unnamed: 0_level_0 Original tribes                                \
             Episode               1  1.1    2    3  3.1    4  4.1
6            Michele             NaN  NaN  NaN  NaN  NaN  NaN  NaN

  Switched tribes       ... Merged tribe                                   \
                5    6  ...           10     11     12   12.1   13     14
6             NaN  NaN  ...          Tai  Julia  Jason  Jason  NaN  Aubry

       Unnamed: 20_level_0 Unnamed: 21_level_0 Unnamed: 22_level_0
  14.1 Unnamed: 20_level_1 Unnamed: 21_level_1 Unnamed: 22_level_1
6  NaN                 NaN                 NaN                 NaN

[1 rows x 23 columns]

## Survivor 33

In [ ]:
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
}

r = requests.get('https://en.wikipedia.org/wiki/Survivor:_Millennials_vs._Gen_X', headers=headers)
html_contents = r.text
html_soup = BeautifulSoup(html_contents,"lxml")

In [ ]:
tables = html_soup.find_all('table',class_="wikitable")
tables[0].find_all('a')

[<a href="/wiki/Los_Angeles" title="Los Angeles">Los Angeles<br/>California</a>,
 <a href="/wiki/Mari_Takahashi" title="Mari Takahashi">Mari Takahashi</a>,
 <a href="/wiki/Los_Angeles" title="Los Angeles">Los Angeles,<br/>California</a>,
 <a href="/wiki/Sugarloaf_Key" title="Sugarloaf Key">Sugarloaf Key,<br/>Florida</a>,
 <a href="/wiki/Diamond_Bar,_California" title="Diamond Bar, California">Diamond Bar,<br/>California</a>,
 <a href="/wiki/Granada_Hills,_Los_Angeles" title="Granada Hills, Los Angeles">Granada Hills,<br/>California</a>,
 <a href="/wiki/Nashville,_Tennessee" title="Nashville, Tennessee">Nashville,<br/>Tennessee</a>,
 <a href="/wiki/Fort_Worth,_Texas" title="Fort Worth, Texas">Fort Worth,<br/>Texas</a>,
 <a href="/wiki/Yakima,_Washington" title="Yakima, Washington">Yakima,<br/>Washington</a>,
 <a href="/wiki/Post_Falls,_Idaho" title="Post Falls, Idaho">Post Falls,<br/>Idaho</a>,
 <a href="/wiki/Chris_Hammons" title="Chris Hammons">Chris Hammons</a>,
 <a href="/wiki/Moore,_Oklahoma" title="Moore, Oklahoma">Moore,<br/>Oklahoma</a>,
 <a href="/wiki/Voorheesville,_New_York" title="Voorheesville, New York">Voorheesville,<br/>New York</a>,
 <a href="#cite_note-15"><span class="cite-bracket">[</span>a<span class="cite-bracket">]</span></a>,
 <a href="/wiki/Brooklyn" title="Brooklyn">Brooklyn,<br/>New York</a>,
 <a href="/wiki/Long_Valley,_New_Jersey" title="Long Valley, New Jersey">Long Valley,<br/>New Jersey</a>,
 <a href="/wiki/Otsego,_Minnesota" title="Otsego, Minnesota">Otsego,<br/>Minnesota</a>,
 <a href="/wiki/Fort_Lauderdale,_Florida" title="Fort Lauderdale, Florida">Fort Lauderdale,<br/>Florida</a>,
 <a href="/wiki/Dedham,_Massachusetts" title="Dedham, Massachusetts">Dedham,<br/>Massachusetts</a>,
 <a href="/wiki/Sherman_Oaks,_Los_Angeles" title="Sherman Oaks, Los Angeles">Sherman Oaks,<br/>California</a>,
 <a href="/wiki/West_Hollywood,_California" title="West Hollywood, California"><span class="nowrap">West Hollywood,</span><br/>California</a>,
 <a href="/wiki/Denver" title="Denver">Denver,<br/>Colorado</a>,
 <a href="/wiki/San_Francisco" title="San Francisco">San Francisco,<br/>California</a>]

In [ ]:
df = pd.read_html(str(tables))[3]
df

/tmp/ipykernel_3126/1238544221.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(tables))[3]

   Unnamed: 0_level_0 Original tribes                           \
              Episode               1      2       3         4
0                 Day               4      7      10        12
1               Tribe          Takali  Vanua  Takali    Takali
2          Eliminated          Rachel   Mari    Paul      Lucy
3               Votes         5–3–1–1    7–3     6–3  2–1–0[c]
4                 NaN             NaN    NaN     NaN       NaN
5               Voter            Vote   Vote    Vote      Vote
6                Adam             NaN  Figgy     NaN       NaN
7              Hannah             NaN   Mari     NaN       NaN
8                 Ken          Rachel    NaN    Paul   Jessica
9               David          Rachel    NaN    Paul      Lucy
10               Bret          Rachel    NaN    CeCe   Jessica
11                Jay             NaN   Mari     NaN       NaN
12             Sunday            CeCe    NaN    Paul   Jessica
13               Will             NaN   Mari     NaN       NaN
14               Zeke             NaN  Figgy     NaN       NaN
15            Jessica            CeCe    NaN    Paul      CeCe
16              Chris          Rachel    NaN    CeCe   Jessica
17             Taylor             NaN   Mari     NaN       NaN
18           Michelle             NaN   Mari     NaN       NaN
19           Michaela             NaN   Mari     NaN       NaN
20              Figgy             NaN   Mari     NaN       NaN
21               CeCe           David    NaN    Paul      Lucy
22               Lucy            CeCe    NaN    Paul   Jessica
23               Paul          Rachel    NaN    CeCe       NaN
24               Mari             NaN  Figgy     NaN       NaN
25             Rachel          Sunday    NaN     NaN       NaN

   Switched tribes                   Merged tribe          ...           \
                 5       6         7            8       9  ...     10.2
0               15      18        20           23      25  ...       30
1            Vanua  Takali   Ikabula       Vinaka  Vinaka  ...   Vinaka
2             CeCe   Figgy  Michaela     Michelle  Taylor  ...   Tie[b]
3              4–1     3–2       4–2          9–4   7–4–1  ...      4–4
4              NaN     NaN       NaN          NaN     NaN  ...      NaN
5             Vote    Vote      Vote         Vote    Vote  ...     Vote
6              NaN   Figgy       NaN     Michelle  Taylor  ...     Zeke
7              NaN     NaN      Bret     Michelle     Jay  ...  None[h]
8              NaN   Figgy       NaN     Michelle  Taylor  ...     Zeke
9             CeCe     NaN       NaN     Michelle  Taylor  ...     Zeke
10             NaN     NaN  Michaela     Michelle     Jay  ...   Hannah
11             NaN     NaN  Michaela         Adam  Taylor  ...   Hannah
12             NaN     NaN  Michaela     Michelle  Taylor  ...   Hannah
13             NaN     NaN  Michaela         Adam     Jay  ...   Hannah
14            CeCe     NaN       NaN     Michelle  Taylor  ...  None[h]
15             NaN   Figgy       NaN     Michelle     Jay  ...     Zeke
16            CeCe     NaN       NaN     Michelle  Taylor  ...      NaN
17             NaN     Ken       NaN         Adam    Adam  ...      NaN
18            CeCe     NaN       NaN         Adam     NaN  ...      NaN
19             NaN     NaN      Bret          NaN     NaN  ...      NaN
20             NaN     Ken       NaN          NaN     NaN  ...      NaN
21        Michelle     NaN       NaN          NaN     NaN  ...      NaN
22             NaN     NaN       NaN          NaN     NaN  ...      NaN
23             NaN     NaN       NaN          NaN     NaN  ...      NaN
24             NaN     NaN       NaN          NaN     NaN  ...      NaN
25             NaN     NaN       NaN          NaN     NaN  ...      NaN

                                                                    \
            10.3      11      12      12.1      13    13.1    13.2
0             30      33      34        35      36      37      38
1         Vinaka  Vinaka  Vinaka    Vinaka  Vinaka  Vinaka  Vinaka
2        Jessica    Zeke    Will    Sunday     Jay    Bret   David
3   Rock Draw[d]  5–0[e]     6–2  4–2–0[f]  5–0[g]     3–2     3–1
4            NaN     NaN     NaN       NaN     NaN     NaN     NaN
5           Vote    Vote    Vote      Vote    Vote    Vote    Vote
6     White rock    Zeke    Will    Sunday     Jay   David   David
7         Immune    Zeke    Will    Sunday     Jay    Bret   David
8      Immune[i]    Zeke    Will    Sunday     Jay    Bret   David
9     White rock    Zeke    Will    Sunday     Jay    Bret    Adam
10    White rock  Hannah    Will     David     Jay   David     NaN
11        Immune  Hannah   David     David     Ken     NaN     NaN
12    White rock  Hannah    Will       Jay     NaN     NaN     NaN
13    White rock    Zeke   David       NaN     NaN     NaN     NaN
14        Immune  Hannah     NaN       NaN     NaN     NaN     NaN
15    Black rock     NaN     NaN       NaN     NaN     NaN     NaN
16           NaN     NaN     NaN       NaN     NaN     NaN     NaN
17           NaN     NaN     NaN       NaN     NaN     NaN     NaN
18           NaN     NaN     NaN       NaN     NaN     NaN     NaN
19           NaN     NaN     NaN       NaN     NaN     NaN     NaN
20           NaN     NaN     NaN       NaN     NaN     NaN     NaN
21           NaN     NaN     NaN       NaN     NaN     NaN     NaN
22           NaN     NaN     NaN       NaN     NaN     NaN     NaN
23           NaN     NaN     NaN       NaN     NaN     NaN     NaN
24           NaN     NaN     NaN       NaN     NaN     NaN     NaN
25           NaN     NaN     NaN       NaN     NaN     NaN     NaN

   Unnamed: 20_level_0 Unnamed: 21_level_0
   Unnamed: 20_level_1 Unnamed: 21_level_1
0                  NaN                 NaN
1                  NaN                 NaN
2                  NaN                 NaN
3                  NaN                 NaN
4                  NaN                 NaN
5                  NaN                 NaN
6                  NaN                 NaN
7                  NaN                 NaN
8                  NaN                 NaN
9                  NaN                 NaN
10                 NaN                 NaN
11                 NaN                 NaN
12                 NaN                 NaN
13                 NaN                 NaN
14                 NaN                 NaN
15                 NaN                 NaN
16                 NaN                 NaN
17                 NaN                 NaN
18                 NaN                 NaN
19                 NaN                 NaN
20                 NaN                 NaN
21                 NaN                 NaN
22                 NaN                 NaN
23                 NaN                 NaN
24                 NaN                 NaN
25                 NaN                 NaN

[26 rows x 22 columns]

In [ ]:
adam_row = df[df[('Unnamed: 0_level_0', 'Episode')] == 'Adam']
print(adam_row)

  Unnamed: 0_level_0 Original tribes                  Switched tribes         \
             Episode               1      2    3    4               5      6
6               Adam             NaN  Figgy  NaN  NaN             NaN  Figgy

       Merged tribe          ...                                             \
     7            8       9  ...  10.2        10.3    11    12    12.1   13
6  NaN     Michelle  Taylor  ...  Zeke  White rock  Zeke  Will  Sunday  Jay

                Unnamed: 20_level_0 Unnamed: 21_level_0
    13.1   13.2 Unnamed: 20_level_1 Unnamed: 21_level_1
6  David  David                 NaN                 NaN

[1 rows x 22 columns]

## Survivor 34

In [ ]:
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
}

r = requests.get('https://en.wikipedia.org/wiki/Survivor:_Game_Changers', headers=headers)
html_contents = r.text
html_soup = BeautifulSoup(html_contents,"lxml")

In [ ]:
tables = html_soup.find_all('table',class_="wikitable")
tables[0].find_all('a')

[<a href="/wiki/Survivor:_Blood_vs._Water" title="Survivor: Blood vs. Water">Blood vs. Water</a>,
 <a href="/wiki/Survivor:_Cambodia" title="Survivor: Cambodia">Cambodia</a>,
 <a href="/wiki/Salem,_Oregon" title="Salem, Oregon">Salem,<br/>Oregon</a>,
 <a href="/wiki/Tony_Vlachos" title="Tony Vlachos">Tony Vlachos</a>,
 <a href="/wiki/Survivor:_Cagayan" title="Survivor: Cagayan"><i>Cagayan</i></a>,
 <a href="/wiki/Jersey_City,_New_Jersey" title="Jersey City, New Jersey">Jersey City,<br/>New Jersey</a>,
 <a href="/wiki/Survivor:_Ka%C3%B4h_R%C5%8Dng" title="Survivor: Kaôh Rōng"><i>Kaôh Rōng</i></a>,
 <a href="/wiki/Hopkinsville,_Kentucky" title="Hopkinsville, Kentucky">Hopkinsville,<br/>Kentucky</a>,
 <a href="/wiki/Survivor:_Philippines" title="Survivor: Philippines">Philippines</a>,
 <a href="/wiki/Survivor:_Caramoan" title="Survivor: Caramoan">Caramoan</a>,
 <a href="/wiki/Hermosa_Beach,_California" title="Hermosa Beach, California">Hermosa Beach,<br/>California</a>,
 <a href="/wiki/Survivor:_Tocantins" title="Survivor: Tocantins">Tocantins</a>,
 <a href="/wiki/Survivor:_Heroes_vs._Villains" title="Survivor: Heroes vs. Villains">Heroes vs. Villains</a>,
 <a href="/wiki/Mobile,_Alabama" title="Mobile, Alabama">Mobile,<br/>Alabama</a>,
 <a href="/wiki/Sandra_Diaz-Twine" title="Sandra Diaz-Twine">Sandra Diaz-Twine</a>,
 <a href="/wiki/Survivor:_Pearl_Islands" title="Survivor: Pearl Islands">Pearl Islands</a>,
 <a href="/wiki/Survivor:_Heroes_vs._Villains" title="Survivor: Heroes vs. Villains">Heroes vs. Villains</a>,
 <a href="/wiki/Fayetteville,_North_Carolina" title="Fayetteville, North Carolina">Fayetteville,<br/>North Carolina</a>,
 <a href="/wiki/Jeff_Varner" title="Jeff Varner">Jeff Varner</a>,
 <a href="/wiki/Survivor:_The_Australian_Outback" title="Survivor: The Australian Outback">The Australian Outback</a>,
 <a href="/wiki/Survivor:_Cambodia" title="Survivor: Cambodia">Cambodia</a>,
 <a href="/wiki/High_Point,_North_Carolina" title="High Point, North Carolina">High Point,<br/>North Carolina</a>,
 <a href="/wiki/Survivor:_Worlds_Apart" title="Survivor: Worlds Apart"><i>Worlds Apart</i></a>,
 <a href="/wiki/Knoxville,_Tennessee" title="Knoxville, Tennessee">Knoxville,<br/>Tennessee</a>,
 <a href="/wiki/Ozzy_Lusth" title="Ozzy Lusth">Oscar "Ozzy" Lusth</a>,
 <a href="/wiki/Survivor:_Cook_Islands" title="Survivor: Cook Islands">Cook Islands</a>,
 <a href="/wiki/Survivor:_Micronesia" title="Survivor: Micronesia">Micronesia</a>,
 <a href="/wiki/Survivor:_South_Pacific" title="Survivor: South Pacific">South Pacific</a>,
 <a href="/wiki/Venice,_Los_Angeles" title="Venice, Los Angeles">Venice,<br/>California</a>,
 <a href="/wiki/Survivor:_Ka%C3%B4h_R%C5%8Dng" title="Survivor: Kaôh Rōng"><i>Kaôh Rōng</i></a>,
 <a href="/wiki/Reading,_Pennsylvania" title="Reading, Pennsylvania">Reading,<br/>Pennsylvania</a>,
 <a href="/wiki/Survivor:_Millennials_vs._Gen_X" title="Survivor: Millennials vs. Gen X"><i>Millennials vs. Gen X</i></a>,
 <a href="/wiki/Brooklyn" title="Brooklyn">Brooklyn,<br/>New York</a>,
 <a href="/wiki/Survivor:_Worlds_Apart" title="Survivor: Worlds Apart"><i>Worlds Apart</i></a>,
 <a href="/wiki/Roy,_Utah" title="Roy, Utah">Roy,<br/>Utah</a>,
 <a href="/wiki/Survivor:_Redemption_Island" title="Survivor: Redemption Island">Redemption Island</a>,
 <a href="/wiki/Survivor:_Caramoan" title="Survivor: Caramoan">Caramoan</a>,
 <a href="/wiki/New_York_City" title="New York City">New York City,<br/>New York</a>,
 <a href="/wiki/Survivor:_Millennials_vs._Gen_X" title="Survivor: Millennials vs. Gen X"><i>Millennials vs. Gen X</i></a>,
 <a href="/wiki/Fort_Worth,_Texas" title="Fort Worth, Texas">Fort Worth,<br/>Texas</a>,
 <a href="/wiki/Cirie_Fields" title="Cirie Fields">Cirie Fields</a>,
 <a href="/wiki/Survivor:_Panama" title="Survivor: Panama">Panama</a>,
 <a href="/wiki/Survivor:_Micronesia" title="Survivor: Micronesia">Micronesia</a>,
 <a href="/wiki/Survivor:_Heroes_vs._Villains" title="Survivor: Heroes vs. Villains">Heroes vs. Villains</a>,
 <a href="/wiki/Norwalk,_Connecticut" title="Norwalk, Connecticut">Norwalk,<br/>Connecticut</a>,
 <a href="#cite_note-16"><span class="cite-bracket">[</span>a<span class="cite-bracket">]</span></a>,
 <a href="/wiki/Survivor:_Ka%C3%B4h_R%C5%8Dng" title="Survivor: Kaôh Rōng"><i>Kaôh Rōng</i></a>,
 <a href="/wiki/Cambridge,_Massachusetts" title="Cambridge, Massachusetts">Cambridge,<br/>Massachusetts</a>,
 <a href="/wiki/Survivor:_Ka%C3%B4h_R%C5%8Dng" title="Survivor: Kaôh Rōng"><i>Kaôh Rōng</i></a>,
 <a href="/wiki/San_Francisco" title="San Francisco">San Francisco,<br/>California</a>,
 <a class="mw-redirect" href="/wiki/Troy_%22Troyzan%22_Robertson" title='Troy "Troyzan" Robertson'>Troy "Troyzan" Robertson</a>,
 <a href="/wiki/Survivor:_One_World" title="Survivor: One World"><i>One World</i></a>,
 <a href="/wiki/Miami" title="Miami">Miami,<br/>Florida</a>,
 <a href="/wiki/Brad_Culpepper" title="Brad Culpepper">Brad Culpepper</a>,
 <a href="/wiki/Survivor:_Blood_vs._Water" title="Survivor: Blood vs. Water"><i>Blood vs. Water</i></a>,
 <a href="/wiki/Tampa,_Florida" title="Tampa, Florida">Tampa,<br/>Florida</a>,
 <a href="/wiki/Sarah_Lacina" title="Sarah Lacina">Sarah Lacina</a>,
 <a href="/wiki/Survivor:_Cagayan" title="Survivor: Cagayan"><i>Cagayan</i></a>,
 <a href="/wiki/Marion,_Iowa" title="Marion, Iowa">Marion,<br/>Iowa</a>]

In [ ]:
df = pd.read_html(str(tables))[3]
df

/tmp/ipykernel_3126/1238544221.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(tables))[3]

   Unnamed: 0_level_0 Original tribes        First switch                     \
              Episode               1    1.1            2        3         4
0                 Day               3      6            9    11[a]        13
1               Tribe            Mana   Mana         Mana     Nuku      Nuku
2          Eliminated           Ciera   Tony        Caleb  Malcolm      J.T.
3               Votes             9–1    7–2          5–1   5–0[b]       3–2
4                 NaN             NaN    NaN          NaN      NaN       NaN
5               Voter            Vote   Vote         Vote     Vote      Vote
6               Sarah             NaN    NaN          NaN      NaN       NaN
7                Brad             NaN    NaN        Caleb  Malcolm       NaN
8             Troyzan           Ciera   Tony          NaN      NaN       NaN
9                 Tai             NaN    NaN        Caleb  Malcolm       NaN
10              Aubry           Ciera   Tony          NaN   Sierra  Michaela
11              Cirie             NaN    NaN          NaN      NaN       NaN
12           Michaela           Ciera   Tony          NaN   Sierra      J.T.
13             Andrea             NaN    NaN          NaN      NaN       NaN
14             Sierra             NaN    NaN        Caleb  Malcolm       NaN
15               Zeke             NaN    NaN          NaN      NaN       NaN
16             Debbie             NaN    NaN        Caleb  Malcolm       NaN
17               Ozzy             NaN    NaN          NaN      NaN       NaN
18               Hali           Ciera   Tony        Caleb  Malcolm       NaN
19               Jeff           Ciera   Tony          NaN   Sierra      J.T.
20             Sandra           Ciera  Aubry          NaN   Sierra      J.T.
21               J.T.             NaN    NaN          NaN   Sierra  Michaela
22            Malcolm           Ciera   Tony          NaN   Sierra       NaN
23              Caleb           Ciera   Tony         Hali      NaN       NaN
24               Tony           Ciera  Aubry          NaN      NaN       NaN
25              Ciera        Michaela    NaN          NaN      NaN       NaN

   Second switch          Merged tribe             ...                        \
               5        6            7        7.1  ...          8          9
0             16       18           21         24  ...         26         29
1           Nuku     Nuku    Maku Maku  Maku Maku  ...  Maku Maku  Maku Maku
2         Sandra     Jeff         Hali       Ozzy  ...     Debbie       Zeke
3            5–2   6–0[c]        7–4–2    7–4–1–1  ...        6–5      5–3–2
4            NaN      NaN          NaN        NaN  ...        NaN        NaN
5           Vote     Vote         Vote       Vote  ...       Vote       Vote
6         Sandra     Jeff     Michaela       Ozzy  ...     Debbie       Zeke
7            NaN      NaN         Hali       Ozzy  ...     Andrea        Tai
8            NaN      NaN         Hali       Ozzy  ...     Andrea        Tai
9         Sandra     Jeff         Hali       Ozzy  ...     Andrea     Sierra
10           NaN      NaN         Hali       Zeke  ...     Debbie       Zeke
11           NaN      NaN     Michaela     Sierra  ...     Debbie       Zeke
12           NaN      NaN         Zeke       Zeke  ...     Debbie       Zeke
13        Sandra     Jeff     Michaela       Zeke  ...     Debbie       Zeke
14           NaN      NaN         Hali       Ozzy  ...     Andrea        Tai
15        Sandra     Jeff     Michaela      Aubry  ...     Debbie     Sierra
16     Exiled[f]     Jeff         Hali       Ozzy  ...     Andrea        NaN
17        Sandra     Jeff         Hali       Zeke  ...        NaN        NaN
18           NaN      NaN         Zeke        NaN  ...        NaN        NaN
19           Tai  None[c]          NaN        NaN  ...        NaN        NaN
20           Tai      NaN          NaN        NaN  ...        NaN        NaN
21           NaN      NaN          NaN        NaN  ...        NaN        NaN
22           NaN      NaN          NaN        NaN  ...        NaN        NaN
23           NaN      NaN          NaN        NaN  ...        NaN        NaN
24           NaN      NaN          NaN        NaN  ...        NaN        NaN
25           NaN      NaN          NaN        NaN  ...        NaN        NaN

                                                                            \
           10         11       11.1         11.2         12           12.1
0          32         33         35           35         36             36
1   Maku Maku  Maku Maku  Maku Maku    Maku Maku  Maku Maku      Maku Maku
2      Sierra     Andrea   Michaela     Michaela        NaN          Cirie
3         6–3        6–2      4–2–1        4–2–1   0–0–0[d]     Default[d]
4         NaN        NaN        NaN          NaN        NaN            NaN
5        Vote       Vote       Vote         Vote       Vote           Vote
6      Sierra     Andrea   Michaela  Michaela[e]        Tai         Immune
7      Andrea     Andrea   Michaela     Michaela      Aubry         Immune
8      Andrea     Andrea   Michaela     Michaela        Tai         Immune
9      Sierra     Andrea    None[e]      None[e]      Sarah         Immune
10     Sierra       Brad        Tai          Tai      Sarah         Immune
11     Sierra     Andrea      Aubry        Aubry      Sarah  Eliminated[d]
12     Sierra     Andrea        Tai          Tai        NaN            NaN
13     Sierra       Brad        NaN          NaN        NaN            NaN
14     Andrea        NaN        NaN          NaN        NaN            NaN
15        NaN        NaN        NaN          NaN        NaN            NaN
16        NaN        NaN        NaN          NaN        NaN            NaN
17        NaN        NaN        NaN          NaN        NaN            NaN
18        NaN        NaN        NaN          NaN        NaN            NaN
19        NaN        NaN        NaN          NaN        NaN            NaN
20        NaN        NaN        NaN          NaN        NaN            NaN
21        NaN        NaN        NaN          NaN        NaN            NaN
22        NaN        NaN        NaN          NaN        NaN            NaN
23        NaN        NaN        NaN          NaN        NaN            NaN
24        NaN        NaN        NaN          NaN        NaN            NaN
25        NaN        NaN        NaN          NaN        NaN            NaN


         12.2       12.3
0          37         38
1   Maku Maku  Maku Maku
2       Aubry        Tai
3         4–1        3–1
4         NaN        NaN
5        Vote       Vote
6       Aubry        Tai
7       Aubry        Tai
8       Aubry        Tai
9       Aubry    Troyzan
10    Troyzan        NaN
11        NaN        NaN
12        NaN        NaN
13        NaN        NaN
14        NaN        NaN
15        NaN        NaN
16        NaN        NaN
17        NaN        NaN
18        NaN        NaN
19        NaN        NaN
20        NaN        NaN
21        NaN        NaN
22        NaN        NaN
23        NaN        NaN
24        NaN        NaN
25        NaN        NaN

[26 rows x 21 columns]

In [ ]:
sarah_row = df[df[('Unnamed: 0_level_0', 'Episode')] == 'Sarah']
print(sarah_row)

  Unnamed: 0_level_0 Original tribes      First switch            \
             Episode               1  1.1            2    3    4
6              Sarah             NaN  NaN          NaN  NaN  NaN

  Second switch       Merged tribe        ...                                \
              5     6            7   7.1  ...       8     9      10      11
6        Sandra  Jeff     Michaela  Ozzy  ...  Debbie  Zeke  Sierra  Andrea


       11.1         11.2   12    12.1   12.2 12.3
6  Michaela  Michaela[e]  Tai  Immune  Aubry  Tai

[1 rows x 21 columns]

## Survivor 35

In [ ]:
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
}

r = requests.get('https://en.wikipedia.org/wiki/Survivor:_Heroes_vs._Healers_vs._Hustlers', headers=headers)
html_contents = r.text
html_soup = BeautifulSoup(html_contents,"lxml")

In [ ]:
tables = html_soup.find_all('table',class_="wikitable")
tables[0].find_all('a')

[<a href="/wiki/Trina_Radke" title="Trina Radke">Katrina Radke</a>,
 <a href="/wiki/Excelsior,_Minnesota" title="Excelsior, Minnesota">Excelsior,<br/>Minnesota</a>,
 <a href="/wiki/New_York_City" title="New York City">New York,<br/> New York</a>,
 <a href="/wiki/Auburn,_Alabama" title="Auburn, Alabama">Auburn,<br/>Alabama</a>,
 <a href="/wiki/Alan_Ball_(American_football)" title="Alan Ball (American football)">Alan Ball</a>,
 <a href="/wiki/Houston" title="Houston">Houston,<br/>Texas</a>,
 <a href="/wiki/Santa_Monica,_California" title="Santa Monica, California">Santa Monica,<br/>California</a>,
 <a href="/wiki/Los_Angeles" title="Los Angeles">Los Angeles,<br/>California</a>,
 <a href="/wiki/Louisville,_Kentucky" title="Louisville, Kentucky">Louisville,<br/>Kentucky</a>,
 <a href="/wiki/Newport_News,_Virginia" title="Newport News, Virginia">Newport News,<br/>Virginia</a>,
 <a href="/wiki/Little_Rock,_Arkansas" title="Little Rock, Arkansas">Little Rock,<br/>Arkansas</a>,
 <a href="/wiki/Los_Angeles" title="Los Angeles">Los Angeles,<br/>California</a>,
 <a href="/wiki/Tolland,_Connecticut" title="Tolland, Connecticut">Tolland,<br/>Connecticut</a>,
 <a href="/wiki/Beaufort,_North_Carolina" title="Beaufort, North Carolina">Beaufort,<br/>North Carolina</a>,
 <a href="/wiki/Satellite_Beach,_Florida" title="Satellite Beach, Florida">Satellite Beach,<br/>Florida</a>,
 <a href="/wiki/Parkland,_Florida" title="Parkland, Florida">Parkland,<br/>Florida</a>,
 <a href="/wiki/Solana_Beach,_California" title="Solana Beach, California">Solana Beach,<br/>California</a>,
 <a href="/wiki/North_Arlington,_New_Jersey" title="North Arlington, New Jersey">North Arlington,<br/>New Jersey</a>,
 <a href="/wiki/Lebanon_Township,_New_Jersey" title="Lebanon Township, New Jersey"><span class="nowrap">Lebanon Township</span>,<br/> New Jersey</a>,
 <a href="/wiki/Boise,_Idaho" title="Boise, Idaho">Boise,<br/>Idaho</a>]

In [ ]:
df = pd.read_html(str(tables))[3]
df

/tmp/ipykernel_3126/1238544221.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(tables))[3]

   Unnamed: 0_level_0 Original tribes                   Switched tribes  \
              Episode               1        2        3               4
0                 Day               3        6        8              11
1               Tribe            Levu     Yawa     Yawa            Levu
2          Eliminated         Katrina   Simone  Patrick            Alan
3               Votes             5–1      5–1      4–1          2–0[b]
4                 NaN             NaN      NaN      NaN             NaN
5               Voter            Vote     Vote     Vote            Vote
6                 Ben         Katrina      NaN      NaN             NaN
7             Chrissy         Katrina      NaN      NaN             NaN
8                Ryan             NaN   Simone  Patrick             NaN
9               Devon             NaN   Simone  Patrick         None[h]
10               Mike             NaN      NaN      NaN             NaN
11             Ashley         Katrina      NaN      NaN             Joe
12             Lauren             NaN   Simone  Patrick             NaN
13                Joe             NaN      NaN      NaN            Alan
14                 JP         Katrina      NaN      NaN             NaN
15               Cole             NaN      NaN      NaN             NaN
16               Desi             NaN      NaN      NaN            Alan
17            Jessica             NaN      NaN      NaN             NaN
18                Ali             NaN   Simone  Patrick             NaN
19              Roark             NaN      NaN      NaN             NaN
20               Alan         Katrina      NaN      NaN             Joe
21            Patrick             NaN   Simone   Lauren             NaN
22             Simone             NaN  Patrick      NaN             NaN
23            Katrina          Ashley      NaN      NaN             NaN

                  Merged tribe                    ...                  \
          5     6            7        8      8.1  ...      11      12
0        14    16           19       21       21  ...      33      36
1      Soko  Soko       Solewa   Solewa   Solewa  ...  Solewa  Solewa
2     Roark   Ali      Jessica   Tie[a]     Desi  ...  Lauren  Ashley
3       3–2   3–1          7–5  4–4–1–1      7–1  ...  1–0[e]     5–1
4       NaN   NaN          NaN      NaN      NaN  ...     NaN     NaN
5      Vote  Vote         Vote     Vote     Vote  ...    Vote    Vote
6       NaN   NaN      Jessica     Desi     Desi  ...  Lauren  Ashley
7     Roark   Ali      Jessica      Joe     Desi  ...     Ben  Ashley
8     Roark   Ali      Jessica     Desi     Desi  ...     Ben  Ashley
9       NaN   NaN      Jessica     Desi     Desi  ...     Ben  Ashley
10      NaN   NaN      Chrissy      Joe      Joe  ...     Ben  Ashley
11      NaN   NaN      Jessica      Joe     Desi  ...     Ben    Mike
12      NaN   NaN      Jessica  None[j]  None[j]  ...     Ben     NaN
13      NaN   NaN      Chrissy      Ben  None[k]  ...     NaN     NaN
14    Roark   Ali      Jessica     Desi     Desi  ...     NaN     NaN
15      NaN   NaN      Chrissy      Joe     Desi  ...     NaN     NaN
16      NaN   NaN      Chrissy   Lauren  None[k]  ...     NaN     NaN
17      NaN   NaN      Chrissy      NaN      NaN  ...     NaN     NaN
18  Chrissy    JP          NaN      NaN      NaN  ...     NaN     NaN
19  Chrissy   NaN          NaN      NaN      NaN  ...     NaN     NaN
20      NaN   NaN          NaN      NaN      NaN  ...     NaN     NaN
21      NaN   NaN          NaN      NaN      NaN  ...     NaN     NaN
22      NaN   NaN          NaN      NaN      NaN  ...     NaN     NaN
23      NaN   NaN          NaN      NaN      NaN  ...     NaN     NaN

                                 Unnamed: 18_level_0 Unnamed: 19_level_0  \
          13     13.1       13.2 Unnamed: 18_level_1 Unnamed: 19_level_1
0         37       37         38                 NaN                 NaN
1     Solewa   Solewa     Solewa                 NaN                 NaN
2     Tie[a]     Mike      Devon                 NaN                 NaN
3   1–1–0[f]      2–1    None[g]                 NaN                 NaN
4        NaN      NaN        NaN                 NaN                 NaN
5       Vote     Vote  Challenge                 NaN                 NaN
6      Devon    Devon     Won[g]                 NaN                 NaN
7        Ben     Mike  Immune[g]                 NaN                 NaN
8        Ben     Mike   Saved[g]                 NaN                 NaN
9       Mike  None[i]    Lost[g]                 NaN                 NaN
10       Ben  None[i]        NaN                 NaN                 NaN
11       NaN      NaN        NaN                 NaN                 NaN
12       NaN      NaN        NaN                 NaN                 NaN
13       NaN      NaN        NaN                 NaN                 NaN
14       NaN      NaN        NaN                 NaN                 NaN
15       NaN      NaN        NaN                 NaN                 NaN
16       NaN      NaN        NaN                 NaN                 NaN
17       NaN      NaN        NaN                 NaN                 NaN
18       NaN      NaN        NaN                 NaN                 NaN
19       NaN      NaN        NaN                 NaN                 NaN
20       NaN      NaN        NaN                 NaN                 NaN
21       NaN      NaN        NaN                 NaN                 NaN
22       NaN      NaN        NaN                 NaN                 NaN
23       NaN      NaN        NaN                 NaN                 NaN

   Unnamed: 20_level_0 Unnamed: 21_level_0 Unnamed: 22_level_0
   Unnamed: 20_level_1 Unnamed: 21_level_1 Unnamed: 22_level_1
0                  NaN                 NaN                 NaN
1                  NaN                 NaN                 NaN
2                  NaN                 NaN                 NaN
3                  NaN                 NaN                 NaN
4                  NaN                 NaN                 NaN
5                  NaN                 NaN                 NaN
6                  NaN                 NaN                 NaN
7                  NaN                 NaN                 NaN
8                  NaN                 NaN                 NaN
9                  NaN                 NaN                 NaN
10                 NaN                 NaN                 NaN
11                 NaN                 NaN                 NaN
12                 NaN                 NaN                 NaN
13                 NaN                 NaN                 NaN
14                 NaN                 NaN                 NaN
15                 NaN                 NaN                 NaN
16                 NaN                 NaN                 NaN
17                 NaN                 NaN                 NaN
18                 NaN                 NaN                 NaN
19                 NaN                 NaN                 NaN
20                 NaN                 NaN                 NaN
21                 NaN                 NaN                 NaN
22                 NaN                 NaN                 NaN
23                 NaN                 NaN                 NaN

[24 rows x 23 columns]

In [ ]:
ben_row = df[df[('Unnamed: 0_level_0', 'Episode')] == 'Ben']
print(ben_row)

  Unnamed: 0_level_0 Original tribes           Switched tribes            \
             Episode               1    2    3               4    5    6
6                Ben         Katrina  NaN  NaN             NaN  NaN  NaN

  Merged tribe              ...                                        \
             7     8   8.1  ...      11      12     13   13.1    13.2
6      Jessica  Desi  Desi  ...  Lauren  Ashley  Devon  Devon  Won[g]

  Unnamed: 18_level_0 Unnamed: 19_level_0 Unnamed: 20_level_0  \
  Unnamed: 18_level_1 Unnamed: 19_level_1 Unnamed: 20_level_1
6                 NaN                 NaN                 NaN

  Unnamed: 21_level_0 Unnamed: 22_level_0
  Unnamed: 21_level_1 Unnamed: 22_level_1
6                 NaN                 NaN

[1 rows x 23 columns]

## Survivor 36

In [ ]:
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
}

r = requests.get('https://en.wikipedia.org/wiki/Survivor:_Ghost_Island', headers=headers)
html_contents = r.text
html_soup = BeautifulSoup(html_contents,"lxml")

In [ ]:
tables = html_soup.find_all('table',class_="wikitable")
tables[0].find_all('a')

[<a href="/wiki/Ocala,_Florida" title="Ocala, Florida">Ocala,<br/>Florida</a>,
 <a href="/wiki/Brooklyn" title="Brooklyn">Brooklyn,<br/>New York</a>,
 <a href="/wiki/Orlando,_Florida" title="Orlando, Florida">Orlando,<br/>Florida</a>,
 <a href="/wiki/Herndon,_Virginia" title="Herndon, Virginia">Herndon,<br/>Virginia</a>,
 <a href="/wiki/Chicago" title="Chicago">Chicago,<br/>Illinois</a>,
 <a href="/wiki/New_York_City" title="New York City">New York,<br/>New York</a>,
 <a href="/wiki/Los_Angeles" title="Los Angeles">Los Angeles,<br/>California</a>,
 <a href="/wiki/Brooklyn" title="Brooklyn">Brooklyn,<br/>New York</a>,
 <a href="/wiki/Houston" title="Houston">Houston,<br/>Texas</a>,
 <a href="/wiki/Brooklyn" title="Brooklyn">Brooklyn,<br/>New York</a>,
 <a href="/wiki/Venice,_Los_Angeles" title="Venice, Los Angeles">Venice Beach,<br/>California</a>,
 <a href="/wiki/Los_Angeles" title="Los Angeles">Los Angeles,<br/>California</a>,
 <a href="/wiki/Los_Angeles" title="Los Angeles">Los Angeles,<br/>California</a>,
 <a href="/wiki/Denver" title="Denver">Denver,<br/>Colorado</a>,
 <a href="/wiki/Satellite_Beach,_Florida" title="Satellite Beach, Florida"><span class="nowrap">Satellite Beach,</span><br/>Florida</a>,
 <a href="/wiki/Kimper,_Kentucky" title="Kimper, Kentucky">Kimper,<br/>Kentucky</a>,
 <a href="/wiki/Cincinnati" title="Cincinnati">Cincinnati,<br/>Ohio</a>,
 <a href="/wiki/Minneapolis" title="Minneapolis">Minneapolis,<br/>Minnesota</a>,
 <a href="#cite_note-2nd_runner-up-4"><span class="cite-bracket">[</span>a<span class="cite-bracket">]</span></a>,
 <a href="/wiki/Nesconset,_New_York" title="Nesconset, New York">Nesconset,<br/>New York</a>,
 <a href="/wiki/Philadelphia" title="Philadelphia">Philadelphia,<br/>Pennsylvania</a>]

In [ ]:
df = pd.read_html(str(tables))[3]
df

/tmp/ipykernel_3126/1238544221.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(tables))[3]

   Unnamed: 0_level_0 Original tribes            First switch           \
              Episode               1        1.1            2        3
0                 Day               3          6            9       12
1               Tribe          Malolo     Malolo       Naviti   Malolo
2          Eliminated        Gonzalez      Jacob       Morgan  Brendan
3               Votes             8–1      5–2–1        4–3–1      5–4
4                 NaN             NaN        NaN          NaN      NaN
5               Voter            Vote       Vote         Vote     Vote
6             Wendell             NaN        NaN       Angela      NaN
7            Domenick             NaN        NaN       Angela      NaN
8              Laurel        Gonzalez      Jacob       Morgan      NaN
9              Angela             NaN        NaN        Libby      NaN
10           Donathan        Gonzalez  Exiled[i]       Morgan      NaN
11          Sebastian             NaN        NaN          NaN  Brendan
12             Kellyn             NaN        NaN          NaN  Brendan
13            Chelsea             NaN        NaN          NaN  Brendan
14            Michael        Gonzalez      James          NaN  Bradley
15              Jenna        Gonzalez      Jacob          NaN  Bradley
16            Desiree             NaN        NaN          NaN  Brendan
17              Libby        Gonzalez      James       Morgan      NaN
18              Chris             NaN        NaN    Exiled[i]      NaN
19            Bradley             NaN        NaN          NaN  Brendan
20              James        Gonzalez      Jacob       Morgan      NaN
21          Stephanie        Gonzalez      Jacob          NaN  Bradley
22            Brendan        Gonzalez      Jacob          NaN  Bradley
23             Morgan             NaN        NaN       Angela      NaN
24              Jacob       Exiled[i]    Michael          NaN      NaN
25           Gonzalez        Donathan        NaN          NaN      NaN

              Second switch          Merged tribe            ...           \
            4             5        6            7         8  ...       11
0          14            17       19           22        25  ...       32
1      Malolo        Malolo   Naviti       Lavita    Lavita  ...   Lavita
2   Stephanie         James  Bradley        Chris     Libby  ...  Chelsea
3         7–1           4–1      4–1         10–2  4–1–0[c]  ...      5–3
4         NaN           NaN      NaN          NaN       NaN  ...      NaN
5        Vote          Vote     Vote         Vote      Vote  ...     Vote
6         NaN           NaN      NaN        Chris   Michael  ...  Chelsea
7         NaN           NaN  Bradley        Chris   Michael  ...  Chelsea
8         NaN           NaN      NaN        Chris     Libby  ...  Chelsea
9         NaN         James      NaN        Libby   Michael  ...  Wendell
10        NaN           NaN  Bradley        Chris   Michael  ...  Chelsea
11  Stephanie           NaN      NaN        Chris   Michael  ...  Chelsea
12  Stephanie         James      NaN        Chris     Libby  ...  Wendell
13  Stephanie           NaN  Bradley        Chris     Libby  ...  Wendell
14  Stephanie         James      NaN        Chris   Wendell  ...      NaN
15  Stephanie           NaN      NaN        Chris   Michael  ...      NaN
16  Stephanie         James      NaN        Libby     Libby  ...      NaN
17        NaN           NaN  Bradley        Chris   Michael  ...      NaN
18        NaN           NaN      NaN      None[h]       NaN  ...      NaN
19  Stephanie           NaN    Libby          NaN       NaN  ...      NaN
20        NaN       Desiree      NaN          NaN       NaN  ...      NaN
21    Desiree           NaN      NaN          NaN       NaN  ...      NaN
22        NaN           NaN      NaN          NaN       NaN  ...      NaN
23        NaN           NaN      NaN          NaN       NaN  ...      NaN
24        NaN           NaN      NaN          NaN       NaN  ...      NaN
25        NaN           NaN      NaN          NaN       NaN  ...      NaN

                                                       Unnamed: 21_level_0  \
          12      12.1         13      13.1       13.2                  13
0         35        35         36        37         38                 NaN
1     Lavita    Lavita     Lavita    Lavita     Lavita                 NaN
2     Tie[b]    Kellyn  Sebastian  Donathan     Angela                 NaN
3      3–3–1       4–1      4–1–1    4–0[e]    None[f]                 NaN
4        NaN       NaN        NaN       NaN        NaN                 NaN
5       Vote      Vote       Vote      Vote  Challenge                 NaN
6     Kellyn    Kellyn  Sebastian  Donathan     Won[f]                 NaN
7     Kellyn    Kellyn  Sebastian  Donathan  Immune[f]                 NaN
8     Kellyn    Kellyn  Sebastian  Donathan   Saved[f]                 NaN
9   Donathan    Kellyn  Sebastian  Donathan    Lost[f]                 NaN
10  Domenick   None[j]   Domenick    Laurel        NaN                 NaN
11  Donathan  Donathan   Donathan       NaN        NaN                 NaN
12  Donathan   None[j]        NaN       NaN        NaN                 NaN
13       NaN       NaN        NaN       NaN        NaN                 NaN
14       NaN       NaN        NaN       NaN        NaN                 NaN
15       NaN       NaN        NaN       NaN        NaN                 NaN
16       NaN       NaN        NaN       NaN        NaN                 NaN
17       NaN       NaN        NaN       NaN        NaN                 NaN
18       NaN       NaN        NaN       NaN        NaN                 NaN
19       NaN       NaN        NaN       NaN        NaN                 NaN
20       NaN       NaN        NaN       NaN        NaN                 NaN
21       NaN       NaN        NaN       NaN        NaN                 NaN
22       NaN       NaN        NaN       NaN        NaN                 NaN
23       NaN       NaN        NaN       NaN        NaN                 NaN
24       NaN       NaN        NaN       NaN        NaN                 NaN
25       NaN       NaN        NaN       NaN        NaN                 NaN

   Unnamed: 22_level_0 Unnamed: 23_level_0 Unnamed: 24_level_0
   Unnamed: 22_level_1 Unnamed: 23_level_1 Unnamed: 24_level_1
0                  NaN                 NaN                 NaN
1                  NaN                 NaN                 NaN
2                  NaN                 NaN                 NaN
3                  NaN                 NaN                 NaN
4                  NaN                 NaN                 NaN
5                  NaN                 NaN                 NaN
6                  NaN                 NaN                 NaN
7                  NaN                 NaN                 NaN
8                  NaN                 NaN                 NaN
9                  NaN                 NaN                 NaN
10                 NaN                 NaN                 NaN
11                 NaN                 NaN                 NaN
12                 NaN                 NaN                 NaN
13                 NaN                 NaN                 NaN
14                 NaN                 NaN                 NaN
15                 NaN                 NaN                 NaN
16                 NaN                 NaN                 NaN
17                 NaN                 NaN                 NaN
18                 NaN                 NaN                 NaN
19                 NaN                 NaN                 NaN
20                 NaN                 NaN                 NaN
21                 NaN                 NaN                 NaN
22                 NaN                 NaN                 NaN
23                 NaN                 NaN                 NaN
24                 NaN                 NaN                 NaN
25                 NaN                 NaN                 NaN

[26 rows x 25 columns]

In [ ]:
wendell_row = df[df[('Unnamed: 0_level_0', 'Episode')] == 'Wendell']
print(wendell_row)

  Unnamed: 0_level_0 Original tribes      First switch            \
             Episode               1  1.1            2    3    4
6            Wendell             NaN  NaN       Angela  NaN  NaN

  Second switch      Merged tribe           ...                           \
              5    6            7        8  ...       11      12    12.1
6           NaN  NaN        Chris  Michael  ...  Chelsea  Kellyn  Kellyn

                               Unnamed: 21_level_0 Unnamed: 22_level_0  \
          13      13.1    13.2                  13 Unnamed: 22_level_1
6  Sebastian  Donathan  Won[f]                 NaN                 NaN

  Unnamed: 23_level_0 Unnamed: 24_level_0
  Unnamed: 23_level_1 Unnamed: 24_level_1
6                 NaN                 NaN

[1 rows x 25 columns]

## Survivor 37

In [ ]:
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
}

r = requests.get('https://en.wikipedia.org/wiki/Survivor:_David_vs._Goliath', headers=headers)
html_contents = r.text
html_soup = BeautifulSoup(html_contents,"lxml")

In [ ]:
tables = html_soup.find_all('table',class_="wikitable")
tables[0].find_all('a')

[<a href="/wiki/Watervliet,_New_York" title="Watervliet, New York">Watervliet,<br/>New York</a>,
 <a href="/wiki/Lakeland,_Florida" title="Lakeland, Florida">Lakeland,<br/>Florida</a>,
 <a href="/wiki/New_York_City" title="New York City">New York City,<br/>New York</a>,
 <a href="/wiki/Houston" title="Houston">Houston,<br/>Texas</a>,
 <a href="/wiki/Irvine,_California" title="Irvine, California">Irvine,<br/>California</a>,
 <a href="/wiki/Los_Angeles" title="Los Angeles">Los Angeles,<br/>California</a>,
 <a href="/wiki/Boston" title="Boston">Boston,<br/>Massachusetts</a>,
 <a href="/wiki/Longview,_Texas" title="Longview, Texas">Longview,<br/>Texas</a>,
 <a href="/wiki/John_Morrison_(wrestler)" title="John Morrison (wrestler)">John Hennigan</a>,
 <a href="/wiki/Los_Angeles" title="Los Angeles">Los Angeles,<br/>California</a>,
 <a href="/wiki/Gainesville,_Florida" title="Gainesville, Florida">Gainesville,<br/>Florida</a>,
 <a href="/wiki/San_Clemente,_California" title="San Clemente, California">San Clemente,<br/>California</a>,
 <a href="/wiki/Houston" title="Houston">Houston,<br/>Texas</a>,
 <a href="/wiki/Denver" title="Denver">Denver,<br/>Colorado</a>,
 <a href="/wiki/Tallahassee,_Florida" title="Tallahassee, Florida">Tallahassee,<br/>Florida</a>,
 <a href="/wiki/Atlanta" title="Atlanta">Atlanta,<br/>Georgia</a>,
 <a href="/wiki/Chapel_Hill,_North_Carolina" title="Chapel Hill, North Carolina">Chapel Hill,<br/>North Carolina</a>,
 <a href="/wiki/San_Diego" title="San Diego">San Diego,<br/>California</a>,
 <a href="/wiki/San_Clemente,_California" title="San Clemente, California">San Clemente,<br/>California</a>,
 <a href="/wiki/Mike_White_(filmmaker)" title="Mike White (filmmaker)">Mike White</a>,
 <a href="/wiki/Los_Angeles" title="Los Angeles">Los Angeles,<br/>California</a>,
 <a href="/wiki/Nick_Wilson_(Survivor_contestant)" title="Nick Wilson (Survivor contestant)">Nick Wilson</a>,
 <a href="/wiki/Williamsburg,_Kentucky" title="Williamsburg, Kentucky">Williamsburg,<br/>Kentucky</a>]

In [ ]:
df = pd.read_html(str(tables))[3]
df

/tmp/ipykernel_3126/1238544221.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(tables))[3]

   Unnamed: 0_level_0 Original tribes                             \
              Episode               1        2        3        4
0                 Day               3        6        9       10
1               Tribe           David    David  Goliath    David
2          Eliminated             Pat  Jessica   Jeremy       Bi
3               Votes    Evacuated[a]      5–4      9–1  Quit[b]
4                 NaN             NaN      NaN      NaN      NaN
5               Voter            Vote     Vote     Vote     Vote
6                Nick             NaN  Jessica      NaN      NaN
7                Mike             NaN      NaN   Jeremy      NaN
8            Angelina             NaN      NaN   Jeremy      NaN
9                Kara             NaN      NaN   Jeremy      NaN
10             Alison             NaN      NaN   Jeremy      NaN
11              Davie             NaN    Lyrsa      NaN      NaN
12          Christian             NaN  Jessica      NaN      NaN
13              Gabby             NaN  Jessica      NaN      NaN
14               Carl             NaN    Lyrsa      NaN      NaN
15               Alec             NaN      NaN   Jeremy      NaN
16                Dan             NaN      NaN   Jeremy      NaN
17               John             NaN      NaN   Jeremy      NaN
18          Elizabeth             NaN  Jessica      NaN      NaN
19              Lyrsa             NaN  Jessica      NaN      NaN
20            Natalie             NaN      NaN   Jeremy      NaN
21            Natalia             NaN      NaN   Jeremy      NaN
22                 Bi             NaN    Lyrsa      NaN     Quit
23             Jeremy             NaN      NaN  Natalie      NaN
24            Jessica             NaN    Lyrsa      NaN      NaN
25                Pat       Evacuated      NaN      NaN      NaN

   Switched tribes                    Merged tribe             ...             \
                 4        5         6            7          8  ...         11
0               11       15        17           20         22  ...         32
1             Vuku   Jabeni    Jabeni     Kalokalo   Kalokalo  ...   Kalokalo
2          Natalia  Natalie     Lyrsa    Elizabeth       John  ...      Gabby
3            3–1–1      3–2       3–1         12–1   3–0–0[c]  ...   2–1–0[e]
4              NaN      NaN       NaN          NaN        NaN  ...        NaN
5             Vote     Vote      Vote         Vote       Vote  ...       Vote
6              NaN  Natalie     Lyrsa    Elizabeth       John  ...  Christian
7              NaN  Natalie     Lyrsa    Elizabeth  Christian  ...      Gabby
8              NaN    Lyrsa     Lyrsa    Elizabeth  Christian  ...      Gabby
9            Davie      NaN       NaN    Elizabeth  Christian  ...  Christian
10             NaN      NaN       NaN    Elizabeth  Christian  ...  Christian
11         Natalia      NaN       NaN    Elizabeth       John  ...  Christian
12             NaN      NaN       NaN    Elizabeth       John  ...     Alison
13             NaN      NaN       NaN    Elizabeth   Angelina  ...  Christian
14       Exiled[i]      NaN       NaN    Elizabeth   Angelina  ...        NaN
15         Natalia      NaN       NaN    Elizabeth  Christian  ...        NaN
16             NaN      NaN       NaN    Elizabeth  Christian  ...        NaN
17             NaN      NaN       NaN    Elizabeth  Christian  ...        NaN
18         Natalia      NaN       NaN     Angelina        NaN  ...        NaN
19             NaN  Natalie  Angelina          NaN        NaN  ...        NaN
20             NaN    Lyrsa       NaN          NaN        NaN  ...        NaN
21       Elizabeth      NaN       NaN          NaN        NaN  ...        NaN
22             NaN      NaN       NaN          NaN        NaN  ...        NaN
23             NaN      NaN       NaN          NaN        NaN  ...        NaN
24             NaN      NaN       NaN          NaN        NaN  ...        NaN
25             NaN      NaN       NaN          NaN        NaN  ...        NaN

                                                                  \
           12        13      13.1       13.2 Unnamed: 19_level_1
0          35        36        37         38                 NaN
1    Kalokalo  Kalokalo  Kalokalo   Kalokalo                 NaN
2   Christian     Davie    Alison       Kara                 NaN
3    3–2–0[f]       4–2       4–1    None[g]                 NaN
4         NaN       NaN       NaN        NaN                 NaN
5        Vote      Vote      Vote  Challenge                 NaN
6   Christian    Alison    Alison  Immune[g]                 NaN
7       Davie     Davie    Alison     Won[g]                 NaN
8   Christian     Davie    Alison   Saved[g]                 NaN
9   Christian     Davie    Alison    Lost[g]                 NaN
10      Davie     Davie      Mike        NaN                 NaN
11     Alison    Alison       NaN        NaN                 NaN
12     Alison       NaN       NaN        NaN                 NaN
13        NaN       NaN       NaN        NaN                 NaN
14        NaN       NaN       NaN        NaN                 NaN
15        NaN       NaN       NaN        NaN                 NaN
16        NaN       NaN       NaN        NaN                 NaN
17        NaN       NaN       NaN        NaN                 NaN
18        NaN       NaN       NaN        NaN                 NaN
19        NaN       NaN       NaN        NaN                 NaN
20        NaN       NaN       NaN        NaN                 NaN
21        NaN       NaN       NaN        NaN                 NaN
22        NaN       NaN       NaN        NaN                 NaN
23        NaN       NaN       NaN        NaN                 NaN
24        NaN       NaN       NaN        NaN                 NaN
25        NaN       NaN       NaN        NaN                 NaN

   Unnamed: 20_level_0 Unnamed: 21_level_0 Unnamed: 22_level_0  \
   Unnamed: 20_level_1 Unnamed: 21_level_1 Unnamed: 22_level_1
0                  NaN                 NaN                 NaN
1                  NaN                 NaN                 NaN
2                  NaN                 NaN                 NaN
3                  NaN                 NaN                 NaN
4                  NaN                 NaN                 NaN
5                  NaN                 NaN                 NaN
6                  NaN                 NaN                 NaN
7                  NaN                 NaN                 NaN
8                  NaN                 NaN                 NaN
9                  NaN                 NaN                 NaN
10                 NaN                 NaN                 NaN
11                 NaN                 NaN                 NaN
12                 NaN                 NaN                 NaN
13                 NaN                 NaN                 NaN
14                 NaN                 NaN                 NaN
15                 NaN                 NaN                 NaN
16                 NaN                 NaN                 NaN
17                 NaN                 NaN                 NaN
18                 NaN                 NaN                 NaN
19                 NaN                 NaN                 NaN
20                 NaN                 NaN                 NaN
21                 NaN                 NaN                 NaN
22                 NaN                 NaN                 NaN
23                 NaN                 NaN                 NaN
24                 NaN                 NaN                 NaN
25                 NaN                 NaN                 NaN

   Unnamed: 23_level_0
   Unnamed: 23_level_1
0                  NaN
1                  NaN
2                  NaN
3                  NaN
4                  NaN
5                  NaN
6                  NaN
7                  NaN
8                  NaN
9                  NaN
10                 NaN
11                 NaN
12                 NaN
13                 NaN
14                 NaN
15                 NaN
16                 NaN
17                 NaN
18                 NaN
19                 NaN
20                 NaN
21                 NaN
22                 NaN
23                 NaN
24                 NaN
25                 NaN

[26 rows x 24 columns]

In [ ]:
nick_row = df[df[('Unnamed: 0_level_0', 'Episode')] == 'Nick']
print(nick_row)

  Unnamed: 0_level_0 Original tribes                    Switched tribes  \
             Episode               1        2    3    4               4
6               Nick             NaN  Jessica  NaN  NaN             NaN

                  Merged tribe        ...                                \
         5      6            7     8  ...         11         12      13
6  Natalie  Lyrsa    Elizabeth  John  ...  Christian  Christian  Alison

                                         Unnamed: 20_level_0  \
     13.1       13.2 Unnamed: 19_level_1 Unnamed: 20_level_1
6  Alison  Immune[g]                 NaN                 NaN

  Unnamed: 21_level_0 Unnamed: 22_level_0 Unnamed: 23_level_0
  Unnamed: 21_level_1 Unnamed: 22_level_1 Unnamed: 23_level_1
6                 NaN                 NaN                 NaN

[1 rows x 24 columns]

## Survivor 38

In [ ]:
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
}

r = requests.get('https://en.wikipedia.org/wiki/Survivor:_Edge_of_Extinction', headers=headers)
html_contents = r.text
html_soup = BeautifulSoup(html_contents,"lxml")

In [ ]:
tables = html_soup.find_all('table',class_="wikitable")
tables[0].find_all('a')

[<a href="#cite_note-16"><span class="cite-bracket">[</span>a<span class="cite-bracket">]</span></a>,
 <a href="/wiki/Ashburn,_Virginia" title="Ashburn, Virginia">Ashburn,<br/>Virginia</a>,
 <a href="#cite_note-PreMergeJury-17"><span class="cite-bracket">[</span>b<span class="cite-bracket">]</span></a>,
 <a href="/wiki/Durham,_North_Carolina" title="Durham, North Carolina">Durham,<br/><span class="nowrap">North Carolina</span></a>,
 <a href="#cite_note-PreMergeJury-17"><span class="cite-bracket">[</span>b<span class="cite-bracket">]</span></a>,
 <a href="/wiki/Survivor:_Ka%C3%B4h_R%C5%8Dng" title="Survivor: Kaôh Rōng">Kaôh Rōng</a>,
 <a href="/wiki/Survivor:_Game_Changers" title="Survivor: Game Changers">Game Changers</a>,
 <a href="/wiki/Los_Angeles" title="Los Angeles">Los Angeles,<br/>California</a>,
 <a href="#cite_note-PreMergeJury-17"><span class="cite-bracket">[</span>b<span class="cite-bracket">]</span></a>,
 <a href="/wiki/Bell,_California" title="Bell, California">Bell,<br/>California</a>,
 <a href="/wiki/Survivor:_Worlds_Apart" title="Survivor: Worlds Apart">Worlds Apart</a>,
 <a href="/wiki/Survivor:_Cambodia" title="Survivor: Cambodia">Cambodia</a>,
 <a href="/wiki/Ogden,_Utah" title="Ogden, Utah">Ogden,<br/>Utah</a>,
 <a href="/wiki/Livermore,_California" title="Livermore, California">Livermore,<br/>California</a>,
 <a href="/wiki/Bethesda,_Maryland" title="Bethesda, Maryland">Bethesda,<br/>Maryland</a>,
 <a href="/wiki/Survivor:_Millennials_vs._Gen_X" title="Survivor: Millennials vs. Gen X">Millennials vs. Gen X</a>,
 <a href="/wiki/Sherman_Oaks,_Los_Angeles" title="Sherman Oaks, Los Angeles"><span class="nowrap">Sherman Oaks</span>,<br/>California</a>,
 <a href="/wiki/Survivor:_San_Juan_del_Sur" title="Survivor: San Juan del Sur">San Juan del Sur</a>,
 <a href="/wiki/Survivor:_Cambodia" title="Survivor: Cambodia">Cambodia</a>,
 <a href="/wiki/Seattle" title="Seattle">Seattle,<br/>Washington</a>,
 <a href="/wiki/Los_Angeles" title="Los Angeles">Los Angeles,<br/>California</a>,
 <a href="/wiki/Ron_Clark_(teacher)" title="Ron Clark (teacher)">Ron Clark</a>,
 <a href="/wiki/Atlanta" title="Atlanta">Atlanta,<br/>Georgia</a>,
 <a href="/wiki/Orlando,_Florida" title="Orlando, Florida">Orlando,<br/>Florida</a>,
 <a href="/wiki/The_Bronx" title="The Bronx">Bronx,<br/>New York</a>,
 <a href="/wiki/Waco,_Texas" title="Waco, Texas">Waco,<br/>Texas</a>,
 <a href="/wiki/Macon,_Georgia" title="Macon, Georgia">Macon,<br/>Georgia</a>,
 <a href="/wiki/New_York_City" title="New York City">New York,<br/>New York</a>,
 <a href="/wiki/Erwin,_Tennessee" title="Erwin, Tennessee">Erwin,<br/>Tennessee</a>,
 <a href="/wiki/Greenville,_South_Carolina" title="Greenville, South Carolina">Greenville,<br/>South Carolina</a>,
 <a href="#cite_note-18"><span class="cite-bracket">[</span>c<span class="cite-bracket">]</span></a>]

In [ ]:
df = pd.read_html(str(tables))[3]
df

/tmp/ipykernel_3126/1238544221.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(tables))[3]

   Unnamed: 0_level_0 Original tribes                 Switched tribes         \
              Episode               1       2       3               4      5
0                 Day               3       6       8              11     13
1               Tribe            Manu    Manu    Manu            Lesu   Manu
2          Eliminated            Reem   Keith   Chris            Rick  Aubry
3               Votes         4–3–1–1   6–1–1     5–2             3–2    4–1
4                 NaN             NaN     NaN     NaN             NaN    NaN
5               Voter            Vote    Vote    Vote            Vote   Vote
6               Chris            Reem   Keith  Kelley             NaN    NaN
7               Gavin             NaN     NaN     NaN             NaN  Aubry
8               Julie             NaN     NaN     NaN             NaN    NaN
9                Rick            Reem   Keith   Chris          Lauren    NaN
10             Lauren           Wendy   Keith   Chris            Rick    NaN
11           Victoria             NaN     NaN     NaN             NaN  Aubry
12             Aurora             NaN     NaN     NaN             NaN    NaN
13                Ron             NaN     NaN     NaN             NaN    NaN
14             Wardog           Wendy   Keith   Chris            Rick    NaN
15             Kelley           Wendy   Keith   Chris            Rick    NaN
16              David            Reem   Keith   Chris          Lauren    NaN
17              Julia             NaN     NaN     NaN             NaN    NaN
18               Eric             NaN     NaN     NaN             NaN  Aubry
19                Joe             NaN     NaN     NaN             NaN    NaN
20              Wendy          Lauren  Kelley  Kelley             NaN  Aubry
21              Aubry             NaN     NaN     NaN             NaN  Wendy
22              Keith            Reem   Wendy     NaN             NaN    NaN
23               Reem          Kelley     NaN     NaN             NaN    NaN

                    Merged tribe          ...                              \
       5.1      5.2            6       7  ...      10        11      11.1
0    16[a]    16[a]           19      22  ...      29        31        31
1     Manu     Manu         Vata    Vata  ...    Vata      Vata      Vata
2   Tie[b]    Wendy          Joe    Eric  ...  Wardog       Ron       Ron
3      4–4      6–0      6–3–2–2   8–2–2  ...     6–2  3–1–0[d]  3–1–0[d]
4      NaN      NaN          NaN     NaN  ...     NaN       NaN       NaN
5     Vote     Vote         Vote    Vote  ...    Vote      Vote      Vote
6      NaN      NaN          NaN     NaN  ...     NaN       NaN       NaN
7   Lauren    Wendy          Joe    Eric  ...  Wardog       Ron    Ron[h]
8      NaN      NaN          Joe  Lauren  ...  Wardog      Rick      Rick
9      NaN      NaN       Kelley  Lauren  ...  Aurora    Aurora    Aurora
10   Wendy  None[i]        David    Eric  ...  Wardog       Ron       Ron
11  Lauren    Wendy          Joe    Eric  ...  Wardog      Rick      Rick
12     NaN      NaN         Rick    Eric  ...  Wardog      Rick      Rick
13     NaN      NaN          Joe  Kelley  ...  Wardog      Rick      Rick
14   Wendy    Wendy        David    Eric  ...  Aurora       NaN       NaN
15   Wendy    Wendy        David    Eric  ...     NaN       NaN       NaN
16   Wendy    Wendy       Kelley    Eric  ...     NaN       NaN       NaN
17     NaN      NaN          Joe    Eric  ...     NaN       NaN       NaN
18  Lauren    Wendy          Joe  Kelley  ...     NaN       NaN       NaN
19     NaN      NaN         Rick     NaN  ...     NaN       NaN       NaN
20  Lauren  None[i]          NaN     NaN  ...     NaN       NaN       NaN
21     NaN      NaN          NaN     NaN  ...     NaN       NaN       NaN
22     NaN      NaN          NaN     NaN  ...     NaN       NaN       NaN
23     NaN      NaN          NaN     NaN  ...     NaN       NaN       NaN

                                        Unnamed: 20_level_0  \
        12        13    13.1       13.2 Unnamed: 20_level_1
0       34        36      37         38                 NaN
1     Vata      Vata    Vata       Vata                 NaN
2   Aurora  Victoria  Lauren       Rick                 NaN
3      5–1  2–0–0[e]  2–0[f]    None[g]                 NaN
4      NaN       NaN     NaN        NaN                 NaN
5     Vote      Vote    Vote  Challenge                 NaN
6      NaN  Victoria  Lauren     Won[g]                 NaN
7   Aurora      Rick   Chris   Saved[g]                 NaN
8   Aurora      Rick   Chris   Saved[g]                 NaN
9   Aurora  Victoria  Lauren    Lost[g]                 NaN
10  Aurora      Rick   Chris        NaN                 NaN
11  Aurora     Chris     NaN        NaN                 NaN
12   Julie       NaN     NaN        NaN                 NaN
13     NaN       NaN     NaN        NaN                 NaN
14     NaN       NaN     NaN        NaN                 NaN
15     NaN       NaN     NaN        NaN                 NaN
16     NaN       NaN     NaN        NaN                 NaN
17     NaN       NaN     NaN        NaN                 NaN
18     NaN       NaN     NaN        NaN                 NaN
19     NaN       NaN     NaN        NaN                 NaN
20     NaN       NaN     NaN        NaN                 NaN
21     NaN       NaN     NaN        NaN                 NaN
22     NaN       NaN     NaN        NaN                 NaN
23     NaN       NaN     NaN        NaN                 NaN

   Unnamed: 21_level_0 Unnamed: 22_level_0
   Unnamed: 21_level_1 Unnamed: 22_level_1
0                  NaN                 NaN
1                  NaN                 NaN
2                  NaN                 NaN
3                  NaN                 NaN
4                  NaN                 NaN
5                  NaN                 NaN
6                  NaN                 NaN
7                  NaN                 NaN
8                  NaN                 NaN
9                  NaN                 NaN
10                 NaN                 NaN
11                 NaN                 NaN
12                 NaN                 NaN
13                 NaN                 NaN
14                 NaN                 NaN
15                 NaN                 NaN
16                 NaN                 NaN
17                 NaN                 NaN
18                 NaN                 NaN
19                 NaN                 NaN
20                 NaN                 NaN
21                 NaN                 NaN
22                 NaN                 NaN
23                 NaN                 NaN

[24 rows x 23 columns]

In [ ]:
chrisU_row = df[df[('Unnamed: 0_level_0', 'Episode')] == 'Chris']
print(chrisU_row)

  Unnamed: 0_level_0 Original tribes                Switched tribes            \
             Episode               1      2       3               4    5  5.1
6              Chris            Reem  Keith  Kelley             NaN  NaN  NaN

       Merged tribe       ...                                                \
   5.2            6    7  ...   10   11 11.1   12        13    13.1    13.2
6  NaN          NaN  NaN  ...  NaN  NaN  NaN  NaN  Victoria  Lauren  Won[g]

  Unnamed: 20_level_0 Unnamed: 21_level_0 Unnamed: 22_level_0
  Unnamed: 20_level_1 Unnamed: 21_level_1 Unnamed: 22_level_1
6                 NaN                 NaN                 NaN

[1 rows x 23 columns]

## Survivor 39

In [ ]:
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
}

r = requests.get('https://en.wikipedia.org/wiki/Survivor:_Island_of_the_Idols', headers=headers)
html_contents = r.text
html_soup = BeautifulSoup(html_contents,"lxml")

In [ ]:
tables = html_soup.find_all('table',class_="wikitable")
tables[0].find_all('a')

[<a href="#cite_note-17"><span class="cite-bracket">[</span>17<span class="cite-bracket">]</span></a>,
 <a href="/wiki/Ronnie_Bardah" title="Ronnie Bardah">Ronnie Bardah</a>,
 <a href="/wiki/Henderson,_Nevada" title="Henderson, Nevada">Henderson,<br/>Nevada</a>,
 <a href="/wiki/Durham,_North_Carolina" title="Durham, North Carolina">Durham,<br/>North Carolina</a>,
 <a href="/wiki/Merced,_California" title="Merced, California">Merced,<br/>California</a>,
 <a href="/wiki/Los_Angeles" title="Los Angeles">Los Angeles,<br/>California</a>,
 <a href="/wiki/Tom_Laidlaw" title="Tom Laidlaw">Tom Laidlaw</a>,
 <a class="mw-redirect" href="/wiki/Brampton,_Ontario" title="Brampton, Ontario">Brampton,<br/>Ontario</a>,
 <a href="/wiki/New_York_City" title="New York City">New York,<br/>New York</a>,
 <a href="/wiki/Harrisonburg,_Virginia" title="Harrisonburg, Virginia">Harrisonburg,<br/>Virginia</a>,
 <a href="/wiki/Philadelphia" title="Philadelphia">Philadelphia,<br/>Pennsylvania</a>,
 <a href="/wiki/Providence,_Rhode_Island" title="Providence, Rhode Island">Providence,<br/>Rhode Island</a>,
 <a href="/wiki/Warwick,_Rhode_Island" title="Warwick, Rhode Island">Warwick,<br/>Rhode Island</a>,
 <a href="/wiki/Tacoma,_Washington" title="Tacoma, Washington">Tacoma,<br/>Washington</a>,
 <a href="/wiki/Elizabeth_Beisel" title="Elizabeth Beisel">Elizabeth Beisel</a>,
 <a href="/wiki/Saunderstown,_Rhode_Island" title="Saunderstown, Rhode Island">Saunderstown,<br/>Rhode Island</a>,
 <a href="/wiki/Houston" title="Houston">Houston,<br/>Texas</a>,
 <a href="/wiki/Rockholds,_Kentucky" title="Rockholds, Kentucky">Rockholds,<br/>Kentucky</a>,
 <a href="/wiki/Los_Angeles" title="Los Angeles">Los Angeles,<br/>California</a>,
 <a href="/wiki/Palm_Bay,_Florida" title="Palm Bay, Florida">Palm Bay,<br/>Florida</a>,
 <a href="/wiki/Glendale,_California" title="Glendale, California">Glendale,<br/>California</a>,
 <a href="/wiki/North_Potomac,_Maryland" title="North Potomac, Maryland"><span class="nowrap">North Potomac</span>,<br/>Maryland</a>,
 <a href="/wiki/New_York_City" title="New York City">New York,<br/>New York</a>,
 <a href="/wiki/Long_Beach,_New_York" title="Long Beach, New York">Long Beach,<br/>New York</a>]

In [ ]:
df = pd.read_html(str(tables))[3]
df

/tmp/ipykernel_3126/1238544221.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(tables))[3]

   Unnamed: 0_level_0 Original tribes                             \
              Episode               1      2         3         4
0                 Day               3      6         8        11
1               Tribe           Lairo  Vokai     Lairo     Lairo
2          Eliminated          Ronnie  Molly     Vince   Chelsea
3               Votes             7–2  7–2–1     5–3–1       6–2
4                 NaN             NaN    NaN       NaN       NaN
5               Voter            Vote   Vote      Vote      Vote
6               Tommy             NaN  Molly       NaN       NaN
7                Dean          Ronnie    NaN  Karishma  Karishma
8               Noura             NaN  Molly       NaN       NaN
9              Lauren             NaN  Molly       NaN       NaN
10              Janet             NaN  Molly       NaN       NaN
11                Dan             NaN  Molly       NaN       NaN
12             Elaine          Ronnie    NaN     Vince   Chelsea
13           Karishma          Ronnie    NaN     Vince   Chelsea
14          Elizabeth         None[i]    NaN     Vince   Chelsea
15              Missy          Ronnie    NaN     Vince   Chelsea
16              Aaron           Vince    NaN  Karishma   Chelsea
17              Jamal             NaN  Jason       NaN       NaN
18             Kellee             NaN  Molly       NaN       NaN
19               Jack             NaN  Jason       NaN       NaN
20              Jason             NaN  Molly       NaN       NaN
21                Tom          Ronnie    NaN  Karishma   Chelsea
22            Chelsea          Ronnie    NaN     Vince  Karishma
23              Vince          Ronnie    NaN       Tom       NaN
24              Molly             NaN  Noura       NaN       NaN
25             Ronnie           Vince    NaN       NaN       NaN

   Switched tribes                  Merged tribe                      \
                 5        6       7            8       8.1         9
0               14       16      19           22        24     27[a]
1            Lairo    Vokai   Lairo     Lumuwaku  Lumuwaku  Lumuwaku
2              Tom    Jason    Jack       Kellee     Jamal     Aaron
3              5–2      4–3  2–0[c]          8–5  6–3–0[d]       5–1
4              NaN      NaN     NaN          NaN       NaN       NaN
5             Vote     Vote    Vote         Vote      Vote      Vote
6              NaN   Elaine     NaN       Kellee     Jamal       NaN
7         Karishma      NaN    Jack       Kellee     Jamal     Aaron
8          None[i]      NaN    Jack          Dan     Jamal     Aaron
9              NaN   Elaine     NaN       Kellee  Karishma     Aaron
10             Tom      NaN    Dean          Dan     Jamal     Aaron
11             NaN   Elaine     NaN       Kellee     Jamal     Aaron
12             NaN    Jason     NaN       Kellee  Karishma       NaN
13             Tom      NaN    Dean          Dan     Janet       NaN
14             NaN    Jason     NaN       Kellee  Karishma       NaN
15             NaN    Jason     NaN       Kellee     Janet       NaN
16             NaN    Jason     NaN       Kellee     Jamal     Janet
17             Tom      NaN    Dean          Dan   None[i]       NaN
18             Tom      NaN    Dean          Dan       NaN       NaN
19             Tom      NaN    Dean          NaN       NaN       NaN
20             NaN  None[k]     NaN          NaN       NaN       NaN
21        Karishma      NaN     NaN          NaN       NaN       NaN
22             NaN      NaN     NaN          NaN       NaN       NaN
23             NaN      NaN     NaN          NaN       NaN       NaN
24             NaN      NaN     NaN          NaN       NaN       NaN
25             NaN      NaN     NaN          NaN       NaN       NaN

                                                                              \
         9.1         10       10.1        11        12        12.1        13
0      27[a]         30         30        32        35          36        37
1   Lumuwaku   Lumuwaku   Lumuwaku  Lumuwaku  Lumuwaku    Lumuwaku  Lumuwaku
2      Missy     Tie[b]  Elizabeth  Karishma    Elaine         Dan     Janet
3        3–2   1–1–0[e]        7–0       5–3       5–2  Ejected[f]    4–1[g]
4        NaN        NaN        NaN       NaN       NaN         NaN       NaN
5       Vote       Vote       Vote      Vote      Vote        Vote      Vote
6      Missy   Karishma  Elizabeth  Karishma    Elaine         NaN     Janet
7        NaN   Karishma  Elizabeth  Karishma    Elaine         NaN     Janet
8        NaN   Karishma  Elizabeth  Karishma    Elaine         NaN     Janet
9        NaN   Karishma  Elizabeth  Karishma    Elaine         NaN     Janet
10       NaN   Karishma    None[j]     Noura    Elaine         NaN    Lauren
11       NaN  Elizabeth  Elizabeth     Noura     Noura     Ejected       NaN
12     Missy   Karishma  Elizabeth  Karishma     Noura         NaN       NaN
13     Missy      Janet  Elizabeth     Noura       NaN         NaN       NaN
14     Tommy   Karishma    None[j]       NaN       NaN         NaN       NaN
15     Tommy        NaN        NaN       NaN       NaN         NaN       NaN
16       NaN        NaN        NaN       NaN       NaN         NaN       NaN
17       NaN        NaN        NaN       NaN       NaN         NaN       NaN
18       NaN        NaN        NaN       NaN       NaN         NaN       NaN
19       NaN        NaN        NaN       NaN       NaN         NaN       NaN
20       NaN        NaN        NaN       NaN       NaN         NaN       NaN
21       NaN        NaN        NaN       NaN       NaN         NaN       NaN
22       NaN        NaN        NaN       NaN       NaN         NaN       NaN
23       NaN        NaN        NaN       NaN       NaN         NaN       NaN
24       NaN        NaN        NaN       NaN       NaN         NaN       NaN
25       NaN        NaN        NaN       NaN       NaN         NaN       NaN


         13.1
0          38
1    Lumuwaku
2      Lauren
3     None[h]
4         NaN
5   Challenge
6    Saved[h]
7      Won[h]
8   Immune[h]
9     Lost[h]
10        NaN
11        NaN
12        NaN
13        NaN
14        NaN
15        NaN
16        NaN
17        NaN
18        NaN
19        NaN
20        NaN
21        NaN
22        NaN
23        NaN
24        NaN
25        NaN

In [ ]:
tommy_row = df[df[('Unnamed: 0_level_0', 'Episode')] == 'Tommy']
print(tommy_row)

  Unnamed: 0_level_0 Original tribes                  Switched tribes          \
             Episode               1      2    3    4               5       6
6              Tommy             NaN  Molly  NaN  NaN             NaN  Elaine

       Merged tribe                                                            \
     7            8    8.1    9    9.1        10       10.1        11      12
6  NaN       Kellee  Jamal  NaN  Missy  Karishma  Elizabeth  Karishma  Elaine


  12.1     13      13.1
6  NaN  Janet  Saved[h]

## Survivor 40

In [ ]:
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
}

r = requests.get('https://en.wikipedia.org/wiki/Survivor:_Winners_at_War', headers=headers)
html_contents = r.text
html_soup = BeautifulSoup(html_contents,"lxml")

In [ ]:
tables = html_soup.find_all('table',class_="wikitable")
tables[0].find_all('a')

[<a href="#cite_note-27"><span class="cite-bracket">[</span>a<span class="cite-bracket">]</span></a>,
 <a href="#cite_note-28"><span class="cite-bracket">[</span>b<span class="cite-bracket">]</span></a>,
 <a class="mw-redirect" href="/wiki/Natalie_and_Nadiya_Anderson" title="Natalie and Nadiya Anderson">Natalie Anderson</a>,
 <a href="#cite_note-PreMergeJury-29"><span class="cite-bracket">[</span>c<span class="cite-bracket">]</span></a>,
 <a href="/wiki/Amber_Mariano" title="Amber Mariano">Amber Mariano</a>,
 <a href="/wiki/Survivor:_The_Australian_Outback" title="Survivor: The Australian Outback">The Australian Outback</a>,
 <a href="/wiki/Survivor:_All-Stars" title="Survivor: All-Stars">All-Stars</a>,
 <a href="/wiki/Pensacola,_Florida" title="Pensacola, Florida">Pensacola,<br/>Florida</a>,
 <a href="#cite_note-PreMergeJury-29"><span class="cite-bracket">[</span>c<span class="cite-bracket">]</span></a>,
 <a href="/wiki/Danni_Boatwright" title="Danni Boatwright">Danni Boatwright</a>,
 <a href="/wiki/Survivor:_Guatemala" title="Survivor: Guatemala">Guatemala</a>,
 <a href="/wiki/Shawnee,_Kansas" title="Shawnee, Kansas">Shawnee,<br/>Kansas</a>,
 <a href="#cite_note-PreMergeJury-29"><span class="cite-bracket">[</span>c<span class="cite-bracket">]</span></a>,
 <a href="/wiki/Ethan_Zohn" title="Ethan Zohn">Ethan Zohn</a>,
 <a href="/wiki/Survivor:_Africa" title="Survivor: Africa">Africa</a>,
 <a href="/wiki/Survivor:_All-Stars" title="Survivor: All-Stars">All-Stars</a>,
 <a href="/wiki/Hillsborough,_New_Hampshire" title="Hillsborough, New Hampshire">Hillsborough,<br/>New Hampshire</a>,
 <a href="#cite_note-PreMergeJury-29"><span class="cite-bracket">[</span>c<span class="cite-bracket">]</span></a>,
 <a href="/wiki/Tyson_Apostol" title="Tyson Apostol">Tyson Apostol</a>,
 <a href="/wiki/Rob_Mariano" title="Rob Mariano">Rob Mariano</a>,
 <a href="/wiki/Survivor:_Marquesas" title="Survivor: Marquesas">Marquesas</a>,
 <a href="/wiki/Survivor:_All-Stars" title="Survivor: All-Stars">All-Stars</a>,
 <a href="/wiki/Survivor:_Heroes_vs._Villains" title="Survivor: Heroes vs. Villains">Heroes vs. Villains</a>,
 <a href="/wiki/Survivor:_Redemption_Island" title="Survivor: Redemption Island">Redemption Island</a>,
 <a href="/wiki/Pensacola,_Florida" title="Pensacola, Florida">Pensacola,<br/>Florida</a>,
 <a href="#cite_note-PreMergeJury-29"><span class="cite-bracket">[</span>c<span class="cite-bracket">]</span></a>,
 <a href="/wiki/Parvati_Shallow" title="Parvati Shallow">Parvati Shallow</a>,
 <a href="/wiki/Survivor:_Cook_Islands" title="Survivor: Cook Islands">Cook Islands</a>,
 <a href="/wiki/Survivor:_Micronesia" title="Survivor: Micronesia">Micronesia</a>,
 <a href="/wiki/Survivor:_Heroes_vs._Villains" title="Survivor: Heroes vs. Villains">Heroes vs. Villains</a>,
 <a href="/wiki/Los_Angeles" title="Los Angeles">Los Angeles,<br/>California</a>,
 <a href="#cite_note-PreMergeJury-29"><span class="cite-bracket">[</span>c<span class="cite-bracket">]</span></a>,
 <a href="/wiki/Sandra_Diaz-Twine" title="Sandra Diaz-Twine">Sandra Diaz-Twine</a>,
 <a href="/wiki/Survivor:_Pearl_Islands" title="Survivor: Pearl Islands">Pearl Islands</a>,
 <a href="/wiki/Survivor:_Heroes_vs._Villains" title="Survivor: Heroes vs. Villains">Heroes vs. Villains</a>,
 <a href="/wiki/Survivor:_Game_Changers" title="Survivor: Game Changers">Game Changers</a>,
 <a href="/wiki/Riverview,_Florida" title="Riverview, Florida">Riverview,<br/>Florida</a>,
 <a href="/wiki/Yul_Kwon" title="Yul Kwon">Yul Kwon</a>,
 <a href="/wiki/Survivor:_Cook_Islands" title="Survivor: Cook Islands">Cook Islands</a>,
 <a href="/wiki/Los_Altos,_California" title="Los Altos, California">Los Altos,<br/>California</a>,
 <a href="#cite_note-PreMergeJury-29"><span class="cite-bracket">[</span>c<span class="cite-bracket">]</span></a>,
 <a href="/wiki/Survivor:_Ghost_Island" title="Survivor: Ghost Island">Ghost Island</a>,
 <a href="/wiki/Philadelphia" title="Philadelphia">Philadelphia,<br/>Pennsylvania</a>,
 <a href="/wiki/Survivor:_Millennials_vs._Gen_X" title="Survivor: Millennials vs. Gen X">Millennials vs. Gen X</a>,
 <a href="/wiki/Los_Angeles" title="Los Angeles">Los Angeles,<br/>California</a>,
 <a href="/wiki/Tyson_Apostol" title="Tyson Apostol">Tyson Apostol</a>,
 <a href="/wiki/Survivor:_Tocantins" title="Survivor: Tocantins">Tocantins</a>,
 <a href="/wiki/Survivor:_Heroes_vs._Villains" title="Survivor: Heroes vs. Villains">Heroes vs. Villains</a>,
 <a href="/wiki/Survivor:_Blood_vs._Water" title="Survivor: Blood vs. Water">Blood vs. Water</a>,
 <a href="/wiki/Mesa,_Arizona" title="Mesa, Arizona">Mesa,<br/>Arizona</a>,
 <a href="#cite_note-switched-30"><span class="cite-bracket">[</span>d<span class="cite-bracket">]</span></a>,
 <a href="/wiki/Survivor:_South_Pacific" title="Survivor: South Pacific">South Pacific</a>,
 <a href="/wiki/Santa_Monica,_California" title="Santa Monica, California">Santa Monica,<br/>California</a>,
 <a href="/wiki/Survivor:_One_World" title="Survivor: One World">One World</a>,
 <a href="/wiki/San_Antonio" title="San Antonio">San Antonio,<br/>Texas</a>,
 <a href="/wiki/Jeremy_Collins" title="Jeremy Collins">Jeremy Collins</a>,
 <a href="/wiki/Survivor:_San_Juan_del_Sur" title="Survivor: San Juan del Sur">San Juan del Sur</a>,
 <a href="/wiki/Survivor:_Cambodia" title="Survivor: Cambodia">Cambodia</a>,
 <a href="/wiki/Foxborough,_Massachusetts" title="Foxborough, Massachusetts">Foxborough,<br/>Massachusetts</a>,
 <a href="/wiki/Nick_Wilson_(Survivor_contestant)" title="Nick Wilson (Survivor contestant)">Nick Wilson</a>,
 <a href="/wiki/Survivor:_David_vs._Goliath" title="Survivor: David vs. Goliath">David vs. Goliath</a>,
 <a href="/wiki/Williamsburg,_Kentucky" title="Williamsburg, Kentucky">Williamsburg,<br/>Kentucky</a>,
 <a href="/wiki/Survivor:_Philippines" title="Survivor: Philippines">Philippines</a>,
 <a href="/wiki/Marion,_Iowa" title="Marion, Iowa">Marion,<br/>Iowa</a>,
 <a href="/wiki/Survivor:_Heroes_vs._Healers_vs._Hustlers" title="Survivor: Heroes vs. Healers vs. Hustlers">Heroes vs. Healers vs. Hustlers</a>,
 <a href="/wiki/Boise,_Idaho" title="Boise, Idaho">Boise,<br/>Idaho</a>,
 <a href="/wiki/Sarah_Lacina" title="Sarah Lacina">Sarah Lacina</a>,
 <a href="/wiki/Survivor:_Cagayan" title="Survivor: Cagayan">Cagayan</a>,
 <a href="/wiki/Survivor:_Game_Changers" title="Survivor: Game Changers">Game Changers</a>,
 <a href="/wiki/Cedar_Rapids,_Iowa" title="Cedar Rapids, Iowa">Cedar Rapids,<br/>Iowa</a>,
 <a href="/wiki/Survivor:_Ka%C3%B4h_R%C5%8Dng" title="Survivor: Kaôh Rōng">Kaôh Rōng</a>,
 <a href="/wiki/Hoboken,_New_Jersey" title="Hoboken, New Jersey">Hoboken,<br/>New Jersey</a>,
 <a class="mw-redirect" href="/wiki/Natalie_and_Nadiya_Anderson" title="Natalie and Nadiya Anderson">Natalie Anderson</a>,
 <a href="/wiki/Survivor:_San_Juan_del_Sur" title="Survivor: San Juan del Sur">San Juan del Sur</a>,
 <a href="/wiki/Edgewater,_New_Jersey" title="Edgewater, New Jersey">Edgewater,<br/>New Jersey</a>,
 <a href="#cite_note-switched-30"><span class="cite-bracket">[</span>d<span class="cite-bracket">]</span></a>,
 <a href="/wiki/Tony_Vlachos" title="Tony Vlachos">Tony Vlachos</a>,
 <a href="/wiki/Survivor:_Cagayan" title="Survivor: Cagayan">Cagayan</a>,
 <a href="/wiki/Survivor:_Game_Changers" title="Survivor: Game Changers">Game Changers</a>,
 <a href="/wiki/Jersey_City,_New_Jersey" title="Jersey City, New Jersey">Jersey City,<br/>New Jersey</a>]

In [ ]:
df = pd.read_html(str(tables))[3]
df

/tmp/ipykernel_3126/1238544221.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(tables))[3]

   Unnamed: 0_level_0 Original tribes                                  \
              Episode               1    1.1        2        3      4
0                 Day               2      3        6        9     11
1               Tribe            Sele  Dakal     Sele     Sele  Dakal
2          Eliminated         Natalie  Amber    Danni    Ethan  Tyson
3               Votes           7–2–1  6–3–1      8–1    4–3–1  7–1–1
4                 NaN             NaN    NaN      NaN      NaN    NaN
5               Voter            Vote   Vote     Vote     Vote   Vote
6                Tony             NaN    Kim      NaN      NaN  Tyson
7             Natalie          Denise    NaN      NaN      NaN    NaN
8             Michele          Denise    NaN    Danni    Ethan    NaN
9               Sarah             NaN    Kim      NaN      NaN  Tyson
10                Ben         Natalie    NaN    Danni    Ethan    NaN
11             Denise         Natalie    NaN    Danni    Ethan    NaN
12               Nick             NaN  Amber      NaN      NaN    Kim
13             Jeremy            Adam    NaN    Danni    Ethan    NaN
14                Kim             NaN  Amber      NaN      NaN  Tyson
15             Sophie             NaN    Kim      NaN      NaN  Tyson
16              Tyson             NaN  Amber      NaN      NaN   Nick
17               Adam         Natalie    NaN    Danni  Parvati    NaN
18            Wendell             NaN  Amber      NaN      NaN  Tyson
19                Yul             NaN  Amber      NaN      NaN  Tyson
20             Sandra             NaN  Amber      NaN      NaN  Tyson
21            Parvati         Natalie    NaN    Danni     Adam    NaN
22                Rob         Natalie    NaN    Danni     Adam    NaN
23              Ethan         Natalie    NaN    Danni     Adam    NaN
24              Danni         Natalie    NaN  Parvati      NaN    NaN
25              Amber             NaN   Nick      NaN      NaN    NaN

   Switched tribes                            ... Merged tribe            \
                 5        6     6.1        7  ...           10      10.1
0               14       16      16       18  ...           25        25
1             Yara     Sele   Dakal     Sele  ...         Koru      Koru
2              Rob  Parvati  Sandra      Yul  ...        Tyson     Tyson
3              4–1      3–2  1–0[b]      3–1  ...     5–2–0[c]  5–2–0[c]
4              NaN      NaN     NaN      NaN  ...          NaN       NaN
5             Vote     Vote    Vote     Vote  ...         Vote      Vote
6              NaN      NaN  Denise      NaN  ...        Tyson     Tyson
7              NaN      NaN     NaN      NaN  ...          NaN       NaN
8              NaN  Wendell     NaN      Yul  ...        Tyson     Tyson
9              Rob      NaN     NaN      NaN  ...       Denise  Tyson[f]
10             Rob      NaN     NaN      NaN  ...        Tyson     Tyson
11             NaN      NaN  Sandra      NaN  ...      None[f]   None[f]
12             NaN  Parvati     NaN      Yul  ...        Tyson     Tyson
13             NaN      NaN  Denise      NaN  ...      None[g]   None[g]
14             NaN      NaN  Denise      NaN  ...       Sophie    Sophie
15             Rob      NaN     NaN      NaN  ...       Denise    Denise
16             NaN      NaN     NaN      NaN  ...       Sophie    Sophie
17             Rob      NaN     NaN      NaN  ...          NaN       NaN
18             NaN  Parvati     NaN      Yul  ...          NaN       NaN
19             NaN  Parvati     NaN  Wendell  ...          NaN       NaN
20             NaN      NaN  Denise      NaN  ...          NaN       NaN
21             NaN  Wendell     NaN      NaN  ...          NaN       NaN
22           Sarah      NaN     NaN      NaN  ...          NaN       NaN
23             NaN      NaN     NaN      NaN  ...          NaN       NaN
24             NaN      NaN     NaN      NaN  ...          NaN       NaN
25             NaN      NaN     NaN      NaN  ...          NaN       NaN


         11      12        13    13.1       14     14.1     14.2       14.3
0        28      29        31      34       36       36       37         38
1      Koru    Koru      Koru    Koru     Koru     Koru     Koru       Koru
2    Sophie     Kim    Jeremy    Nick  None[a]   Denise      Ben      Sarah
3     4–3–2     5–3  3–2–0[d]     4–2   0–0[a]      4–0      3–2    None[e]
4       NaN     NaN       NaN     NaN      NaN      NaN      NaN        NaN
5      Vote    Vote      Vote    Vote     Vote     Vote     Vote  Challenge
6    Sophie     Kim    Jeremy    Nick  Natalie   Denise  Michele     Won[e]
7       NaN     NaN       NaN     NaN      Ben   Denise      Ben  Immune[e]
8    Sophie  Jeremy       Ben  Denise      Ben   Denise      Ben   Saved[e]
9   Michele     Kim   Michele    Nick  Natalie  None[a]      Ben    Lost[e]
10   Jeremy     Kim    Jeremy    Nick  Natalie   Denise  Michele        NaN
11   Jeremy  Jeremy   Michele    Nick  Natalie  None[a]      NaN        NaN
12   Sophie     Kim    Jeremy  Denise      NaN      NaN      NaN        NaN
13   Sophie     Kim       Ben     NaN      NaN      NaN      NaN        NaN
14  Michele  Jeremy       NaN     NaN      NaN      NaN      NaN        NaN
15   Jeremy     NaN       NaN     NaN      NaN      NaN      NaN        NaN
16      NaN     NaN       NaN     NaN      NaN      NaN      NaN        NaN
17      NaN     NaN       NaN     NaN      NaN      NaN      NaN        NaN
18      NaN     NaN       NaN     NaN      NaN      NaN      NaN        NaN
19      NaN     NaN       NaN     NaN      NaN      NaN      NaN        NaN
20      NaN     NaN       NaN     NaN      NaN      NaN      NaN        NaN
21      NaN     NaN       NaN     NaN      NaN      NaN      NaN        NaN
22      NaN     NaN       NaN     NaN      NaN      NaN      NaN        NaN
23      NaN     NaN       NaN     NaN      NaN      NaN      NaN        NaN
24      NaN     NaN       NaN     NaN      NaN      NaN      NaN        NaN
25      NaN     NaN       NaN     NaN      NaN      NaN      NaN        NaN

[26 rows x 22 columns]

In [ ]:
tony2_row = df[df[('Unnamed: 0_level_0', 'Episode')] == 'Tony']
print(tony2_row)

  Unnamed: 0_level_0 Original tribes                       Switched tribes  \
             Episode               1  1.1    2    3      4               5
6               Tony             NaN  Kim  NaN  NaN  Tyson             NaN

                     ... Merged tribe                                    \
     6     6.1    7  ...           10   10.1      11   12      13  13.1
6  NaN  Denise  NaN  ...        Tyson  Tyson  Sophie  Kim  Jeremy  Nick


        14    14.1     14.2    14.3
6  Natalie  Denise  Michele  Won[e]

[1 rows x 22 columns]

## Survivor 41

In [ ]:
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
}

r = requests.get('https://en.wikipedia.org/wiki/Survivor:_41', headers=headers)
html_contents = r.text
html_soup = BeautifulSoup(html_contents,"lxml")

In [ ]:
tables = html_soup.find_all('table',class_="wikitable")
tables[0].find_all('a')

[<a href="#cite_note-28"><span class="cite-bracket">[</span>27<span class="cite-bracket">]</span></a>,
 <a class="mw-redirect" href="/wiki/San_Antonio,_Texas" title="San Antonio, Texas">San Antonio,<br/>Texas</a>,
 <a class="mw-redirect" href="/wiki/Boston,_Massachusetts" title="Boston, Massachusetts">Boston,<br/>Massachusetts</a>,
 <a class="mw-redirect" href="/wiki/Chicago,_Illinois" title="Chicago, Illinois">Chicago,<br/>Illinois</a>,
 <a href="/wiki/Shawnee,_Wyoming" title="Shawnee, Wyoming">Shawnee,<br/>Wyoming</a>,
 <a class="mw-redirect" href="/wiki/Oklahoma_City,_Oklahoma" title="Oklahoma City, Oklahoma">Oklahoma City,<br/>Oklahoma</a>,
 <a href="/wiki/Portland,_Oregon" title="Portland, Oregon">Portland,<br/>Oregon</a>,
 <a class="mw-redirect" href="/wiki/Brooklyn,_New_York" title="Brooklyn, New York">Brooklyn,<br/>New York</a>,
 <a href="#cite_note-29"><span class="cite-bracket">[</span>a<span class="cite-bracket">]</span></a>,
 <a href="/wiki/Plainview,_New_York" title="Plainview, New York">Plainview,<br/>New York</a>,
 <a href="/wiki/Morgan_Hill,_California" title="Morgan Hill, California">Morgan Hill,<br/>California</a>,
 <a href="/wiki/Arlington,_Massachusetts" title="Arlington, Massachusetts">Arlington,<br/>Massachusetts</a>,
 <a href="/wiki/Washington,_D.C." title="Washington, D.C.">Washington,<br/>D.C.</a>,
 <a href="/wiki/Washington,_D.C." title="Washington, D.C.">Washington,<br/>D.C.</a>,
 <a href="/wiki/Danny_McCray" title="Danny McCray">Danny McCray</a>,
 <a href="/wiki/Frisco,_Texas" title="Frisco, Texas">Frisco,<br/>Texas</a>,
 <a href="/wiki/Sedro-Woolley,_Washington" title="Sedro-Woolley, Washington"><span class="nowrap">Sedro-Woolley,</span><br/>Washington</a>,
 <a href="/wiki/Charleston,_South_Carolina" title="Charleston, South Carolina">Charleston,<br/>South Carolina</a>,
 <a class="mw-redirect" href="/wiki/Chicago,_Illinois" title="Chicago, Illinois">Chicago,<br/>Illinois</a>,
 <a class="mw-redirect" href="/wiki/Miami,_Florida" title="Miami, Florida">Miami,<br/>Florida</a>,
 <a class="mw-redirect" href="/wiki/Toronto,_Ontario" title="Toronto, Ontario">Toronto,<br/> Ontario</a>]

In [ ]:
df = pd.read_html(str(tables))[3]
df

/tmp/ipykernel_3126/1238544221.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(tables))[3]

   Unnamed: 0_level_0 Original tribes                                   \
              Episode               1     1.1        2        3      4
0                 Day               3       3        5        7      9
1               Tribe            Yase      Ua     Yase       Ua     Ua
2          Eliminated         Abraham    Sara     Voce     Brad     JD
3               Votes             5–1   4–1–1      3–1      3–1    3–1
4                 NaN             NaN     NaN      NaN      NaN    NaN
5               Voter            Vote    Vote     Vote     Vote   Vote
6               Erika             NaN     NaN      NaN      NaN    NaN
7             Deshawn             NaN     NaN      NaN      NaN    NaN
8              Xander         Abraham     NaN  None[f]      NaN    NaN
9             Heather             NaN     NaN      NaN      NaN    NaN
10             Ricard             NaN    Sara      NaN     Brad     JD
11              Danny             NaN     NaN      NaN      NaN    NaN
12              Liana         Abraham     NaN     Voce      NaN    NaN
13               Shan             NaN    Sara      NaN     Brad     JD
14              Evvie         Abraham     NaN     Voce      NaN    NaN
15             Naseer             NaN     NaN      NaN      NaN    NaN
16            Tiffany         Abraham     NaN     Voce      NaN    NaN
17             Sydney             NaN     NaN      NaN      NaN    NaN
18              Genie             NaN  Ricard      NaN       JD     JD
19                 JD             NaN    Sara      NaN     Brad  Genie
20               Brad             NaN    Sara      NaN  None[f]    NaN
21               Voce         Abraham     NaN  Tiffany      NaN    NaN
22               Sara             NaN    Brad      NaN      NaN    NaN
23            Abraham         Tiffany     NaN      NaN      NaN    NaN

           No tribes           Merged tribe  ... Unnamed: 200_level_0  \
         5       6/7     6/7.1            8  ... Unnamed: 200_level_1
0       11        14        14           16  ...                  NaN
1       Ua       NaN       NaN      Viakana  ...                  NaN
2    Genie    Sydney    Sydney      Tiffany  ...                  NaN
3      2–1     5–4–3     5–4–3      6–2–2–1  ...                  NaN
4      NaN       NaN       NaN          NaN  ...                  NaN
5     Vote      Vote      Vote         Vote  ...                  NaN
6      NaN    Sydney    Sydney      Tiffany  ...                  NaN
7      NaN     Evvie  Evvie[d]      Tiffany  ...                  NaN
8      NaN   Deshawn   Deshawn       Naseer  ...                  NaN
9      NaN    Sydney    Sydney      Tiffany  ...                  NaN
10   Genie     Evvie     Evvie      Tiffany  ...                  NaN
11     NaN     Evvie     Evvie       Xander  ...                  NaN
12     NaN    Sydney    Sydney      Tiffany  ...                  NaN
13   Genie    Sydney    Sydney      Tiffany  ...                  NaN
14     NaN   Deshawn   Deshawn      Heather  ...                  NaN
15     NaN    Sydney    Sydney       Xander  ...                  NaN
16     NaN   Deshawn   Deshawn      Heather  ...                  NaN
17     NaN   None[j]   None[j]          NaN  ...                  NaN
18  Ricard       NaN       NaN          NaN  ...                  NaN
19     NaN       NaN       NaN          NaN  ...                  NaN
20     NaN       NaN       NaN          NaN  ...                  NaN
21     NaN       NaN       NaN          NaN  ...                  NaN
22     NaN       NaN       NaN          NaN  ...                  NaN
23     NaN       NaN       NaN          NaN  ...                  NaN

   Unnamed: 201_level_0 Unnamed: 202_level_0 Unnamed: 203_level_0  \
   Unnamed: 201_level_1 Unnamed: 202_level_1 Unnamed: 203_level_1
0                   NaN                  NaN                  NaN
1                   NaN                  NaN                  NaN
2                   NaN                  NaN                  NaN
3                   NaN                  NaN                  NaN
4                   NaN                  NaN                  NaN
5                   NaN                  NaN                  NaN
6                   NaN                  NaN                  NaN
7                   NaN                  NaN                  NaN
8                   NaN                  NaN                  NaN
9                   NaN                  NaN                  NaN
10                  NaN                  NaN                  NaN
11                  NaN                  NaN                  NaN
12                  NaN                  NaN                  NaN
13                  NaN                  NaN                  NaN
14                  NaN                  NaN                  NaN
15                  NaN                  NaN                  NaN
16                  NaN                  NaN                  NaN
17                  NaN                  NaN                  NaN
18                  NaN                  NaN                  NaN
19                  NaN                  NaN                  NaN
20                  NaN                  NaN                  NaN
21                  NaN                  NaN                  NaN
22                  NaN                  NaN                  NaN
23                  NaN                  NaN                  NaN

   Unnamed: 204_level_0 Unnamed: 205_level_0 Unnamed: 206_level_0  \
   Unnamed: 204_level_1 Unnamed: 205_level_1 Unnamed: 206_level_1
0                   NaN                  NaN                  NaN
1                   NaN                  NaN                  NaN
2                   NaN                  NaN                  NaN
3                   NaN                  NaN                  NaN
4                   NaN                  NaN                  NaN
5                   NaN                  NaN                  NaN
6                   NaN                  NaN                  NaN
7                   NaN                  NaN                  NaN
8                   NaN                  NaN                  NaN
9                   NaN                  NaN                  NaN
10                  NaN                  NaN                  NaN
11                  NaN                  NaN                  NaN
12                  NaN                  NaN                  NaN
13                  NaN                  NaN                  NaN
14                  NaN                  NaN                  NaN
15                  NaN                  NaN                  NaN
16                  NaN                  NaN                  NaN
17                  NaN                  NaN                  NaN
18                  NaN                  NaN                  NaN
19                  NaN                  NaN                  NaN
20                  NaN                  NaN                  NaN
21                  NaN                  NaN                  NaN
22                  NaN                  NaN                  NaN
23                  NaN                  NaN                  NaN

   Unnamed: 207_level_0 Unnamed: 208_level_0 Unnamed: 209_level_0
   Unnamed: 207_level_1 Unnamed: 208_level_1 Unnamed: 209_level_1
0                   NaN                  NaN                  NaN
1                   NaN                  NaN                  NaN
2                   NaN                  NaN                  NaN
3                   NaN                  NaN                  NaN
4                   NaN                  NaN                  NaN
5                   NaN                  NaN                  NaN
6                   NaN                  NaN                  NaN
7                   NaN                  NaN                  NaN
8                   NaN                  NaN                  NaN
9                   NaN                  NaN                  NaN
10                  NaN                  NaN                  NaN
11                  NaN                  NaN                  NaN
12                  NaN                  NaN                  NaN
13                  NaN                  NaN                  NaN
14                  NaN                  NaN                  NaN
15                  NaN                  NaN                  NaN
16                  NaN                  NaN                  NaN
17                  NaN                  NaN                  NaN
18                  NaN                  NaN                  NaN
19                  NaN                  NaN                  NaN
20                  NaN                  NaN                  NaN
21                  NaN                  NaN                  NaN
22                  NaN                  NaN                  NaN
23                  NaN                  NaN                  NaN

[24 rows x 210 columns]

In [ ]:
erika_row = df[df[('Unnamed: 0_level_0', 'Episode')] == 'Erika']
print(erika_row)

  Unnamed: 0_level_0 Original tribes                          No tribes  \
             Episode               1  1.1    2    3    4    5       6/7
6              Erika             NaN  NaN  NaN  NaN  NaN  NaN    Sydney

          Merged tribe  ... Unnamed: 200_level_0 Unnamed: 201_level_0  \
    6/7.1            8  ... Unnamed: 200_level_1 Unnamed: 201_level_1
6  Sydney      Tiffany  ...                  NaN                  NaN

  Unnamed: 202_level_0 Unnamed: 203_level_0 Unnamed: 204_level_0  \
  Unnamed: 202_level_1 Unnamed: 203_level_1 Unnamed: 204_level_1
6                  NaN                  NaN                  NaN

  Unnamed: 205_level_0 Unnamed: 206_level_0 Unnamed: 207_level_0  \
  Unnamed: 205_level_1 Unnamed: 206_level_1 Unnamed: 207_level_1
6                  NaN                  NaN                  NaN

  Unnamed: 208_level_0 Unnamed: 209_level_0
  Unnamed: 208_level_1 Unnamed: 209_level_1
6                  NaN                  NaN

[1 rows x 210 columns]

## Survivor 42

In [ ]:
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
}

r = requests.get('https://en.wikipedia.org/wiki/Survivor:_42', headers=headers)
html_contents = r.text
html_soup = BeautifulSoup(html_contents,"lxml")

In [ ]:
tables = html_soup.find_all('table',class_="wikitable")
tables[0].find_all('a')

[<a href="#cite_note-5"><span class="cite-bracket">[</span>5<span class="cite-bracket">]</span></a>,
 <a href="/wiki/Houston" title="Houston">Houston,<br/>Texas</a>,
 <a href="/wiki/St._Louis" title="St. Louis">St. Louis,<br/>Missouri</a>,
 <a href="/wiki/Noblesville,_Indiana" title="Noblesville, Indiana">Noblesville,<br/>Indiana</a>,
 <a href="/wiki/Brooklyn" title="Brooklyn">Brooklyn,<br/>New York</a>,
 <a href="/wiki/Palo_Alto,_California" title="Palo Alto, California">Palo Alto,<br/>California</a>,
 <a href="/wiki/New_Haven,_Connecticut" title="New Haven, Connecticut">New Haven,<br/>Connecticut</a>,
 <a href="/wiki/Santa_Monica,_California" title="Santa Monica, California">Santa Monica,<br/>California</a>,
 <a href="#cite_note-6"><span class="cite-bracket">[</span>a<span class="cite-bracket">]</span></a>,
 <a href="/wiki/New_York_City" title="New York City">New York,<br/>New York</a>,
 <a href="/wiki/Las_Vegas" title="Las Vegas">Las Vegas,<br/>Nevada</a>,
 <a href="/wiki/Rogers,_Arkansas" title="Rogers, Arkansas">Rogers,<br/>Arkansas</a>,
 <a href="/wiki/New_Orleans" title="New Orleans">New Orleans,<br/>Louisiana</a>,
 <a href="/wiki/Montreal" title="Montreal">Montreal,<br/>Quebec</a>,
 <a href="/wiki/Whitby,_Ontario" title="Whitby, Ontario">Whitby,<br/>Ontario</a>,
 <a href="/wiki/Asbury_Park,_New_Jersey" title="Asbury Park, New Jersey">Asbury Park,<br/>New Jersey</a>,
 <a href="/wiki/Gulf_Shores,_Alabama" title="Gulf Shores, Alabama">Gulf Shores,<br/>Alabama</a>,
 <a href="/wiki/Norwalk,_California" title="Norwalk, California">Norwalk,<br/>California</a>,
 <a href="/wiki/Hoboken,_New_Jersey" title="Hoboken, New Jersey">Hoboken,<br/>New Jersey</a>,
 <a href="/wiki/Maryanne_Oketch" title="Maryanne Oketch">Maryanne Oketch</a>,
 <a href="/wiki/Ajax,_Ontario" title="Ajax, Ontario">Ajax,<br/>Ontario</a>]

In [ ]:
df = pd.read_html(str(tables))[3]
df

/tmp/ipykernel_3126/1238544221.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(tables))[3]

   Unnamed: 0_level_0 Original tribes                                      \
              Episode               1      1.1        2        3      3.1
0                 Day               3        3        5        7        7
1               Tribe            Taku      Ika     Taku     Vati     Vati
2          Eliminated         Jackson     Zach    Marya   Tie[b]   Tie[c]
3               Votes      Removed[d]      5–0      4–0      2–2      1–1
4                 NaN             NaN      NaN      NaN      NaN      NaN
5               Voter            Vote     Vote     Vote     Vote     Vote
6            Maryanne             NaN      NaN    Marya      NaN      NaN
7                Mike             NaN      NaN      NaN  None[i]  None[i]
8               Romeo             NaN     Zach      NaN      NaN      NaN
9            Jonathan             NaN      NaN    Marya      NaN      NaN
10            Lindsay             NaN      NaN    Marya      NaN      NaN
11               Omar             NaN      NaN    Marya      NaN      NaN
12               Drea             NaN     Zach      NaN      NaN      NaN
13                Hai             NaN      NaN      NaN    Jenny    Jenny
14               Tori             NaN     Zach      NaN      NaN      NaN
15           Rocksroy             NaN     Zach      NaN      NaN      NaN
16           Chanelle             NaN      NaN      NaN  None[j]  None[j]
17              Lydia             NaN      NaN      NaN    Jenny  None[m]
18             Daniel             NaN      NaN      NaN    Lydia    Lydia
19              Swati             NaN     Zach      NaN      NaN      NaN
20              Jenny             NaN      NaN      NaN    Lydia  None[m]
21              Marya             NaN      NaN  None[k]      NaN      NaN
22               Zach             NaN  None[k]      NaN      NaN      NaN
23            Jackson         Removed      NaN      NaN      NaN      NaN

                                              ... Merged tribe             \
             3.2        4         5      5.1  ...            8          9
0              7        9        11       11  ...           16      17[a]
1           Vati      Ika      Vati     Vati  ...    Kula Kula  Kula Kula
2          Jenny    Swati    Tie[b]   Daniel  ...     Chanelle   Rocksroy
3   Consensus[e]      3–1     2–2–1      3–0  ...        7–3–1        4–1
4            NaN      NaN       NaN      NaN  ...          NaN        NaN
5           Vote     Vote      Vote     Vote  ...         Vote       Vote
6            NaN      NaN       NaN      NaN  ...        Romeo        NaN
7        None[i]      NaN  Chanelle   Daniel  ...     Chanelle   Rocksroy
8            NaN    Swati       NaN      NaN  ...          Hai   Rocksroy
9            NaN      NaN       NaN      NaN  ...     Chanelle        NaN
10           NaN      NaN       NaN      NaN  ...     Chanelle        NaN
11           NaN      NaN       NaN      NaN  ...        Romeo   Rocksroy
12           NaN    Swati       NaN      NaN  ...     Chanelle        NaN
13         Jenny      NaN    Daniel   Daniel  ...     Chanelle   Rocksroy
14           NaN    Swati       NaN      NaN  ...     Chanelle        NaN
15           NaN     Tori       NaN      NaN  ...     Chanelle      Romeo
16       None[j]      NaN      Mike  None[l]  ...        Romeo        NaN
17       None[m]      NaN    Daniel   Daniel  ...          NaN        NaN
18         Jenny      NaN  Chanelle  None[l]  ...          NaN        NaN
19           NaN  None[k]       NaN      NaN  ...          NaN        NaN
20       None[m]      NaN       NaN      NaN  ...          NaN        NaN
21           NaN      NaN       NaN      NaN  ...          NaN        NaN
22           NaN      NaN       NaN      NaN  ...          NaN        NaN
23           NaN      NaN       NaN      NaN  ...          NaN        NaN

                                                                      \
          9.1         10         11       11.1         12       12.1
0       17[a]         19         21         21         23         23
1   Kula Kula  Kula Kula  Kula Kula  Kula Kula  Kula Kula  Kula Kula
2        Tori        Hai       Drea       Drea       Omar       Omar
3      4–0[f]        6–2        5–3        5–3      3–2–2      3–2–2
4         NaN        NaN        NaN        NaN        NaN        NaN
5        Vote       Vote       Vote       Vote       Vote       Vote
6        Tori        Hai       Drea       Drea       Omar    Omar[h]
7         NaN        Hai       Drea       Drea      Romeo      Romeo
8         NaN   Jonathan       Mike       Mike       Omar       Omar
9        Tori        Hai       Drea       Drea      Romeo      Romeo
10       Tori        Hai       Drea       Drea   Jonathan   Jonathan
11        NaN        Hai       Drea       Drea   Jonathan   Jonathan
12       Tori        Hai       Mike    Mike[h]        NaN        NaN
13        NaN   Jonathan        NaN        NaN        NaN        NaN
14    None[k]        NaN        NaN        NaN        NaN        NaN
15        NaN        NaN        NaN        NaN        NaN        NaN
16        NaN        NaN        NaN        NaN        NaN        NaN
17        NaN        NaN        NaN        NaN        NaN        NaN
18        NaN        NaN        NaN        NaN        NaN        NaN
19        NaN        NaN        NaN        NaN        NaN        NaN
20        NaN        NaN        NaN        NaN        NaN        NaN
21        NaN        NaN        NaN        NaN        NaN        NaN
22        NaN        NaN        NaN        NaN        NaN        NaN
23        NaN        NaN        NaN        NaN        NaN        NaN


           13       13.1
0          24         25
1   Kula Kula  Kula Kula
2     Lindsay   Jonathan
3         4–1    None[g]
4         NaN        NaN
5        Vote  Challenge
6     Lindsay   Saved[g]
7     Lindsay     Won[g]
8     Lindsay  Immune[g]
9     Lindsay    Lost[g]
10   Jonathan        NaN
11        NaN        NaN
12        NaN        NaN
13        NaN        NaN
14        NaN        NaN
15        NaN        NaN
16        NaN        NaN
17        NaN        NaN
18        NaN        NaN
19        NaN        NaN
20        NaN        NaN
21        NaN        NaN
22        NaN        NaN
23        NaN        NaN

[24 rows x 21 columns]

In [ ]:
maryanne_row = df[df[('Unnamed: 0_level_0', 'Episode')] == 'Maryanne']
print(maryanne_row)

  Unnamed: 0_level_0 Original tribes                                       \
             Episode               1  1.1      2    3  3.1  3.2    4    5
6           Maryanne             NaN  NaN  Marya  NaN  NaN  NaN  NaN  NaN

        ... Merged tribe                                                      \
   5.1  ...            8    9   9.1   10    11  11.1    12     12.1       13
6  NaN  ...        Romeo  NaN  Tori  Hai  Drea  Drea  Omar  Omar[h]  Lindsay


       13.1
6  Saved[g]

[1 rows x 21 columns]

## Survivor 43

In [ ]:
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
}

r = requests.get('https://en.wikipedia.org/wiki/Survivor:_43', headers=headers)
html_contents = r.text
html_soup = BeautifulSoup(html_contents,"lxml")

In [ ]:
tables = html_soup.find_all('table',class_="wikitable")
tables[0].find_all('a')

[<a class="mw-redirect" href="/wiki/Philadelphia,_Pennsylvania" title="Philadelphia, Pennsylvania">Philadelphia,<br/>Pennsylvania</a>,
 <a class="mw-redirect" href="/wiki/Marina_Del_Rey,_California" title="Marina Del Rey, California"><span class="nowrap">Marina del Rey</span>,<br/>California</a>,
 <a href="/wiki/Weatherford,_Texas" title="Weatherford, Texas">Weatherford,<br/>Texas</a>,
 <a href="/wiki/Downingtown,_Pennsylvania" title="Downingtown, Pennsylvania">Downingtown,<br/>Pennsylvania</a>,
 <a class="mw-redirect" href="/wiki/Honolulu,_Hawaii" title="Honolulu, Hawaii">Honolulu,<br/>Hawaii</a>,
 <a class="mw-redirect" href="/wiki/Salt_Lake_City,_Utah" title="Salt Lake City, Utah"><span class="nowrap">Salt Lake City</span>,<br/>Utah</a>,
 <a href="#cite_note-8"><span class="cite-bracket">[</span>a<span class="cite-bracket">]</span></a>,
 <a href="/wiki/Collierville,_Tennessee" title="Collierville, Tennessee">Collierville,<br/>Tennessee</a>,
 <a class="mw-redirect" href="/wiki/San_Francisco,_California" title="San Francisco, California"><span class="nowrap">San Francisco</span>,<br/>California</a>,
 <a class="mw-redirect" href="/wiki/Philadelphia,_Pennsylvania" title="Philadelphia, Pennsylvania">Philadelphia,<br/>Pennsylvania</a>,
 <a href="/wiki/Ryan_Medrano" title="Ryan Medrano">Ryan Medrano</a>,
 <a href="/wiki/El_Paso,_Texas" title="El Paso, Texas">El Paso,<br/>Texas</a>,
 <a href="/wiki/Noelle_Lambert" title="Noelle Lambert">Noelle Lambert</a>,
 <a href="/wiki/Manchester,_New_Hampshire" title="Manchester, New Hampshire">Manchester,<br/><span class="nowrap">New Hampshire</span></a>,
 <a class="mw-redirect" href="/wiki/Las_Vegas,_Nevada" title="Las Vegas, Nevada">Las Vegas,<br/>Nevada</a>,
 <a class="mw-redirect" href="/wiki/Honolulu,_Hawaii" title="Honolulu, Hawaii">Honolulu,<br/>Hawaii</a>,
 <a href="/wiki/Newark,_Delaware" title="Newark, Delaware">Newark,<br/>Delaware</a>,
 <a href="/wiki/Durham,_North_Carolina" title="Durham, North Carolina">Durham,<br/><span class="nowrap">North Carolina</span></a>,
 <a class="mw-redirect" href="/wiki/New_Orleans,_Louisiana" title="New Orleans, Louisiana">New Orleans,<br/>Louisiana</a>,
 <a href="/wiki/Austin,_Texas" title="Austin, Texas">Austin,<br/>Texas</a>,
 <a href="/wiki/Meridian,_Idaho" title="Meridian, Idaho">Meridian,<br/>Idaho</a>]

In [ ]:
df = pd.read_html(str(tables))[3]
df

/tmp/ipykernel_3126/1238544221.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(tables))[3]

   Unnamed: 0_level_0 Original tribes                                     \
              Episode               1        2       3        4        5
0                 Day               3        5       7        9       11
1               Tribe            Baka     Vesi    Vesi     Coco     Coco
2          Eliminated         Morriah  Justine   Nneka  Lindsay      Geo
3               Votes             5–1    3–1–1     4–1    4–1–1      3–2
4                 NaN             NaN      NaN     NaN      NaN      NaN
5               Voter            Vote     Vote    Vote     Vote     Vote
6              Gabler         Morriah      NaN     NaN      NaN      NaN
7             Cassidy             NaN      NaN     NaN  Lindsay      Geo
8                Owen         Morriah      NaN     NaN      NaN      NaN
9               Jesse             NaN  Justine   Nneka      NaN      NaN
10              Karla             NaN      NaN     NaN  Lindsay      Geo
11               Cody             NaN  Justine   Nneka      NaN      NaN
12               Sami         Morriah      NaN     NaN      NaN      NaN
13             Noelle             NaN    Nneka   Nneka      NaN      NaN
14               Ryan             NaN      NaN     NaN  Lindsay  Cassidy
15              James             NaN      NaN     NaN  Lindsay      Geo
16            Jeanine         Morriah      NaN     NaN      NaN      NaN
17             Dwight             NaN  None[f]   Nneka      NaN      NaN
18               Elie         Morriah      NaN     NaN      NaN      NaN
19                Geo             NaN      NaN     NaN  Cassidy  Cassidy
20            Lindsay             NaN      NaN     NaN      Geo      NaN
21              Nneka             NaN  Justine  Noelle      NaN      NaN
22            Justine             NaN     Cody     NaN      NaN      NaN
23            Morriah            Owen      NaN     NaN      NaN      NaN

   No tribes Merged tribe                                               \
           6            7        8        9       9.1      9.2      10
0         13           14       16    17[a]     17[a]    17[a]      19
1        NaN         Gaia     Gaia     Gaia      Gaia     Gaia    Gaia
2       Elie       Dwight  Jeanine    James     James     Ryan  Noelle
3    7–2–1–1        7–3–2      9–2      4–1       4–1      4–1   5–2–1
4        NaN          NaN      NaN      NaN       NaN      NaN     NaN
5       Vote         Vote     Vote     Vote      Vote     Vote    Vote
6       Elie         Ryan  Jeanine      NaN       NaN     Ryan  Noelle
7       Elie       Dwight     Ryan      NaN       NaN     Ryan  Noelle
8      James         Ryan  Jeanine  None[e]   None[e]      NaN   Karla
9    None[f]       Dwight  Jeanine      NaN       NaN     Ryan  Noelle
10      Owen       Dwight  Jeanine    James     James      NaN  Noelle
11      Elie       Dwight  Jeanine      NaN       NaN     Ryan  Noelle
12      Elie       Dwight  Jeanine    James     James      NaN   Karla
13   Cassidy        James  Jeanine    James  James[e]      NaN    Sami
14      Elie       Dwight  Jeanine      NaN       NaN  Cassidy     NaN
15      Elie       Dwight  Jeanine     Owen      Owen      NaN     NaN
16   None[f]         Ryan     Ryan      NaN       NaN      NaN     NaN
17      Elie        James      NaN      NaN       NaN      NaN     NaN
18     James          NaN      NaN      NaN       NaN      NaN     NaN
19       NaN          NaN      NaN      NaN       NaN      NaN     NaN
20       NaN          NaN      NaN      NaN       NaN      NaN     NaN
21       NaN          NaN      NaN      NaN       NaN      NaN     NaN
22       NaN          NaN      NaN      NaN       NaN      NaN     NaN
23       NaN          NaN      NaN      NaN       NaN      NaN     NaN


         11        12      13       13.1
0        21        23      24         25
1      Gaia      Gaia    Gaia       Gaia
2      Sami      Cody   Karla      Jesse
3       6–0  4–0–0[b]  4–0[c]    None[d]
4       NaN       NaN     NaN        NaN
5      Vote      Vote    Vote  Challenge
6      Sami      Cody   Karla     Won[d]
7      Sami      Cody   Karla  Immune[d]
8      Sami      Cody   Karla   Saved[d]
9      Sami      Cody   Karla    Lost[d]
10     Sami      Owen   Jesse        NaN
11     Sami     Karla     NaN        NaN
12  None[g]       NaN     NaN        NaN
13      NaN       NaN     NaN        NaN
14      NaN       NaN     NaN        NaN
15      NaN       NaN     NaN        NaN
16      NaN       NaN     NaN        NaN
17      NaN       NaN     NaN        NaN
18      NaN       NaN     NaN        NaN
19      NaN       NaN     NaN        NaN
20      NaN       NaN     NaN        NaN
21      NaN       NaN     NaN        NaN
22      NaN       NaN     NaN        NaN
23      NaN       NaN     NaN        NaN

In [ ]:
gabler_row = df[df[('Unnamed: 0_level_0', 'Episode')] == 'Gabler']
print(gabler_row)

  Unnamed: 0_level_0 Original tribes                     No tribes  \
             Episode               1    2    3    4    5         6
6             Gabler         Morriah  NaN  NaN  NaN  NaN      Elie

  Merged tribe
             7        8    9  9.1   9.2      10    11    12     13    13.1
6         Ryan  Jeanine  NaN  NaN  Ryan  Noelle  Sami  Cody  Karla  Won[d]

## Survivor 44

In [ ]:
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
}

r = requests.get('https://en.wikipedia.org/wiki/Survivor:_44', headers=headers)
html_contents = r.text
html_soup = BeautifulSoup(html_contents,"lxml")

In [ ]:
tables = html_soup.find_all('table',class_="wikitable")
tables[0].find_all('a')

[<a href="/wiki/Warwick,_Rhode_Island" title="Warwick, Rhode Island">Warwick,<br/>Rhode Island</a>,
 <a href="/wiki/Brooklyn" title="Brooklyn">Brooklyn,<br/>New York</a>,
 <a href="/wiki/San_Francisco" title="San Francisco">San Francisco,<br/>California</a>,
 <a href="/wiki/Brooklyn" title="Brooklyn">Brooklyn,<br/>New York</a>,
 <a href="/wiki/Chicago" title="Chicago">Chicago,<br/>Illinois</a>,
 <a href="/wiki/Columbus,_Ohio" title="Columbus, Ohio">Columbus,<br/>Ohio</a>,
 <a href="/wiki/Atlanta" title="Atlanta">Atlanta,<br/>Georgia</a>,
 <a href="#cite_note-6"><span class="cite-bracket">[</span>a<span class="cite-bracket">]</span></a>,
 <a href="/wiki/San_Francisco" title="San Francisco">San Francisco,<br/>California</a>,
 <a href="/wiki/Brandon_Cottom" title="Brandon Cottom">Brandon Cottom</a>,
 <a href="/wiki/Newtown,_Bucks_County,_Pennsylvania" title="Newtown, Bucks County, Pennsylvania">Newtown,<br/>Pennsylvania</a>,
 <a href="/wiki/Saskatoon" title="Saskatoon">Saskatoon,<br/>Saskatchewan</a>,
 <a href="/wiki/Cambridge,_Massachusetts" title="Cambridge, Massachusetts">Cambridge,<br/>Massachusetts</a>,
 <a href="/wiki/The_Bronx" title="The Bronx">Bronx,<br/>New York</a>,
 <a href="/wiki/Mesa,_Arizona" title="Mesa, Arizona">Mesa,<br/>Arizona</a>,
 <a href="/wiki/Mont_Belvieu,_Texas" title="Mont Belvieu, Texas">Mont Belvieu,<br/>Texas</a>,
 <a href="/wiki/Atlanta" title="Atlanta">Atlanta,<br/>Georgia</a>,
 <a href="/wiki/Hugo,_Minnesota" title="Hugo, Minnesota">Hugo,<br/>Minnesota</a>,
 <a href="/wiki/Pittsburgh" title="Pittsburgh">Pittsburgh,<br/>Pennsylvania</a>,
 <a href="/wiki/San_Juan,_Puerto_Rico" title="San Juan, Puerto Rico">San Juan,<br/>Puerto Rico</a>]

In [ ]:
df = pd.read_html(str(tables))[3]
df

/tmp/ipykernel_3126/1238544221.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(tables))[3]

   Unnamed: 0_level_0 Original tribes                             \
              Episode               1      1.1        2        3
0                 Day               1        3        5        7
1               Tribe            Tika     Ratu     Tika     Soka
2          Eliminated           Bruce    Maddy    Helen   Claire
3               Votes    Evacuated[a]   1–0[b]      3–1      4–0
4                 NaN             NaN      NaN      NaN      NaN
5               Voter            Vote     Vote     Vote     Vote
6             Yam Yam             NaN      NaN    Helen      NaN
7               Heidi             NaN      NaN      NaN   Claire
8             Carolyn             NaN      NaN    Helen      NaN
9              Carson             NaN      NaN    Helen      NaN
10             Lauren             NaN  None[i]      NaN      NaN
11              Jaime             NaN  None[k]      NaN      NaN
12              Danny             NaN      NaN      NaN   Claire
13            Frannie             NaN      NaN      NaN   Claire
14               Kane             NaN  Brandon      NaN      NaN
15            Brandon             NaN    Maddy      NaN      NaN
16               Matt             NaN      NaN      NaN  None[m]
17               Josh             NaN      NaN      NaN   Claire
18            Matthew             NaN  None[k]      NaN      NaN
19              Sarah             NaN      NaN  None[m]      NaN
20             Claire             NaN      NaN      NaN  None[k]
21              Helen             NaN      NaN  Carolyn      NaN
22              Maddy             NaN  Brandon      NaN      NaN
23              Bruce       Evacuated      NaN      NaN      NaN

   Switched tribes          No tribes Merged tribe                    \
                 4        5         6            7        8        9
0                9       11        13           14       15       17
1             Tika     Ratu       NaN        Va Va    Va Va    Va Va
2            Sarah  Matthew      Josh         Matt  Brandon     Kane
3           2–0[c]  Quit[d]     7–3–1          3–2   4–0[e]  5–3–1–1
4              NaN      NaN       NaN          NaN      NaN      NaN
5             Vote     Vote      Vote         Vote     Vote     Vote
6             Josh      NaN      Josh         Matt  Frannie     Kane
7              NaN      NaN      Josh    Immune[h]  Brandon     Kane
8            Sarah      NaN      Kane    Immune[h]  Brandon     Kane
9              NaN      NaN      Josh    Immune[h]  Frannie     Kane
10             NaN      NaN      Josh   Yam Yam[j]  Frannie    Heidi
11             NaN      NaN      Josh         Matt  Frannie    Heidi
12             NaN      NaN      Josh    Immune[h]  Brandon     Kane
13             NaN      NaN      Josh    Immune[h]  Brandon    Jaime
14             NaN      NaN   Yam Yam    Immune[h]  Frannie    Danny
15             NaN      NaN   Yam Yam         Matt  Frannie      NaN
16             NaN      NaN   None[m]      Yam Yam      NaN      NaN
17           Sarah      NaN   Yam Yam          NaN      NaN      NaN
18             NaN     Quit       NaN          NaN      NaN      NaN
19            Josh      NaN       NaN          NaN      NaN      NaN
20             NaN      NaN       NaN          NaN      NaN      NaN
21             NaN      NaN       NaN          NaN      NaN      NaN
22             NaN      NaN       NaN          NaN      NaN      NaN
23             NaN      NaN       NaN          NaN      NaN      NaN


         9.1       10        11       12       13       13.1
0         17       19        21       23       24         25
1      Va Va    Va Va     Va Va    Va Va    Va Va      Va Va
2       Kane  Frannie     Danny    Jaime   Lauren     Carson
3    5–3–1–1    5–2–1  3–2–0[f]      4–2    3–1–1    None[g]
4        NaN      NaN       NaN      NaN      NaN        NaN
5       Vote     Vote      Vote     Vote     Vote  Challenge
6       Kane  Frannie     Danny    Jaime    Heidi   Saved[g]
7       Kane    Danny    Carson    Jaime   Lauren     Won[g]
8       Kane    Heidi     Danny    Jaime   Lauren   Saved[g]
9       Kane  Frannie     Danny    Jaime   Lauren    Lost[g]
10     Heidi  Frannie     Heidi  Carolyn  Yam Yam        NaN
11  Heidi[l]  Frannie     Heidi  Carolyn      NaN        NaN
12      Kane  Frannie    Carson      NaN      NaN        NaN
13     Jaime    Heidi       NaN      NaN      NaN        NaN
14     Danny      NaN       NaN      NaN      NaN        NaN
15       NaN      NaN       NaN      NaN      NaN        NaN
16       NaN      NaN       NaN      NaN      NaN        NaN
17       NaN      NaN       NaN      NaN      NaN        NaN
18       NaN      NaN       NaN      NaN      NaN        NaN
19       NaN      NaN       NaN      NaN      NaN        NaN
20       NaN      NaN       NaN      NaN      NaN        NaN
21       NaN      NaN       NaN      NaN      NaN        NaN
22       NaN      NaN       NaN      NaN      NaN        NaN
23       NaN      NaN       NaN      NaN      NaN        NaN

In [ ]:
yamyam_row = df[df[('Unnamed: 0_level_0', 'Episode')] == 'Yam Yam']
print(yamyam_row)

  Unnamed: 0_level_0 Original tribes                  Switched tribes       \
             Episode               1  1.1      2    3               4    5
6            Yam Yam             NaN  NaN  Helen  NaN            Josh  NaN

  No tribes Merged tribe                                                     \
          6            7        8     9   9.1       10     11     12     13
6      Josh         Matt  Frannie  Kane  Kane  Frannie  Danny  Jaime  Heidi


       13.1
6  Saved[g]

## Survivor 45

In [ ]:
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
}

r = requests.get('https://en.wikipedia.org/wiki/Survivor:_45', headers=headers)
html_contents = r.text
html_soup = BeautifulSoup(html_contents,"lxml")

In [ ]:
tables = html_soup.find_all('table',class_="wikitable")
tables[0].find_all('a')

[<a href="/wiki/Baltimore" title="Baltimore">Baltimore,<br/>Maryland</a>,
 <a href="/wiki/Sicklerville,_New_Jersey" title="Sicklerville, New Jersey">Sicklerville,<br/>New Jersey</a>,
 <a href="/wiki/Jacksonville,_North_Carolina" title="Jacksonville, North Carolina">Jacksonville,<br/>North Carolina</a>,
 <a href="/wiki/Provo,_Utah" title="Provo, Utah">Provo,<br/>Utah</a>,
 <a href="/wiki/Seattle" title="Seattle">Seattle,<br/>Washington</a>,
 <a href="/wiki/Janani_K._Jha" title="Janani K. Jha">Janani "J. Maya" Krishnan-Jha</a>,
 <a href="/wiki/Los_Angeles" title="Los Angeles">Los Angeles,<br/>California</a>,
 <a href="#cite_note-11"><span class="cite-bracket">[</span>a<span class="cite-bracket">]</span></a>,
 <a href="/wiki/O%27Fallon,_Illinois" title="O'Fallon, Illinois">O'Fallon,<br/>Illinois</a>,
 <a href="/wiki/Vancouver" title="Vancouver">Vancouver,<br/>British Columbia</a>,
 <a href="/wiki/New_York_City" title="New York City">New York City,<br/>New York</a>,
 <a href="/wiki/Steamboat_Springs,_Colorado" title="Steamboat Springs, Colorado">Steamboat Springs,<br/>Colorado</a>,
 <a href="/wiki/Survivor_44" title="Survivor 44">Survivor 44</a>,
 <a href="/wiki/Warwick,_Rhode_Island" title="Warwick, Rhode Island">Warwick,<br/>Rhode Island</a>,
 <a href="/wiki/Laurel,_Maryland" title="Laurel, Maryland">Laurel,<br/>Maryland</a>,
 <a href="/wiki/Philadelphia" title="Philadelphia">Philadelphia,<br/>Pennsylvania</a>,
 <a href="/wiki/Brentwood,_Tennessee" title="Brentwood, Tennessee">Brentwood,<br/>Tennessee</a>,
 <a href="/wiki/Brooklyn" title="Brooklyn">Brooklyn,<br/>New York</a>,
 <a href="/wiki/Boston" title="Boston">Boston,<br/>Massachusetts</a>,
 <a href="/wiki/Chicago" title="Chicago">Chicago,<br/>Illinois</a>,
 <a href="/wiki/Miami" title="Miami">Miami,<br/>Florida</a>]

In [ ]:
df = pd.read_html(str(tables))[3]
df

/tmp/ipykernel_3126/1238544221.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(tables))[3]

   Unnamed: 0_level_0 Original tribes                   Switched tribes  \
              Episode               1        2        3               4
0                 Day               3        5        7               9
1               Tribe            Lulu     Lulu     Lulu            Reba
2          Eliminated          Hannah  Brandon  Sabiyah            Sean
3               Votes         Quit[b]      3–0      2–1           3–1–1
4               Voter            Vote     Vote     Vote            Vote
5                 Dee             NaN      NaN      NaN            Sifu
6              Austin             NaN      NaN      NaN             NaN
7                Jake             NaN      NaN      NaN             NaN
8             Katurah             NaN      NaN      NaN             NaN
9               Julie             NaN      NaN      NaN            Sean
10               Drew             NaN      NaN      NaN             NaN
11              Emily             NaN  Brandon  Sabiyah             NaN
12              Bruce             NaN      NaN      NaN             NaN
13             Kendra             NaN      NaN      NaN             NaN
14             Kellie             NaN      NaN      NaN             NaN
15              Kaleb             NaN  Brandon  Sabiyah             NaN
16               Sifu             NaN      NaN      NaN            Sean
17            J. Maya             NaN      NaN      NaN            Sean
18             Brando             NaN      NaN      NaN             NaN
19               Sean             NaN  Brandon    Kaleb             Dee
20            Sabiyah             NaN  None[l]  None[h]             NaN
21            Brandon             NaN  None[l]      NaN             NaN
22             Hannah            Quit      NaN      NaN             NaN

              No tribes          Merged tribe                                 \
            5         6      6.1            7       7.1         8          9
0          11        13       13        14[a]     14[a]        16         17
1        Belo       NaN      NaN     Dakuwaqa  Dakuwaqa  Dakuwaqa   Dakuwaqa
2      Brando       NaN  J. Maya         Sifu     Kaleb    Kellie     Kendra
3         3–2    0–0[c]     10–1          5–1       4–2       5–3        6–1
4        Vote      Vote     Vote         Vote      Vote      Vote       Vote
5         NaN     Kaleb  J. Maya          NaN     Kaleb    Kellie     Kendra
6   Brando[g]   None[h]  None[h]          NaN     Kaleb    Kellie  Kendra[i]
7         NaN     Kaleb  J. Maya          NaN     Julie   None[j]     Kendra
8         NaN     Kaleb  J. Maya          NaN     Kaleb      Jake    None[i]
9         NaN     Kaleb  J. Maya          NaN     Kaleb    Kellie     Kendra
10     Brando     Kaleb  J. Maya         Sifu       NaN    Kellie     Kendra
11     Brando     Kaleb  J. Maya         Sifu       NaN    Kellie    None[i]
12        NaN     Kaleb  J. Maya         Sifu       NaN   None[k]     Kendra
13       Drew     Kaleb  J. Maya         Sifu       NaN      Jake       Jake
14        NaN     Kaleb  J. Maya         Sifu       NaN      Jake        NaN
15        NaN   None[j]  None[j]          NaN     Julie       NaN        NaN
16        NaN     Kaleb  J. Maya        Bruce       NaN       NaN        NaN
17        NaN     Kaleb    Emily          NaN       NaN       NaN        NaN
18       Drew       NaN      NaN          NaN       NaN       NaN        NaN
19        NaN       NaN      NaN          NaN       NaN       NaN        NaN
20        NaN       NaN      NaN          NaN       NaN       NaN        NaN
21        NaN       NaN      NaN          NaN       NaN       NaN        NaN
22        NaN       NaN      NaN          NaN       NaN       NaN        NaN

                                                        Unnamed: 17_level_0
          10        11        12          13       13.1 Unnamed: 17_level_1
0         19        21        23          24         25                 NaN
1   Dakuwaqa  Dakuwaqa  Dakuwaqa    Dakuwaqa   Dakuwaqa                 NaN
2      Bruce     Emily      Drew       Julie    Katurah                 NaN
3      4–3–1    1–0[d]       4–2  2–1–1–0[e]    None[f]                 NaN
4       Vote      Vote      Vote        Vote  Challenge                 NaN
5       Jake     Julie      Drew     Katurah  Immune[f]                 NaN
6       Jake     Julie     Julie       Julie   Saved[f]                 NaN
7      Bruce     Julie      Drew         Dee     Won[f]                 NaN
8      Bruce     Julie      Drew       Julie    Lost[f]                 NaN
9      Bruce     Emily      Drew        Jake        NaN                 NaN
10      Jake     Julie     Julie         NaN        NaN                 NaN
11     Bruce     Julie       NaN         NaN        NaN                 NaN
12     Julie       NaN       NaN         NaN        NaN                 NaN
13       NaN       NaN       NaN         NaN        NaN                 NaN
14       NaN       NaN       NaN         NaN        NaN                 NaN
15       NaN       NaN       NaN         NaN        NaN                 NaN
16       NaN       NaN       NaN         NaN        NaN                 NaN
17       NaN       NaN       NaN         NaN        NaN                 NaN
18       NaN       NaN       NaN         NaN        NaN                 NaN
19       NaN       NaN       NaN         NaN        NaN                 NaN
20       NaN       NaN       NaN         NaN        NaN                 NaN
21       NaN       NaN       NaN         NaN        NaN                 NaN
22       NaN       NaN       NaN         NaN        NaN                 NaN

In [ ]:
dee_row = df[df[('Unnamed: 0_level_0', 'Episode')] == 'Dee']
print(dee_row)

  Unnamed: 0_level_0 Original tribes           Switched tribes      No tribes  \
             Episode               1    2    3               4    5         6
5                Dee             NaN  NaN  NaN            Sifu  NaN     Kaleb

           Merged tribe                                                     \
       6.1            7    7.1       8       9    10     11    12       13
5  J. Maya          NaN  Kaleb  Kellie  Kendra  Jake  Julie  Drew  Katurah

             Unnamed: 17_level_0
        13.1 Unnamed: 17_level_1
5  Immune[f]                 NaN

## Survivor 46

In [ ]:
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
}

r = requests.get('https://en.wikipedia.org/wiki/Survivor:_46', headers=headers)
html_contents = r.text
html_soup = BeautifulSoup(html_contents,"lxml")

In [ ]:
tables = html_soup.find_all('table',class_="wikitable")
tables[0].find_all('a')

[<a href="/wiki/Las_Vegas" title="Las Vegas">Las Vegas,<br/>Nevada</a>,
 <a href="/wiki/San_Francisco" title="San Francisco">San Francisco,<br/>California</a>,
 <a href="/wiki/Orlando,_Florida" title="Orlando, Florida">Orlando,<br/>Florida</a>,
 <a href="/wiki/Acton,_Massachusetts" title="Acton, Massachusetts">Acton,<br/>Massachusetts</a>,
 <a href="/wiki/Chicago" title="Chicago">Chicago,<br/>Illinois</a>,
 <a href="/wiki/San_Diego" title="San Diego">San Diego,<br/>California</a>,
 <a href="#cite_note-7"><span class="cite-bracket">[</span>a<span class="cite-bracket">]</span></a>,
 <a href="/wiki/Atlanta" title="Atlanta">Atlanta,<br/>Georgia</a>,
 <a href="/wiki/Lake_Hopatcong,_New_Jersey" title="Lake Hopatcong, New Jersey"><span class="nowrap">Lake Hopatcong</span>,<br/>New Jersey</a>,
 <a href="/wiki/Richmond,_Virginia" title="Richmond, Virginia">Richmond,<br/>Virginia</a>,
 <a href="/wiki/French_Camp,_Mississippi" title="French Camp, Mississippi">French Camp,<br/>Mississippi</a>,
 <a href="/wiki/Elizabeth,_New_Jersey" title="Elizabeth, New Jersey">Elizabeth,<br/>New Jersey</a>,
 <a href="/wiki/Toronto" title="Toronto">Toronto,<br/>Ontario</a>,
 <a href="/wiki/Senatobia,_Mississippi" title="Senatobia, Mississippi"> Senatobia,<br/>Mississippi</a>,
 <a href="/wiki/Dallas" title="Dallas">Dallas,<br/>Texas</a>,
 <a href="/wiki/Orlando,_Florida" title="Orlando, Florida">Orlando,<br/>Florida</a>,
 <a href="/wiki/Miami" title="Miami">Miami,<br/>Florida</a>,
 <a href="/wiki/Boston" title="Boston">Boston,<br/>Massachusetts</a>,
 <a href="/wiki/Charlotte,_North_Carolina" title="Charlotte, North Carolina">Charlotte,<br/>North Carolina</a>]

In [ ]:
df = pd.read_html(str(tables))[3]
df

/tmp/ipykernel_3126/1238544221.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(tables))[3]

   Unnamed: 0_level_0 Original tribes                                         \
              Episode               1      2             3        4        5
0                 Day               3      5             7        9       11
1               Tribe            Yanu   Yanu          Nami     Yanu     Siga
2          Eliminated        Jelinsky   Jess        Randen    Bhanu      Jem
3               Votes             5–0    4–1  Evacuated[c]   3–0[d]      4–2
4               Voter            Vote   Vote          Vote     Vote     Vote
5              Kenzie        Jelinsky   Jess           NaN    Bhanu      NaN
6             Charlie             NaN    NaN           NaN      NaN      Jem
7                 Ben             NaN    NaN           NaN      NaN  None[f]
8                 Liz             NaN    NaN           NaN      NaN      NaN
9               Maria             NaN    NaN           NaN      NaN      Jem
10                  Q        Jelinsky   Jess           NaN    Bhanu      NaN
11              Venus             NaN    NaN           NaN      NaN      NaN
12            Tiffany        Jelinsky   Jess           NaN    Bhanu      NaN
13             Hunter             NaN    NaN           NaN      NaN      NaN
14              Tevin             NaN    NaN           NaN      NaN      NaN
15               Soda             NaN    NaN           NaN      NaN      NaN
16                Tim             NaN    NaN           NaN      NaN      Jem
17             Moriah             NaN    NaN           NaN      NaN      Ben
18                Jem             NaN    NaN           NaN      NaN      Ben
19              Bhanu        Jelinsky   Jess           NaN  None[f]      NaN
20             Randen             NaN    NaN     Evacuated      NaN      NaN
21               Jess        Jelinsky  Bhanu           NaN      NaN      NaN
22           Jelinsky         None[f]    NaN           NaN      NaN      NaN

            No tribes Merged tribe                                            \
        5.1         6            7     7.1       8       9      9.1       10
0        11        13        14[a]   14[a]      16      17       17       19
1      Siga       NaN       Nuinui  Nuinui  Nuinui  Nuinui   Nuinui   Nuinui
2       Jem    Moriah          Tim    Soda   Tevin  Tie[b]   Hunter  Tiffany
3       4–2      10–1          4–2     4–2     8–2   4–4–1      6–1      5–3
4      Vote      Vote         Vote    Vote    Vote    Vote     Vote     Vote
5       NaN    Moriah          Tim     NaN   Tevin       Q   Hunter        Q
6       Jem     Venus          NaN    Soda   Tevin  Hunter   Hunter  Tiffany
7   None[f]    Moriah       Hunter     NaN   Tevin  Hunter   Hunter  Tiffany
8       NaN    Moriah          NaN    Soda   Tevin       Q        Q  Tiffany
9    Jem[g]    Moriah          NaN    Soda   Tevin  Hunter   Hunter  Tiffany
10      NaN    Moriah          Tim     NaN   Tevin     Ben  None[h]  Tiffany
11      NaN    Moriah          NaN    Soda   Tevin       Q   Hunter        Q
12      NaN    Moriah          Tim     NaN   Tevin  Hunter   Hunter        Q
13      NaN   None[f]          Tim     NaN   Venus       Q  None[h]      NaN
14      NaN    Moriah          NaN   Venus   Venus     NaN      NaN      NaN
15      NaN    Moriah          NaN   Venus     NaN     NaN      NaN      NaN
16      Jem    Moriah       Hunter     NaN     NaN     NaN      NaN      NaN
17      Ben   None[i]          NaN     NaN     NaN     NaN      NaN      NaN
18      Ben       NaN          NaN     NaN     NaN     NaN      NaN      NaN
19      NaN       NaN          NaN     NaN     NaN     NaN      NaN      NaN
20      NaN       NaN          NaN     NaN     NaN     NaN      NaN      NaN
21      NaN       NaN          NaN     NaN     NaN     NaN      NaN      NaN
22      NaN       NaN          NaN     NaN     NaN     NaN      NaN      NaN


        11       12      13       13.1
0       21       23      24         25
1   Nuinui   Nuinui  Nuinui     Nuinui
2    Venus        Q   Maria        Liz
3    5–1–1      4–2     4–1    None[e]
4     Vote     Vote    Vote  Challenge
5    Venus        Q   Maria     Won[e]
6    Venus        Q   Maria   Saved[e]
7   Kenzie        Q   Maria  Immune[e]
8    Venus        Q   Maria    Lost[e]
9    Venus  Charlie     Ben        NaN
10   Venus  Charlie     NaN        NaN
11       Q      NaN     NaN        NaN
12     NaN      NaN     NaN        NaN
13     NaN      NaN     NaN        NaN
14     NaN      NaN     NaN        NaN
15     NaN      NaN     NaN        NaN
16     NaN      NaN     NaN        NaN
17     NaN      NaN     NaN        NaN
18     NaN      NaN     NaN        NaN
19     NaN      NaN     NaN        NaN
20     NaN      NaN     NaN        NaN
21     NaN      NaN     NaN        NaN
22     NaN      NaN     NaN        NaN

In [ ]:
kenzie_row = df[df[('Unnamed: 0_level_0', 'Episode')] == 'Kenzie']
print(kenzie_row)

  Unnamed: 0_level_0 Original tribes                             No tribes  \
             Episode               1     2    3      4    5  5.1         6
5             Kenzie        Jelinsky  Jess  NaN  Bhanu  NaN  NaN    Moriah

  Merged tribe
             7  7.1      8  9     9.1 10     11 12     13    13.1
5          Tim  NaN  Tevin  Q  Hunter  Q  Venus  Q  Maria  Won[e]

## Survivor 47

In [ ]:
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
}

r = requests.get('https://en.wikipedia.org/wiki/Survivor_47', headers=headers)
html_contents = r.text
html_soup = BeautifulSoup(html_contents,"lxml")

In [ ]:
tables = html_soup.find_all('table',class_="wikitable")
tables[0].find_all('a')

[<a href="/wiki/Jon_Lovett" title="Jon Lovett">Jon Lovett</a>,
 <a href="/wiki/Los_Angeles" title="Los Angeles">Los Angeles,<br/>California</a>,
 <a href="/wiki/Upper_Marlboro,_Maryland" title="Upper Marlboro, Maryland"><span class="nowrap">Upper Marlboro</span>,<br/>Maryland</a>,
 <a href="/wiki/Houston" title="Houston">Houston,<br/>Texas</a>,
 <a href="/wiki/San_Francisco" title="San Francisco">San Francisco,<br/>California</a>,
 <a href="/wiki/Los_Angeles" title="Los Angeles">Los Angeles,<br/>California</a>,
 <a href="/wiki/Phoenix,_Arizona" title="Phoenix, Arizona">Phoenix,<br/>Arizona</a>,
 <a href="#cite_note-10"><span class="cite-bracket">[</span>a<span class="cite-bracket">]</span></a>,
 <a class="mw-redirect" href="/wiki/Aiea,_Hawaii" title="Aiea, Hawaii">Aiea,<br/>Hawaii</a>,
 <a href="/wiki/Phoenixville,_Pennsylvania" title="Phoenixville, Pennsylvania">Phoenixville,<br/>Pennsylvania</a>,
 <a href="/wiki/Norwalk,_Connecticut" title="Norwalk, Connecticut">Norwalk,<br/>Connecticut</a>,
 <a href="/wiki/Baltimore" title="Baltimore">Baltimore,<br/>Maryland</a>,
 <a href="/wiki/Cheboygan,_Michigan" title="Cheboygan, Michigan">Cheboygan,<br/>Michigan</a>,
 <a href="/wiki/Chicago" title="Chicago">Chicago,<br/>Illinois</a>,
 <a href="/wiki/Brooklyn" title="Brooklyn">Brooklyn,<br/>New York</a>,
 <a href="/wiki/Winnipeg" title="Winnipeg">Winnipeg,<br/>Manitoba</a>,
 <a href="/wiki/Manahawkin,_New_Jersey" title="Manahawkin, New Jersey">Manahawkin,<br/> New Jersey</a>,
 <a href="/wiki/Putnam_Valley,_New_York" title="Putnam Valley, New York">Putnam Valley,<br/>New York</a>,
 <a href="/wiki/Nashville,_Tennessee" title="Nashville, Tennessee">Nashville,<br/>Tennessee</a>,
 <a href="/wiki/Southfield,_Michigan" title="Southfield, Michigan">Southfield,<br/>Michigan</a>]

In [ ]:
df = pd.read_html(str(tables))[3]
df

/tmp/ipykernel_3126/1238544221.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(tables))[3]

   Unnamed: 0_level_0 Original tribes                                        \
              Episode               1     2           3        4        4.1
0                 Day               3     5           7        8          8
1               Tribe            Gata  Tuku        Lavo     Lavo       Lavo
2          Eliminated             Jon    TK       Aysha   Kishan     Kishan
3               Votes             5–1   4–2  3–1–1–0[c]      4–0        4–0
4               Voter            Vote  Vote        Vote     Vote       Vote
5              Rachel             Jon   NaN         NaN      NaN        NaN
6                 Sam             Jon   NaN         NaN      NaN        NaN
7                 Sue             NaN    TK         NaN      NaN        NaN
8               Teeny             NaN   NaN         Sol  None[k]    None[k]
9           Genevieve             NaN   NaN       Aysha   Kishan     Kishan
10               Andy             Jon   NaN         NaN      NaN        NaN
11           Caroline             NaN    TK         NaN      NaN        NaN
12               Kyle             NaN   Sue         NaN      NaN        NaN
13               Gabe             NaN    TK         NaN      NaN        NaN
14                Sol             NaN   NaN        Rome   Kishan     Kishan
15             Sierra             Jon   NaN         NaN      NaN        NaN
16             Tiyana             NaN    TK         NaN      NaN        NaN
17               Rome             NaN   NaN       Aysha   Kishan  Kishan[n]
18              Anika             Jon   NaN         NaN      NaN        NaN
19             Kishan             NaN   NaN       Aysha  None[n]    None[n]
20              Aysha             NaN   NaN   Genevieve      NaN        NaN
21                 TK             NaN   Sue         NaN      NaN        NaN
22                Jon           Anika   NaN         NaN      NaN        NaN

            No tribes Merged tribe                                        \
          5         6            7        8      8.1        9         10
0        10        12           13       15       15       16         18
1      Gata       NaN         Beka     Beka     Beka     Beka       Beka
2     Anika      Rome       Tiyana   Tie[b]   Sierra      Sol       Gabe
3       3–1     9–2–1          4–1    4–4–1      8–1      8–1        7–2
4      Vote      Vote         Vote     Vote     Vote     Vote       Vote
5      Andy      Rome    Immune[f]  None[g]  None[g]      Sol       Gabe
6     Anika      Rome    Immune[h]  None[i]  None[i]      Sol       Gabe
7       NaN      Andy       Tiyana   Sierra   Sierra      Sol  Genevieve
8       NaN      Rome    Immune[h]      Sam   Sierra      Sol       Gabe
9       NaN      Rome    Immune[h]      Sam   Sierra      Sol       Gabe
10    Anika      Rome    Immune[h]      Sam   Sierra      Sol       Gabe
11      NaN      Rome       Tiyana   Sierra   Sierra  None[l]       Gabe
12      NaN   None[k]       Tiyana   Sierra   Sierra      Sol       Gabe
13      NaN      Rome       Tiyana   Sierra   Sierra      Sol  Genevieve
14      NaN      Andy    Immune[h]      Sam   Sierra      Sue        NaN
15    Anika      Rome    Immune[h]     Gabe   Sam[m]      NaN        NaN
16      NaN      Rome         Gabe      NaN      NaN      NaN        NaN
17      NaN       Sam          NaN      NaN      NaN      NaN        NaN
18  None[k]       NaN          NaN      NaN      NaN      NaN        NaN
19      NaN       NaN          NaN      NaN      NaN      NaN        NaN
20      NaN       NaN          NaN      NaN      NaN      NaN        NaN
21      NaN       NaN          NaN      NaN      NaN      NaN        NaN
22      NaN       NaN          NaN      NaN      NaN      NaN        NaN

                                                        Unnamed: 18_level_0
           11         12       13       13.1         14 Unnamed: 18_level_1
0          20         22       23         24         25                 NaN
1        Beka       Beka     Beka       Beka       Beka                 NaN
2        Kyle   Caroline     Andy  Genevieve      Teeny                 NaN
3       6–1–1      3–2–2   2–0[d]        3–2    None[e]                 NaN
4        Vote       Vote     Vote       Vote  Challenge                 NaN
5        Kyle  Genevieve     Andy  Genevieve  Immune[e]                 NaN
6        Kyle   Caroline  None[j]  Genevieve     Won[e]                 NaN
7        Kyle        Sam     Andy  Genevieve   Saved[e]                 NaN
8        Kyle        Sam   Rachel        Sam    Lost[e]                 NaN
9        Kyle   Caroline   Rachel        Sam        NaN                 NaN
10  Genevieve   Caroline   Rachel        NaN        NaN                 NaN
11       Kyle  Genevieve      NaN        NaN        NaN                 NaN
12      Teeny        NaN      NaN        NaN        NaN                 NaN
13        NaN        NaN      NaN        NaN        NaN                 NaN
14        NaN        NaN      NaN        NaN        NaN                 NaN
15        NaN        NaN      NaN        NaN        NaN                 NaN
16        NaN        NaN      NaN        NaN        NaN                 NaN
17        NaN        NaN      NaN        NaN        NaN                 NaN
18        NaN        NaN      NaN        NaN        NaN                 NaN
19        NaN        NaN      NaN        NaN        NaN                 NaN
20        NaN        NaN      NaN        NaN        NaN                 NaN
21        NaN        NaN      NaN        NaN        NaN                 NaN
22        NaN        NaN      NaN        NaN        NaN                 NaN

In [ ]:
rachel_row = df[df[('Unnamed: 0_level_0', 'Episode')] == 'Rachel']
print(rachel_row)

  Unnamed: 0_level_0 Original tribes                           No tribes  \
             Episode               1    2    3    4  4.1     5         6
5             Rachel             Jon  NaN  NaN  NaN  NaN  Andy      Rome

  Merged tribe                                                                 \
             7        8      8.1    9    10    11         12    13       13.1
5    Immune[f]  None[g]  None[g]  Sol  Gabe  Kyle  Genevieve  Andy  Genevieve

             Unnamed: 18_level_0
          14 Unnamed: 18_level_1
5  Immune[e]                 NaN

## Survivor 48

In [ ]:
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
}

r = requests.get('https://en.wikipedia.org/wiki/Survivor_48', headers=headers)
html_contents = r.text
html_soup = BeautifulSoup(html_contents,"lxml")

In [ ]:
tables = html_soup.find_all('table',class_="wikitable")
tables[0].find_all('a')

[<a href="/wiki/Brooklyn" title="Brooklyn">Brooklyn,<br/>New York</a>,
 <a href="/wiki/Livermore,_California" title="Livermore, California">Livermore,<br/>California</a>,
 <a href="/wiki/Winthrop,_Massachusetts" title="Winthrop, Massachusetts">Winthrop,<br/>Massachusetts</a>,
 <a href="/wiki/Los_Angeles" title="Los Angeles">Los Angeles,<br/>California</a>,
 <a class="mw-redirect" href="/wiki/Arlington,_Virginia" title="Arlington, Virginia">Arlington,<br/>Virginia</a>,
 <a href="/wiki/St._Petersburg,_Florida" title="St. Petersburg, Florida">St. Petersburg,<br/>Florida</a>,
 <a href="#cite_note-8"><span class="cite-bracket">[</span>a<span class="cite-bracket">]</span></a>,
 <a class="mw-redirect" href="/wiki/Simi_Valley" title="Simi Valley">Simi Valley,<br/>California</a>,
 <a href="/wiki/Greenville,_South_Carolina" title="Greenville, South Carolina">Greenville,<br/>South Carolina</a>,
 <a href="/wiki/Chicago" title="Chicago">Chicago,<br/>Illinois</a>,
 <a class="mw-redirect" href="/wiki/Buena_Park" title="Buena Park">Buena Park,<br/>California</a>,
 <a href="/wiki/Augusta,_Georgia" title="Augusta, Georgia">Augusta,<br/>Georgia</a>,
 <a class="mw-redirect" href="/wiki/Philadelphia,_Pennsylvania" title="Philadelphia, Pennsylvania">Philadelphia,<br/>Pennsylvania</a>,
 <a class="mw-redirect" href="/wiki/Costa_Mesa" title="Costa Mesa">Costa Mesa,<br/>California</a>,
 <a class="mw-redirect" href="/wiki/Waco" title="Waco">Waco,<br/>Texas</a>,
 <a href="/wiki/Foster_City,_California" title="Foster City, California">Foster City,<br/>California</a>,
 <a href="/wiki/West_Sacramento,_California" title="West Sacramento, California">West Sacramento,<br/>California</a>,
 <a href="/wiki/Providence,_Rhode_Island" title="Providence, Rhode Island">Providence,<br/>Rhode Island</a>,
 <a href="/wiki/Kyle_Fraser" title="Kyle Fraser">Kyle Fraser</a>,
 <a class="mw-redirect" href="/wiki/Brooklyn,_New_York" title="Brooklyn, New York">Brooklyn,<br/>New York</a>]

In [ ]:
df = pd.read_html(str(tables))[3]
df

/tmp/ipykernel_3126/1238544221.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(tables))[3]

   Unnamed: 0_level_0 Original tribes                                        \
              Episode               1        2        3      3.1        3.2
0                 Day               3        5        7        7          7
1               Tribe            Vula     Vula     Vula     Vula       Vula
2          Eliminated       Stephanie    Kevin  None[b]   Tie[c]     Tie[d]
3               Votes             4–1   3–0[e]   0–0[b]      1–1        1–1
4               Voter            Vote     Vote     Vote     Vote       Vote
5                Kyle             NaN      NaN      NaN      NaN        NaN
6                 Eva             NaN      NaN      NaN      NaN        NaN
7                 Joe             NaN      NaN      NaN      NaN        NaN
8             Kamilla             NaN      NaN      NaN      NaN        NaN
9               Mitch             NaN      NaN      NaN      NaN        NaN
10            Shauhin             NaN      NaN      NaN      NaN        NaN
11               Mary             Sai  None[j]  None[k]  None[k]    None[k]
12               Star             NaN      NaN      NaN      NaN        NaN
13              David             NaN      NaN      NaN      NaN        NaN
14            Chrissy             NaN      NaN      NaN      NaN        NaN
15             Cedrek       Stephanie    Kevin     Mary      Sai        Sai
16                Sai       Stephanie    Kevin     Mary   Justin  Justin[m]
17            Charity             NaN      NaN      NaN      NaN        NaN
18             Bianca             NaN      NaN      NaN      NaN        NaN
19             Thomas             NaN      NaN      NaN      NaN        NaN
20             Justin       Stephanie    Kevin  None[j]  None[j]    None[j]
21              Kevin       Stephanie      Sai      NaN      NaN        NaN
22          Stephanie         None[k]      NaN      NaN      NaN        NaN

                 Switched tribes                     No tribes Merged tribe  \
             3.3               4        4.1        5         6            7
0              7               9          9       11        13        14[a]
1           Vula            Vula       Vula     Civa       NaN      Niu Nai
2         Justin          Thomas     Thomas   Bianca   Charity          Sai
3   Consensus[f]          3–0[g]     3–0[g]    2–1–1     7–5–1          5–0
4           Vote            Vote       Vote     Vote      Vote         Vote
5            NaN          Thomas  Thomas[i]      NaN   Charity          NaN
6            NaN             NaN        NaN      NaN       Sai          Sai
7            NaN            Kyle       Kyle      NaN   Charity          Sai
8            NaN          Thomas     Thomas      NaN   Charity          NaN
9            NaN             NaN        NaN      Sai       Sai          Sai
10           NaN            Kyle       Kyle      NaN       Sai          NaN
11       None[k]             NaN        NaN      NaN   Charity          NaN
12           NaN             NaN        NaN      NaN   Charity          Sai
13           NaN             NaN        NaN      NaN       Sai          NaN
14           NaN             NaN        NaN   Bianca   Charity          Sai
15        Justin             NaN        NaN   Bianca   Charity          NaN
16       None[f]             NaN        NaN  Chrissy    Cedrek      None[n]
17           NaN             NaN        NaN      NaN       Sai          NaN
18           NaN             NaN        NaN  None[j]       NaN          NaN
19           NaN            Kyle       Kyle      NaN       NaN          NaN
20       None[j]             NaN        NaN      NaN       NaN          NaN
21           NaN             NaN        NaN      NaN       NaN          NaN
22           NaN             NaN        NaN      NaN       NaN          NaN


        7.1        8        9       10       11       12       13       13.1
0     14[a]       15       17       19       21       23       24         25
1   Niu Nai  Niu Nai  Niu Nai  Niu Nai  Niu Nai  Niu Nai  Niu Nai    Niu Nai
2    Cedrek  Chrissy    David     Star     Mary  Shauhin    Mitch    Kamilla
3       5–1      8–1      6–3      5–3      6–1      4–2      4–1    None[h]
4      Vote     Vote     Vote     Vote     Vote     Vote     Vote  Challenge
5    Cedrek  Chrissy    David     Star     Mary  Shauhin    Mitch  Immune[h]
6       NaN  Chrissy    David     Star     Mary  Shauhin    Mitch     Won[h]
7       NaN  Chrissy    David     Star     Mary  Shauhin    Mitch   Saved[h]
8    Cedrek  Chrissy    David     Mary     Mary    Mitch    Mitch    Lost[h]
9       NaN  Chrissy    David     Mary     Mary  Shauhin     Kyle        NaN
10   Cedrek  Chrissy    David     Star     Mary    Mitch      NaN        NaN
11   Cedrek  Chrissy    Mitch     Star      Joe      NaN      NaN        NaN
12      NaN  None[l]    Mitch     Mary      NaN      NaN      NaN        NaN
13   Cedrek  Chrissy    Mitch      NaN      NaN      NaN      NaN        NaN
14      NaN  Shauhin      NaN      NaN      NaN      NaN      NaN        NaN
15  Shauhin      NaN      NaN      NaN      NaN      NaN      NaN        NaN
16      NaN      NaN      NaN      NaN      NaN      NaN      NaN        NaN
17      NaN      NaN      NaN      NaN      NaN      NaN      NaN        NaN
18      NaN      NaN      NaN      NaN      NaN      NaN      NaN        NaN
19      NaN      NaN      NaN      NaN      NaN      NaN      NaN        NaN
20      NaN      NaN      NaN      NaN      NaN      NaN      NaN        NaN
21      NaN      NaN      NaN      NaN      NaN      NaN      NaN        NaN
22      NaN      NaN      NaN      NaN      NaN      NaN      NaN        NaN

In [ ]:
kyle_row = df[df[('Unnamed: 0_level_0', 'Episode')] == 'Kyle']
print(kyle_row)

  Unnamed: 0_level_0 Original tribes                          Switched tribes  \
             Episode               1    2    3  3.1  3.2  3.3               4
5               Kyle             NaN  NaN  NaN  NaN  NaN  NaN          Thomas

                  No tribes Merged tribe                                      \
         4.1    5         6            7     7.1        8      9    10    11
5  Thomas[i]  NaN   Charity          NaN  Cedrek  Chrissy  David  Star  Mary


        12     13       13.1
5  Shauhin  Mitch  Immune[h]

## Survivor 49

In [ ]:
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
}

r = requests.get('https://en.wikipedia.org/wiki/Survivor_49', headers=headers)
html_contents = r.text
html_soup = BeautifulSoup(html_contents,"lxml")

In [ ]:
tables = html_soup.find_all('table',class_="wikitable")
tables[0].find_all('a')

[<a href="/wiki/Philadelphia" title="Philadelphia">Philadelphia,<br/>Pennsylvania</a>,
 <a href="/wiki/Annie_Davis" title="Annie Davis">Kimberly "Annie" Davis</a>,
 <a href="/wiki/Austin,_Texas" title="Austin, Texas">Austin,<br/>Texas</a>,
 <a href="/wiki/St._Albert,_Alberta" title="St. Albert, Alberta">St. Albert,<br/>Alberta</a>,
 <a href="/wiki/Toronto" title="Toronto">Toronto,<br/>Ontario</a>,
 <a href="/wiki/St._George,_Utah" title="St. George, Utah">St. George,<br/>Utah</a>,
 <a href="/wiki/Santa_Ana,_California" title="Santa Ana, California">Santa Ana,<br/>California</a>,
 <a href="/wiki/Boston" title="Boston">Boston,<br/>Massachusetts</a>,
 <a href="/wiki/Hermosa_Beach,_California" title="Hermosa Beach, California"><span class="nowrap">Hermosa Beach,</span><br/>California</a>,
 <a href="/wiki/San_Diego" title="San Diego">San Diego,<br/>California</a>,
 <a href="/wiki/Washington,_D.C." title="Washington, D.C.">Washington,<br/>D.C.</a>,
 <a href="/wiki/Los_Angeles" title="Los Angeles">Los Angeles,<br/>California</a>,
 <a href="/wiki/New_York_City" title="New York City">New York City,<br/>New York</a>,
 <a href="/wiki/Denver" title="Denver">Denver,<br/>Colorado</a>,
 <a href="/wiki/Edmond,_Oklahoma" title="Edmond, Oklahoma">Edmond,<br/>Oklahoma</a>,
 <a href="/wiki/Yonkers,_New_York" title="Yonkers, New York">Yonkers,<br/>New York</a>,
 <a href="/wiki/Olympia,_Washington" title="Olympia, Washington">Olympia,<br/>Washington</a>,
 <a href="/wiki/Miami" title="Miami">Miami,<br/>Florida</a>,
 <a href="/wiki/Atlanta" title="Atlanta">Atlanta,<br/>Georgia</a>]

In [ ]:
df = pd.read_html(str(tables))[3]
df

/tmp/ipykernel_3126/1238544221.py:1: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(tables))[3]

   Unnamed: 0_level_0 Original tribes                                 \
              Episode               1      2             3       3.1
0                 Day               3      5             6         6
1               Tribe            Kele   Kele          Kele      Kele
2          Eliminated          Nicole  Annie          Jake  Jeremiah
3               Votes             5–1    4–1  Evacuated[a]    2–0[b]
4               Voter            Vote   Vote          Vote      Vote
5            Savannah             NaN    NaN           NaN       NaN
6               Sophi          Nicole  Annie           NaN  Jeremiah
7                Sage             NaN    NaN           NaN       NaN
8                Rizo             NaN    NaN           NaN       NaN
9            Kristina             NaN    NaN           NaN       NaN
10             Steven             NaN    NaN           NaN       NaN
11             Sophie             NaN    NaN           NaN       NaN
12              Jawan             NaN    NaN           NaN       NaN
13               Alex          Nicole  Annie           NaN  Jeremiah
14                 MC             NaN    NaN           NaN       NaN
15               Nate             NaN    NaN           NaN       NaN
16            Shannon             NaN    NaN           NaN       NaN
17              Jason             NaN    NaN           NaN       NaN
18               Matt             NaN    NaN           NaN       NaN
19           Jeremiah          Nicole  Annie           NaN      Alex
20               Jake          Nicole  Annie     Evacuated       NaN
21              Annie          Nicole  Sophi           NaN       NaN
22             Nicole           Annie    NaN           NaN       NaN

   First switch        Second switch Merged tribe                      \
              4      5             6            7           8       9
0             8     10            12           14          15      17
1          Hina   Hina          Kele       Lewatu      Lewatu  Lewatu
2          Matt  Jason       Shannon         Nate          MC    Alex
3         4–2–1    5–1           3–1          7–4         4–1   6–2–1
4          Vote   Vote          Vote         Vote        Vote    Vote
5         Jason  Jason           NaN       Steven  None[d][e]    Alex
6         Jason  Jason           NaN       Steven   Immune[d]    Alex
7           NaN    NaN       Shannon         Nate          MC    Alex
8          Matt  Jason           NaN       Steven          MC    Alex
9           NaN    NaN           NaN         Nate   Immune[d]   Sophi
10          NaN    NaN       Shannon         Nate   Immune[d]   Sophi
11          NaN    NaN           NaN         Nate          MC    Alex
12         Matt  Jason       Shannon         Nate          MC    Alex
13          NaN    NaN           NaN         Nate   Immune[d]    Rizo
14          NaN    NaN           NaN         Nate      Sophie     NaN
15         Matt  Jason           NaN       Steven         NaN     NaN
16          NaN    NaN         Jawan          NaN         NaN     NaN
17         Matt   Rizo           NaN          NaN         NaN     NaN
18         Nate    NaN           NaN          NaN         NaN     NaN
19          NaN    NaN           NaN          NaN         NaN     NaN
20          NaN    NaN           NaN          NaN         NaN     NaN
21          NaN    NaN           NaN          NaN         NaN     NaN
22          NaN    NaN           NaN          NaN         NaN     NaN


          10      10.1        11       12        13       13.1
0         19        19        21       23        24         25
1     Lewatu    Lewatu    Lewatu   Lewatu    Lewatu     Lewatu
2      Jawan     Jawan    Sophie   Steven  Kristina       Rizo
3      5–3–1     5–3–1       6–1      4–1       4–1    None[c]
4       Vote      Vote      Vote     Vote      Vote  Challenge
5      Jawan  Jawan[f]    Sophie  None[g]  Kristina     Won[c]
6      Jawan     Jawan    Sophie   Steven  Kristina  Immune[c]
7   Savannah  Savannah    Sophie   Steven  Kristina   Saved[c]
8      Jawan     Jawan    Sophie   Steven  Kristina    Lost[c]
9       Rizo      Rizo    Sophie   Steven      Sage        NaN
10  Savannah  Savannah    Sophie    Sophi       NaN        NaN
11     Jawan     Jawan  Savannah      NaN       NaN        NaN
12  Savannah  Savannah       NaN      NaN       NaN        NaN
13       NaN       NaN       NaN      NaN       NaN        NaN
14       NaN       NaN       NaN      NaN       NaN        NaN
15       NaN       NaN       NaN      NaN       NaN        NaN
16       NaN       NaN       NaN      NaN       NaN        NaN
17       NaN       NaN       NaN      NaN       NaN        NaN
18       NaN       NaN       NaN      NaN       NaN        NaN
19       NaN       NaN       NaN      NaN       NaN        NaN
20       NaN       NaN       NaN      NaN       NaN        NaN
21       NaN       NaN       NaN      NaN       NaN        NaN
22       NaN       NaN       NaN      NaN       NaN        NaN

In [ ]:
savannah_row = df[df[('Unnamed: 0_level_0', 'Episode')] == 'Savannah']
print(savannah_row)

  Unnamed: 0_level_0 Original tribes                First switch         \
             Episode               1    2    3  3.1            4      5
5           Savannah             NaN  NaN  NaN  NaN        Jason  Jason

  Second switch Merged tribe                                             \
              6            7           8     9     10      10.1      11
5           NaN       Steven  None[d][e]  Alex  Jawan  Jawan[f]  Sophie


        12        13    13.1
5  None[g]  Kristina  Won[c]

## Combining Tables

In [ ]:
winner_rows = [
    (richard_row, "Richard Hatch", 1),
    (tina_row, "Tina Wesson", 2),
    (ethan_row, "Ethan Zohn", 3),
    (vecepia_row, "Vecepia Towery", 4),
    (brian_row, "Brian Heidik", 5),
    (jenna_row, "Jenna Morasca", 6),
    (sandra_row, "Sandra Diaz-Twine", 7),
    (amber_row, "Amber Brkich", 8),
    (chrisD_row, "Chris Daugherty", 9),
    (tom_row, "Tom Westman", 10),
    (danni_row, "Danni Boatwright", 11),
    (aras_row, "Aras Baskauskas", 12),
    (yul_row, "Yul Kwon", 13),
    (earl_row, "Earl Cole", 14),
    (todd_row, "Todd Herzog", 15),
    (parvati_row, "Parvati Shallow", 16),
    (bob_row, "Bob Crowley", 17),
    (jt_row, "JT Thomas", 18),
    (nataliew_row, "Natalie White", 19),
    (sandra2_row, "Sandra Diaz-Twine", 20),
    (fabio_row, "Fabio Birza", 21),
    (rob_row, "Boston Rob Mariano", 22),
    (sophie_row, "Sophie Clarke", 23),
    (kim_row, "Kim Spradlin", 24),
    (denise_row, "Denise Stapley", 25),
    (cochran_row, "John Cochran", 26),
    (tyson_row, "Tyson Apostol", 27),
    (tony_row, "Tony Vlachos", 28),
    (natalieA_row, "Natalie Anderson", 29),
    (mike_row, "Mike Holloway", 30),
    (jeremy_row, "Jeremy Collins", 31),
    (michele_row, "Michele Fitzgerald", 32),
    (adam_row, "Adam Klein", 33),
    (sarah_row, "Sarah Lacina", 34),
    (ben_row, "Ben Driebergen", 35),
    (wendell_row, "Wendell Holland", 36),
    (nick_row, "Nick Wilson", 37),
    (chrisU_row, "Chris Underwood", 38),
    (tommy_row, "Tommy Sheehan", 39),
    (tony2_row, "Tony Vlachos", 40),
    (erika_row, "Erika Casupanan", 41),
    (maryanne_row, "Maryanne Oketch", 42),
    (gabler_row, "Mike Gabler", 43),
    (yamyam_row, "Yam Yam Arocho", 44),
    (dee_row, "Dee Valladares", 45),
    (kenzie_row, "Kenzie Petty", 46),
    (rachel_row, "Rachel Lamont", 47),
    (kyle_row, "Kyle Fraser", 48),
    (savannah_row, "Savannah Louie", 49)
]

In [ ]:
all_winners = []

for df, name, season in winner_rows:
    df = df.copy()

    df["Winner"] = name
    df["Season"] = season

    all_winners.append(df)

final_df = pd.concat(all_winners, ignore_index=True)

In [ ]:
final_df.to_csv("survivor_winner_voting_history.csv", index=False)